### ISSUE TITLE
CytoTRACEKernel produces the same results for backward=True and False

### ISSUE THREAD

**Issue by JenniferWUSTL** [theislab/cellrank#1009]
Good morning! Thank you for maintaining this excellent package!  I updated to the latest version of cellrank and noticed the CytoTRACEKernel is not performing as expected from prior versions on my data. I repeated these results following the tutorial here: https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/cellrank_meets_cytotrace.html modifying CytoTRACEKernel to compare `backward = True` and `backward = False`. Thank you for your time and please let me know if this is expected behavior in this version or if additional information would be helpful from me. Thanks!!

`CytoTRACEKernel(adata, backward = True)` and `CytoTRACEKernel(adata, backward = False)` result in the same projections.
...

```python
import scvelo as scv
import sys
import warnings
import scanpy as sc
import cellrank as cr
import numpy as np
from cellrank.kernels import CytoTRACEKernel
adata = cr.datasets.zebrafish()
sc.pp.filter_genes(adata, min_cells=10)
scv.pp.normalize_per_cell(adata)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata)
adata.layers["spliced"] = adata.X
adata.layers["unspliced"] = adata.X
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
ctkb = CytoTRACEKernel(adata, backward = True).compute_cytotrace()
ctkb.compute_transition_matrix(threshold_scheme = "soft", nu = 0.5)
ctkb.plot_projection(basis = "force_directed", color = "Stage", legend_loc = "right", save = "backwardTrueCytotrace.png")
adata ## confirming addition of T_bwd_force_directed in adata.obs

ctkf = CytoTRACEKernel(adata, backward = False).compute_cytotrace()
ctkf.compute_transition_matrix(threshold_scheme = "soft", nu = 0.5)
ctkf.plot_projection(basis = "force_directed", color = "Stage", legend_loc = "right", save = "backwardFalseCytotrace.png")
adata ## confirming addition of T_fwd_force_directed in adata.obs

...
```

#### Versions:

cellrank==1.5.1+g5853d0e0 scanpy==1.9.2 anndata==0.8.0 numpy==1.23.5 numba==0.56.4 scipy==1.9.3 pandas==1.5.3 pygpcca==1.0.4 scikit-learn==1.2.0rc1 statsmodels==0.13.5 python-igraph==0.10.4 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.6.2 seaborn==0.12.2
> ...
![scvelo_backwardTrueCytotrace](https://user-images.githubusercontent.com/56699896/227559036-73df3460-3dfd-4a14-8d8e-8a27373af4e4.png)
![scvelo_backwardFalse_2Cytotrace](https://user-images.githubusercontent.com/56699896/227559063-8aaea885-e543-4e8e-8e97-1e8a38a122f5.png)

**Comment by michalk8** [comment]
Thanks @JenniferWUSTL , fixed in #1010!

**Comment by JenniferWUSTL** [comment]
Thank you for fixing this so quickly @michalk8 ! I can confirm that the plots look as expected with the code above.

On another note, just an fyi as this is not really a cellrank issue, but when I updated the cellrank version with: `pip3 install git+https://github.com/theislab/cellrank@master` I get this message regarding `pygam`: 
```
ERROR: pygam 0.9.0 has requirement numpy<2.0.0,>=1.24.2, but you'll have numpy 1.23.5 which is incompatible.
ERROR: pygam 0.9.0 has requirement scipy<2.0.0,>=1.10.1, but you'll have scipy 1.9.3 which is incompatible.
Installing collected packages: python-utils, progressbar2, pygam, wrapt, MarkupSafe, jinja2, docrep, pygpcca, click, numpy-groupies, loompy, typing-extensions, scvelo, cellrank
Successfully installed MarkupSafe-2.1.2 cellrank-1.5.2.dev167+g6dac53bc click-8.1.3 docrep-0.3.2 jinja2-3.0.3 loompy-3.0.7 numpy-groupies-0.9.20 progressbar2-4.2.0 pygam-0.9.0 pygpcca-1.0.4 python-utils-3.5.2 scvelo-0.2.5 typing-extensions-4.5.0 wrapt-1.15.0
```

If I update `numpy` and `scipy` to get rid of this error: `scvelo`, `scanpy`, and `cellrank` now fail to import- I believe due to numba: 
`ERROR: numba 0.56.4 has requirement numpy<1.24,>=1.18, but you'll have numpy 1.24.2 which is incompatible.` 


I am not sure what the best fix of this is since this is largely dependency issues, but if you know it is alright to ignore the first ERRORs, that would be great to know.  pygam so far seems to import and install despite the Errors and just wanted to share in case this is helpful or of interest, thanks!

**Comment by michalk8** [comment]
> I am not sure what the best fix of this is since this is largely dependency issues, but if you know it is alright to ignore the first ERRORs, that would be great to know. pygam so far seems to import and install despite the Errors and just wanted to share in case this is helpful or of interest, thanks!

This should be fine, `pyGAM` is only used for the `cellrank.models.GAM`. I will create an issue to remove `cellrank.models.GAM` and replace it with something else, as `pyGAM` is no longer maintained.

**Comment by JenniferWUSTL** [comment]
Thank you!!
