### ISSUE TITLE
Condition number for sparse matrices

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#101]
Currently, we use `np.linalg.cond` to get the condition number, which works only on dense matrices.
Implement the approximation for sparse matrices as described in: https://github.com/sparse-condest/condest

**Comment by Marius1311** [comment]
nice linear algebra programming exercise :) But I guess to make this fast, you would have to implement in C++ and interface to python. So it's probably best to check first whether standard C/C++/Fortran libraries like ARPACK, LAPACK or BLAS already have the ingredients you need for this. I'm sure there must be something in there for estimating either the condition number directly, or it's ingredients (e.g. smalles and largest singluar value of sparse matrices)

**Comment by Marius1311** [comment]
Hi @michalk8 , please have a look through SLEPSc and PETSc whether they offer anything useful here. The github you posted essentially tries to solve some (potentially shifted) least squares problem using an iterative (I believe lanczos) solver. There is **no point** in re-implementing this, it will never be efficient. If we want to have a useful implementation, then we need to find the paper that described this procedure and re-implement it using efficient solvers from SLEPSc or PETSc. Re-implementing that github as it is would be re-inventing the wheel with no chances of success. 

If you're not interested, feel free to close this, it's absolutely not essential.

**Comment by michalk8** [comment]
Yes, I think this is too much of a low-prio right now.
