### ISSUE TITLE
Remove `pyGAM` dependency

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#1011]
> I am not sure what the best fix of this is since this is largely dependency issues, but if you know it is alright to ignore the first ERRORs, that would be great to know. pygam so far seems to import and install despite the Errors and just wanted to share in case this is helpful or of interest, thanks!

This should be fine, `pyGAM` is only used for the `cellrank.models.GAM`. I will create an issue to remove `cellrank.models.GAM` and replace it with something else, as `pyGAM` is no longer maintained.

_Originally posted by @michalk8 in https://github.com/theislab/cellrank/issues/1009#issuecomment-1485842176_

**Comment by Marius1311** [comment]
@michalk8, do you already have an alternative in mind?

**Comment by michalk8** [comment]
> @michalk8, do you already have an alternative in mind?

Not yet, will keep looking.

**Comment by michalk8** [comment]
Wasn't able to find an alternative, closing this for now.
