### ISSUE TITLE
no function `compute_terminal_states` in current version

### ISSUE THREAD

**Issue by zoepiran** [theislab/cellrank#1013]
In the current version `compute_terminal_states` -> `predict_terminal_states` whereas docs refer to `compute_terminal_states` for example [here](https://github.com/theislab/cellrank/blob/5853d0e0c48cbbd0b4c86fa5578f19ee9bf100df/cellrank/estimators/mixins/_absorption_probabilities.py#L477).

**Comment by Marius1311** [comment]
Good point, we should keep this on our radar @michalk8 @WeilerP, need to update docs in a few places. Thanks @zoepiran for pointing this out.

**Comment by michalk8** [comment]
This seems to have been the only instance for the error message, closing via [51afb11](https://github.com/theislab/cellrank/commit/51afb111700f91bde205f1a48a5fc326229a4161).
General doc overhaul will be done in a separate issue!
