### ISSUE TITLE
Attribute renaming

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#102]
To ensure harmonization between scvelo and cellrank, we should rename a couple of our attributes in cellrank. This is in particular relevant for scvelo's `latent_time` and for the directed PAGA. I suggest the following changes:

- In `adata`, write to `final_states` and `root_states`, rather than `final_cells` and `root_cells`
- write continuous annotations to `final_states_cont` and `root_states_cont`. This should be the aggregated probability that a cells belongs to a final/root state, no matter which one. (I guess we called this `approx_rcs_probs` in MC, so we already have it there). 

The above two should be consistent between MC and GPCCA, we can talk about the details tonight. Also, I was thinking about how to make the naming more consistent between MC and GPCCA in general. I would suggest:

- rename `approx_rcs` to `metastable_states` everywhere, i.e. `compute_approx_rcs` goes to `compute_metastable_states` in MC etc. 
- The MC class directly writes `metastable_states` to `final_states` or `root_states` in AnnData
- The GPCCA class writes `metastable_states` to `metastable_states_fwd` and `metastable_states_bwd` in AnnData, and their restriction ('main states') to `final_states` and `root_states` in AnnData

**Comment by michalk8** [comment]
@Marius1311 should be implemented in the #103

**Comment by Marius1311** [comment]
thanks!

**Comment by michalk8** [comment]
Implemented via #103
