### ISSUE TITLE
compute absorption probabilities leads to error message

### ISSUE THREAD

**Issue by mbensouda** [theislab/cellrank#1022]
Hi, I have the same error than raised before:

ValueError: 48455 value(s) do not sum to 1 (rtol=1e-3). Try decreasing the tolerance as tol=..., specifying a preconditioner as preconditioner=... or use a direct solver as solver='direct' if the matrix is small. `

I used this function: g_fwd.compute_absorption_probabilities(preconditioner='ilu') with g_fwd = GPCCA(kernel). I could compute the macrostates, terminal states (from macrostates), the coarse grained transition matrix, and the random walk.
Thank you in advance for your help!

**Comment by Marius1311** [comment]
Hi @mbensouda, thanks for reporting this, would it be possible to provide us with an example, so that we can potentially reproduce this error on our side?

**Comment by sneddonucsf** [comment]
Hi @Marius1311 sorry to piggyback off of this, but I've been having the same issue. I've run CellRank (dev branch) with: 

```
adata_early = sc.read_h5ad("/Users/seandelao/Desktop/Early_Endocrine_Slingshot.h5ad"). #computed with Seurat
sc.pl.umap(adata_late, color='annotation', title='', frameon=False,
           add_outline = True, size = 50, palette={
        "Beta": "#F8766D",
        "Alpha": "#D39200",
        "Pre-Beta" : "#00B9E3",
        "FEV_High" : "#DB72FB",
        "cEP" : "#FF61C3",
        "Pre-Alpha_Pre-Epsilon" : "#619CFF",
        "Delta" : "#00BA38", 
        "Epsilon" : "#00C19F"},
           legend_loc = None,
           edges = False
          #save = "Endocrine_UMAP_CellRank_High_res.pdf"
          )
sc.pl.umap(adata_early, color='Slingshot_avg', title='', frameon=False,
           add_outline = True, size = 15, 
          color_map = "gnuplot2")
![download-1](https://github.com/theislab/cellrank/assets/12053091/c1514641-af4b-4cdc-b4d0-f02381bd58b5)
![download-2](https://github.com/theislab/cellrank/assets/12053091/bb2584e6-6299-4455-895e-bfb46a48a9d8)

adata_early.layers["spliced"] = adata_early.X
adata_early.layers["unspliced"] = adata_early.X
scv.pp.moments(adata_early, n_pcs=9)

pk_early = cr.kernels.PseudotimeKernel(adata_early, time_key="Slingshot_avg")
pk_early.compute_transition_matrix(threshold_scheme='soft')
print(pk_early)
#PseudotimeKernel[n=1236]

pk_early.plot_projection(basis="umap", recompute=True)
![download](https://github.com/theislab/cellrank/assets/12053091/a8ab06a8-37d1-46a6-9414-3d099f33ce7c)

g_early = cr.estimators.GPCCA(pk_early)
print(g_early)
GPCCA[kernel=PseudotimeKernel[n=1236], initial_states=None, terminal_states=None]

g_early.compute_schur()
g_early.compute_macrostates(n_states=6, cluster_key="annotation")
![download-3](https://github.com/theislab/cellrank/assets/12053091/fcd7ef79-5e18-4a2e-8baa-941babaf69e5)


g_early.set_terminal_states(states=["Alpha", "Beta", "Epsilon", "Delta"])
![download-4](https://github.com/theislab/cellrank/assets/12053091/c1186476-5639-43d4-8a86-83bdb7888e8a)

g_early.set_initial_states(states=['cEP'])
![download-5](https://github.com/theislab/cellrank/assets/12053091/6ee5caaf-5d27-4158-9238-9180d997b6dd)

g_early.compute_fate_probabilities(preconditioner= 'ilu', tol = 1e-10, solver = 'direct')
```
gives
```
`408` value(s) are negative. Try decreasing the tolerance as `tol=...`, specifying a preconditioner as `preconditioner=...` or use a direct solver as `solver='direct'` if the matrix is small.
```
I've tried increasing the tol, but it doesn't decrease the number of negative values.

**Comment by Marius1311** [comment]
mh, what happens when you set the tolerance e.g. to `1e-2`? You could look into the underlying transition matrix a bit, check e.g. whether it's irreducible: https://github.com/theislab/cellrank/blob/bd35386fb1556841fcd69323aa1269122155f5be/src/cellrank/_utils/_utils.py#L682

**Comment by Marius1311** [comment]
You can also look into transient and recurrent classes: https://github.com/theislab/cellrank/blob/bd35386fb1556841fcd69323aa1269122155f5be/src/cellrank/_utils/_utils.py#L631

I've noticed in the past that many small recurrent classes, i.e. individual absorbing cells in the extreme case, can cause issues with convergence. One solution would be to just filter them out. Alternatively, you could play with the parameters for transition matrix construction in your pseudotime kernel.

**Comment by Marius1311** [comment]
@sneddonucsf, can you please post the full traceback of the error you're getting?

**Comment by Marius1311** [comment]
I looked into this a bit more. I managed to generate an example of this error happening using the hematopoeisis dataset (https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/kernels/300_pseudotime.html#) and the `PseudotimeKernel`  with the following call: 
`pk.compute_transition_matrix(threshold_scheme='soft', nu=0.01, b=20.0)`. 

These are really unrealistic parameters, very far from our defaults. I can  still compute terminal states, but when trying to compute fate probabilities with defaults (`g.compute_fate_probabilities()`), I get 

```pytb
ValueError: `9` value(s) are negative. Try decreasing the tolerance as `tol=...`, specifying a preconditioner as `preconditioner=...` or use a direct solver as `solver='direct'` if the matrix is small.
```

However, I was able to resolve this in a number of ways:
1. Change the parameters of transition matrix computation. In this case, just using the defaults works perfectly fine. 
2. Set the tolerance in `g.compute_fate_probabilities` to `tol=1e-20`. 
3. Use a direct solver (`g.compute_fate_probabilities(solver='direct')`)

An alternative option, which did not work in this case, would be to specify a preconditioner, as stated in the error message. 

For very large datasets, option 3 might not be feasible. In case Option 2, i.e. decreasing the tolerance, also does not work, I recommend varying the parameters of transition matrix computation to improve matrix conditioning (-> Option 1). 

### Option 1
To diagnose problems with transition matrix conditioning, I recommend two strategies: 

1. Look into the spectrum of the matrix (`g.plot_spectrum(real_only=True)`). In the example from above, we see many eigenvalues very close to one, see screenshot below. That's an indication of a badly conditioned matrix for our purposes. Try changing transition matrix computation parameters to have fewer eigenvalues very close to one. 
2. Look into [transient and recurrent classes](https://www.probabilitycourse.com/chapter11/11_2_4_classification_of_states.php#:~:text=A%20class%20is%20said%20to,and%20assume%20X0%3Di.), see the code snippet below. Having many small recurrent classes may constitute a problem for our solvers. In the example from above, this is actually not an issue. 

Code snippet to look into transient and recurrent classes:
```python
from cellrank._utils._utils import _partition

conn = g.transition_matrix
rec, trans = _partition(conn)
len(rec), len(trans)
```

### Spectrum of the example transition matrix
<img width="549" alt="Screenshot 2023-09-13 at 14 08 56" src="https://github.com/theislab/cellrank/assets/24494650/b5258220-19fa-4edb-ba29-8f7ef3d04105">

**Comment by Marius1311** [comment]
I'll close the issue with that, feel free to re-open or comment in case none of these strategies work.

**Comment by EchoCode4Fun** [comment]
Thank you Marius for the helpful tips! I also encountered negative values when calculating fate probabilities using mouse bone marrow data. 
I tried to improve the transition matrix conditioning by  


  **_1.     Tuning parameters - nu and b_** 

I tried many combo, but the smallest number of eigenvalues very close to one is **6**. Is this an acceptable number?


  **_2.      Looking into recurrent and transient classes_** 

The code snippet returned to me: **(1, 0)**
I did not do any filtering yet, but does this make biological sense?

<img width="699" alt="Image" src="https://github.com/user-attachments/assets/8811a493-16ff-4935-a61f-ee0a28770e6e" />



Besides, I tried running this code when computing fate probabilities but it still returns negative values... 
The matrix is 9167x9167 so it should be a small matrix? 

> g_fwd.compute_fate_probabilities(tol=1e-20, preconditioner="ilu", solver="direct")



I have attached my code below for your reference. 

<img width="1101" alt="Image" src="https://github.com/user-attachments/assets/b30383cd-aeaf-4ef5-b5d8-1b65df125f08" />


Thank you!!!

**Comment by EchoCode4Fun** [comment]
I looked into another matrix that worked without problems, and interestingly, it has six eigenvalues very close to one, and also 1 recurrent and 0 transient class. It worked when I ran

> g_fwd.compute_fate_probabilities(tol=1e-10)

.
However, when I ran this on another matrix with the same eigenvalues and classes, this parameter above did not work. It said I have got negative values. 

When I increased the tol to 1e-2, the negative values dropped to 1. 

> g_fwd.compute_fate_probabilities(tol=1e-2)

<img width="955" alt="Image" src="https://github.com/user-attachments/assets/7db52afd-4684-4c09-a5b6-53592bb2dcde" />

When I decreased the tol to 1e-10 and 1e-20, the number of negative values increased dramatically. Also when I ran solver='direct'. 


**_How could I eliminate the 1 negative value? Any suggestions?_**

**Comment by Marius1311** [comment]
Mh, interesting, nothing comes to mind immediately, but maybe @WeilerP or @WWXkenmo have some ideas? It's more of a pyGPCCA (https://github.com/msmdev/pyGPCCA) issue than a CellRank issue.

**Comment by EchoCode4Fun** [comment]
Hi all I finally solved the issues using the parameters below: 

1. Using threshold_scheme = "hard" instead of = "soft" 

`pk.compute_transition_matrix(threshold_scheme='hard')`

3. Tune tol, starting from 1e-1 to 1e-10. The negative values disappear when tol = 1e-7. As I decreased the tol, the negative values dropped to 1 when tol = 1e-2, then the numbers increased again but then dropped to 0 when tol = 1e-7.

`g_fwd.compute_fate_probabilities(tol=1e-7)`


Although I finally managed to eliminate the negative values, how will changing the threshold_schem from "soft" to "hard" affect the calculated fate probabilities? Any possible negative effects? Thank you so much!

**Comment by Marius1311** [comment]
that's in the PseudotimeKernel, right? The hard scheme removes connections to certain cells in the "pseudotime past" of the current cell, whereas the soft scheme keeps all connections, but down-weights the ones that point to the pseudotime past. Using the hard scheme is totally valid, it's essentially what Palantir does.
