### ISSUE TITLE
What is y-axis on WOTKernel.plot_single_flow() ?

### ISSUE THREAD

**Issue by JenniferWUSTL** [theislab/cellrank#1023]
Hi! I am so sorry to ask another question! What is the y-axis scale in wk.plot_single_flow() for the Waddington-OT Kernel? https://cellrank.readthedocs.io/en/stable/real_time.html#Probability-mass-flow-in-time 

Is there a way to compare outgoing flow across clusters? For example, if multiple clusters have outgoing flow into a given cluster, is it possible to export from the WOTKernel the flow to compare the width of the veins across multiple clusters? 

Thank you for your maintenance of this package!
...

**Comment by Marius1311** [comment]
Hi @JenniferWUSTL, in `plot_single_flow`, only a single cluster is allowed to have outgoing flow; thus you won't be able to compare outgoing flow across multiple clusters. You can compare incoming flow across multiple clusters, the definition of the flow is here: https://github.com/theislab/cellrank/blob/7de9678f415a04fe92322f7867fb66960d4be0d0/cellrank/kernels/utils/_tmat_flow.py#L153

@michalk8 implemented this method and might be able to tell you more about flow-normalization across different clusters.

**Comment by JenniferWUSTL** [comment]
Thank you @Marius1311, I will look into this code ! 

Is there a method to export the data for multiple clusters for outgoing flow and then I could compare in a different visualization, or is it not accurate to compare outgoing flow across clusters regardless of how the data is visualized?

**Comment by Marius1311** [comment]
We currently don't have any method in CellRank that computes or visualizes outgoing flow for several clusters at a time. We played around with this a bit but could not come up with a good way to determine which flows should be considered significant and which shouldn't. If you have an idea for how this could be done, we would welcome your contribution :)

**Comment by michalk8** [comment]
> We currently don't have any method in CellRank that computes or visualizes outgoing flow for several clusters at a time. We played around with this a bit but could not come up with a good way to determine which flows should be considered significant and which shouldn't. If you have an idea for how this could be done, we would welcome your contribution :)

For the sake of completeness, there is/was an implementation [here](https://github.com/theislab/cellrank/blob/plot_multiflow/cellrank/tl/kernels/_tmat_flow.py#L675) but we weren't able to come up with a way to determine only significant flows.

**Comment by JenniferWUSTL** [comment]
Thank you both! I will take a look and close this issue as complete, will follow up if I have any ideas for the multi-flow plot in the future :)
