### ISSUE TITLE
Add initial/terminal states to existing annotations

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#1027]
Hi @michalk8, just a quick question - there used to be the ` add_to_existing` parameter in `estimator.set_terminal_states`, which has been removed in the new method. Did you do this intentionally? I think it would be handy to have this functionality, but understand that this might create some extra complications of course, so just wanted to hear your opinion here.

**Comment by michalk8** [comment]
Yes, I think this was causing some issues (would need to check exactly what), so I decided to remove this. Am closing this, feel free to re-open if you want to have this back or discuss a bit more.
