### ISSUE TITLE
Manual setting of terminal states is not working

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#1028]
When I try to manually set terminal states via `g2.set_terminal_states(names=['Alpha', 'Beta', 'Epsilon', 'Delta'])`, the estimators declares all macrostates to be terminal, and not just the ones I passed. The output I get is 
```python
Adding `adata.obs['term_states_fwd']`
       `adata.obs['term_states_fwd_probs']`
       `.terminal_states`
       `.terminal_states_probabilities`
       `.terminal_states_memberships
    Finish`
GPCCA[kernel=VelocityKernel[n=2531], initial_states=None, terminal_states=['Alpha', 'Beta', 'Delta', 'Epsilon', 'Ngn3 high EP_1', 'Ngn3 high EP_2', 'Ngn3 high EP_3', 'Ngn3 high EP_4', 'Ngn3 high EP_5', 'Ngn3 low EP_1', 'Ngn3 low EP_2', 'Ngn3 low EP_3']]
```

#### Versions:
Running CellRank 1.5.1+gedbc651e, on 2023-05-16 13:17.
> ...

**Comment by Marius1311** [comment]
Automatic identification of terminal states works, though.

**Comment by michalk8** [comment]
The argument name is called `states`, not `names`.

**Comment by Marius1311** [comment]
Ah, I'm an idiot, thanks. However, why does it not raise an exception when this happens?
