### ISSUE TITLE
About cr.tl.terminal_states

### ISSUE THREAD

**Issue by victorwang123** [theislab/cellrank#1030]
Thanks for your amazing tool. Now I have a question about cr.tl.terminal_states.
Here when I run cellrank basic analysis, it is very clear that cluster 0 is the terminal, but in cr.pl.cluster_fates(adata, mode="bar”), the Group0 is not in terminal_states, even I increase the n_states(cr.tl.terminal_states), what’s the reason, Can I assign my own group0 of terminals? The code follows:
cr.tl.terminal_states(
    adata,
    cluster_key="clusters",
    n_states=4
)
cr.tl.lineages(adata)
sc.tl.paga(adata, "clusters")
cr.pl.cluster_fates(adata, mode="bar")

**Comment by michalk8** [comment]
Hi @victorwang123 , `cellrank.tl.terminal_states` will be shortly removed in the `2.0`, please use the estimators interface directly. We will be adding new tutorials shortly!
