### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by denvercal1234GitHub** [theislab/cellrank#1031]
Hi there, 

I was trying to install `cellrank` on Mac M1, but I encountered this error "cannot import name 'Iterable' from 'collections' as in #942 

Python 3.11.3 installed. 

Would you mind letting me know how to proceed?

Thank you. 

```
```

**Comment by michalk8** [comment]
Hi @denvercal1234GitHub , this was fixed in #943, you just need to install `CellRank` from `master` as `pip install git+https://github.com/theislab/cellrank@master`. Feel free to re-open if you encounter any issues!

**Comment by pratarora** [comment]
Thanks a lot, @michalk8 
just changing the command slightly. It should be : 
`pip install git+https://github.com/theislab/cellrank@main`
