### ISSUE TITLE
ModuleNotFoundError: No module named 'cr' 

### ISSUE THREAD

**Issue by denvercal1234GitHub** [theislab/cellrank#1036]
Hi there, 

When I ran `from cr.tl.kernels import VelocityKernel`, it threw an error `ModuleNotFoundError: No module named 'cr'`

But, `import cellrank as cr` was successful as below. 

Would you mind letting me know how to proceed?

Thank you. 

Mac M1. 

```
cr.logging.print_versions()

cellrank==1.5.1+gccb3a81 scanpy==1.9.3 anndata==0.8.0 numpy==1.23.5 numba==0.56.4 scipy==1.10.1 pandas==1.5.3 pygpcca==1.0.4 scikit-learn==1.2.2 statsmodels==0.14.0rc0 python-igraph==0.10.4 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2
```

**Comment by michalk8** [comment]
It should be:
```python
from cellrank.tl.kernels import VelocityKernel
```
Below just defines an alias:
```python
import cellrank as cr
```

**Comment by denvercal1234GitHub** [comment]
Thanks @michalk8. 

When I ran `from cellrank.tl.kernels import VelocityKernel` it said 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[25], line 1
----> 1 from cellrank.tl.kernels import VelocityKernel
      3 #vk = VelocityKernel(adata)

ModuleNotFoundError: No module named 'cellrank.tl'
```

**Comment by michalk8** [comment]
It should be ``from cellrank.kernels import VelocityKernel``.

**Comment by denvercal1234GitHub** [comment]
Thanks so much @michalk8. I seemed to have a wrong tutorial page (https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html)?
