### ISSUE TITLE
ctk.compute_projection does not work on CytoTRACEKernel

### ISSUE THREAD

**Issue by wfaalajr** [theislab/cellrank#1038]
I have been following the "CellRank beyond RNA velocity" vignette and I am currently stuck on the 'compute_projection' step. When I execute this, it says: "AttributeError: 'CytoTRACEKernel' object has no attribute 'compute_projection'". I checked for related issues, and it seems like the vignette is no longer up to date. I have the 'master' version of CellRank installed. Can anyone help on this part? Not really an expert on this.

```
import scvelo as scv
import scanpy as sc
import cellrank as cr
import numpy as np
scv.settings.verbosity = 3
scv.settings.set_figure_params("scvelo")
cr.settings.verbosity = 2

#Load h5ad object
adata = sc.read_h5ad("scrnaseq_local/object.h5ad")
adata

scv.pl.scatter(adata, alpha=0.7, color='Pseudotime', legend_loc="right")
sc.pl.umap(adata, color='CellType')

#Pre-process [filter, normalize, log-transform]
sc.pp.filter_genes(adata, min_cells=10)
scv.pp.normalize_per_cell(adata)
sc.pp.log1p(adata)

#HVG annotation
sc.pp.highly_variable_genes(adata)
print(f"This detected {np.sum(adata.var['highly_variable'])} highly variable genes.")

#Use scvelo 'moments' function for imputation of 'spliced' and 'unspliced' counts
#Stash '.X' matrix to layers since scv.tl.moments expects the counts to be there
adata.layers["spliced"] = adata.X
adata.layers["unspliced"] = adata.X
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)

#Run CytoTRACE kernel
from cellrank.kernels import CytoTRACEKernel
ctk = CytoTRACEKernel(adata).compute_cytotrace()

#Compute transition matrix
ctk.compute_transition_matrix(threshold_scheme="soft", nu=0.5)
ctk.compute_projection(basis="umap")

```

**Comment by Marius1311** [comment]
Hey! Should be here now: https://cellrank.readthedocs.io/en/latest/api/_autosummary/kernels/cellrank.kernels.CytoTRACEKernel.html#cellrank.kernels.CytoTRACEKernel.plot_projection

**Comment by wfaalajr** [comment]
@Marius1311 Thanks for this! So what should be the steps after ctk.compute_transition_matrix(threshold_scheme="soft", nu=0.5)?

Should it be like:

ctk.plot_projection(basis='umap')

and then just proceed with the rest of the vignette?

**Comment by Marius1311** [comment]
Yes, as in the updated tutorial: https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/cellrank_meets_cytotrace.html

**Comment by michalk8** [comment]
I assume this has been resolved, if not, please feel free to re-open. Closing this.
