### ISSUE TITLE
Fix extensions in naming

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#1057]
Also, maybe this is just me, but I find it very frustrating when packages try to be smart about how they name files for me. If I pass `filename="my_file_name.pickle"`, I don't want it to add extensions by default. Can we set `ext=None` by default?

_Originally posted by @dburkhardt in https://github.com/theislab/cellrank/issues/904#issuecomment-1533444319_

**Comment by michalk8** [comment]
closed via 86ee069
