### ISSUE TITLE
TypeError: Fatal model failure ``.

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#1077]
### Discussed in https://github.com/theislab/cellrank/discussions/1076

<div type='discussions-op-text'>

<sup>Originally posted by **alexandre-jf-fernandes** June 28, 2023</sup>
Hi there,

I'm using cell rank, and every step works correctly unless the model fits. I tried every model and had the same problem. 
When I use the model data, it shows the following error:

`TypeError: Fatal model failure ``.`

Any thoughts?</div>

**Comment by Marius1311** [comment]
Hi @alexandre-jf-fernandes, I converted this into an issue. Please provide us with the output of `cellrank.logging.print_versions()`

**Comment by alexandre-jf-fernandes** [comment]
Hello again,

The output is 

`cellrank==1.5.1 scanpy==1.9.3 anndata==0.9.1 numpy==1.21.1 numba==0.57.0 scipy==1.10.1 pandas==2.0.2 pygpcca==1.0.4 scikit-learn==1.2.2 statsmodels==0.14.0 python-igraph==0.10.4 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2`


The traceback is: 

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File [~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/ul/models/_base_model.py:65](https://file+.vscode-resource.vscode-cdn.net/Users/alexandrefernandes/Library/CloudStorage/OneDrive-UniversidadedeLisboa/Thesis/OralHumanMouse/mouse/CellRank/~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/ul/models/_base_model.py:65), in _handle_exception..handle..wrapper(wrapped, instance, args, kwargs)
     64         instance.reraise()
---> 65     return wrapped(*args, **kwargs)
     66 except Exception as e:  # noqa: B902

TypeError: prepare() got an unexpected keyword argument 'how_all_genes'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[72], line 3
      1 n_genes = 200
      2 genes='Krt14'
----> 3 ax = cr.pl.heatmap(adata, model, genes=genes,
      4               show_absorption_probabilities=False,
      5               lineages='1', n_jobs=1, backend='loky', how_all_genes=True,time_key='end_points')

File [~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/ul/_utils.py:286](https://file+.vscode-resource.vscode-cdn.net/Users/alexandrefernandes/Library/CloudStorage/OneDrive-UniversidadedeLisboa/Thesis/OralHumanMouse/mouse/CellRank/~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/ul/_utils.py:286), in _genesymbols(wrapped, instance, args, kwargs)
    276 @wrapt.decorator
    277 def _genesymbols(
    278     wrapped: Callable[..., Any], instance: Any, args: Any, kwargs: Any
    279 ) -> Any:
    280     with _gene_symbols_ctx(
    281         args[0],
    282         key=kwargs.pop("gene_symbols", None),
    283         make_unique=True,
    284         use_raw=kwargs.get("use_raw", False),
    285     ):
--> 286         return wrapped(*args, **kwargs)

File [~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/pl/_heatmap.py:538](https://file+.vscode-resource.vscode-cdn.net/Users/alexandrefernandes/Library/CloudStorage/OneDrive-UniversidadedeLisboa/Thesis/OralHumanMouse/mouse/CellRank/~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/pl/_heatmap.py:538), in heatmap(adata, model, genes, lineages, backward, mode, time_key, time_range, callback, cluster_key, show_absorption_probabilities, cluster_genes, keep_gene_order, scale, n_convolve, show_all_genes, cbar, lineage_height, fontsize, xlabel, cmap, dendrogram, return_genes, return_models, n_jobs, backend, show_progress_bar, figsize, dpi, save, **kwargs)
    536 kwargs["time_key"] = time_key
    537 models = _create_models(model, genes, lineages)
--> 538 all_models, data, genes, lineages = _fit_bulk(
    539     models,
    540     _create_callbacks(adata, callback, genes, lineages, **kwargs),
    541     genes,
    542     lineages,
    543     time_range,
    544     return_models=True,  # always return (better error messages)
    545     filter_all_failed=True,
    546     parallel_kwargs={
    547         "show_progress_bar": show_progress_bar,
    548         "n_jobs": _get_n_cores(n_jobs, len(genes)),
    549         "backend": _get_backend(models, backend),
    550     },
    551     **kwargs,
    552 )
    554 xlabel = time_key if xlabel is None else xlabel
    556 logg.debug(f"Plotting `{mode!r}` heatmap")

File [~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/pl/_utils.py:485](https://file+.vscode-resource.vscode-cdn.net/Users/alexandrefernandes/Library/CloudStorage/OneDrive-UniversidadedeLisboa/Thesis/OralHumanMouse/mouse/CellRank/~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/pl/_utils.py:485), in _fit_bulk(models, callbacks, genes, lineages, time_range, parallel_kwargs, return_models, filter_all_failed, **kwargs)
    469 models = parallelize(
    470     _fit_bulk_helper,
    471     genes,
   (...)
    481     **kwargs,
    482 )
    483 logg.info("    Finish", time=start)
--> 485 return _filter_models(
    486     models, return_models=return_models, filter_all_failed=filter_all_failed
    487 )

File [~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/pl/_utils.py:534](https://file+.vscode-resource.vscode-cdn.net/Users/alexandrefernandes/Library/CloudStorage/OneDrive-UniversidadedeLisboa/Thesis/OralHumanMouse/mouse/CellRank/~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/pl/_utils.py:534), in _filter_models(models, return_models, filter_all_failed)
    530         for model in ms.values():
    531             assert isinstance(
    532                 model, FailedModel
    533             ), f"Expected `FailedModel`, found `{type(model).__name__!r}`."
--> 534             model.reraise()
    536 if not np.all(modelmask.values):
    537     failed_models = modelmat.values[~modelmask.values]

File [~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/ul/models/_base_model.py:1351](https://file+.vscode-resource.vscode-cdn.net/Users/alexandrefernandes/Library/CloudStorage/OneDrive-UniversidadedeLisboa/Thesis/OralHumanMouse/mouse/CellRank/~/miniconda3/envs/cellrank/lib/python3.9/site-packages/cellrank/ul/models/_base_model.py:1351), in FailedModel.reraise(self)
   1349 """Raise the original exception with additional model information."""
   1350 # retain the exception type and also the original exception
-> 1351 raise type(self._exc)(f"Fatal model failure `{self}`.") from self._exc

TypeError: Fatal model failure ``.`

**Comment by michalk8** [comment]
Hi , @alexandre-jf-fernandes , if you go above the traceback, it says:
```pytb
TypeError: prepare() got an unexpected keyword argument 'how_all_genes'
```
`how_all_genes` is not a valid argument for `prepare`, so you're passing something extra.

**Comment by alexandre-jf-fernandes** [comment]
Do you have any tips to solve this? Because I do everything like in the tutorial and the error appears

**Comment by Marius1311** [comment]
I would recommend writing `show_all_genes` rather than `how_all_genes`, as in the tutorial (see screenshot below). 


<img width="766" alt="Screenshot 2023-06-29 at 21 39 22" src="https://github.com/theislab/cellrank/assets/24494650/840c79e8-4554-46ee-8198-6116958f0ca6">
