### ISSUE TITLE
Attribute Error; can't set attribute 

### ISSUE THREAD

**Issue by AnuSitu1** [theislab/cellrank#1078]
Hi, I am running cellrank on a preprocessed data set and I am experiencing a repreated issue of "can't set attribute on the following codes:

ctk.plot_projection(basis="umap", color="Sample", stream=True, legend_loc="left")

ctk.plot_random_walks()

g_fwd.compute_macrostates(n_states=11, cluster_key='seurat_clusters')

I moved along assuming these errors were simply bugs seeing as the plots and calculations were still performed. However, the code fails at plotting the macrostates. 

#### Versions:
These are my package versions.
cellrank==1.5.2.dev232+g705f070 scanpy==1.9.3 anndata==0.9.1 numpy==1.23.5 numba==0.56.4 scipy==1.10.1 pandas==2.0.1 pygpcca==1.0.4 scikit-learn==1.2.2 statsmodels==0.14.0rc0 python-igraph==0.10.4 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2

**Comment by AnuSitu1** [comment]
Here is the exact code and output: 
ctk.plot_projection(basis="umap", color="Sample", stream=True, legend_loc="left")

Output:

Using precomputed projection `adata.obsm['T_fwd_umap']`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[43], line 10
      1 import pandas
      3 # ctk.compute_projection(basis="umap")
      4 
      5 # scv.pl.velocity_embedding_stream(
      6 #     adata, 
      7 #     color="Sample", vkey="T_fwd", basis="umap", legend_loc="right"
      8 #     )
---> 10 ctk.plot_projection(basis="umap", color="Sample", stream=True, legend_loc="left")

File [~/.virtualenvs/Cell_Rank_April2023/lib/python3.9/site-packages/cellrank/kernels/_utils.py:263](https://file+.vscode-resource.vscode-cdn.net/Users/anusitu/Work_Documents/anuSingleCells/trajectory_inference/cellrank_python/~/.virtualenvs/Cell_Rank_April2023/lib/python3.9/site-packages/cellrank/kernels/_utils.py:263), in require_tmat(wrapped, instance, args, kwargs)
    261 if instance.transition_matrix is None:
    262     raise RuntimeError("Compute transition matrix first as `.compute_transition_matrix()`.")
--> 263 return wrapped(*args, **kwargs)

File [~/.virtualenvs/Cell_Rank_April2023/lib/python3.9/site-packages/cellrank/kernels/_base_kernel.py:294](https://file+.vscode-resource.vscode-cdn.net/Users/anusitu/Work_Documents/anuSingleCells/trajectory_inference/cellrank_python/~/.virtualenvs/Cell_Rank_April2023/lib/python3.9/site-packages/cellrank/kernels/_base_kernel.py:294), in KernelExpression.plot_projection(self, basis, key_added, recompute, stream, connectivities, **kwargs)
    292 proj = TmatProjection(self, basis=basis)
    293 proj.project(key_added=key_added, recompute=recompute, connectivities=connectivities)
--> 294 proj.plot(stream=stream, **kwargs)

File [~/.virtualenvs/Cell_Rank_April2023/lib/python3.9/site-packages/cellrank/kernels/utils/_projection.py:139](https://file+.vscode-resource.vscode-cdn.net/Users/anusitu/Work_Documents/anuSingleCells/trajectory_inference/cellrank_python/~/.virtualenvs/Cell_Rank_April2023/lib/python3.9/site-packages/cellrank/kernels/utils/_projection.py:139), in TmatProjection.plot(self, stream, *args, **kwargs)
    122 """Plot projected transition matrix in a embedding.
    123 
...
File [~/.virtualenvs/Cell_Rank_April2023/lib/python3.9/site-packages/pandas/core/arrays/categorical.py:2460](https://file+.vscode-resource.vscode-cdn.net/Users/anusitu/Work_Documents/anuSingleCells/trajectory_inference/cellrank_python/~/.virtualenvs/Cell_Rank_April2023/lib/python3.9/site-packages/pandas/core/arrays/categorical.py:2460), in CategoricalAccessor._delegate_property_set(self, name, new_values)
   2459 def _delegate_property_set(self, name, new_values):
-> 2460     return setattr(self._parent, name, new_values)

AttributeError: can't set attribute

**Comment by Zodiac111111** [comment]
hi, I encounter the same issue and install the scvelo through the master, but the error still there.

**Comment by aterceros** [comment]
Hello,

I computed a transition matrix using RealTimeKernel and subsequently fed it to cr.estimators.GPCCA(vk) to compute macrostates. However I'm also getting the error "AttributeError: can't set attribute" when running plot_macrostates(). I downloaded the scvelo through the master but it persists, and even tried downgrading pandas. Any hints on how to solve the error? 
Thanks in advance

**Comment by Marius1311** [comment]
Hi @aterceros, please print relevant package versions.

**Comment by aterceros** [comment]
Hi @Marius1311,
Thank you for the reply, the package versions I have are: pandas 1.5.3, scvelo 0.3.0, cellrank 2.0.0, scanpy 1.9.5, mascot 0.3.3, numpy 1.24.4, numba 0.58.0, pygpcca 1.0.4.

**Comment by outland21** [comment]
Hi,
I'm also getting the error "AttributeError: can't set attribute" when running "PseudotimeKernel.plot_random_walks" and "gpcca.plot_macrostates". I have downloaded the scvelo through the master, but it's not work. My packages version are "cellrank==2.0.0 scanpy==1.9.5 anndata==0.9.1 numpy==1.24.4 numba==0.57.1 scipy==1.10.1 pandas==2.0.3 pygpcca==1.0.4 scikit-learn==1.3.2 statsmodels==0.14.0 scvelo==0.3.0 pygam==0.8.0 matplotlib==3.7.3 seaborn==0.13.0". Any hints on how to solve the error?
Thanks!

**Comment by michalk8** [comment]
Can you please post the full traceback? Otherwise it's hard to debug.

**Comment by outland21** [comment]
Sure. I am running cellrank 2 tutorial 100_getting_started.ipynb, I encounter this error when I am running " pk.plot_random_walks(
    seed=0,
    n_sims=100,
    start_ixs={"clusters": "HSC_1"},
    basis="tsne",
    legend_loc="right",
    dpi=150
)". And the full traceback is:
AttributeError                            Traceback (most recent call last)
Cell In[27], line 1
----> 1 pk.plot_random_walks(
      2    # seed=0,
      3     #n_sims=10,
      4     #start_ixs={"clusters": "HSC_1"},
      5     #basis="umap",
      6     #legend_loc="right",
      7     #dpi=150
      8 )

File ~/miniconda3/envs/cr2-py38/lib/python3.8/site-packages/cellrank/kernels/_utils.py:184, in require_tmat(wrapped, instance, args, kwargs)
    182 if instance.transition_matrix is None:
    183     raise RuntimeError("Compute transition matrix first as `.compute_transition_matrix()`.")
--> 184 return wrapped(*args, **kwargs)

File ~/miniconda3/envs/cr2-py38/lib/python3.8/site-packages/cellrank/kernels/_base_kernel.py:246, in KernelExpression.plot_random_walks(self, n_sims, max_iter, seed, successive_hits, start_ixs, stop_ixs, basis, cmap, linewidth, linealpha, ixs_legend_loc, n_jobs, backend, show_progress_bar, figsize, dpi, save, **kwargs)
    235 rw = RandomWalk(self.adata, self.transition_matrix, start_ixs=start_ixs, stop_ixs=stop_ixs)
    236 sims = rw.simulate_many(
    237     n_sims=n_sims,
    238     max_iter=max_iter,
   (...)
    243     show_progress_bar=show_progress_bar,
    244 )
--> 246 rw.plot(
    247     sims,
    248     basis=basis,
    249     cmap=cmap,
    250     linewidth=linewidth,
    251     linealpha=linealpha,
    252     ixs_legend_loc=ixs_legend_loc,
    253     figsize=figsize,
    254     dpi=dpi,
    255     save=save,
    256     **kwargs,
    257 )

File ~/miniconda3/envs/cr2-py38/lib/python3.8/site-packages/cellrank/kernels/utils/_random_walk.py:236, in RandomWalk.plot(self, sims, basis, cmap, linewidth, linealpha, ixs_legend_loc, figsize, dpi, save, **kwargs)
    229     cmap = LinearSegmentedColormap.from_list(
    230         "random_walk",
    231         colors=cmap.colors,
    232         N=max(map(len, sims)),
    233     )
    235 fig, ax = plt.subplots(figsize=figsize, dpi=dpi)
--> 236 scv.pl.scatter(self._adata, basis=basis, show=False, ax=ax, **kwargs)
    238 logg.info("Plotting random walks")
    239 for sim in sims:

File ~/miniconda3/envs/cr2-py38/lib/python3.8/site-packages/scvelo/plotting/scatter.py:668, in scatter(adata, basis, x, y, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_loc_lines, legend_fontsize, legend_fontweight, legend_fontoutline, legend_align_text, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, add_density, add_assignments, add_linfit, add_polyfit, add_rug, add_text, add_text_pos, add_margin, add_outline, outline_width, outline_color, n_convolve, smooth, normalize_data, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    666     if not (add_outline is None or g_bool is None):
    667         groups = add_outline
--> 668     set_legend(
    669         adata,
    670         ax,
    671         color,
    672         legend_loc,
    673         scatter_array,
    674         legend_fontweight,
    675         legend_fontsize,
    676         legend_fontoutline,
    677         legend_align_text,
    678         groups,
    679     )
    680 if add_density:
    681     plot_density(x, y, add_density, ax=ax)

File ~/miniconda3/envs/cr2-py38/lib/python3.8/site-packages/scvelo/plotting/utils.py:555, in set_legend(adata, ax, value_to_plot, legend_loc, scatter_array, legend_fontweight, legend_fontsize, legend_fontoutline, legend_align_text, groups)
    553     legend_fontoutline = 1
    554 obs_vals = adata.obs[value_to_plot]
--> 555 obs_vals.cat.categories = obs_vals.cat.categories.astype(str)
    556 color_keys = adata.uns[f"{value_to_plot}_colors"]
    557 if isinstance(color_keys, dict):

File ~/miniconda3/envs/cr2-py38/lib/python3.8/site-packages/pandas/core/base.py:178, in NoNewAttributesMixin.__setattr__(self, key, value)
    172 if getattr(self, "__frozen", False) and not (
    173     key == "_cache"
    174     or key in type(self).__dict__
    175     or getattr(self, key, None) is not None
    176 ):
    177     raise AttributeError(f"You cannot add any new attribute '{key}'")
--> 178 object.__setattr__(self, key, value)

File ~/miniconda3/envs/cr2-py38/lib/python3.8/site-packages/pandas/core/accessor.py:99, in PandasDelegate._add_delegate_accessors.<locals>._create_delegator_property.<locals>._setter(self, new_values)
     98 def _setter(self, new_values):
---> 99     return self._delegate_property_set(name, new_values)

File ~/miniconda3/envs/cr2-py38/lib/python3.8/site-packages/pandas/core/arrays/categorical.py:2460, in CategoricalAccessor._delegate_property_set(self, name, new_values)
   2459 def _delegate_property_set(self, name, new_values):
-> 2460     return setattr(self._parent, name, new_values)

AttributeError: can't set attribute

**Comment by outland21** [comment]
Thank for your reply. This error was solved by reinstall matplotlib version 3.7.0. .

**Comment by aterceros** [comment]
Hello, 

I ran: tmk = RealTimeKernel.from_moscot(tp)
 then computed the transition matrix: tmk.compute_transition_matrix(self_transitions="all", conn_weight=0.2, threshold="auto")
then the estimators: g3 = cr.estimators.GPCCA(tmk)
then compute macrostates: g3.compute_macrostates(n_states=3, cluster_key="time")
but plotting them triggers the error: g3.plot_macrostates(which="all", legend_loc="right",basis='tsne', s=100)

<img width="572" alt="Screenshot 2023-10-28 at 2 11 33 PM" src="https://github.com/theislab/cellrank/assets/99988924/9423985e-f417-49ee-9781-d690539002f2">
