### ISSUE TITLE
Cluster fate plot - Splitting violin plot by subgroups

### ISSUE THREAD

**Issue by skarunan** [theislab/cellrank#1085]
...
Hi,

Is it possible to create violin plot with subgroups (like the hue in seaborn) in the function `cr.pl.cluster_fates(cdata, mode="violin")`?

Many thanks for the great tool.

**Comment by Marius1311** [comment]
Hi @skarunan, I don't think that's currently possible - feel free to open a PR for this, though! FYI, the function has been renamed in the upcoming version 2 and can now be found here: https://cellrank.readthedocs.io/en/latest/api/_autosummary/plotting/cellrank.pl.aggregate_fate_probabilities.html#cellrank.pl.aggregate_fate_probabilities

**Comment by skarunan** [comment]
Thanks, I'll try to work on it.
