### ISSUE TITLE
Can't plot after .terminal_states()

### ISSUE THREAD

**Issue by alexandre-jf-fernandes** [theislab/cellrank#1090]
...
Hi there,

I'm trying to get a heatmap of genes of each macrostate, but when running g_fwd.compute_terminal_states() g_fwd.compute_absorption_probabilities() the not terminal lineages can't longer be used for plotting the heatmap or calculating lineage_drivers. Can you help me?

cr.pl.heatmap(adata, model, genes=epi_list_filtered, backend='loky',  show_all_genes=True, show_absorption_probabilities=True, time_key='velocity_pseudotime', cluster_genes=True, cmap='viridis', )

Output: Just terminal state lineage

**Comment by Marius1311** [comment]
Hey, I think the easiest would be to just manually declare those macrostates as terminal. You can do that using `estimator.set_terminal_states`: https://cellrank.readthedocs.io/en/latest/api/_autosummary/estimators/cellrank.estimators.GPCCA.html#cellrank.estimators.GPCCA.set_terminal_states

**Comment by Marius1311** [comment]
I assume that my comment above solved this issue, feel free to reopen if not.
