### ISSUE TITLE
Inconsistent `time_key` types between `RealTimeKernel.from_moscot()` and `TemporalProblem.prepare()`

### ISSUE THREAD

**Issue by palfalvi** [theislab/cellrank#1104]
Hello,

First of all, thank you for the great tools and the continuous updates. I tried to run moscot+cellrank on my data and I run into some issues. I went back to the tutorial and I encountered the same things:

Moscot's `TemporalProblem.prepare()` requires a numerical `time_key`, while CellRank's `RealTimeKernel.from_moscot()` wants a categorical variable. By running the tutorial example, I get the below error after `tp.prepare(time_key = 'day')`. 

If I change `day` into `day_numerical`, it runs, however CellRank's kernel will fail as it needs a categorical variable.

```pytb
TypeError: Temporal key has to be of numeric type.Found `adata.obs['day']` to be of type `categorical`.
```

```pytb
TypeError: Expected `adata.obs['day_numerical']` to be categorical, found `floating`.
```

#### Versions:

> cellrank==2.0.0 scanpy==1.9.3 anndata==0.9.2 numpy==1.24.4 numba==0.57.1 scipy==1.11.1 pandas==1.5.3 pygpcca==1.0.4 scikit-learn==1.3.0 statsmodels==0.14.0 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2

**Comment by Marius1311** [comment]
Hey @palfalvi, thanks for pointing this out, I ran into the same error and we fixed it on moscot's side here: https://github.com/theislab/moscot/pull/548 Can you please try installing moscot from main to see whether this works for you? 

@MUCDK @michalk8, I think we should make a patch release in moscot to fix this, the RealTimeKernel in CellRank is currently not usable because of this.

**Comment by palfalvi** [comment]
Hey @Marius1311 ,

Thank you for the rapid answer.
I reinstalled moscot from github and now it works fine. 

Best,
Gergo

**Comment by RijndertAriese** [comment]
Hi,

Thanks for developing this powerful tool. 
I ran into the same issue and reinstalled moscot from main, however when passing "Day" as categorical I get the following error:

```
tp <- tp.prepare(time_key="Day", joint_attr='X_scpoli')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 1
----> 1 tp <- tp.prepare(time_key="Day", joint_attr='X_scpoli')

TypeError: bad operand type for unary -: 'TemporalProblem'
```

My adata.obs['Day'] looks like:
```
Name: Day, Length: 55327, dtype: category
Categories (8, float64): [5.0, 11.0, 14.0, 20.0, 30.0, 60.0, 90.0, 120.0]
```
:
<details>
<summary>Versions</summary>
    `
    -----
    anndata     0.10.8
    scanpy      1.10.3
    -----
    PIL                         10.3.0
    absl                        NA
    asttokens                   NA
    backports                   NA
    cellrank                    2.0.6
    cffi                        1.17.1
    chex                        0.1.86
    cloudpickle                 3.0.0
    colorama                    0.4.6
    comm                        0.2.1
    contextlib2                 NA
    cycler                      0.12.1
    cython_runtime              NA
    dateutil                    2.9.0
    debugpy                     1.6.7
    decorator                   5.1.1
    diffrax                     0.6.0
    docrep                      0.3.2
    docstring_inheritance       NA
    equinox                     0.11.7
    etils                       1.9.4
    executing                   0.8.3
    filelock                    3.16.1
    flax                        0.9.0
    fsspec                      2024.9.0
    google                      NA
    h5py                        3.11.0
    igraph                      0.11.6
    ipykernel                   6.28.0
    jaraco                      NA
    jax                         0.4.35
    jax_cuda12_plugin           NA
    jax_plugins                 NA
    jaxlib                      0.4.35
    jaxopt                      NA
    jaxtyping                   0.2.34
    jedi                        0.19.1
    joblib                      1.4.2
    kiwisolver                  1.4.7
    legacy_api_wrap             NA
    leidenalg                   0.10.2
    lightning                   2.4.0
    lightning_utilities         0.11.7
    lineax                      0.0.7
    llvmlite                    0.43.0
    matplotlib                  3.8.4
    matplotlib_inline           0.1.6
    ml_collections              NA
    ml_dtypes                   0.5.0
    more_itertools              10.3.0
    moscot                      0.3.6.dev63+g655e179
    mpl_toolkits                NA
    mpmath                      1.3.0
    msgpack                     1.1.0
    mudata                      0.3.1
    multipledispatch            0.6.0
    natsort                     8.4.0
    networkx                    3.4.2
    numba                       0.60.0
    numpy                       1.26.4
    numpyro                     0.15.3
    nvidia                      NA
    opt_einsum                  v3.3.0
    optax                       0.2.2
    optimistix                  0.0.9
    ott                         0.4.8
    packaging                   24.1
    pandas                      2.2.3
    parso                       0.8.3
    patsy                       0.5.6
    petsc4py                    3.21.5
    pkg_resources               NA
    platformdirs                3.10.0
    plotly                      5.24.1
    progressbar                 4.5.0
    prompt_toolkit              3.0.43
    psutil                      5.9.0
    pure_eval                   0.2.2
    pydev_ipython               NA
    pydevconsole                NA
    pydevd                      2.9.5
    pydevd_file_utils           NA
    pydevd_plugins              NA
    pydevd_tracing              NA
    pygam                       0.9.1
    pygments                    2.18.0
    pygpcca                     1.0.4
    pyparsing                   3.1.4
    pyro                        1.9.1+0a67ddc
    python_utils                NA
    pytz                        2024.2
    rich                        NA
    scipy                       1.12.0
    scvelo                      0.3.2
    scvi                        1.1.6.post2
    seaborn                     0.13.2
    session_info                1.0.0
    six                         1.16.0
    sklearn                     1.1.3
    slepc4py                    3.21.1
    sparse                      0.15.4
    stack_data                  0.2.0
    statsmodels                 0.14.3
    sympy                       1.13.2
    texttable                   1.7.0
    threadpoolctl               3.5.0
    toolz                       0.12.1
    torch                       2.4.0
    torchgen                    NA
    torchmetrics                1.4.2
    tornado                     6.4.1
    tqdm                        4.66.5
    traitlets                   5.14.3
    typeguard                   NA
    typing_extensions           NA
    wcwidth                     0.2.5
    wrapt                       1.16.0
    yaml                        6.0.2
    zmq                         25.1.2
    zstandard                   0.23.0
    -----
    IPython             8.27.0
    jupyter_client      8.6.0
    jupyter_core        5.7.2
    -----
    Python 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
    Linux-4.18.0-553.16.1.el8_10.x86_64-x86_64-with-glibc2.31
    -----
    Session information updated at 2024-11-05 12:04
    `
</details>

**Comment by MUCDK** [comment]
Hi,

This is strange to me. Would you mind posting a short reproducible example? I.e. create a small toy AnnData with the same dtype of `Day`.

**Comment by Marius1311** [comment]
I've encountered this before as well.

**Comment by RijndertAriese** [comment]
> Hi,
> 
> This is strange to me. Would you mind posting a short reproducible example? I.e. create a small toy AnnData with the same dtype of `Day`.

Hi Dominik,

You can download a toy dataset from this link:

https://filesender.surf.nl/?s=download&token=197bda9c-835b-42b2-9a75-fd197481266f

Following the CellRank tutorial I run 
```
adata.obs["Day"] = adata.obs["Day"].astype(float).astype("category")
adata.obs["day_numerical"] = adata.obs["Day"].astype(float)

### Run moscot to couple cells across timepoints
tp = TemporalProblem(toy_adata)
tp = tp.score_genes_for_marginals(gene_set_proliferation="human", gene_set_apoptosis="human")
tp <- tp.prepare(time_key="Day", joint_attr='X_scPoli')
```
Also tried without passing a joint_attr, but it will give the same error after computing the last PCA. 
If you need additional information, .obs/.obsm/.layers, let me know!

Thanks!

**Comment by MUCDK** [comment]
@selmanozleyen can you please have a look?
