### ISSUE TITLE
vk.plot_projection():  KeyError: "Unable to find a basis in `adata.obsm['X_umap']` or `adata.obsm['umap']`."

### ISSUE THREAD

**Issue by GaF123** [theislab/cellrank#1112]
I'm using tsne, when I got this step:
vk.plot_projection()

#Projecting transition matrix onto `umap`
#Adding `adata.obsm['T_fwd_umap']`
# Finish (0:00:00)

KeyError: "Unable to find a basis in `adata.obsm['X_umap']` or `adata.obsm['umap']`."

How can I change it to tsne?

Thank you so much!

**Comment by Marius1311** [comment]
Hi @GaF123, please check the API: https://cellrank.readthedocs.io/en/latest/api/_autosummary/kernels/cellrank.kernels.VelocityKernel.html#cellrank.kernels.VelocityKernel.plot_projection

Should be possible using the `basis` parameter.

**Comment by GaF123** [comment]
thank you it works
