### ISSUE TITLE
Estimating Fate Probabilities and Driver Genes----Uncover driver genes:  RuntimeError: No stationary distribution found in `.eigendecomposition['stationary_dist']`.

### ISSUE THREAD

**Issue by GaF123** [theislab/cellrank#1113]
...
I was doing: Estimating Fate Probabilities and Driver Genes----Uncover driver genes

when I got here: driver_clusters = ["Delta", "Fev+", "Ngn3 high EP", "Ngn3 low EP"]

delta_df = g.compute_lineage_drivers(
    lineages=["Delta"], cluster_key="clusters", clusters=driver_clusters
)
delta_df.head(10)

I changed it to my cell-type: 
driver_clusters = ["4-fib", "1-fib","2-fib","5-fib","7-fib"]

delta_df = g.compute_lineage_drivers(
    lineages=["4-fib"], cluster_key="cell_type", clusters=driver_clusters
)
delta_df.head(10)

But it got this: WARNING: There is only 1 lineage present. Using stationary distribution instead
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[93], line 3
      1 driver_clusters = ["4-fib", "1-fib","2-fib","5-fib","7-fib"]
----> 3 delta_df = g.compute_lineage_drivers(
      4     lineages=["4-fib"], cluster_key="cell_type", clusters=driver_clusters
      5 )
      6 delta_df.head(10)

File ~/anaconda3/envs/py39/lib/python3.9/site-packages/cellrank/estimators/mixins/_lineage_drivers.py:126, in LinDriversMixin.compute_lineage_drivers(self, lineages, method, cluster_key, clusters, layer, use_raw, confidence_level, n_perms, seed, **kwargs)
    124     stat_dist = self.eigendecomposition.get("stationary_dist", None)
    125     if stat_dist is None:
--> 126         raise RuntimeError("No stationary distribution found in `.eigendecomposition['stationary_dist']`.")
    127     fate_probs = Lineage(
    128         stat_dist,
    129         names=fate_probs.names,
    130         colors=fate_probs.colors,
    131     )
    133 # check all lin_keys exist in self.lin_names

RuntimeError: No stationary distribution found in `.eigendecomposition['stationary_dist']`.

Thank you, please help.

**Comment by Marius1311** [comment]
Hi @GaF123, it looks like you only have a single terminal state present in your data, is that correct? At least that's what the warning indicates.

**Comment by GaF123** [comment]
Yes I only have one terminal state. Does that mean I can't use this function? Or how can I change it to make the function correct?
Thank you

**Comment by Marius1311** [comment]
If you only have one terminal state, say it's called `A`, then computing fate probabilities does not make sense because every cell will have 100% fate probability of transitioning towards `A`, because you give it no alternative. It this case, CellRank computes the stationary distribution instead, which tells about the long term evolution of the associated Markov chain. If you're interested in fate probabilities, make sure you have at least two terminal states.
