### ISSUE TITLE
How to delete gridlines in figures

### ISSUE THREAD

**Issue by ryanhchung** [theislab/cellrank#1116]
...
Hi Team,

I was wondering how to remove gridlines from each figure.

For example, in scvelo, they provide an option scv.set_figure_params('scvelo') to remove gridlines and make the plot more beautiful, but I was wondering cellrank2 also provides a similar function

Thanks in advance

**Comment by Marius1311** [comment]
Hi @ryanhchung, under the hood, CellRank 2 uses scVelo or scanpy for many plotting functions - have you tried setting parameters for scVelo as you described above also for CellRank analysis?

**Comment by ryanhchung** [comment]
Hi @Marius1311 

It works

Thanks!
