### ISSUE TITLE
Request for Intestinal organoid dataset(scEU-seq)

### ISSUE THREAD

**Issue by xfchen0912** [theislab/cellrank#1117]
Hi there,
I noticed that CellRank2 already supports analysis of metabolic labeling data and provides example data, but the dataset does not provide a download link, please update the download link for the **intestinal organoid dataset** to datasets.py
Thank you very much!

**Comment by michalk8** [comment]
cc'ing @WeilerP

**Comment by WeilerP** [comment]
@xfchen0912, we will not expose the data via a corresponding function in `cellrank`. As mentioned in the reproducibility README, you can simply download the corresponding files from FigShare [here](https://figshare.com/account/home#/projects/88787).

**Comment by Marius1311** [comment]
I think the correct download link would be:
- Raw data: https://figshare.com/ndownloader/files/41674299
- Processed data: https://figshare.com/ndownloader/files/41674206
