### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by JuliaChristiaanse** [theislab/cellrank#1119]
Hi there Cellrank people,

I am new to this part of scRNA seq analysis and I really want to give rna velocity a shot.. While running scv.tl.recover_dynamics(adata, n_jobs=8) according to your tutorial https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/kernels/200_rna_velocity.html I came across this error:

ValueError                                Traceback (most recent call last)
Cell In[29], line 1
----> 1 scv.tl.recover_dynamics(adata, n_jobs=8)

File [c:\Users\julia\.virtualenvs\project-VjJne3mB\lib\site-packages\scvelo\tools\dynamical_model.py:588](file:///C:/Users/julia/.virtualenvs/project-VjJne3mB/lib/site-packages/scvelo/tools/dynamical_model.py:588), in recover_dynamics(data, var_names, n_top_genes, max_iter, assignment_mode, t_max, fit_time, fit_scaling, fit_steady_states, fit_connected_states, fit_basal_transcription, use_raw, load_pars, return_model, plot_results, steady_state_prior, add_key, copy, n_jobs, backend, **kwargs)
    585     adata.varm["loss"] = loss
    587 if t_max is not False:
--> 588     dm = align_dynamics(adata, t_max=t_max, dm=dm, idx=idx)
    590 logg.info("    finished", time=True, end=" " if settings.verbosity > 2 else "\n")
    591 logg.hint(
    592     "added \n"
    593     f"    '{add_key}_pars', "
    594     f"fitted parameters for splicing dynamics (adata.var)"
    595 )

File [c:\Users\julia\.virtualenvs\project-VjJne3mB\lib\site-packages\scvelo\tools\dynamical_model.py:721](file:///C:/Users/julia/.virtualenvs/project-VjJne3mB/lib/site-packages/scvelo/tools/dynamical_model.py:721), in align_dynamics(data, t_max, dm, idx, mode, remove_outliers, copy)
    718 if dm is not None and dm.recoverable:
    719     dm.m = m[idx]
    720     dm.alpha, dm.beta, dm.gamma, dm.pars[:3] = (
--> 721         np.array([dm.alpha, dm.beta, dm.gamma, dm.pars[:3]]) / dm.m[-1]
    722     )
    723     dm.t, dm.tau, dm.t_, dm.pars[4] = (
    724         np.array([dm.t, dm.tau, dm.t_, dm.pars[4]]) * dm.m[-1]
    725     )
    727 return adata if copy else dm

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

When running with the cellrank test dataset of the tutorial & if I run my own dataset. I have an anndata object of 10X genomics cellranger output with a .loom file output from a velocyto run. I now added spliced and unspliced layers of the loom file as layers to my anndata object and did all steps according to your vignette up to this one. 
Are there any pre-processing steps I missed that might come before this? Or might this be a bug?

Thank you in advance for your reply!

Kind regards, a bioinformatics student :)

**Comment by Marius1311** [comment]
HI @JuliaChristiaanse, please try installing scVelo from main.

**Comment by JuliaChristiaanse** [comment]
HI @Marius1311 I had already installed scVelo, I re-installed it, and the problem still persisted. Any other suggestions?

**Comment by Marius1311** [comment]
Closing this issue, installing scVelo from the master branch on GitHub should resolve this. In the future, a patch release in scVelo will resolve this.
