### ISSUE TITLE
Remove L2 penalty from pygam models

### ISSUE THREAD

**Issue by bfurtwa** [theislab/cellrank#1126]
The cellrank GAM model initializes by default with `penalties=["derivative", "l2"]`. However the default for pygam is: 

> Available penalties - second derivative smoothing (default on numerical features) - L2 smoothing (default on categorical features)
https://pygam.readthedocs.io/en/latest/notebooks/tour_of_pygam.html#Penalties-/-Constraints

Removing the L2 penalty improves the fits a lot, especially for me at the start of the lineage where I have a small number of cells that would be seen as outliers by L2. It also makes the confidence interval much more believable.

So I would request to either make the penalties available via `spline_kwargs` or remove L2 in the code.

**Comment by Marius1311** [comment]
Interesting! We should for sure expose this to the user @michalk8, and we might want to adjust our defaults. Thank you for reporting this @bfurtwa!
