### ISSUE TITLE
Using Seurat SNN graph in place of connectivities matrix

### ISSUE THREAD

**Issue by WesleyRosales** [theislab/cellrank#1129]
Hello! First off, thank you for creating such a useful package! It has been very useful for my analyses.

I have a dataset with a shared nearest neighbor graph derived from Seurat's Weighted Nearest Neighbor algorithm. I want to use this graph in a ConnectivityKernel, replacing the default RNA-based connectivities matrix. As far as I can tell, the Seurat's weighted SNN graph and the connectivities matrix from Scanpy's neighbors algorithm both contain euclidean distance between cells' nearest neighbors. In your opinion, would it be bad practice to use Seurat's weighted SNN graph as the connectivities matrix in the ConnectivityKernel?

Thank you for your time,
Wesley

**Comment by Marius1311** [comment]
Hi @WesleyRosales, that should be perfectly fine! I think that's a good approach to include multi-modal data in CellRank.

**Comment by WesleyRosales** [comment]
Fantastic! Thanks for your quick reply!
