### ISSUE TITLE
Tests for GPCCA

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#113]

**Comment by Marius1311** [comment]
As of https://github.com/msmdev/msmtools/pull/9, the SLEPSc dependency for `brandts` is gone, so we can start writing tests! Should we only write these, assuming that `brandts` is used, to avoid having to install SLEPSc during the tests?

**Comment by michalk8** [comment]
Implemented via #178

**Comment by Marius1311** [comment]
Wow, that was quick... Amazing!
