### ISSUE TITLE
A question about g.predict_terminal_states(method="top_n", n_states=6) and g.plot_macrostates(which="terminal")

### ISSUE THREAD

**Issue by liuyang218622** [theislab/cellrank#1131]
I used this tutorial (https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/general/100_getting_started.html) to analyze our sc-RNA-seq data. 
I suffered from a question: 
When I calculated the terminal status for each batch, I got the results below: 
![image](https://github.com/theislab/cellrank/assets/13673840/70776840-8ad0-4033-8567-85f4d9cf5ebc)
For example, in this picture, we can find that KO1 had the terminal status of granulocytes1 and granulocytes2, and KO2 had the terminal status of granulocytes1 and granulocytes3. But when we combine the KO1 and KO2 together. we got the granulocytes2 and granulocytes4. 
<img width="189" alt="image" src="https://github.com/theislab/cellrank/assets/13673840/8b6aa1ee-447b-425a-bd6a-a75a2862ec44">
Why do we get the granulocytes4  in KO? why do the granulocytes1 and granulocytes3 lost?

**Comment by Marius1311** [comment]
Hi @liuyang218622, might this just be a question of the number of terminal states you're looking for? Maybe different terminal states are more or less dominant between the different conditions, the their relative ordering changes? There might then be an additional change in their order when you combine the two perturbations. It's probably best to define a joint set of terminal states across the two perturbations, and then combine them in terms of fate probabilities, e.g. contrast the different conditions in terms of their induced fate bias. Compare Fig. 4 in this recent paper, which compares fate probabilities between WT and perturbed brain organoids using CellRank 2: https://www.nature.com/articles/s41586-023-06473-y

**Comment by Marius1311** [comment]
Closing this, feel free to reopen if the issues persists.
