### ISSUE TITLE
Saving vk.plot_projection()

### ISSUE THREAD

**Issue by JuliaChristiaanse** [theislab/cellrank#1133]
Hello CellRank team!

I am quite new to cellrank and recently made some lovely RNA velocity plots which I would love to save to my specified directory.
I noticed there isn't a "save" argument for vk.plot_projection(). Can I still save the plot?

Thank you in andvance.

Kind regards,

**Comment by Marius1311** [comment]
Hi @JuliaChristiaanse, can you try whether passing `save=PATH` still works? We might just have forgotten to expose the argument. @michalk8

**Comment by Marius1311** [comment]
sure, great to hear that this worked!
