### ISSUE TITLE
AttributeError: module 'cellrank' has no attribute 'kernels' 

### ISSUE THREAD

**Issue by jwalewski** [theislab/cellrank#1137]
When I attempt to run cellrank in a conda enviornment that also contains velocyto (so that I can generate my count matrices and then proceed) I am running into an issue where cellrank claims it has no kernel module, despite me copying and pasting the vignette into my shell script.

```python
# ------- 1. installing packages common to all vignettes -------
print("Step 2: cellrank preprocessing has begun")
import numpy as np
import sys
import pandas as pd
import cellrank as cr
import scvelo as scv
import scanpy as sc
import warnings
warnings.simplefilter("ignore", category=UserWarning)

## ------- 2. Configuring basic packages -------
scv.settings.verbosity = 3
sc.settings.set_figure_params("scvelo") #these may change as we wish
cr.settings.verbosity = 2
warnings.simplefilter("ignore", category=UserWarning)

# ------- 3. read input data from loom file generated from velocyto -------
adata = scv.read("<my_data>.loom", cache=True) 
# Loading in test data & confirming
scv.pl.proportions(adata)
adata

# ------- 4. Running scVelo -------
# Running scvelo
scv.tl.recover_dynamics(adata, n_jobs=8)
scv.tl.velocity(adata, mode="dynamical")

# ------ 5. main RNA Velocity Kernel --------
vk = cr.kernels.VelocityKernel(adata)
...
```

```pytb
AttributeError: module 'cellrank' has no attribute 'kernels'
...
```

Any ideas about what could be going on here?

**Comment by Marius1311** [comment]
I guess this must be an outdated CellRank version, could be due to some version conflicts with velocyto.

**Comment by jwalewski** [comment]
I'm quite sure this is the most recent version (I installed from conda a few days ago). How can I check for sure?

**Comment by michalk8** [comment]
Try running `python -c "import cellrank; print(cellrank.__version__)"`.

**Comment by jwalewski** [comment]
I have version 2.0.0

This is the the most up to date version, right?

**Comment by michalk8** [comment]
Yes, I made `2.0.1` release a few days back, but `conda` version will come soon (hopefully end of this week).
Am thinking there can be 2 reasons while the `cellrank.kernels` is not found:
1. the script is using an interpreted with `cellrank<2` - can be checked by printing the version in your script
2. somehow importing `cellrank` causes only partial module initialization (not sure how though, it should raise the error) - can be checked by running `python -c "import cellrank.kernels; print(print(cellrank.kernels.__all__))"`

**Comment by jwalewski** [comment]
1. Interestingly enough, I verified the version by printing it in the terminal, so I know that it is running v2.0.0.
2. Thanks for that suggestion, it was very informative - even when explicity importing cellrank.kernels I still get the issue of ```
$ python -c 'import cellrank.kernels; print(print(cellrank.kernels.__all__))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cellrank.kernels'
```

Any idea of why this could be the case?

**Comment by michalk8** [comment]
Maybe for some reason it's just not loaded; one way to test would be running:
```bash
python -c "import cellrank.kernels; print(cellrank.kernels.__all__)"
```

**Comment by jwalewski** [comment]
Thanks for your suggestion, but I tried doing that and again it gave the same error.

**Comment by Marius1311** [comment]
Hi @jwalewski, does the error persist when you re-install the current CellRank version from conda?

**Comment by Marius1311** [comment]
Closing this, fee free to reopen if the error still persists in the current CellRank version.
