### ISSUE TITLE
Where to find the old tutorials?

### ISSUE THREAD

**Issue by hyjforesight** [theislab/cellrank#1149]
Hello CellRank,
Just realized that this amazing package was updated to v2, which is awesome and fascinating!
I used the v1 version and could you please let me know where I can find the v1 tutorials since I'm writing the Methods.

Thank you!
Best,
Yuanjian

**Comment by michalk8** [comment]
Hi @hyjforesight , you can find the old tutorial for example here https://github.com/theislab/cellrank_notebooks/tree/804c8de61d98fd9b887b3184d1a446e5fe617aee/tutorials

**Comment by hyjforesight** [comment]
Thank you @michalk
I close this issue.
