### ISSUE TITLE
A question about cr.pl.circular_projection parameter "normalize_by_mean"

### ISSUE THREAD

**Issue by yulicarp** [theislab/cellrank#1150]
Hi, 

Thanks for this amazing work! 

I have a questions about using the parameter `normalize_by_mean` set to `True`.  When I focus the `early cells` terminal fate probabilities and try to interpret it trajectory fate, it seem different from the results using another function `cr.pl.aggregate_fate_probabilities`. Here are the results I got using different methods. 

when "normalize_by_mean" set to `True`, it seems `HSC_MPP` was `MKP` and `NeuP` bias. But when `normalize_by_mean` set to `False`, it seems `HSC_MPP` was `ProB` bias and same to `cr.pl.aggregate_fate_probabilities` results.

Could you tell me how to interpret these results? i am really confused.

1. when "normalize_by_mean" set to `True`
<img width="371" alt="截屏2024-01-10 10 34 00" src="https://github.com/theislab/cellrank/assets/68860278/d3279a4b-f2a3-4d74-b8b3-2c06cda7e641">

2. when "normalize_by_mean" set to `False`
<img width="382" alt="截屏2024-01-10 10 34 25" src="https://github.com/theislab/cellrank/assets/68860278/cc6cc1f0-2c76-41bf-91bc-c0f045823508">

3. when using `cr.pl.aggregate_fate_probabilities`
<img width="576" alt="截屏2024-01-10 10 37 05" src="https://github.com/theislab/cellrank/assets/68860278/d15b7e57-836c-463b-98c7-5c2ff00a051f">

**Comment by Marius1311** [comment]
Hi @yulicarp, when you use the option `normalize_by_mean=True`, then you run
```python
X = probs.X.copy()
    if normalize_by_mean:
        X /= np.mean(X, axis=0)[None, :]
        X /= X.sum(1)[:, None]
        # this happens when cells for sel. lineages sum to 1 (or when the lineage average is 0, which is unlikely)
        X = np.nan_to_num(X, nan=1.0 / probs.nlin, copy=False)
```

where `X` should be an array of shape `n_cells x n_terminal_states` containing fate probabilities. So you take the mean along the first axis and you divide by that, which means you interpret fate probabilities relative to the sample mean. After than, you re-normalize such that rows sum to one again, i.e. each cell has total probability of 1 to go somewhere. 

If you're interested in the "absolute", fate probabilities, I would work with the heatmap you got from `cr.pl.aggregate_fate_probabilities`, which should correspond to the non-normalized version of the circular embedding.

**Comment by Marius1311** [comment]
Closing this, feel free to reopen if the issues persists.
