### ISSUE TITLE
Why are my fate probabilities so low in the heatmap?

### ISSUE THREAD

**Issue by TdzBAS** [theislab/cellrank#1154]
...
Hi @Marius1311,

thanks for this amazing tool! I used a PseudotimeKernel and plottet the fate probs, which are looking biologically reasonable:
![image](https://github.com/theislab/cellrank/assets/91309592/ea0986a1-2757-4056-92d0-cc227478b50d)

the clusters are like:
![image](https://github.com/theislab/cellrank/assets/91309592/75f15a80-b47e-4678-a587-e8cf204e4f2e)

but the heatmap is showing me clusters from a totally different "lineage". I only want to considers the clusters where the fate probabilities are highlighted and I dont understand why the fate probs seem so low:
![image](https://github.com/theislab/cellrank/assets/91309592/1dfbb995-63e4-4828-a7d9-4cf4400b48a2)

here is my code:
![image](https://github.com/theislab/cellrank/assets/91309592/787ed736-663d-4127-8cbe-f71531590849)

I get the same results when I omit cluster_key and clusters.

Thanks!
Best,
Tolga

**Comment by TdzBAS** [comment]
when I subset my anndataobject to the seurat clusters of interest and then hand over to cr.pl.heatmap, the fate probs are looking good:
![image](https://github.com/theislab/cellrank/assets/91309592/8da2a272-4fd0-4bea-9764-f81706ad4b54)

But is this legit?

**Comment by Marius1311** [comment]
Hi @TdzBAS, two points here:
- this might be a problem of the pseudotime you used - looks like you used Slingshot, which computes lineage-specific pseudotimes, whereas CellRank 1/2 usually assumes global (lineage-agnostic) pseudotimes, i.e. DPT, Palantir, etc. 
- if you have prior knowledge about this system, and you know which clusters should contribute to a given lineage, I think it's legit to subset to those clusters, and to describe this in the Methods section of your manuscript.

**Comment by TdzBAS** [comment]
Hi @Marius1311,

I switched to palantir calculated pseudotime, but still the same issue, If I dont subset my adata to the clusters of interest.
these are my clusters ( I changed the colors, sorry, for any inconvenience):
![image](https://github.com/theislab/cellrank/assets/91309592/5e510bcf-9107-4868-a972-24865c27eac5)
and the heatmap includes clusters from different branches with nearly 0 fate probability:
![image](https://github.com/theislab/cellrank/assets/91309592/f42e8f03-e569-4ecf-936f-7c5d06d296f3)

If I subset, it looks good though..

any other ideas?

Otherwise I think, I will go with the subsetting..

**Comment by Marius1311** [comment]
The heatmap will always include all cells, but their contribution to the GAM-fits is weighted by the fate probabilities, so they "don't hurt" the fit if their fate probability towards the selected terminal state is very low.

**Comment by TdzBAS** [comment]
Hi,

thanks! I guess I will stick to the downstream analysis without subsetting the cells. 

Best,
Tolga
