### ISSUE TITLE
applying Cytotrace to samples with different depth of coverage 

### ISSUE THREAD

**Issue by jlmalin** [theislab/cellrank#1157]
Hi, 
I was wondering about the quality of the Cytotrace results for integrated datasets. Given that the Cytotrace algorithm is highly dependent on number of genes expressed and, thus, depth of coverage; and most batch correction adjusts levels of expression but not the presence/absence of expression, is there a risk in using cytotrace on integrated objects even after batch correction? Even if there are confounding differences in cell type composition between samples, wouldn't some sort of downsampling be recommended to offset differences in depth of coverage?

Thanks!

**Comment by Marius1311** [comment]
Hi @jlmalin, I haven't done extensive testing of our CytoTRACE implementation on integrated datasets, but what you say sounds very reasonable. Maybe reach out to the original CytoTRACE authors with this question? I would be curious to hear what they say, so feel free to get back to me here. We could then include a note or something in the docs about best practices with this kernel.

**Comment by jlmalin** [comment]
Hi @Marius1311 thank you for the quick reply. After posting the question, I revisited the CytoTRACE paper. The tool may in fact be somewhat buffered against impact due to variability in depth of coverage across samples due to the algorithm's use of genes that are correlated with number of expressed genes rather than the number itself.  In any case, I'll reach out to the authors as you suggest and get back to you with what I hear.
