### ISSUE TITLE
Dealing with overlap

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#116]
Currently, we remove overlapping metastable states and we need to deal with them better.
Still TODO:
- Detect how was the mass shifted
- Recalculate init/stationary distribution

**Comment by Marius1311** [comment]
and:
- recompute coarse grained transition matrix.

**Comment by michalk8** [comment]
@Marius1311 question about the mass detection? What's the purpose (i.e. sets of criterions) and the metric to use?

**Comment by Marius1311** [comment]
that's a check for you before you start implementing this, not something that we need to build in to the algorithm. It's a sanity check to make sure that when we use the redistribution with mutual information, the mass is shifted to the right state.

**Comment by michalk8** [comment]
Ah ok, I thought that you wanted to do something with it.

**Comment by Marius1311** [comment]
I wonder why we actually get these overlapping states. Maybe something more fundamental is going wrong in these cases? Could equally raise an request the user to use one more state. I'm just dealing with one example where that gives a much better result.

**Comment by michalk8** [comment]
It's the way we select the top `n` cells from each lineage. Say we have 2 out of 3 of them, like
`[0.8, 0.8, 0.7, 0.7]` and `[0.15, 0.15, 0.1, 0.1]` and we want to select 2 cells. From the 1st lineage, we select the first 2, from the 2nd the 1st 2 are already selected (overlap 100%), so we skip it.

**Comment by Marius1311** [comment]
Oh, I didn't mean that - I was more thinking of why does GPCCA return this? Clearly, this does not give a very crisp clustering (have a look at the coarse grained transition matrix, it does not look very diagonal, at least in my examples). Maybe it's something about the spectrum at this point, and maybe this is just not a good number of states to cluster into.

**Comment by michalk8** [comment]
I though this is what we were talking about. Then i'm not sure what the problem is.

**Comment by Marius1311** [comment]
Check correlation of to be removed vector with the others.

**Comment by michalk8** [comment]
Implemented via #159
