### ISSUE TITLE
Is there a way to remove the legend in cr.pl.gene_trends ?

### ISSUE THREAD

**Issue by t-nol** [theislab/cellrank#1169]
Hi,
Thank you for this great tool! 
I've been playing around for the past few days and I'm facing some difficulties for some figure legends because my lineages names are pretty long. Especially, in `cr.pl.gene_trends()` the legend being on the plot ends up hiding most of it. 
I have tried to set `return_figure=True` and modify the output figure, but this has only allowed me to add a second legend on the side of the plot (that also has a every line twice, with the gene name and the lineage name for some reason) without being able to remove/move the one already in the plot. 
Is there a way to just remove the legend from the plot or move it outside the graph area ? There might be easy fix but I'm not very experienced with plotting in python yet and haven't been able to find a way.

**Comment by WeilerP** [comment]
@t-nol, you can remove the legend with `legend_loc=None`.
