### ISSUE TITLE
Setting main states

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#117]
Currently, `plot_main_states(n_cells!=None`, ...) writes the `root/final_states` because there
we have the information of how much cells we want to select (no such information is provided in `set_states`).
@Marius1311 how to solve this the best?

**Comment by Marius1311** [comment]
Let's just always write them in `set_main_states`, and let's introduce a parameter for that which is `30` by default. Let's not write them when plotting. This is more expected behaviour, I think. 

So for plotting, the user can select a number of cells, but this will not be written to adata.

**Comment by michalk8** [comment]
Closed via #128
