### ISSUE TITLE
Cellrank - CytoTRACE Kernel with Harmony results

### ISSUE THREAD

**Issue by xiandxing** [theislab/cellrank#1180]
Hi, I would like to know what would happen if I pass a harmony-corrected PCA matrix `X_pca_harmony` to `scvelo.pp.moments()`? Is that allowed?

**Comment by WeilerP** [comment]
@xiandxing, CytoTRACE is run on the actual GEX data, not a latent representation; we use first-order moment imputation to address data sparsity - you can read about it in greater detail in the [CellRank 2 preprint](https://doi.org/10.1101/2023.07.19.549685). PCA representations are already dense, _i.e._, there is no need for smoothing.
