### ISSUE TITLE
3D UMAP and RNA velocity matrices

### ISSUE THREAD

**Issue by fafa92** [theislab/cellrank#1187]
Hi,

Appreciate the nice package,

I was wondering if there is an option to plot RNA velocities on a 3D UMAP or get their calculated matrices. If not, what direction would you recommend for the integration of this feature into the project? 

Best,

**Comment by Marius1311** [comment]
Hi @fafa92, this seems like that's an scVelo question - CellRank does not provide plotting functionality for RNA velocity, nor does it compute RNA velocities. A quick search through scVelo issues brought up this one: https://github.com/theislab/scvelo/issues/220

Please follow up in the scVelo repo.

**Comment by fafa92** [comment]
Thanks for the reference! @Marius1311
