### ISSUE TITLE
Manually adding a macrostate?

### ISSUE THREAD

**Issue by mxposed** [theislab/cellrank#1193]
Hi, thank you for the great package.

I was wondering what are my options for manually defining or hinting at a particular macrostate for the model, if this is possible at all?
I have a large dataset (~130k cells) where I have my biological prior on the start of the differentiation trajectory (monocytes), this is where I set my PseudotimeKernel root, however they don't form their own macrostate (n=13). I know I can increase the number of macrostates, but it's getting computationally expensive, and I'm not sure at which number they will appear.

- Are there other ways to hint or tell the model to find macrostates among that group of cells?
- Does the transition matrix and macrostates depend on the value of pseudotime? So if I use a different method, they can change significantly?

**Comment by Marius1311** [comment]
Hi @mxposed, 

Re 1: What's the biological question you're trying to solve with this? If you know the trajectory starts in monocytes, and you initialize your pseudotime in this cluster, then what additional information can you extract by identifying a macrostate corresponding to these cells? Usually, when the initial state is well known, terminal states, and fate probabilities towards terminal states, are more interesting. 
Re 2: Yes, if you use the `PseudotimeKernel`, then the transition matrix depends on the Pseudotime you pass. Please see our CellRank 2 preprint for more information.

**Comment by mxposed** [comment]
Hi @Marius1311 

Thank you for the quick reply. Re 1: you're right, I'm interested in the terminal states, their number and identity, the shape of the trajectory (branches, no branches), distribution of cell commitment towards them, if there is any difference between 2 experimental groups of samples, and the genes that are behind.

**Comment by Marius1311** [comment]
great, in that case, it looks like you don't need to worry about your initial state. Closing this issue, feel free to reopen if your question persists.

**Comment by mxposed** [comment]
Thank you! I didn't realize I can proceed with these analyses without identifying initial states first!
