### ISSUE TITLE
heatmap plot: what are the column

### ISSUE THREAD

**Issue by mxposed** [theislab/cellrank#1195]
I apologize if I missed this in the tutorials, but I don't think it's in the [API docs](https://cellrank.readthedocs.io/en/stable/api/_autosummary/plotting/cellrank.pl.heatmap.html)

What are the columns here?

I pass the object with ~27k cells, but the heatmap that is plotted has 200 columns. Are those 200 sampled cells? How are they sampled? Or are these all cells aggregated into 200 pseudo-cells with expression smoothed? Then how is metadata colors computed for this? The code is quite complex around there, and I could find the code that is responsible for these things.

My calls are here:
```python
model = cellrank.models.GAM(myeloid, n_knots=6)
myeloid_raw = myeloid.raw.to_adata()
myeloid_raw.shape
# (26772, 25538)
qqq = cellrank.pl.heatmap(
    myeloid_raw,
    model=model,
    lineages='Cluster 4',
    cluster_key=['cell_type', 'cell_type_state'],
    show_fate_probabilities=True,
    genes=cluster_4_drivers.head(80).index,
    time_key='dpt_pseudotime',
    show_all_genes=True,
    n_convolve=1,
    return_figure=True,
)
qqq[0][0].data.shape
# (30, 200)
```

**Comment by WeilerP** [comment]
@mxposed, the plot shows smoothed gene expression change over pseudotime, _i.e._, each entry _(j, k)_ is the value of gene _g_ at pseudotime _k_.

**Comment by mxposed** [comment]
Finally got to look into the code properly: the heatmap column annotation colors are pulled from cells closest to the 200 sampled pseudotime points. Pseudotime is sampled with linspace, gene expression is the predicted expression from the GAM models.

https://github.com/theislab/cellrank/blob/721c59fe3bbbad41450a9b0fd5f34eebe683c08b/src/cellrank/pl/_heatmap.py#L380

https://github.com/theislab/cellrank/blob/721c59fe3bbbad41450a9b0fd5f34eebe683c08b/src/cellrank/pl/_heatmap.py#L176
