### ISSUE TITLE
plot_single_flow raw data interpretation

### ISSUE THREAD

**Issue by fafa92** [theislab/cellrank#1196]
Hi, 

I'm trying to get the raw data behind this plot. I'm getting the data in all polygons in the ax.get_children(), but it's hard to interpret them, is there any documentation or other way to reconstruct this chart using its data? 

```

ax = tmk.plot_single_flow(
    cluster_key="cell_sets",
    time_key="day",
    cluster="MEF/other",
    min_flow=0.1,
    xticks_step_size=4,
    show=False,
    clusters=["MEF/other", "MET", "Stromal"],
)

_ = ax.set_xticklabels(ax.get_xticklabels(), rotation=90)
```

I appreciate any help in advance!

**Comment by WeilerP** [comment]
Sorry, there are no additional docs, so you'll have to check the corresponding code directly.
