### ISSUE TITLE
CellRank can't be used in Python versions >3.9

### ISSUE THREAD

**Issue by mpiersonsmela** [theislab/cellrank#1199]
When running `import cellrank as cr`, I get an error related to importing Iterable from collections. Apparently this was deprecated in python version 3.9 and removed in version 3.10. See: https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

```import cellrank as cr```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mdp817/mambaforge/envs/scvelo/lib/python3.11/site-packages/cellrank/__init__.py", line 2, in <module>
    import cellrank.pl
  File "/home/mdp817/mambaforge/envs/scvelo/lib/python3.11/site-packages/cellrank/pl/__init__.py", line 2, in <module>
    from cellrank.pl._heatmap import heatmap
  File "/home/mdp817/mambaforge/envs/scvelo/lib/python3.11/site-packages/cellrank/pl/_heatmap.py", line 8, in <module>
    from collections import Iterable, defaultdict
ImportError: cannot import name 'Iterable' from 'collections' (/home/mdp817/mambaforge/envs/scvelo/lib/python3.11/collections/__init__.py)

```

#### Versions:

Python 3.11
> ...

**Comment by mpiersonsmela** [comment]
If you are not planning to fix this, I recommend adding the python version as an explicit dependency.

**Comment by mpiersonsmela** [comment]
I installed from bioconda:

mamba install -c bioconda cellrank

But I now see that this gave me CellRank 1.5.1 and I should have used conda-forge which has version 2.0.4. This fixed the problem.

Just wondering, is there a reason bioconda is so far behind conda-forge?

**Comment by WeilerP** [comment]
We switched to conda-forge and do not release CellRank via bioconda anymore.
