### ISSUE TITLE
Plotting the Schur matrix

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#120]
Currently, it's only available for `method!=krylov`. Add an option to visualize this.
@Marius1311 do you want to add this for the `krylov` method (since you've been following more closely the email convo) or shall i?

**Comment by Marius1311** [comment]
Hi Mike, I think it should be relatively straightforward, basically
```
R = E.getDS().getMat(SLEPc.DS.MatType.A)
R.view()
```

would be great if you could try this and check whether it aligns with what we get from `brandts` and `scipy`

**Comment by Marius1311** [comment]
but we better integrate this into GPCCA rather than cellrank.

**Comment by michalk8** [comment]
Ok, I will hopefulyl make a PR later today and add an option to plot them in CellRank.

**Comment by Marius1311** [comment]
great, thanks!

**Comment by michalk8** [comment]
Implemented in CellRank via #133. I've also made PR in `msmtools` here: https://github.com/msmdev/msmtools/pull/5.

**Comment by Marius1311** [comment]
Great, thanks!
