### ISSUE TITLE
Can key genes be identified?

### ISSUE THREAD

**Issue by GLking123** [theislab/cellrank#1203]
hi，

CellRank is a versatile single-cell processing software.which is very useful for studying development using single-cell data. However, if we want to study the fate of cells that shift from **health to disease**, can we use Cellrank to find those genes that play a decisive role?

For the above question, could you provide some debugging suggestions? Thank you for your valuable time and assistance. I sincerely look forward to your response！

**Comment by Marius1311** [comment]
Hi @GLking123, sure, you can look at genes the correlate highly with the fate probability of ending up in the disease state. You can look at expression patterns of these correlated genes over pseudotime to identify potential activation cascades. You could further restrict the set of candidate genes by looking at TFs or by using prior regulatory information like binding sites etc. We cover a few of these analysis in our tutorials, please take a look. (not specific to disease trajectories, but you should be able to apply similar principles).

**Comment by GLking123** [comment]
Thank you for your clarification. I understand now.
