### ISSUE TITLE
Errors for compute_transition_matrix 

### ISSUE THREAD

**Issue by mainharryHR** [theislab/cellrank#1205]
...
Dear Team,

I am new for this package, please help me with this errors or pipeline.

**Here comes my pipeline**: CellRank Meets CytoTRACE
 I imported seurat object as adata. Then I did the PCA and Neighbors. 

`sc.pl.embedding(adata, basis="X_harmony_UMAP", color="annotationV2")`
`sc.pp.filter_genes(adata, min_cells=1)`
`scv.pp.normalize_per_cell(adata)`
`sc.pp.log1p(adata)`
`sc.pp.highly_variable_genes(adata)`
`adata.layers['spliced'] = adata.X`
  `adata.layers['unspliced'] = adata.X`
`scv.pp.moments(adata, n_pcs=None, n_neighbors=None)  # hack for CytoTRACEkernel`

`from cellrank.kernels import CytoTRACEKernel
ctk = CytoTRACEKernel(adata).compute_cytotrace()`

**Compute transition matrix**
`ctk = ctk.compute_cytotrace().compute_transition_matrix(scheme="soft", nu=0.5)`

**Then I have errors:**  
Computing CytoTRACE score with 3000 genes. Consider using more than 10000 genes
Adding adata.obs['ct_score']
       adata.obs['ct_pseudotime']
       adata.obs['ct_num_exp_genes']
       adata.var['ct_gene_corr']
       adata.var['ct_correlates']
       adata.uns['ct_params']
    Finish (0:00:00)
Computing transition matrix based on pseudotime
  0%|          | 0/3640 [00:00<?, ?cell/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 290, in run_path
  File "<frozen runpy>", line 254, in _get_code_from_file
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hairu/PycharmProjects/pythonProject/Lynch project/<input>'
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Users/hairu/PycharmProjects/pythonProject/Lynch project/venv/lib/python3.11/site-packages/cellrank/kernels/_pseudotime_kernel.py", line 158, in compute_transition_matrix
    biased_conn = scheme.bias_knn(
                  ^^^^^^^^^^^^^^^^
  File "/Users/hairu/PycharmProjects/pythonProject/Lynch project/venv/lib/python3.11/site-packages/cellrank/kernels/utils/_pseudotime_scheme.py", line 95, in bias_knn
    res = parallelize(
          ^^^^^^^^^^^^
  File "/Users/hairu/PycharmProjects/pythonProject/Lynch project/venv/lib/python3.11/site-packages/cellrank/_utils/_parallelize.py", line 90, in wrapper
    queue = multiprocessing.Manager().Queue()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py", line 567, in start
    self._address = reader.recv()
                    ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 249, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 382, in _recv
    raise EOFError
EOFError

**Comment by WeilerP** [comment]
@mainharryHR, it looks like you running your code in Pycharm. Can you please check if it works when you run it in a standard terminal?

**Comment by mainharryHR** [comment]
I tried the terminal, It seems the bug is getting worse. I even can not run the this line due to the conflicts among numba package, cellrank, and others.  
`ctk = CytoTRACEKernel(adata)
    ctk.compute_cytotrace()`


Here comes package list: Selection deleted
!pip list


Package                   Version
------------------------- ------------------
absl-py                   2.1.0
altair                    5.3.0
anndata                   0.10.8
annotated-types           0.7.0
anyio                     4.4.0
appnope                   0.1.4
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
array_api_compat          1.7.1
arrow                     1.3.0
asttokens                 2.4.1
astunparse                1.6.3
async-lru                 2.0.4
attrs                     23.2.0
Babel                     2.14.0
backoff                   2.2.1
beautifulsoup4            4.12.3
bleach                    6.1.0
blessed                   1.19.1
Brotli                    1.1.0
build                     1.2.1
CacheControl              0.14.0
cached-property           1.5.2
cellrank                  2.0.4
certifi                   2024.6.2
cffi                      1.16.0
charset-normalizer        3.3.2
chex                      0.1.86
cleo                      2.1.0
click                     8.1.7
colorama                  0.4.6
comm                      0.2.2
contextlib2               21.6.0
contourpy                 1.2.1
crashtest                 0.4.1
croniter                  1.4.1
cycler                    0.12.1
dateutils                 0.6.12
debugpy                   1.8.2
decorator                 5.1.1
deepdiff                  7.0.1
defusedxml                0.7.1
distlib                   0.3.8
dm-tree                   0.1.8
dnspython                 2.6.1
docrep                    0.3.2
dulwich                   0.21.7
email_validator           2.2.0
entrypoints               0.4
et-xmlfile                1.1.0
etils                     1.6.0
exceptiongroup            1.2.0
executing                 2.0.1
fastapi                   0.111.0
fastapi-cli               0.0.4
fastjsonschema            2.20.0
filelock                  3.15.4
flatbuffers               24.3.25
flax                      0.8.5
fonttools                 4.53.0
fqdn                      1.5.1
fsspec                    2024.6.1
future                    1.0.0
gast                      0.5.5
get-annotations           0.1.2
gmpy2                     2.1.5
google-pasta              0.2.0
grpcio                    1.62.2
h11                       0.14.0
h2                        4.1.0
h5py                      3.11.0
hpack                     4.0.0
httpcore                  1.0.5
httpx                     0.27.0
hyperframe                6.0.1
idna                      3.7
importlib_metadata        8.0.0
importlib_resources       6.4.0
inquirer                  3.1.4
installer                 0.7.0
ipykernel                 6.29.5
ipython                   8.18.1
isoduration               20.11.0
itsdangerous              2.2.0
jaraco.classes            3.4.0
jax                       0.4.27
jaxlib                    0.4.23.dev20240522
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.2
jupyter_core              5.7.1
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.1
jupyter_server_terminals  0.5.3
jupyterlab                4.2.3
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.2
keras                     3.0.5
keyring                   24.3.1
kiwisolver                1.4.5
legacy-api-wrap           1.4
lightning                 2.0.9.post0
lightning-cloud           0.5.39
lightning-utilities       0.11.3.post0
llvmlite                  0.42.0
loompy                    3.0.6
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
mistune                   3.0.2
ml-collections            0.1.1
ml-dtypes                 0.3.2
more-itertools            10.3.0
mpi4py                    3.1.6
mpmath                    1.3.0
msgpack                   1.0.8
mudata                    0.2.4
multipledispatch          0.6.0
munkres                   1.1.4
namex                     0.0.8
natsort                   8.4.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest_asyncio              1.6.0
networkx                  3.2.1
notebook_shim             0.2.4
numba                     0.59.1
numpy                     1.26.4
numpy-groupies            0.11.1
numpyro                   0.15.0
openpyxl                  3.1.4
opt-einsum                3.3.0
optax                     0.2.2
orbax-checkpoint          0.4.4
ordered-set               4.1.0
orjson                    3.10.6
overrides                 7.7.0
packaging                 24.1
pandas                    2.2.2
pandocfilters             1.5.0
parso                     0.8.4
patsy                     0.5.6
petsc4py                  3.21.1
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    10.3.0
pip                       24.0
pkginfo                   1.11.1
pkgutil_resolve_name      1.3.10
platformdirs              4.2.2
poetry                    1.8.3
poetry-core               1.9.0
poetry-plugin-export      1.8.0
progressbar2              4.4.2
prometheus_client         0.20.0
prompt_toolkit            3.0.47
protobuf                  4.25.3
psutil                    6.0.0
ptyprocess                0.7.0
pure-eval                 0.2.2
pycparser                 2.22
pydantic                  2.1.1
pydantic_core             2.4.0
pygam                     0.9.1
Pygments                  2.18.0
pygpcca                   1.0.4
PyJWT                     2.8.0
pynndescent               0.5.13
pyobjc-core               10.3.1
pyobjc-framework-Cocoa    10.3.1
pyparsing                 3.1.2
pyproject_hooks           1.1.0
pyro-api                  0.1.2
pyro-ppl                  1.9.1+0a67ddc
PySocks                   1.7.1
python-dateutil           2.9.0
python-editor             1.0.4
python-json-logger        2.0.7
python-multipart          0.0.9
python-utils              3.8.2
pytorch-lightning         2.3.0
pytz                      2024.1
PyYAML                    6.0.1
pyzmq                     26.0.3
rapidfuzz                 3.9.4
readchar                  4.1.0.dev3
referencing               0.35.1
requests                  2.32.3
requests-toolbelt         1.0.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.7.1
rpds-py                   0.18.1
scanpy                    1.9.8
scikit-learn              1.1.3
scipy                     1.13.1
scvelo                    0.0.0
scvi-tools                1.1.5
seaborn                   0.13.2
Send2Trash                1.8.3
session-info              1.0.0
setuptools                70.1.1
shellingham               1.5.4
six                       1.16.0
slepc4py                  3.21.1
sniffio                   1.3.1
soupsieve                 2.5
sparse                    0.15.4
stack-data                0.6.2
starlette                 0.37.2
starsessions              1.3.0
statsmodels               0.14.2
stdlib-list               0.10.0
sympy                     1.12.1
tensorboard               2.16.2
tensorboard-data-server   0.7.0
tensorflow                2.16.1
tensorflow_estimator      2.15.0
tensorstore               0.1.60
termcolor                 2.4.0
terminado                 0.18.1
threadpoolctl             3.5.0
tinycss2                  1.3.0
tomli                     2.0.1
tomlkit                   0.12.5
toolz                     0.12.1
torch                     2.3.1
torchmetrics              1.4.0.post0
tornado                   6.4.1
tqdm                      4.66.4
traitlets                 5.14.3
trove-classifiers         2024.7.2
typer                     0.12.3
typer-slim                0.12.3
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.2
typing-utils              0.1.0
tzdata                    2024.1
ujson                     5.10.0
umap-learn                0.5.5
unicodedata2              15.1.0
uri-template              1.3.0
urllib3                   2.2.2
uvicorn                   0.30.1
virtualenv                20.26.3
wcwidth                   0.2.13
webcolors                 24.6.0
webencodings              0.5.1
websocket-client          1.8.0
websockets                12.0
Werkzeug                  3.0.3
wheel                     0.43.0
wrapt                     1.16.0
xarray                    2023.7.0
xattr                     1.1.0
zipp                      3.19.2

**Comment by mainharryHR** [comment]
> @mainharryHR, it looks like you running your code in Pycharm. Can you please check if it works when you run it in a standard terminal?

Thank you very much. It works in another terminal. I appreciate your kind help and fast reaponse.
