### ISSUE TITLE
How to improve the accuracy for CytoTRACEKernel pipeline? Any parameter I can adjust?

### ISSUE THREAD

**Issue by mainharryHR** [theislab/cellrank#1206]
...
Dear Team,
I used R platiform for CytoTrace, which gives the reasonable results. 
When I tried to combine the CellRank and use **CellRank Meets CytoTRACE**  to caculate the  pseudotime by the following code, It give me different results, which does not make sense to me. I am wondering which parameter I could use to adjust or improve?

I am not sure where to get the unspliced RNA or complicated to get it from Serurat object. I feel I have to use the Cytotrace pipeline.

Any comments are welcome. :)

Thank you all very much.

`ctk = cr.kernels.CytoTRACEKernel(adata)`
`ckt = ctk.compute_cytotrace().compute_transition_matrix()`

**Comment by Marius1311** [comment]
Hi @mainharryHR, if you're happy with the CytoTRACE results you got in R, then just port them to Python, save them in `adata.obs`, and continue in CellRank with a `PseudotimeKernel`, see our corresponding tutorials.

**Comment by mainharryHR** [comment]
Dear Marius,
Thank you very much for the suggestions.
After reading, It seems I need to use this pipeline.
'pk = cr.kernels.PseudotimeKernel(adata, time_key="palantir_pseudotime")'
'pk.compute_transition_matrix()'

 I have 2 questions;
1: Which Key I should use from CytoTrace2 as pseudotime?
'CytoTRACE2_Score', 'CytoTRACE2_Potency', 'CytoTRACE2_Relative', 'preKNN_CytoTRACE2_Score', 'preKNN_CytoTRACE2_Potency',

2: Before running above pipeline, should I perform: PCA and compute neighbors, and other upstream processing? Or After reading adata, I directly start with above pipeline?

You comments are very valuable .

Have a nice day!

Best,
Harry

**Comment by WeilerP** [comment]
Hi @mainharryHR,
1. Use the inverted CytoTRACE score, s.t. 0 corresponds to immature, and 1 to mature cells.
2. You'll need a neighbor graph!

**Comment by mainharryHR** [comment]
Great!

Thank you for the important suggestions. You are right that CytoTrace score is opposite as pseudotime.

I really appreciate your team for helpful directions. I will keep you updated. :)
Have a nice day

**Comment by mainharryHR** [comment]
Great, It works,

Then I tried to exploring to plotting. This one is not working. I guess some parameter might be wrong. Please help how to adjust.  I guess I can not plot `pl.violin`  as well.  Thank you all. :)
`pk.plot_single_flow(
    cluster="annotationV2",
    cluster_key="annotationV2",
    time_key="inverted_CytoTRACE2_Score",
    clusters=None,
    time_points=None,
    min_flow=0,
    remove_empty_clusters=True,
    ascending=False,
    legend_loc='upper right out',
    alpha=0.8,
    xticks_step_size=1,
    figsize=None,
    dpi=None,
    save=None,
    show=True
)`

**Comment by WeilerP** [comment]
Please have a look at the [docs](https://cellrank.readthedocs.io/en/latest/api/_autosummary/kernels/cellrank.kernels.PseudotimeKernel.html#cellrank.kernels.PseudotimeKernel.plot_single_flow). It's also unrelated to your original question, so you should open another issue if at all, and without any traceback, we cannot help you.
