### ISSUE TITLE
Binder notebooks

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#121]
@Marius1311 I remember you wanted to have our notebooks interactive - I think we could us binder for that: https://mybinder.org/. Benefits over Google collab is that no sign-in is required + we can also show a badge.

**Comment by Marius1311** [comment]
Nice! That would be very cool. Can you check whether that would work for us? We need to give it the a requirements file so it can build the docker container for us.

**Comment by michalk8** [comment]
Implemented via #132
