### ISSUE TITLE
pl.log_odds() shows no figure

### ISSUE THREAD

**Issue by Alvis-Jiang** [theislab/cellrank#1216]
...
Hi,

I am have successfully run the kernels.RealTimeKernel with. my time-series datasets, but when I tried to run the pl.log_odds() to make log odds plots, it returned no figure, just some equations as shown below. Could you please give me some guidance on how to use this function? Thanks a lot!

Best,
Boyu
![WX20240829-132859](https://github.com/user-attachments/assets/6327b627-69df-409a-bc40-f8f7ec87d0b4)

**Comment by WeilerP** [comment]
Seems to be an issue with your Jupyter notebook/lab setup. Everything works fine for me.
