### ISSUE TITLE
can i use cellrank2 on scrna dataset which which i have computed a pseudotime and vector filed using sctour?

### ISSUE THREAD

**Issue by JIMCAOWJ** [theislab/cellrank#1228]
...
hello, can i use cellrank2 on scrna dataset which which i have computed a pseudotime and vector filed using sctour?

**Comment by WeilerP** [comment]
@JIMCAOWJ, you can use any pseudotime with our `PseudotimeKernel`. You simply need to save it as a column in `AnnData.obs` and can then follow our dedicated [tutorial](https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/kernels/300_pseudotime.html).
