### ISSUE TITLE
Calculation of transition matrix problem,ValueError: Input matrix P is not a transition matrix.

### ISSUE THREAD

**Issue by Angle28** [theislab/cellrank#1234]
Hello, I would like to ask if I have no error after running this
kernel = cr.tl.transition_matrix(ad,
weight_connectivities=weight_connectivities,
mode=mode,
n_jobs=n_jobs,
softmax_scale=softmax_scale)
And then I run this without error g_fwd = GPCCA(kernel)
Then run this g_fwd.compute_macrostates(n_states=4, cluster_key="lineage")

These errors appear in g_fwd ValueError Traceback (most recent call last)
Cell In[41], line 1
----> 1 g_fwd.compute_macrostates(n_states=4, cluster_key="lineage")
3 g_fwd

The File ~ / local/lib/python3.9 / site - packages/cellrank/tl/estimators terminal_states / _gpcca py: 175, in compute_macrostates(self, n_states, n_cells, cluster_key, **kwargs)

The File ~ / local/lib/python3.9 / site - packages/cellrank/tl/estimators/mixins/decomposition / _schur py: 161, in compute_schur(self, n_components, initial_distribution, method, which, alpha)

The File ~ / local/lib/python3.9 / site - packages/pygpcca / _gpcca. Py: 776, in GPCCA. init (self, P, eta, z, method)
768 def init(
769 self,
770 P: Union[np.ndarray, spmatrix],
(...).
773 method: str = DEFAULT_SCHUR_METHOD,
774):
775 if not is_transition_matrix(P):
--> 776 raise ValueError("Input matrix P is not a transition matrix.")
777 if z not in ["LM", "LR"]:
778 raise ValueError("You didn't give a valid sorting criterion z. Valid options are: 'LM', 'LR'.")

ValueError: Input matrix P is not a transition matrix.
...

**Comment by WeilerP** [comment]
@Angle28, can you please update to the latest version of CellRank and check again?

**Comment by Angle28** [comment]
Hello, I have updated cellrank to 2.0.6, the latest version, and did I use the test data in the literature to do this or such problems occurred.

**Comment by WeilerP** [comment]
@Angle28, sorry, I'm a bit confused and cannot follow what you did: (1) There is no `cellrank.tl` module anymore, and (2) what data did you use?

**Comment by WeilerP** [comment]
Closing this for now as not reproducible.
