### ISSUE TITLE
Query about weightage for kernels and combining Realtime with Pseudotime kernel

### ISSUE THREAD

**Issue by ramadatta** [theislab/cellrank#1236]
Hi,

Thank you for the cellrank package.

I am running cellrank on dataset which has experimental time information across different days (12h, 24h, 48h, 96h, 144h). 
I have created different kernels and combined all of them here like below with different weights for diffusion pseudotime, palantir pseudotime, RNA velocity and Realtime kernels:

`comb_pt_rt_kernel = 0.1 * dptk + 0.3 * pptk + 0.3 * vk + 0.2 * tmk` 

**My question1 is:**

Since we have experimental time information, is it that we should always have highest weight for realtime kernel? Does it make sense to leave out other kernels such diffusion, if I have palantir PT? or choose either one?

**My question2 is:**

When I am plotting the gene expression trends using: `cr.pl.gene_trends` , i provide the `time_key` option with column which I have obtained by combining both pseudotime and realtime by normalizing each of them separately between 0 to 1 and taking mean for each cell.

The reason for the above is because my timepoints are distinct, i do not see a smooth line. May I know if this approach seems reasonable?
Many thanks in advance for your kind reply.

**Comment by Marius1311** [comment]
Closing this, we we're discussing in slack.

**Comment by ramadatta** [comment]
Posting @Marius1311 reply for others benefit:

Re 1: I would actually start with just a single kernel and then build it up gradually, otherwise, you won't be able to interpret the outputs. Also, as always, it's garbage-in-garbage-out, so any kernel addition can either hurt or benefit, depending on the data quality. You should independently validate that each of your kernels gives you some output that is compatible with what you know about your system. e.g., are velocities meaningful here? if not, don't include them.

Re 2: If I were you, I would compute a pseudotime, and check whether it correlates with real time. i.e., do cells on later days on average get a higher pseudotime assigned? If yes, just use that pseudotime, it's compatible with your real-time information. If not, you can try to compute a real-time informed pseudotime, see our CR2 manuscript or talk to Philip (Weiler). It looks like you're doing something similar.

Re 3: yes, I would try with a pseudotime kernel
