### ISSUE TITLE
An error is reported when importing cellrank

### ISSUE THREAD

**Issue by Zstark11** [theislab/cellrank#1240]
An error occurred in the first step of importing cellrank

`import cellrank as cr`

The error is

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 import cellrank as cr

File [~/linux](http://biotrainee.vip:8102/home/data/linux)系统py/cellrank.py:6
      4 #设置图形参数
      5 sc.settings.set_figure_params(frameon=False, dpi=300)
----> 6 cr.settings.verbosity = 2
      7 #忽略所有 UserWarning 类型的警告
      8 import warnings

AttributeError: partially initialized module 'cellrank' has no attribute 'settings' (most likely due to a circular import)
```

My Cellrank version is 2.0.6, Python version is 3.10

This is an error I encountered while importing on the server, but I successfully imported it on my own computer's Linux system

**Comment by WeilerP** [comment]
@Zstark11, it seems to be an issue on your end. Everything works fine on my personal machine, the servers I run CellRank on, and our CIs import CellRank successfully as well. The `partially initialized module` part can occur, for example, if you have a local file called _cellrank.py_ s.t. Python gets confused about the imports.
