### ISSUE TITLE
Directed PAGA

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#125]
Hi Volker! I have two questions/observations I wanted to share with you:

1. increasing the `node_size` scale covers the arrows, see Fig 1 and 2 below. Would it be possible to shorten the arrow length in this case, so that the head remains visible?
1. does the arrow size also scale with connectivity, or is that only the dashed lines?
1. title setting does not seem to work yet. (setting a title does not change the displayed title)

## Fig 1
`node_size_scale=1`(default):
![image](https://user-images.githubusercontent.com/24494650/81864587-213f6c80-956d-11ea-86eb-fb6d2120784b.png)

## Fig 2
`node_size_scale=2.5` (this is a nicer size to look at the pie charts)
![image](https://user-images.githubusercontent.com/24494650/81864659-37e5c380-956d-11ea-8671-0837ff8b9334.png)

**Comment by VolkerBergen** [comment]
Let me know, if it's resolved now.

**Comment by Marius1311** [comment]
thanks! Will give it a go.

**Comment by Marius1311** [comment]
1. arrows look better now, overlap with pie charts is smaller, but still visible (see below)
1. title passing works now for calling `scv.pl.paga`, but not for `cr.pl.cluster_fates`. This is a cellrank problem now - @michalk8 , could you look into this please?

![image](https://user-images.githubusercontent.com/24494650/82048692-5eaf1180-96b5-11ea-9466-184e1fcf839c.png)

**Comment by VolkerBergen** [comment]
The pie charts are plotted each individually on top of paga with approx. node_sizes. With the current implementation it's not possible to make the arrows perfectly align with the pie's (same in scanpy). Would need to re-implemented this in parts, but I couldn't find any example on the web that implements graphs with flex-sized pies. Maybe @michalk8 has an idea. The critical part is [here](https://github.com/theislab/scvelo/blob/ef5727f8231cd510233c10152c8840bbaba145a6/scvelo/plotting/paga.py#L669).

**Comment by Marius1311** [comment]
We can leave this issue open and discuss PAGA interfacing here.

**Comment by Marius1311** [comment]
@VolkerBergen , any updates on this? You said you had to rename some parameters/clean up internal logic?

**Comment by Marius1311** [comment]
I just tried using this, but it does not seem to really take into account the cellrank `root/final_states_probs` yet. I have both of these in `adata.obs` and run `scv.tl.paga`, the function prints
```
computing terminal states
WARNING: Uncertain or fuzzy root cell identification. Please verify.
    identified 1 region of root cells and 1 region of end points 
    finished (0:00:00) --> added
    'root_cells', root cells of Markov diffusion process (adata.obs)
    'end_points', end points of Markov diffusion process (adata.obs)
running PAGA
    finished (0:00:01) --> added
    'paga/connectivities', connectivities adjacency (adata.uns)
    'paga/connectivities_tree', connectivities subtree (adata.uns)
    'paga/transitions_confidence', velocity transitions (adata.uns)
```
so I take from that that it recomputed root/final cells, even though they were present already. 

@VolkerBergen , could you try this on your machine, computing cellrank root/final states by running
```
# forwards case
kernel = cr.tl.transition_matrix(adata)
g = cr.tl.GPCCA(kernel)
g.compute_schur()
g.compute_metastable_states(n_states=3)
g.set_main_states() # this will write `adata.obs['final_states_probs']

# backwards case
kernel_b = cr.tl.transition_matrix(adata, backward=True)
g_b = cr.tl.GPCCA(kernel_b)
g_b.compute_schur()
g_b.compute_metastable_states(n_states=1)
g_b.set_main_states() # this will write `adata.obs['root_states_probs']
```

and then compute a directed PAGA based on this.

**Comment by VolkerBergen** [comment]
It's propagated now - no need to recompute terminal states. 

However, `g.compute_schur()` raises the error:
```
~/theislab/cellrank/cellrank/tools/estimators/_gppca.py in compute_schur
--> 302                 "D": self._gpcca.eigenvalues,
AttributeError: 'GPCCA' object has no attribute 'eigenvalues'
```

**Comment by michalk8** [comment]
You need to update `msmtools` again, this has been recently merged.

**Comment by Marius1311** [comment]
@VolkerBergen , does that fix the bug for you?

**Comment by VolkerBergen** [comment]
Works. 
```
# after computing schur via gpcca
scv.tl.paga(adata, root_key='root_states_probs')
scv.pl.paga(adata, basis='umap', min_edge_width=1.5)
```

![image](https://user-images.githubusercontent.com/31883718/83860588-bcb49f00-a71f-11ea-888a-abbee265ff0e.png)

As discussed earlier, we only get confident transitions for Ductal and Epsilon cells with a larger neighbor grap b/c the 'best' transitions are not within direct neighbors.

**Comment by Marius1311** [comment]
Thanks!

**Comment by Marius1311** [comment]
It would be nice if `scv.tl.paga` would print out which priors it uses, similar to `scv.tl.recover_latent_time`

**Comment by VolkerBergen** [comment]
sure, will do.

**Comment by Marius1311** [comment]
How does directed paga determine what's an endpoint if I give it `final_states_probs`, `root_states_probs` and a `time_prior`?

**Comment by VolkerBergen** [comment]
roots and finals are 
- used in paga directly (above threshold of 0.7 counts as terminal)
- propagated to velocity_pseudotime (if use_time_prior is set True), and therein pseudotimes are calculated starting from argmax(roots/finals) and then averaged. It can instead also directly use e.g. 'latent_time' , if passed as obs_key string to `use_time_prior`.

**Comment by Marius1311** [comment]
Thanks! Can you explain what you mean by `argmax(roots/finals)` further? I guess this relates to `velocity_pseudotime` rather than directed PAGA, but I'm just curious anyways. Under what circumstances do you use final cells in the computation of the `velocity_pseudotime`?

**Comment by VolkerBergen** [comment]
sure, `velocity_pseudotime` is computed once starting from root (simply defined as the cell ID that has max value in `root_states_probs`) and once computed from end (defined as the cell ID that has max value in `final_states_probs`) - all defined on symm. velo kernel. dpt from root and reversed dpt from end are then averaged.

**Comment by Marius1311** [comment]
I'm not quite sure I can follow the way in which the arrows are drawn currently. I have root & final state probs shown in Fig 1 below. Based on these, I compute the latent time and velo pseudotimes of Fig 2. I pass these as time prior, together with the root & final state priors and I recompute my velo graph to have recurse neighbors. Yet, I get funny arrows, see Fig 3 (time prior `latent_time) and Fig 4 (time prior `velocity_pseudotime`). What could be the reason for this?

Fig 1
![image](https://user-images.githubusercontent.com/24494650/85166376-7d319b00-b267-11ea-86a6-da4f7672d19c.png)

Fig 2
![image](https://user-images.githubusercontent.com/24494650/85166394-83c01280-b267-11ea-854e-f7d1f1eafd73.png)

Fig 3
time prior latent time
![image](https://user-images.githubusercontent.com/24494650/85166446-96d2e280-b267-11ea-8331-c0c6ae52cf98.png)
Transition from Epsilon to Alpha, and 2 transitions missing

Fig 4
time prior velocity pseudotime
![image](https://user-images.githubusercontent.com/24494650/85166537-b702a180-b267-11ea-9776-c26f13b17f0d.png)
multiple transitions among final states, and even back towards progenitor states

**Comment by VolkerBergen** [comment]
Oh! That doesn't look right! Do you have the notebook somewhere to reproduce these? Is it using all priors (root, final and time)? What if you remove the final_states prior?

**Comment by Marius1311** [comment]
Sure! Will send you the notebook in mattermost!

**Comment by VolkerBergen** [comment]
This 'false artefact' of arrows among the final states arise when specifically setting the `end_key` - when setting the threshold from 0.7 to 0.9, it gets resolved. I only tested it on scvelo's `terminal_states` where the states are clearly divided into two compartments (with bimodal distribution), thus any threshold between 0.5 and 0.9 would roughly lead to the same. In your case, you got more of a 'continuous' fashion for terminal states, thus the threshold matters a lot more. Setting it to 0.7 (current default) removes many transitions which should have been retained - and eventually leads to those arrows within the terminal states.. So I would suggest to increase the default threshold to e.g. 0.9 in order to ensure that only 'real' terminal states are considered as such.

**Comment by Marius1311** [comment]
Awesome, thanks so much for figuring this out! I agree - let's increase that threshold. The way I compute the `final_states_probs` is by

- taking one membership vector per final state
- scaling each of them to [0, 1]
- per cell, take the max over all scaled membership vectors

This way, there will always be at least 1 cell per final state which has prob. 1 of being a final state.

**Comment by VolkerBergen** [comment]
Right! What do you think - set it to 0.9 then? Could also add another parameter to have user-control over that.

**Comment by Marius1311** [comment]
Yes, for now, I would add this as a user exposed parameter since we don't have much experience with it yet. Once we have figured out a value that works well for most datasets, we could hide it from the user again. I would default the parameter to 0.9

**Comment by Marius1311** [comment]
Let me know once the parameter is exposed so that I can test this please.

**Comment by VolkerBergen** [comment]
Added `threshold_root_end_prior` (defaulted to 0.9).

**Comment by Marius1311** [comment]
Awesome, thanks! Will check this out today.

**Comment by Marius1311** [comment]
Fantastic, works: 
![image](https://user-images.githubusercontent.com/24494650/85742975-f9aef880-b703-11ea-8dfb-c0cfe7baef09.png)

The only thing still missing is the info about which priors were used. I pulled scvelo from master, yet the only info I get printed out is:
```
running PAGA
    finished (0:00:01) --> added
    'paga/connectivities', connectivities adjacency (adata.uns)
    'paga/connectivities_tree', connectivities subtree (adata.uns)
    'paga/transitions_confidence', velocity transitions (adata.uns)
```
would be nice to know which root/final annotation and time_prior was used, to be on the safe side.

**Comment by Marius1311** [comment]
One more thing: it seems like `velocity_pseudotime` (Fig 1) works better than `latent_time` (Fig 2) below. Any intuition for why this may be? Does `velocity_pseudotime` take cellrank's roots into account already?

## Figure 1
![image](https://user-images.githubusercontent.com/24494650/85746087-7cd14e00-b706-11ea-9e50-845d6c7016d2.png)

## Figure 2
![image](https://user-images.githubusercontent.com/24494650/85746148-86f34c80-b706-11ea-9472-8663aa421e05.png)

Latent time just misses that one transition to Epsilon. `latent_time` vs `velocity_pseudotime`: 
![image](https://user-images.githubusercontent.com/24494650/85746222-983c5900-b706-11ea-96f2-4c33d4e72664.png)

**Comment by VolkerBergen** [comment]
Priors are printed now. 

Yes, I've seen that latent time 'hides' one connection due to low confidence. I will have a look what my the reason for that.

**Comment by Marius1311** [comment]
Excellent, thanks.

**Comment by Marius1311** [comment]
Is it possible to use cellrank's root prior for velocity pseudotime as well?

**Comment by Marius1311** [comment]
@VolkerBergen just checked printing the priors for directed PAGA, works, thanks! What's left from an interfacing point of view is to not recompute root/start points if only one of the two is not provided.

**Comment by michalk8** [comment]
@Marius1311 can we close this?

**Comment by Marius1311** [comment]
Yes, let's close this.
