### ISSUE TITLE
scvelo interfacing

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#131]
Hi @VolkerBergen , we have `final_states_probs` and `root_states_probs` in place in `adata.obs` now and can discuss interfacing with directed PAGA and also latent time:

## Directed PaGA
I had a quick look at directed PAGA, if I'm not mistaken, we have to modify this parameter:

`use_root_prior : `str` or bool, optional (default: True)
    Obs key for root/final states. If True, 'root_cells' and 'final_cells' are used if available.
`

Is it already possible to pass a tuple `('final_states_probs', 'root_states_probs')`? I'm not saying this is the best way of passing this information, I'm happy to hear your opinion on this!

## Latent time
I tried calling latent time like this:
```
scv.tl.latent_time(adata_t, root_key='root_states_probs', end_key='final_states_probs')
```
but this issued the warning: `WARNING: No root cells detected. Consider specifying root cells to improve latent time prediction.`

Also, the result tells me that my root state was not taken into account. Can we change this, to take the keys into account?

**Comment by VolkerBergen** [comment]
Just tested `final_states_probs` and `root_states_probs` in several runs with diff. parameters (n_neighbors, n_top_genes etc.) and got the impression that it requires some improvements towards robustness. Currently, I get the following:
![image](https://user-images.githubusercontent.com/31883718/82349164-13209e80-99fa-11ea-90e3-4092d38250b3.png)
![image](https://user-images.githubusercontent.com/31883718/82349190-187de900-99fa-11ea-93b7-5ec13d803ff3.png)

Final states seems fine, yet a correct root state identification is also vital when using it as prior for latent time or dir. paga.

**Comment by VolkerBergen** [comment]
The simplified implementation in `terminal_states` does not capture the final cells as nice as your new version, but seems to capture the root cells better for some reason. I'd suggest a revision of the current implementation of computing `root_states_probs`.
![image](https://user-images.githubusercontent.com/31883718/82349967-081a3e00-99fb-11ea-8323-03a0b5304203.png)

**Comment by Marius1311** [comment]
Hi Volker, something seems to be going wrong with the root states probs, I agree. Can you please pull from master, run again and poste the code/notebook you used to generate this? Happy to look into it.

**Comment by VolkerBergen** [comment]
This can be reproduced with the standard pipeline (non-dynamical for quick review):
```
adata = scv.datasets.pancreas()
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)

scv.tl.velocity(adata)
scv.tl.velocity_graph(adata)
scv.tl.terminal_states(adata)

cr.tl.find_root(adata, cluster_key='clusters')
cr.tl.find_final(adata, cluster_key='clusters')
cr.tl.lineages(adata)
```

**Comment by Marius1311** [comment]
Follow up from today: the root's above are a result of not using 'connectivities' for `velocity_graph` computation. Will add a check for the velocity graph parameters and issue a warning if they don't adhere with cellrank's expected param settings.

**Comment by Marius1311** [comment]
@VolkerBergen , I have an issue with latent time. I pass `root_key='root_states_probs'` , where `root_states_probs` is in Fig 1 below and the resulting latent time is Fig 2. Something must have gone wrong with passing over the root information. I looked into the latent time function and found this line here: https://github.com/theislab/scvelo/blob/8314397ca79a5a0b271990121c92320020c9993c/scvelo/tools/dynamical_model.py#L603

`idx_root` is a boolean array with one `True` element in my case. I check where that sits using `np.where`, the index is 2371, see Fig 3 below. This seems like a fine root cells. 

However, the next two lines change this index, see https://github.com/theislab/scvelo/blob/8314397ca79a5a0b271990121c92320020c9993c/scvelo/tools/dynamical_model.py#L604

I check the value of `roots`, it's now `1764`, see Fig 4 below. Now, that's not the desired root cells, and this has the latent time of Fig 2 as a consequence. 

The same thing happens for the final states, their internal indices also do not reflect what I input. What's the reason for this function behaviour?

## Fig 1
![image](https://user-images.githubusercontent.com/24494650/82834216-bec96300-9ec0-11ea-9394-1d77f35944d9.png)

## Fig 2
![image](https://user-images.githubusercontent.com/24494650/82834233-c852cb00-9ec0-11ea-8ea8-0fd7ad072847.png)

## Fig 3
![image](https://user-images.githubusercontent.com/24494650/82834266-dbfe3180-9ec0-11ea-8969-921bd7b925aa.png)

## Fig 4
![image](https://user-images.githubusercontent.com/24494650/82834288-ee786b00-9ec0-11ea-9874-ab7a1fe473f7.png)

**Comment by VolkerBergen** [comment]
crap, thanks for spotting this. With the latest edit to allow for str/nan values (`root_states`), a bug has sneaked in. It should be fixed now. Would appreciate if you could test again. Urgently need to add a build test for latent_time.

**Comment by Marius1311** [comment]
Hi Volker, the above error is solved. Below, I show the root & final states probs (Fig 1) and the cells which are now chosen by latent time (Fig 2). In Fig 3, I show the resulting latent time. One thing seems strange: why do cells in the intermediate region, between Alpha and Beta cells, get higher latent times assigned than the final Alpha cells? See Fig 4 for cluster annotations. I'm talking about the early Alpha cells, which don't yet seem fully commited towards Alpha.

## Fig 1
![image](https://user-images.githubusercontent.com/24494650/82880842-40f86c80-9f3f-11ea-964b-7e780d364821.png)

## Fig 2
![image](https://user-images.githubusercontent.com/24494650/82881015-6e451a80-9f3f-11ea-9c11-818ce74fa518.png)

## Fig 3
![image](https://user-images.githubusercontent.com/24494650/82881100-887ef880-9f3f-11ea-9f8e-14dcb99c9e52.png)

## Fig 4
![image](https://user-images.githubusercontent.com/24494650/82881282-cbd96700-9f3f-11ea-92e2-697a181ca385.png)

**Comment by VolkerBergen** [comment]
Great! Does it make a difference if you don't pass `end_key`, but solely `root_key`?

**Comment by Marius1311** [comment]
Let me check that. Will get back to you.

**Comment by Marius1311** [comment]
Hi Volker, I just checked, passing the `end_key` makes no difference, the latent time is exactly the same. Maybe it's not taken into account for some reason?

**Comment by Marius1311** [comment]
Update, I looked into this in a bit more detail and went through different scenarios:
- no `root_cells`, no `end_points` present and either `root_states_probs` or `final_states_probs` missing --> recomputes terminal states
- no `root_cells`, no `end_points` present but both `root_states_probs` and `final_states_probs` present --> uses these
- providing `root_states_probs` vs. not providing anything --> makes a difference
- providing `root_states_probs` and `final_stats_probs` vs. only providing `root_states_probs` --> does not change anything

The first 3 are fine, the last one worries me. In the case where I provide only `roor_states_probs`, the terminal states are recomputed. I check what the final states are, see Fig 1 below. This is very different from what I pass in using `final_states_probs` (see Fig 2), so I'm confused that it leads to the same result

## Fig 1
![image](https://user-images.githubusercontent.com/24494650/83018551-cbb39700-a025-11ea-93d7-65120c6c8dc3.png)

## Fig 2
![image](https://user-images.githubusercontent.com/24494650/83018581-d9691c80-a025-11ea-9660-aecb90a0c71c.png)

**Comment by VolkerBergen** [comment]
Right, it was only using root_cells as described in the manuscript. Having end_points/final_cells was only experimentally and not yet active, b/c it needs some discussion how to deal with those correctly. We usually only have one root and many final states, thus the end_key was meant to cover cases like the lung data, where we have two roots and one final states. It's enabled now, yet we need to have another discussion on that to make sure we're doing it right.

**Comment by Marius1311** [comment]
Alright, let's have that discussion in one of the next meetings. I'm closing this issue now, let's discuss further interfacing issues separately when they arise.
