### ISSUE TITLE
Binder Notebooks

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#134]
Thanks Mike for setting this up, I just checked it out but it failed for me, see below for the last part of the log.

```
Step 41/51 : RUN conda env update -p ${NB_PYTHON_PREFIX} -f "environment.yml" && conda clean --all -f -y && conda list -p ${NB_PYTHON_PREFIX}
 ---> Running in 5efda637825b
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... Failed to connect to event stream
```

**Comment by michalk8** [comment]
Should be fixed. Problem was that I specified wrong version of scanpy in requirements in order to make tests work. They should be working now as well.

**Comment by Marius1311** [comment]
This really works very well, it's just very slow, but I guess we can't do much about that. In any case, the user can just download the notebook in case this is too slow.
