### ISSUE TITLE
GDPT

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#137]
When running the pipeline tests, I get the following:
```python
.0 = <range_iterator object at 0x7fd5313a24b0>

        (
            np.abs(e_vals[l])
            / (1 - np.abs(e_vals[l]))
            * (e_vecs[i, l] - e_vecs[:, l])
        )
        ** 2
        # account for float32 precision
        for l in range(0, e_vals.size)
>       if np.abs(e_vals[l]) < 0.9994
    )
E   ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

../cellrank/tools/estimators/_base_estimator.py:781: ValueError
```
@Marius1311 could you please look into it? (I think the evals are 3rd returned argument).
I also have 1 more request from you: all the methods `'scipy, 'brandts' and 'krylov'` requrire `SLEPc` and `PETSc`, which is very inconvenient for testing (the installtion time time). I remember that for method `'brandts'`, we can get the evals from one of the matrices. It would be great if you could implement this since you have the understanding of it.

**Comment by Marius1311** [comment]
good point, will do!

**Comment by Marius1311** [comment]
Hi Mike' cant' reproduce the bug you get above. Did you set the root cell though? I run
```
adata_t.uns['iroot'] = 9
g_fwd.compute_gdpt()
```
and it works fine. Return values of `krylov_schur` are `return Q, top_eigenvals, top_eigenvals_error`

**Comment by michalk8** [comment]
Ah I see, that was my mistake. I was already using the `sorted_schur` which returns the Schur matrix - i.e. `R, Q, top_eigenvals, top_eigenvals_error`. It works as expected, thanks!
