### ISSUE TITLE
Schur decomposition

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#138]
Long term, it would be better to compute the schur decomposition _before_ running GPCCA, i.e. having a `self.decompose(mode: str = 'schur/eigen', method: str = 'krylov/brandts/scipy')` method that one calls before calling `self.compute_metastable_states` for the following reaons:

1. efficiency. Often, I want to compute the decomposition for several values of `n_states`. Currently, that means I'm recomputing the schur decomposition every time I do that. 
1. a priori defining a set of feasible values for `n_states`. Currently, I run `compute_metastable_states` and it fails if I split a pair of complex conjugate eigenvalues. Would be nicer to know this a priori. Currently, this is possible by first computing the eigendecomposition, but this is actually a duplication. 
1. being able to inspect the schur vectors before running `compute_metastable_states`
1. would enable us to not have to run `krylov_schur` before method `brandts`. The problem at the moments it: where do I get the eigenvalues from to say whether we will split a block of complex conjugates? I can compute the evals from brandts, but only once I have computed the full decomposition, see #137

**Comment by Marius1311** [comment]
In practical terms, this would mean moving some of the GPCCA code to compute decompositions into cellrank, and creating a possibility in msmtool's GPCCA to use an already existing schur decomposition.

**Comment by michalk8** [comment]
@Marius1311 I don't think we need to move any code, look here: https://github.com/msmdev/msmtool/blob/krylov_schur/msmtools/analysis/dense/gpcca.py#L1109 - it runs the Schur decomposition only when previous one is not found!

**Comment by Marius1311** [comment]
oh, I see! Do we make use of this in our code yet, or do we initialise a new GPCA object every time?

**Comment by michalk8** [comment]
Implemented via #155
