### ISSUE TITLE
Fix gene trend plotting test

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#148]
This is failing because some image is missing. Would be great if we could re-generate the image and fix the test.

**Comment by michalk8** [comment]
There's deeper issue at play - the order of genes is not always preserved (across different scanpy/adata versions?) and I'm using indices. I will hardcode the gene names to prevent this issue from rising up again.

**Comment by Marius1311** [comment]
ok I see

**Comment by Marius1311** [comment]
Ah, so good to have that `build=passing` badge!
