### ISSUE TITLE
Flake8

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#161]
Enable Flake8 for more consistent development

**Comment by Marius1311** [comment]
what's the advantage over black?

**Comment by michalk8** [comment]
They work in conjunction - black reformats your file, but doesn't do everything, like warn you about unused imports/variables, wrong phrasing in docs. etc.

**Comment by Marius1311** [comment]
Okay, cool, sounds good!

**Comment by michalk8** [comment]
Closed via #166
