### ISSUE TITLE
Extract the eigenvalues from GPCCA

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#162]
With https://github.com/msmdev/msmtools/pull/9, I included the eigenvalues in the GPCCA class as `self.eigenvalues`, no matter whether `brandts` or `krylov` is used as `method`. We can now go ahead an modify https://github.com/theislab/cellrank/pull/155 such that a call to `self.compute_schur` also extracts the eigenvalues and saves them in our estimator object, to be used in functions like `self.plot_spectrum`. A call to `self.compute_eig` should just overwrite these.

**Comment by michalk8** [comment]
Implemented via #170
