### ISSUE TITLE
Update Tutorials

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#164]
Need to update 
- high level tutorial to use GPCCA behind the scenes once #163 is merged
- low level tutorial to present different kernels and estimators

**Comment by michalk8** [comment]
Had an idea today - we could add regression tests for our notebooks to make sure nothing is broken in the tutorials (or just to regenerate them), such as by doing function renaming.
Issues:
- time: the major bottleneck being scvelo here (~10 minutes per notebook; testing can be parallellized which is good) - not sure how to solve this now
- 'gam_mgcv'` is causing problems in one of the tutorial (could replace with some `sklearn` 
estimator)

This is just a mere suggestion, maybe and overkill.

**Comment by Marius1311** [comment]
I think it's a good idea to somehow include our tutorials in the testing system to be automatically notified when we break something. Let's maybe just adapt our tutorials to used cached velocities, that should solve the first issue.

**Comment by Marius1311** [comment]
Done!
