### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#165]
Should update our docs to introduce the two modules of Cellrank (kernels and estimators). Also, update figures.

**Comment by michalk8** [comment]
When you update the docs, could you please also create file called `pypy.rst`? It will be displayed on PyPI' page (just some boiled down version of `README.rst`).

**Comment by Marius1311** [comment]
Sure, will do.

**Comment by Marius1311** [comment]
This seems to work again - I assume you fixed it @michalk8 , thanks for that!

**Comment by Marius1311** [comment]
Done!
