### ISSUE TITLE
Running `self.compute_metastable_states` modifies schur decomposition

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#177]
Say I compute my schur decomposition using `self.comptue_schur()`, which by default gives me a decomposition of size `10`. If I now compute metastable states using `self.comptute_metastable_states(n_states=3)`, then this also restricts my schur decomposition to be of size 3, which is bad if afterwards, I want to compute `n_states=4` metastable states (because we need to recompute). Therefore, computing metastable states should not restrict the saved schur decomposition, but only enlarge it if needed (in case we have to recompute).

**Comment by michalk8** [comment]
Implemented via #178

**Comment by Marius1311** [comment]
Thanks!
