### ISSUE TITLE
Bug in `self._select_cells`. 

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#181]
I compute metastable states as `g_fwd.compute_metastable_states(cluster_key='clusters', n_states=2)`, which gives the following output:
```
Computing metastable states
INFO: Using pre-computed schur decomposition
WARNING: The following groups could not be mapped uniquely: `AT2 cells_1, AT2 cells_2`
Adding `.schur_vectors`
       `.metastable_states`
       `.coarse_T`
       `.coarse_stationary_distribution`
    Finish (0:00:00)
```
The resulting states look like this: 
![image](https://user-images.githubusercontent.com/24494650/84035028-75d2dd80-a99b-11ea-9058-7222f1d17c8f.png)
This makes no sense. So I check the membership vectors themselves:
![image](https://user-images.githubusercontent.com/24494650/84035081-884d1700-a99b-11ea-9880-e0016932c6b7.png)

They look fine, just the names are off, see the cluster assignment below:
![image](https://user-images.githubusercontent.com/24494650/84035148-a0249b00-a99b-11ea-81f1-90ad394670dd.png)
This tells me: the first state should be called "to ciliated cells", while the second one should be called "to AT2 cells" 

Also, I check the metastable assignment like this: `scv.pl.scatter(adata, color=g_fwd._gpcca.metastable_assignment, color_map='Paired')`, which gives
![image](https://user-images.githubusercontent.com/24494650/84035292-cea27600-a99b-11ea-821d-142d012a3099.png)

This also looks fine, so it must be a problem with selecting cells from each metastable state. It seems like the wrong cells are selected, which subsequently means that the state gets the wrong name and color assigned. 

If needed, I can send you the anndata object to reproduce. Have we got tests yet for 
- selecting cells from each metastable state
- giving names to metastable states
- assigning colors to metastable states
? 

Since these seem to be a bit tricky in practice, would be important to include some tests for them.

**Comment by michalk8** [comment]
Seems pretty serious, will look into it. Don't have tests for this yet, will add.

**Comment by Marius1311** [comment]
Thanks!
