### ISSUE TITLE
Automating the coverage update

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#192]
@michalk8 , did you get round to this yet?

**Comment by michalk8** [comment]
Done via #188 - there was some unknown error, if it persists (I've issued a small fix), I wll create a new issue.

**Comment by Marius1311** [comment]
Code coverage is shown as 0 now...

**Comment by michalk8** [comment]
It means it at least runs, will debug it tomorrow.

**Comment by michalk8** [comment]
I can't seem to pinpoint the source of the error - I went through this, it seems fine: https://github.com/theislab/cellrank/runs/791304725?check_suite_focus=true.

**Comment by Marius1311** [comment]
mhm, I'm also unsure. I checked on codecov, our coverage went to 0 on June 20th. Something about the github action is not quite working yet....

**Comment by Marius1311** [comment]
Maybe the token fixes this problem, otherwise, I would consider opening an issue on the repo: https://github.com/codecov/codecov-action

**Comment by michalk8** [comment]
Done, because I don't know how to fix this. Here's the link: https://github.com/codecov/codecov-action/issues/85.

**Comment by Marius1311** [comment]
Thanks Mike

**Comment by michalk8** [comment]
Hackily fixed via https://github.com/theislab/cellrank/commit/69be28e86b72e2e3da1949ef450bb38cab9c865a
Uploader is the problem, when running under GitHub Actions.

**Comment by Marius1311** [comment]
Wow, I'm impressed!
