### ISSUE TITLE
Lineage object does not preserve column order 

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#198]
Under very particular circumstances, the Lineage class does not preserve the correct order of columns. Say I have a lineage object  `L` with 3 columns and names `['Alpha', 'Beta', 'Epsilon']`. If I now subset the rows and columns at the same time, and give all three keys but in a different order, i.e.

```
# create some bool mask
mask = adata.obs['clusters'] == 'Alpha'
mask = list(np.array(mask, dtype=np.bool))

# slice
L[mask, ['Epsilon', 'Alpha', 'Beta']]
```
The returned object will **not** have columns in the order `['Epsilon', 'Alpha', 'Beta']`. This leads to bugs in the `cluster_fates` function when selecting all lineages, but in a different order. In my case, that's important for plotting as I want the order to be consistent across methods.

**Comment by michalk8** [comment]
Thanks for pointing this out, will fix it later and add tests for this case.

**Comment by Marius1311** [comment]
Excellent, thanks. Will try this later.
