### ISSUE TITLE
`.compute_schur()` falls back to `krylov` even though `brandts` is specified

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#202]
Trying to run cellrank without `SLEPSc` results in a bug when the default number of schur components (20) for `self.compute_schur()` would split a pair of complex conjugates. When computing one more state than requested, method `krylov` is used again which results throws a `ModuleNotFoundError`: 
![image](https://user-images.githubusercontent.com/24494650/85376297-cddf1780-b537-11ea-9203-add8cadb8fb2.png)

**Comment by michalk8** [comment]
I think this is an error in `msmtools`, specifically here: https://github.com/msmdev/msmtools/blob/krylov_schur/msmtools/util/sorted_schur.py#L272
There should be also (or instead of `ImportError`): `ModuleNotFoundError`, since it's not installed.

**Comment by Marius1311** [comment]
okay, but why is the method switched from `brandts` to `krylov`?

**Comment by Marius1311** [comment]
Ah, this is not the current version of bernhard's branch!

**Comment by Marius1311** [comment]
Could that be it?

**Comment by Marius1311** [comment]
What's the best way to update this dependency for someone who has cellrank installed already?

**Comment by michalk8** [comment]
Ok, it's switched because of this: https://github.com/msmdev/msmtools/blob/krylov_schur/msmtools/util/sorted_schur.py#L279
It gets executed only once (when the msg is shown). The second time it's called, no msg is shown, therefore it doesn't default to `'brandts'`. In short, the line should be out of `if`-block.

**Comment by michalk8** [comment]
I will make a quick PR for this, regarding the updating `msmtools`, only through`pip install git+...`

**Comment by michalk8** [comment]
Should be fixed in https://github.com/msmdev/msmtools/pull/13. Afterwards, I think we can close this.

**Comment by Marius1311** [comment]
Thanks for spotting and fixing this Mike!

**Comment by jmchan88** [comment]
Hey Mike! Marius realized that a bug I'm encountering is possibly related to the above.

![image](https://user-images.githubusercontent.com/12499408/85414382-07188700-b53a-11ea-933a-52fcfd9bf5e3.png)

Checking the msmtools version, I have:

import msmtools
msmtools.__version__
1.2.5+216.ga368db7

**Comment by Marius1311** [comment]
Thanks for posting this @jmchan88 . The warning is harmless, it just means that for this state, we aren't quite sure about the name because it overlaps with several of your cluster.

**Comment by Marius1311** [comment]
Once https://github.com/msmdev/msmtools/pull/13 is merged, you can use cellrank properly without SLEPSc

**Comment by michalk8** [comment]
@Marius1311 can you test this once again? If it fallbacks to `'brandts'` correctly, I think we can close this.

**Comment by Marius1311** [comment]
sure, will do.

**Comment by michalk8** [comment]
Assuming this is solved, closing this.
