### ISSUE TITLE
Make sure plotting functions don't select cells

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#204]
In practice, it just gets really confusing with several calls writing metastable states, ie `self.compute_metastable_states` and `self.plot_metastable_states`. Therefore, I would change this such that

- only `self.compute_metastable_states` writes metastable states, ie selects cells and maps these towards precomputed clusters to get names and colors
- plotting functions just plot however many cells have previously been assigned
- plotting functions will no longer have `n_cells` but `discrete: bool = True`.

**Comment by Marius1311** [comment]
Equally, `set_main_states` should not do the cell selection. This should literally only be done once - when we compute the metastable states.

**Comment by michalk8** [comment]
`{set, compute}_main_states` must select cells, because there we merge the states + redistribute the probability mass.
I agree though that from the plotting functions should not select cells.

**Comment by Marius1311** [comment]
agreed.

**Comment by michalk8** [comment]
Implemented via #217 .
