### ISSUE TITLE
Sphinx fails

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#212]
I'm not sure whether we had this already. I'm trying to build the docs locally, `sphinx = v3.1.1`. Calling `make html` fails with
```
Exception occurred:
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/sphinx/domains/python.py", line 1194, in clear_doc
    if obj.docname == docname:
AttributeError: 'tuple' object has no attribute 'docname'
```

**Comment by michalk8** [comment]
I wouldn't ue the latest sphinx version.

**Comment by michalk8** [comment]
Let's close this. It's obvious by now that we'd need to wait till `sphinx==3.1.1` become more stable.
