### ISSUE TITLE
Code coverage showing 0% again

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#230]
I thought this was solved?

**Comment by michalk8** [comment]
This is different error, one due to the fact we're using `python-vendorize`, the previous error is fixed. Haven't found a solution yet.

**Comment by Marius1311** [comment]
oh I see.

**Comment by michalk8** [comment]
Should be fixed via: https://github.com/theislab/cellrank/commit/12415942fcd40a56c7f2a9e9bd7928bafa37f7f0
Problem was the order of operation...

**Comment by Marius1311** [comment]
nice, thanks for fixing this!
