### ISSUE TITLE
[dev] on zsh shell

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#232]
Needs to be `pip install -e .'[dev]'` on the Mac zsh shell, see https://github.com/mu-editor/mu/issues/852

**Comment by michalk8** [comment]
Done via #https://github.com/theislab/cellrank/commit/fb5d59bf1fc82bddeb7c0bef6ef6b62e1f6925a4

**Comment by Marius1311** [comment]
thanks!
