### ISSUE TITLE
Change the default colormap to be colorblind-friendly

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#236]
So far, when I don't provide a cluster key, I get a fairly standard matplotlib color palette:
![image](https://user-images.githubusercontent.com/24494650/86479740-06a79980-bd4d-11ea-9a1a-7fcaaa2af6a5.png)

However, using red and green together is really not very colorblind friendly. Volker takes care of it [here](https://github.com/theislab/scvelo/blob/a7de78ae974b251c366f208aab2e685b23bc101e/scvelo/settings.py#L80) in scvelo. Would be nice to just use the same colormap by default for categorical annotations.

**Comment by michalk8** [comment]
Ok, I've changed the order to `tab10`, `tab20`, etc. This should've fixed it.

**Comment by Marius1311** [comment]
fab, will try!
