### ISSUE TITLE
Add extra install for krylov method

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#246]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

Instead of listing out all 4 extra things to be installed in https://cellrank.readthedocs.io/en/latest/installation.html,
add an option like `pip install cellrank[krylov]` that will install them (libopenmpi is still a necessary precursor).
Also see if it's possible to do it through conda as well.

**Comment by Marius1311** [comment]
what's this issue about?

**Comment by michalk8** [comment]
Mostly convenience: user can type `pip install cellrank[krylov]` or `conda install cellrank-krylov` and it will hopefully add the SLEPc and PETSc dependencies.
For the `conda`, we can do it as matplotlib does - have `cellrank-base` (without slepc, ...) and `cellrank`, see here:
https://github.com/conda-forge/matplotlib-feedstock/blob/5af510232c2fa984e981e3eeb18128a6cab41b6d/recipe/meta.yaml#L69-L82
Or do you prefer `cellrank-krylov`?

**Comment by Marius1311** [comment]
Thanks! This would be a fantastic addition and would make installation so much easier! As for the terminology for conda, I prefer having `cellrank` and `cellrank-krylov`
