### ISSUE TITLE
Rename root/final to initial/terminal.

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#254]
- [ x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

After a discussion with Dana and Fabian, we decided to change terminology from `root_states` and `final_states` to `initial_states` and `terminal_states`, because these terms are used more frequently in the bio community. It means we have to change this throughout our API.

**Comment by michalk8** [comment]
@Marius1311 any consensus yet?

**Comment by Marius1311** [comment]
we can safely rename to `initial_states` and `terminal_states`. Still no consensus on `metastable` vs `macrostates`.

**Comment by Marius1311** [comment]
Let's go ahead with this and rename to `initial/terminal`.
