### ISSUE TITLE
PETSc solver for absorption probabilities

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#260]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

I think it would be worthwhile looking into PETSc and its linear solvers (chapter 4, KSP: Linear Equations Solvers: http://web.mit.edu/tao-petsc_v3.7/petsc_manual.pdf). Seems like it's also well-suited for solving multiple linear systems (chapter 4.2)
So far, running on 100k+ cells, 3 states takes at least 45mins with no end in sight (will let it run for a few hours + change the number of cores).
I think PETSc can speed this up, given our experience with it.
@Marius1311 What do you think? This could effectively also solve #256 and much more elegantly.
Docs are here: https://www.mcs.anl.gov/petsc/petsc4py-current/docs/apiref/petsc4py.PETSc.KSP-class.html  # rather uninformative
Tutorials/code samples:
- https://github.com/JesseLu/petsc4py-tutorial/blob/master/ksp_serial.py
- https://www.firedrakeproject.org/petsc-interface.html

**Comment by michalk8** [comment]
Update: it still hasn't finished.

**Comment by michalk8** [comment]
Other issue is, the solvers from `scipy` are already parallelized - running these solutions separately and parallelizing them was really counter-productive.

**Comment by Marius1311** [comment]
Okay, but how does that work? I thought the `scipy` iterative solvers only take equations of the form `A x = b` where `b` is a vector, so I would always have to iterate? Maybe I missed something.
