### ISSUE TITLE
Installing from conda with option krylov

### ISSUE THREAD

**Issue by mbuttner** [theislab/cellrank#265]
I'm trying to install from conda using
`conda install -c conda-forge -c bioconda cellrank-krylov`. However, this gives
```
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cellrank-krylov

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
...

**Comment by michalk8** [comment]
Hi @mbuttner ,
we're still waiting for this to get merged, see here https://github.com/bioconda/bioconda-recipes/pull/23136

**Comment by michalk8** [comment]
@mbuttner , the PR was merged, could you please try `conda -c install conda-forge -c bioconda cellrank`? It worked flawlessly on my machine.

**Comment by mbuttner** [comment]
@michalk8 
`conda -c install conda-forge -c bioconda cellrank` gives me the following error: 
```
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: -c cellrank
```
I ran 
`conda install -c conda-forge -c bioconda cellrank` instead and that worked flawlessly as well. 

However, running `conda install -c conda-forge -c bioconda cellrank-krylov` returns
```
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
```

**Comment by michalk8** [comment]
Sorry for the typo. Could you please try in a fresh new conda environment if you haven't already?

**Comment by mbuttner** [comment]
A fresh new conda environment did the trick. The command ran smoothly. Thanks a lot for your prompt help!

**Comment by mbuttner** [comment]
I would like to leave a comment concerning the use of `rpy2` in cellrank. Using a fresh conda environment, I would recommend to install `rpy2` first (on my Mac, `conda install -c r rpy2` worked without errors, something I'm not used to for rpy2). Then, running `conda install -c conda-forge -c bioconda cellrank-krylov` works as well.

**Comment by Marius1311** [comment]
@michalk8 , we should consider adding this to our installation instructions under `Gene trend plotting using rpy2` or something - I've had troubles getting rpy2 to run as well, and I've also heard from Joe that this caused difficulties.

**Comment by Marius1311** [comment]
btw. @michalk8 feel free to close this once we have adapted our installation instructions.

**Comment by michalk8** [comment]
Do we really need it? I'd rather just wrap some sklearn models, since GamMGCV is so far the only one working out of the box.
Also, I'm still curious (and waiting) to see how https://github.com/theislab/diffxpy/issues/117 would work.

**Comment by Marius1311** [comment]
`GamMGCV` is also by far the best performer so far, so I do think we need `rpy2`.

**Comment by michalk8** [comment]
Rpy2 is no longer required (although still usable), the new model is based on `pygam` - `cellrank.ul.models.GAM`, see https://github.com/theislab/cellrank/pull/289 for more info.
Closing.
