### ISSUE TITLE
`g_fwd.set_main_states()` does not write absorption probs

### ISSUE THREAD

**Issue by mbuttner** [theislab/cellrank#266]
I compute absorption probs for a GPCCA estimator object and would like to write them to adata using `g_fwd.set_main_states()`. However, this writes something else and not the computed absorption probs. 

#### Versions:
cellrank==1.0.0-b.8 scanpy==1.5.1 anndata==0.7.3 numpy==1.17.4 scipy==1.4.1 pandas==0.25.2 scikit-learn==0.21.3 statsmodels==0.10.1 python-igraph==0.7.1 scvelo==0.2.1
> ...

**Comment by michalk8** [comment]
For GPCCA estimator, `set_main_states` writes the GPCCA memberships to `g_fwd.lineage_probabilities`.
If you want the true absorption probabilities, you need to run `g_fwd.compute_absorption_probabilities` - this will override `g_fwd.lineage_probabilities`. @Marius1311 is still discussing which one we should use (most likely the latter).

**Comment by michalk8** [comment]
closed via #276

**Comment by Marius1311** [comment]
@mbuttner , we refactored our code quite a bit, will update tutorials soon. The workflow should be much clearer then!
