### ISSUE TITLE
Update installation docs

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#271]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

Update docs installation section.

**Comment by Marius1311** [comment]
I would add the following lines, either under `Installation` or in a new section `Default and optimized installation`:

"CellRank has been designed to scale **very well** to large cell numbers. For this, we rely on two highly optimised libraries, `PETSc` and `SLEPSc`. These can take a bit longer to install (up to 10 minutes), so we made them **optional** dependencies, all functionality is available without them as well. In the following , we always give two installation options:
- **default**: without `PETSc` and `SLEPSc`, fast and easy installation, works fine on your laptop up to ~10-15k cells
- **optimized**: with `PETSc` and `SLEPSc`, installation takes a bit longer, scales very well to 100k+ cells

Note: if an error occurs during installation of the **optimized** version, please scroll down to the Dependencies section, where we give detailed installation instructions for `PETSc` and `SLEPSc`. 
"

For both `pip` and `anaconda`, you then give both options, starting always with the default. In these sections, you can then get rid of the link to the Dependencies section. Just make sure to add links/references for both PETSc and SLEPSc, there are corresponding publications.

**Comment by Marius1311** [comment]
Under Dependencies, I would then start with an opening paragraph about `PETSc` and `SLEPSc` before going into the installation details, and remove the text at the bottom ("Note that this is only relevant for the cellrank.tl.GPCCA estimator...") to have more structure. 

Suggestion for this opening paragraph:
"Some of the inference tasks that CellRank performs can be broken down to linear algebra problems. For example, we solve linear systems to compute fate probabilities and we compute partial Schur decompositions and find metastable states. For these computations to be scalable, we rely on highly optimized libraries which make use of sparsity structure, parallel implementations and efficient message passing, among others. The libraries we use are `PETSc` and `SLEPSc`. Note that CellRank **runs without** these as well, however, if you would like to apply it to large (>15k cells) datasets, we recommend you install them. Below, we give details for installing both `PETSc` and `SLEPSc` in case you had issues with  the **optimized** install option above for both `pip` and `anaconda`. If after reading this, you still can't install `PETSc` or `SLEPSc`, feel free to open an issue [LINK]. 
"

And add links to PETSc and SLEPSc
