### ISSUE TITLE
`cr.datasets`

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#28]
The data we use in our tutorials, but also for our figures, will be a bit different from scvelo's data. For reproducibility, it would be nice to have a `.datasets` module, that allows the user to conveniently download our datasets from the notebooks repo. Could you look into how scvelo does this and potentially adapt this to our needs?

**Comment by michalk8** [comment]
`adata` objects can be downloaded from an url and that's how it's done in scvelo (they host the object on the notebooks GH). If you give me the adata object, I can create `datasets.py` file.

**Comment by Marius1311** [comment]
nice, thanks. I'm just working on updating the tutorials, I will push the adata object together with that.

**Comment by Marius1311** [comment]
Alright, I added a `data` folder to our notebook repo. You may want to move this folder to the top level of the repo, so that users can find it more easily. Once the dataset loading is implemented, it would be nice to change this in the tutorials.

**Comment by michalk8** [comment]
Done via #31
