### ISSUE TITLE
`cr.tl.lineage_drivers` is broken

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#285]
`cr.tl.linege_drivers` is supposed to give me gene correlations with different lineages. It used to add one key per lineage to adata.var or adata.raw.var. Obviously, we expect different drivers genes for the different lineages. However, when I run it now, only a single key, `gene_count_corr` is added to `adata.raw.var`. Why is that? I would like to see the correlations of gene expression with the different sets of absorption probabilities, i.el. we need to add one key per lineage. 

#### Versions:
cellrank==1.0.0-rc.0 scanpy==1.5.1 anndata==0.7.3 numpy==1.18.5 scipy==1.4.1 pandas==1.0.5 scikit-learn==0.22 statsmodels==0.10.2 python-igraph==0.7.1 scvelo==0.2.2.dev51+ga7de78a
> ...

**Comment by Marius1311** [comment]
Sorry, I just realised now that I called `cr.tl.lineage_drivers`, whereas in the past, I always called the corresponding estimator method. I just tried, the estimator method still works, so I guess the high level function isn't quite there yet?

**Comment by michalk8** [comment]
Unable to reproduce, `cellrank.tl.lineage_drivers` just calles the estimator's lineage drivers - I've just added tests in the PR and cleaned up some error messages.

**Comment by Marius1311** [comment]
okay, maybe I made some silly mistake. I will check whether this happens again and send a MWE in that case
