### ISSUE TITLE
`cr.pl.heatmap` for genes from adata.raw

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#286]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

So far, our heatmap plotting function can't be used for genes which are only in `adata.raw.var_names`. Adding support for .raw would be nice.

**Comment by michalk8** [comment]
The models' fit function doesn't suppoort .raw attribute, guess it needs to be changed.
