### ISSUE TITLE
Absorption probabilities slowdown

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#306]
The time it took to compute absorption probabilities on the lung used to be about 1.5 min in rc0. In rc4, it suddenly increased to 3.5 min. Any ideas what's going on?

**Comment by Marius1311** [comment]
It may be related to the fact that I'm solving a different problem in rc4 becasue the transition matrix is different. We **really** need to figure out why we deviate from the old transition matrix, even when using the deterministic mode!

**Comment by Marius1311** [comment]
Did you change anything else in the code that could have caused this slowdown? When I call the function without any arguments, it takes 3.5 min to run. If I set `use_petsc=True` and `solver="gmres"`, then it does not even finish in 10min. This is a bit upsetting, as this was really a solved problem!

**Comment by michalk8** [comment]
By default, you compute also the mean time until absorption, which solves 1 more linear system. Could you try running it as `(..., absorption_time_moments=None)`? It should be back to speed.
If that's the case, I will set the default to `None`.

**Comment by michalk8** [comment]
P.S. Since I haven't tested the speed on the Lung (crashed on my PC still and I needed a break from servers), could you please test `absorption_time_moment="second"`?

**Comment by Marius1311** [comment]
> @Marius1311
> By default, you compute also the mean time until absorption, which solves 1 more linear system. Could you try running it as `(..., absorption_time_moments=None)`? It should be back to speed.
> If that's the case, I will set the default to `None`.

Setting absorption time moments to `None` in face reduces the computations time to 1min 55sec. It was at 1min 44 sec before, but this does not really matter and could be random chance. So this is fixed and I would indeed use `None` as the default value here.

**Comment by Marius1311** [comment]
> P.S. Since I haven't tested the speed on the Lung (crashed on my PC still and I needed a break from servers), could you please test `absorption_time_moment="second"`?

Hi Mike, I'm just running the second order computation on my mac and it's been running for over 20min already. I looked into the code and saw that you're doing an explicit matrix inversion. I remember we talked about this - please try to re-formulate this as a linear solve, I'm fairly sure this is possible. This can be a nice little maths exercise for you. We can talk about it tomorrow in case you get stuck.

**Comment by michalk8** [comment]
Ok, will look into it.
