### ISSUE TITLE
absorption time mean and variance?

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#308]
If a bit confused by the naming in the `.compute_absorption_probabilities` method of the base estimator. Why do we talk of time? We're not computing time until absorption, we're computing the probability that an individual cell will be absorbed by a given state, right?

**Comment by michalk8** [comment]
In `.compute_absorption_probabilities`, we're computing the absorption probabilities AND mean time 'til absorption + its variance, because it's more convenient (and effiecient, would have to store the `Q` and `S` matrices between function calls) to do so in 1 go than in 2 functions. Is this what you mean?

**Comment by Marius1311** [comment]
Yes, got it. I just checked out the `mean_abs_time`, this is what it looks like for the lung:
![image](https://user-images.githubusercontent.com/24494650/90637182-f891d780-e22b-11ea-8539-a9154ada5f97.png)
Looks like it's inverted - why would the cell closest to the absorbing states have largest time till absorption? Did you check this in an easy example (e.g. pancreas) and made sure the maths is correct?

**Comment by michalk8** [comment]
I can explain that - it's inverted because I thought it's better to think of it as pseudotime.

**Comment by Marius1311** [comment]
mhm okay I see. I wouldn't do that because it's confusing, and because what you call the variance won't be the variance of this inverted quantity. I would save the actual time until absorption and it's second moment, and I would save a derived pseudotime separetely, under a name like "absorption_pseudotime"
