### ISSUE TITLE
Monte Carlo Mode for the velocity kernel

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#311]
Has this been fixed to be a proper Monte Carlo method to propagate a distribution through a function? Please see the pdf I send you in slack for details on this.

**Comment by michalk8** [comment]
Implemented via https://github.com/theislab/cellrank/pull/301, here's the code if you want to do sanity checking: https://github.com/theislab/cellrank/blob/master/cellrank/tl/kernels/_velocity_kernel.py#L479

**Comment by Marius1311** [comment]
Let's go though this in our call today. This is important.

**Comment by Marius1311** [comment]
We can easily test this mode by comparing with Jax. As I said before, Jax is an approximation, Monte Carlo converges to ground truth for n -> infinity. So we don't expect to get exactly the same transition probabilities, but they should be similar compared to the deterministic transition probabilities.
