### ISSUE TITLE
Failing velocity kernel tests

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#312]
The following tests have been disabled because they were failing: 
- [x] `test_pearson_correlations_fwd` (recompute velo graph)(eleminate zeros)
- [x] `test_pearson_correlations_bwd` (recompute velo graph) (eleminate zeros)
- [x] `test_transition_probabilities_fwd` (recompute velo graph) (eleminate zeros)
- [x] `test_transition_probabilities_bwd` (recompute velo graph) (eleminate zeros)
- [ ] `test_backward_manual_dense_norm` (needs to be changed)
- [ ] `test_backward` (`softmax_scale`)
- [ ] `test_forward_manual_dense_norm ` (needs to be changed)
- [ ] `test_forward` (`softmax_scale`)
- [ ] `test_transition_backward_det` (`softmax_scale`/density normalisation)
- [ ] `test_transition_forward_det` (`softmax_scale`/density normalisation)

Did I miss any tests? For each, I noted down in paranthesis how we may fix it. For `test_backward_manual_dense_norm`  and `test_forward_manual_dense_norm `, we should change it to only test the density normalisation of the connectivities, if we don't already have that.

**Comment by Marius1311** [comment]
@michalk8 , is there any easy way for me to see how you generated the ground truth adata objects used for the testing? Is there a script somewhere that creates these?

**Comment by Marius1311** [comment]
I'm looking at the `test_pearson_correlations_fwd` using the 200 cell anndata testing object. The precomputed velocity graph saved in there does not match the one I get running scvelo. The precomputed graph has 5788 elements, when I re-compute it using scvelo, I get 4048 elements. What's going on here?

**Comment by Marius1311** [comment]
Both tests for pearson correlation pass locally when I recompute scvelo's velocity graph.

**Comment by Marius1311** [comment]
Also, both tests for transition probabilities pass locally when I recompute scvelo's velocity graph. So it may just be a problem with an outdated version of scvelo you used to compute the velocity graph.

**Comment by Marius1311** [comment]
The only thing I'm mildly worried about is: for the correlations, scvelo's velocity graph has 12 fewer elements than cellrank's (4048 vs. 4060). Still, the maximum deviation between the two matrices is 1e-7, so these elements must have been very small. When we move to transition probabilities, both matrix have the same number of elements again (4048). Any idea of what's happening here?

**Comment by Marius1311** [comment]
> > @michalk8 , is there any easy way for me to see how you generated the ground truth adata objects used for the testing? Is there a script somewhere that creates these?
> 
> https://github.com/theislab/cellrank/blob/master/tests/_helpers.py#L382 here's where's it's being generated. You can run the file from cmd line from root dir as: ` python3 tests/_helpers.py` I think I've regenerated them fairly recently, so it should be fine.

Well, when I don't recompute the velo graph, than the tests fail. If I do recompute it, then the tests pass, so I think it must have something to do with it. 

> I also remember having few elements less than expected (it was like ~980 vs 970), will look into it later today.

**Comment by Marius1311** [comment]
Could you check whether using the same value for softmax scale and consistently turning off density normalisation fixes some of these failing tests please?

**Comment by michalk8** [comment]
I can't reproduce this - on 200 adata, VG has 724 elements, the transition matrix (scvelo) has 1444 and ours 1876 (the connectivity kernel in VelocityKernel has 1882 values, so we must read something differet).

**Comment by michalk8** [comment]
I think it's because we first read the data from `obsp` whereas Volker saves it to uns - debug message shows this actually.
I will modify the reading function to use priority and set it to `uns` for Volker, though we should open a PR, since `obsp` should be used for graph data.

**Comment by michalk8** [comment]
Ok, I don't think that's the issue anymore (though I will keep that change just for good measure). The problem is that I get the indices and indptr from `VelocityKernel._conn` which is the graph under `adata.uns['neighbors']['connectivities']`/`adata.obsp['connectivities']`, where as it should be from the velocity graph. However, when I tried that, I get
```python
ValueError: zero-size array to reduction operation not possible
```
The culprit is cell 24, because
```python
<1x50 sparse matrix of type '<class 'numpy.float32'>'
	with 0 stored elements in Compressed Sparse Row format>
```
and I didn't account for this case.

**Comment by michalk8** [comment]
Note, this issue only occurs when using
```python
adata.uns["velocity_graph"]# + adata.uns["velocity_graph_neg"]
```
that is, without the negative.

**Comment by michalk8** [comment]
After using also the neg, I confirm I can reproduce this with the following code:
```python
import cellrank as cr
import scvelo as scv
import numpy as np

adata = cr.read("/opt/projects/helmholtz/cellrank/tests/_ground_truth_adatas/adata_50.h5ad")

T_scv = scv.tl.transition_matrix(adata, scale=4, use_negative_cosines=False, self_transitions=False)
print(T_scv.nnz)

k = cr.tl.kernels.VelocityKernel(adata, check_connectivity=True)
k._conn = adata.uns["velocity_graph"] + adata.uns["velocity_graph_neg"]

k.compute_transition_matrix(use_numba=False, n_jobs=1, softmax_scale=4)
T_cr = k.transition_matrix
print(T_cr.nnz)

assert np.isclose(T_scv.A, T_cr.A).all()
```
Suggested TODOs (mostly for me, let talk about it tomorrow):
- [ ] fix case when a cell doesn't have neighbors (@Marius1311 this shouldn't really happen, right?) - suggestion: do a sanity check (assertion) that we have some neighbors (easy) OR properly handle this case (will be a bit tricky because of the code, but w/e).
- [ ] since in the VelocityKernel we're using the velocity graph, adata `_read_from_adata` to accept `graph_key` (we always look for `connectivities`
- [ ] reintroduce tests

**Comment by michalk8** [comment]
Did a small RCA, found the bad commit: https://github.com/theislab/cellrank/commit/08031301fa6c2daeb900d6c36859fe9f4c8fb5bb#r41602568

**Comment by Marius1311** [comment]
Let's go through this in detail in our call today. I don't understand two things above
- why do you set `use_negative_cosines=False`? Shouldn't this be `True`?
- the scale parameter has inverted meaning between Volker and us.

**Comment by Marius1311** [comment]
A cell can't have no neighbors. In that case, the graph is corrupted and we should recompute it. Did you set `mode_neighbors="connectivities"` in scvelo?

**Comment by Marius1311** [comment]
And we **don't** need the velocity graph in the velocity kernel! It should work with just the connectivities and the Velocities.

**Comment by Marius1311** [comment]
to do's
- eliminate zeros from pearson correlations
- update scvelo (Mike)
- fix density normalisation and softmax scale.
