### ISSUE TITLE
Switch method for velocity kernel

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#317]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Convenience method to propagate uncertainty into the final quantities of interst.

**Comment by michalk8** [comment]
+ automatic_scale when `softmax_scale=None` - (use an estimate from determisitic mode)

**Comment by Marius1311** [comment]
The automatic scaling would be fab.!
