### ISSUE TITLE
References formatting

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#32]
For some reason, our references are not aligned, see https://cellrank.readthedocs.io/en/latest/references.html
It looks a bit odd at the moment.

**Comment by michalk8** [comment]
If you're talking about how they look when built locally vs on rtd.io, then you're right and I'm aware of it - so far, no idea why it happens.

**Comment by michalk8** [comment]
Ok, the problem is locally, we have `<dl>` tags (descriptions lists - I haven't seen them a lot) whereas on rtd, it's `<div>` + tables.

**Comment by michalk8** [comment]
Fixed. Problem was that we were using sphinx < 2 on the server. It now correctly uses 2+.

**Comment by Marius1311** [comment]
well done, thanks.
