### ISSUE TITLE
cellrank.tl.kernels.VelocityKernel deterministic mode

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#323]
Thourougly investigate why it doesn't match with our expectation (scvelo)

```python
https://github.com/theislab/cellrank/blob/master/tests/test_kernels.py#L1026
```

#### Versions:
https://github.com/theislab/cellrank/tree/9eca5d883844dd72058045c1bbb84f56226ea729

**Comment by Marius1311** [comment]
Could you first check whether it matches on the pancreas? After all, there may be a problem with our generated AnnData objects? Keep me up to date on this one please, would be great if we could figure this out today somehow.

**Comment by Marius1311** [comment]
Awesome, thanks a lot for figuring this out. Remaining to do's from my point of view:
- [ ] add a big comment to our code that reminds us of this finding in case we stumble upon this again in the future
- [ ] modify `test_pearson_correlations_{fwd/bwd}` to only compare on the indices that we agree on. Pearson correlations for these indices should be the same between cellrank/scvelo
- [ ] modify `test_transition_probabilities_{fwd/bwd}` to use cellrank's pearson correlations for the `velo_graph`. That should fix the discrepancies.
