### ISSUE TITLE
Estimate softmax_scale for VelocityKernel

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#328]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

As @Marius1311 had said, we can set it as we did previously by the median correlation. However, we'd have to run the method twice, it's better to estimate it using the fastest method (deterministic).

**Comment by Marius1311** [comment]
Great, thanks!
