### ISSUE TITLE
Allow custom function for Velocity kernel

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#330]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Currently, it's correlation + softmax, but it might be useful to allow others to experiment with their impl. @Marius1311 what do you think?

**Comment by Marius1311** [comment]
I think we should focus ourselves as much as we can and delay everything that's "nice to have" until later.

**Comment by Marius1311** [comment]
Hi @michalk8 , now is the time to read through https://www.biorxiv.org/content/10.1101/2020.09.19.304584v1, see which kernel functions they recommend (they have a nice derivation) and see whether these can be easily implemented using jax, to keep our uncertainty propagation intact (this is key, one of our main selling points).
