### ISSUE TITLE
Absorption probability plotting

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#338]
There is still something weird going on when plotting absorption probs for specific lineages. There is a difference between plotting a single lineage, and between plotting the same lineage together with another one. For example, let's plot the epsilon lineage on itself:

![image](https://user-images.githubusercontent.com/24494650/91160136-552c4100-e6c9-11ea-905c-daf53ec169b0.png)

Next, let's plot the epsilon lineage **and** the beta lineage. Note that I did **not** recompute absorption probabilities:
![image](https://user-images.githubusercontent.com/24494650/91160248-6ffeb580-e6c9-11ea-8e64-cd25c99ee041.png)

So why are the absorption probs for the epsilon lineage different now?  There seems to be some weird thresholdind going on. There should be not difference in between plotting the lineage on its own, and together with other lineages!

#### Versions:
cellrank==1.0.0-rc.5 scanpy==1.6.0 anndata==0.7.4 numpy==1.19.1 scipy==1.5.2 pandas==1.1.1 scikit-learn==0.23.2 statsmodels==0.12.0rc0 scvelo==0.2.2
> ...

**Comment by michalk8** [comment]
Also for the 1 case, the diff potential is wrong - it's just copied the abs. probs.

**Comment by Marius1311** [comment]
differentiation potential should always be computed over all lineages, so should also be indepentent of how many lineages you select for plotting.

**Comment by michalk8** [comment]
I knot, it's just plotted wrongly.
I've solved this - it was a typo on my part - I set the percentile to `[0, 95]` when we have stationary distribution, but I was looking at a wrong object. To make sure this doesn't happen in the future, I made the logging message into warning so that user know (was previously debug).

**Comment by Marius1311** [comment]
Ah great, thanks.
