### ISSUE TITLE
More options when plotting gene expression trends

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#343]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

I'm plotting gene expression trends of two genes like so:
```pytb
model = cr.ul.models.GAM(adata, n_splines=10, spline_kwargs={'lam': 3})  
cr.pl.gene_trends(adata, model=model, data_key='Ms',
                  genes=['Hhex', 'Ghrl'], ncols=1,
                  time_key='latent_time', same_plot=True, hide_cells=True,
                  weight_threshold=(0.01, 0.1), figsize=(8, 4))
```
which gives
![image](https://user-images.githubusercontent.com/24494650/91191586-43609300-e6f5-11ea-97a7-7be34f3defef.png)

I would like two extra options:
- `sharex`: if `True`, plots share the time axis and only the lower plot shows the xticklabels and the xlabel
- `show_legend` if `False`, the lineage legend (Alpha, Beta, Epsilon, Delta) is not shown. (I need this for figures). 
- `show_gene_name` or `title`, basically, an option to turn off having the gene names above each plot. In my case, I would like to have the gene name to the left of each plot where it currently says "expression", but this is not the general rule, so I just need control over this.

**Comment by michalk8** [comment]
Closed via https://github.com/theislab/cellrank/pull/345.

**Comment by Marius1311** [comment]
awesome, thanks. Will check this out.
