### ISSUE TITLE
Extra tutorial for directed PAGA

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#344]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

In practice, many people may want to compute a directed PAGA, given PAGAs huge success as a general tool for trajectory inference (best performer in TI benchmarks). To highlight this feature in cellrank, it may be good to have an extra tutorial which is just called "directed PAGA". This will bring more attention to this really cool feature.

**Comment by Marius1311** [comment]
This is what I get for the directed PAGA: 
![image](https://user-images.githubusercontent.com/24494650/91334772-b6d6d300-e7cf-11ea-905f-702caab35883.png)

**Comment by Marius1311** [comment]
I get this by first computing the PAGA using scvelo:
```
scv.tl.paga(adata, groups='clusters', root_key='root_states_probs', end_key='final_states_probs', 
            use_time_prior='velocity_pseudotime')
```
 and then
```
figure_kwargs = {'cluster_key': 'clusters', 'mode':'paga_pie', 'basis':'umap',
                'legend_kwargs':{'loc':'top right out'}, 'legend_loc':'top left out', 'node_size_scale':5, 
                'edge_width_scale':1, 'max_edge_width':4, 'title': f'directed PAGA fate map'}
if save_figure: figure_kwargs['save'] = f'paga_pie.png'
cr.pl.cluster_fates(adata, **figure_kwargs)
```

**Comment by Marius1311** [comment]
To compute latent time/velocity pseudotime, call
```
scv.tl.recover_latent_time(adata, root_key='root_states_probs', end_key='final_states_probs')
```

**Comment by michalk8** [comment]
Closed via https://github.com/theislab/cellrank_notebooks/pull/24
