### ISSUE TITLE
cr.pl.heatmap does not tell me which genes did not converge

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#354]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

I use the following code to plot a heatmap of gene expression trends:
```
model = cr.ul.models.GAM(adata_raw, n_splines=10)
cr.pl.heatmap(adata_raw, model, genes=delta_corr.head(50).index, lineages=['Delta'], cluster_key='clusters', 
              show_absorption_probabilities=False, figsize=(12, 15), show_all_genes=True) 
```

2 genes did not converge, I get 
```
did not converge
did not converge
```

Would be great to know which genes these were.

**Comment by michalk8** [comment]
Can't, there no such information in pygam, only this print statement:
https://github.com/dswah/pyGAM/blob/2323eb7d1cf88bf27d916e965ffa82bb04ae8bc1/pygam/pygam.py#L774

**Comment by michalk8** [comment]
Or a different answer: I can (by capturing the stdout and checking if this message was passed), but it will get messy. Is this really needed?

**Comment by Marius1311** [comment]
you're right, let's not waste time on this if in the future, we may change the underlying model anyhow.
