### ISSUE TITLE
API cleanup

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#359]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

I propose the following:
- [ ] remove `tl.partition` -  will be still used internaly
- [ ] remove `pl.similary_plot`  - remove completely with all underlying functions
- [ ] remove `pl.composition` - remove completely
- [ ] introduce `cellrank.pl.{initial, terminal}` states (or cellrank.pl.final_states) to match the low-level pipeline

Internally, there's some dead code (see gene importance or if we remove similarity plot, the counts/Cramer's V) that should also be removed.

@Marius1311 any thoughts on this? This is precursor to #351 so that we can finish that asap.

**Comment by Marius1311** [comment]
> * [ ]  Additional function parameters, change functionality or change defaults?
> * [ ]  New estimator in `cr.tl.estimators`?
> * [ ]  New kernel in `cr.tl.kernels`?
> * [ ]  New gene trend model in `cr.ul.models`?
> * [ ]  New plotting function in `cr.pl`?
> * [x]  Other?
> 
> I propose the following:
> 
> * [ ]  remove `tl.partition` -  will be still used internaly

agreed. It's very important internally, but we don't need to expose it to the end user

> * [ ]  remove `pl.similary_plot`  - remove completely with all underlying functions

agreed. 

> * [ ]  remove `pl.composition` - remove completely

disagreed. Let's keep it internally please. 

> * [ ]  introduce `cellrank.pl.{initial, terminal}` states (or cellrank.pl.final_states) to match the low-level pipeline
> 

agreed. 

> Internally, there's some dead code (see gene importance or if we remove similarity plot, the counts/Cramer's V) that should also be removed.
> 

agreed. 

> @Marius1311 any thoughts on this? This is precursor to #351 so that we can finish that asap.
