### ISSUE TITLE
x label in gene trends

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#36]
At the moment, the x-axis seems to always be labelled with `pseudotime`, see line 15 & 16 in our basic tutorial, even though `latent_time` is specified. Can we change this, to make it more obvious what we really show on the x-axis?

**Comment by Marius1311** [comment]
Thanks! Will have a look.

**Comment by Marius1311** [comment]
I don't get what you changed, the x-axis still says "Pseudotime", even though my time key is `latent_time`, see below:

![image](https://user-images.githubusercontent.com/24494650/77531737-b38f9200-6e93-11ea-9f06-4d903b90fc74.png)

If the x-axis shows latent time, we should label it accordingly.

**Comment by michalk8** [comment]
You need to manually set it using `xlabel` in `plot_kwargs`. I can make it so that it's automatic.

**Comment by Marius1311** [comment]
Yes, please make it to automatically take the `time_key` - one should still be able to set it manually though, in addition.
