### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by YubinXie** [theislab/cellrank#361]
cant install cellrank.

```
pip install cellrank
```

```
Successfully built docrep loompy numpy-groupies pyrsistent pandocfilters
Installing collected packages: vendorize, llvmlite, numba, click, numpy-groupies, loompy, scvelo, python-utils, progressbar2, future, pygam, docrep, future-fstrings, attrs, pyrsistent, jsonschema, nbformat, pycparser, cffi, argon2-cffi, prometheus-client, Send2Trash, MarkupSafe, jinja2, terminado, webencodings, bleach, pandocfilters, testpath, entrypoints, mistune, defusedxml, nbconvert, notebook, widgetsnbextension, ipywidgets, tzlocal, cellrank
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.33.0+1.g022ab0f
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by YubinXie** [comment]
I was able to install it with 

```
 pip install llvmlite --ignore-installed
```

but in general, i think cellrank is kind of aggressive on package installing and all kinds of package versions...

**Comment by YubinXie** [comment]
Update: to get llvmlite to work, numba needs to be updated, which leads to scanpy numba error.

**Comment by michalk8** [comment]
Hi @YubinXie ,
thanks for posting this. I think I've bumped the version of numba to latest mostly because of this issue: https://github.com/theislab/cellrank/issues/326
I didn't expect there to be issues with scanpy, since it requires `>=0.41.0` https://github.com/theislab/scanpy/blob/master/requirements.txt#L20
I will retest this again and see if I can drop the numba version.

**Comment by YubinXie** [comment]
The numba error was gone after I restart the notebook. It might be some path issue. All is good now.

**Comment by Marius1311** [comment]
great. @michalk8 , can this be closed?
