### ISSUE TITLE
Directed PAGA without dynamic model

### ISSUE THREAD

**Issue by timlai4** [theislab/cellrank#371]
Dear cellrank team,

Thank you for all your help with my various questions so far. I hope this question will be simpler than the previous ones. I am back to the basic workflow, trying to the [directed PAGA part](https://cellrank.readthedocs.io/en/latest/pancreas_basic.html#Directed-PAGA). I believe when I last ran this, I was on v1.0.0rc0. My datasets' velocities are computed using the standard workflow, instead of the dynamic model, and I wish to continue using this. I don't remember what the notebook looked like back then, but the script I had run to generate the corresponding picture was

```{python}
scv.tl.paga(adata, groups = clusters)
# Compute the initial and terminal states in cellrank
cr.pl.cluster_fates(adata, cluster_key=clusters, mode='paga_pie', node_size_scale=4,
                       title=key, edge_width_scale=1, max_edge_width=2, threshold=0.1, basis='umap',
                       show = False, dpi = 300, figsize = (10, 10), save = 'paga.png')
```
I'm attempting to follow the new workflow, which seems to have some new parameters and new commands altogether. 
```{python}
scv.tl.recover_latent_time(adata, root_key='initial_states_probs', end_key='terminal_states_probs')
```
However, it seems this cannot be run without first computing the dynamical velocities. The next command is
```{python}
scv.tl.paga(adata, groups='clusters', root_key='initial_states_probs', end_key='terminal_states_probs',
            use_time_prior='velocity_pseudotime')
```
I verified that my adata object has the root_key and end_key parameters specified, after computing the initial and final states, but I did not see a velocity_pseudotime. I guessed that the recover_latent_time adds this, so I attempted to run instead
```{python}
scv.tl.paga(adata, groups='clusters', root_key='initial_states_probs', end_key='terminal_states_probs')
```
but I'm still missing parameters `KeyError: "Lineage key "to_terminal_states" not found in adata.obsm."`. 

My question is how I can get some form of the Directed PAGA plots without having to run the dynamical model beforehand, as before in an earlier version? 

Ultimately, I wish to wrap this into the advanced workflow. I tried to get the basic workflow working on the new version as a stepping stone for that. I verified that computing forward and backward directions in the advanced workflow and calling the `g.set_final_states_from_metastable_states()` will appropriately modify the `adata` object so that it should resemble the basic workflow. If it's not as straightforward as this, I would appreciate a pointer there too.

Thank you.

**Comment by Marius1311** [comment]
> Dear cellrank team,
> 
> Thank you for all your help with my various questions so far. I hope this question will be simpler than the previous ones. I am back to the basic workflow, trying to the [directed PAGA part](https://cellrank.readthedocs.io/en/latest/pancreas_basic.html#Directed-PAGA). I believe when I last ran this, I was on v1.0.0rc0. My datasets' velocities are computed using the standard workflow, instead of the dynamic model, and I wish to continue using this. I don't remember what the notebook looked like back then, but the script I had run to generate the corresponding picture was
> 
> ```
> scv.tl.paga(adata, groups = clusters)
> # Compute the initial and terminal states in cellrank
> cr.pl.cluster_fates(adata, cluster_key=clusters, mode='paga_pie', node_size_scale=4,
>                        title=key, edge_width_scale=1, max_edge_width=2, threshold=0.1, basis='umap',
>                        show = False, dpi = 300, figsize = (10, 10), save = 'paga.png')
> ```
> 
> I'm attempting to follow the new workflow, which seems to have some new parameters and new commands altogether.
> 
> ```
> scv.tl.recover_latent_time(adata, root_key='initial_states_probs', end_key='terminal_states_probs')
> ```
> 
> However, it seems this cannot be run without first computing the dynamical velocities. The next command is
> 
Right, latent time needs you to infer the parameters of the dynamical model first.
> ```
> scv.tl.paga(adata, groups='clusters', root_key='initial_states_probs', end_key='terminal_states_probs',
>             use_time_prior='velocity_pseudotime')
> ```

This command does not actually need latent time, you can input any pseudotemporal measure, be it dpt_pseudotime, velocity pseudotime or any other. Velocity pseudotime is an adaptation of dpt and can be computed using scvelo. 

> 
> I verified that my adata object has the root_key and end_key parameters specified, after computing the initial and final states, but I did not see a velocity_pseudotime. I guessed that the recover_latent_time adds this, so I attempted to run instead
> 
> ```
> scv.tl.paga(adata, groups='clusters', root_key='initial_states_probs', end_key='terminal_states_probs')
> ```
> 
> but I'm still missing parameters `KeyError: "Lineage key "to_terminal_states" not found in adata.obsm."`.
> 

Not sure why this happens. @michalk8 , why would scvelo complain here? Can you check this? It should only need `.obs` annotations and nothing from `.obsm`. 

> My question is how I can get some form of the Directed PAGA plots without having to run the dynamical model beforehand, as before in an earlier version?

Should be possible by specifying another pseudotemporal measure, try computing dpt using `sc.tl.dpt` and pass the correct key for `use_time_prior`. As for the `KeyError`, we will look into it. 

> 
> Ultimately, I wish to wrap this into the advanced workflow. I tried to get the basic workflow working on the new version as a stepping stone for that. I verified that computing forward and backward directions in the advanced workflow and calling the `g.set_final_states_from_metastable_states()` will appropriately modify the `adata` object so that it should resemble the basic workflow. If it's not as straightforward as this, I would appreciate a pointer there too.
> 
Should be no problem. Calling `g.set_final_states_from_metastable_states()`  writes to AnnData, which can be read by `scv.tl.paga`

> Thank you.

**Comment by timlai4** [comment]
My apologies, I realized that the KeyError happens on the cellrank cluster fates step.
Following your suggestion, I am now running
```{python}
scv.tl.velocity_pseudotime(adata)
scv.tl.paga(samples[key], groups=clusters, root_key='initial_states_probs', end_key='terminal_states_probs',
            use_time_prior='velocity_pseudotime')    
```
Then I run
```{python}
cr.pl.cluster_fates(adata, cluster_key=clusters, mode='paga_pie', node_size_scale=4,
                       title=key, edge_width_scale=1, max_edge_width=2, threshold=0.1, basis='umap',
                       show = False, dpi = 300, figsize = (10, 10), save = 'paga.png')
```
which returns the KeyError.

**Comment by michalk8** [comment]
If you've computed the absorption probabilities using an older version (can't remember in which version we've changed it, but it should be the last time we do such a change), they should be in `adata.obsm['to_final_states']`, try running:
```python
adata.obsm['to_terminal_states'] = adata.obsm['to_final_states']
adata.uns['to_terminal_states_colors'] = adata.uns['to_final_states_colors']  # or adata.obsm["to_terminal_states"].colors if there's nothing in .uns
```

**Comment by timlai4** [comment]
Thanks! I was able to get the cluster_fates step to run. However, I get the warning `WARNING: Invalid color key. Using grey instead.` and my plots indeed come out grey instead. I'm a bit confused since in my command
```{python}
cr.pl.cluster_fates(adata, cluster_key=clusters, mode='paga_pie', node_size_scale=4,
                       title=key, edge_width_scale=1, max_edge_width=2, threshold=0.1, basis='umap',
                       show = False, dpi = 300, figsize = (10, 10), save = 'paga.png')
```
I'm not specifying a color key.

**Comment by michalk8** [comment]
Hmm, this message is from scvelo, see https://github.com/theislab/scvelo/blob/a7de78ae974b251c366f208aab2e685b23bc101e/scvelo/plotting/scatter.py#L528
The color would be related to the `cluster_key=clusters` or the colors of the lineages, but I've tried increasing/decreasing the number of colors in `adata.uns['clusters_colors']` and can't reproduce this or even when doing the same with `adata.uns['to_terminal_states_colors']`.

**Comment by timlai4** [comment]
Thanks for the tip! Since it's a separate issue, I'll go ahead and close this one now. If I can't figure it out after more extensive troubleshooting, I can open a separate issue with more details. Thanks again!
