### ISSUE TITLE
Clean up tests

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#376]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

TODOs:
- [ ] refactor some old code, especially for plotting
- [x] write tests for utils/for files with low coverage
- [ ] start using tox

**Comment by Marius1311** [comment]
Hi @michalk8 , what's the state of the art here?

**Comment by michalk8** [comment]
Putting this on hold right now. I though also about speedup here, maybe there's something, but compared to not testing SLEPc/PETSc (on most of the combinations), it will be miniscule. Closing.
