### ISSUE TITLE
Negative binomial

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#377]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [x] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

TODOs:
- [ ] implement weighted models in batchglm (numpy backend only)
- [ ] interface batchglm using our models
- [ ] either update or remove (in favor of batchglm) GAMR
- [ ] implement tradeSeq-like model fitting (categorical term for lineage assignment, diff pseudotimes, knot placement, etc.)

**Comment by michalk8** [comment]
Hi @Marius1311 , the first version of NB is somewhat working, see attached picture:

Currently, it's not tied to the high-level function, you have to do the following:
```python3
import cellrank as cr
from cellrank.ul.models._utils import _get_offset

offset = _get_offset(adata, use_raw=True)

m = cr.ul.models.GAMR(adata, distribution="nb", n_splines=6)
m.prepare("Ghrl", "Epsilon", offset, time_key='dpt_pseudotime', use_raw=True)
m.fit()
m.predict()
m.confidence_interval()
m.plot()
```
![plot](https://user-images.githubusercontent.com/46717574/93940257-72861680-fd2c-11ea-8060-ec879153ec0f.png)

I have some question you might be able to answer:
- In https://github.com/statOmics/tradeSeq/blob/a3511a037237734dff5774642ed1a0f94da9a4b7/R/predictSmooth.R#L77, they using `exp` to get the smooted values - is it just because it link function by default is `log`? If so, why isn't the inverse link function always applied by default?
- in tradeSeq, they support multiple pseudotimes, 1 per lineage using slingshot (I 've already made available reading PT from `obsm`) - shall we also include it? (currently, it's bugged in [when using the same pseudotime for all lineages] a way that the curve is way too flat... I think it's because I haven't implemented yet their custom predict function, where they are very lineage specific and fit the splines using the extraced bases https://github.com/statOmics/tradeSeq/blob/4492aa19a1da67a4933e527e6045eaa0ce0e9306/R/utils.R#L3)
- what would be the best way to specify formula to fit the count data? The above example uses
`y ~ -1 + U + s(x0, bs='cr', id=1, k=3) + offset(offset)` where `x0` is the PT, `U` is a user-provided fixed effects (currently, all 1s) and `offset` is `log(library_size)`, exactly as in tradeSeq, which uses https://github.com/jianjinxu/edgeR/blob/master/R/calcNormFactors.R (I've transcribed it to python - `cellrank.ul.models._utils._calculate_norm_factors`, still need to debug it + vectorize it) 
- different/better ways of specifying the offset?
- for testing points (uniformly samples from the start to the end of the lineage), the offset is set to constant - the mean offset of training points - is this how people usually do it?

I've also tried directly interfacing `tradeSeq::fitGAM`, problem is, they really expect multiple pseudotimes + some of their code is really inefficient.
Most of the work is done, I have yet to implement https://github.com/statOmics/tradeSeq/blob/4492aa19a1da67a4933e527e6045eaa0ce0e9306/R/utils.R#L3 (if multiple PTs are desired - for future reference, I think it's best to be general as possible) + interface, clean and test everything.
As far as BatchGLM goes, I haven't tested it yet (neither correctness, nor performance), but will do so shortly. I envision that we will have GAM (either 2 backends - pygam + mgcv, both supporting NB), GLM (only numpy backend, supporing not only NB [still needs work]) and the sklearn-models

TODOs:
- [ ] speedup offset function (could also use numba for also sparse data [sparse package has the impl. I think])
- [ ] debug offset function
- [ ] debug knot setting
- [ ] support multiple PTs (optional)
- [ ] intead of default conf int, search or try https://stats.stackexchange.com/questions/33327/confidence-interval-for-gam-model
- [ ] clean the API
- [ ] write tests

**Comment by Marius1311** [comment]
Hi Mike, let's go over this in our call today.
