### ISSUE TITLE
Unable to detect jax installation 

### ISSUE THREAD

**Issue by jmchan88** [theislab/cellrank#379]
Hey CellRank team!

I'm trying to run the "stochastic" mode for uncertainty propagation, which requires jax installed. I've already installed version 0.1.77 but when I run the below command: 

vk.compute_transition_matrix(mode = 'stochastic')

I still get the warning:

WARNING: Unable to detect `jax` installation. Consider installing it as `pip install jax jaxlib`.
Defaulting to mode `'monte_carlo'`

Any ideas on how to troubleshoot this would be great! Thanks so much!

Joe

**Comment by michalk8** [comment]
Hi @jmchan88 ,
we're currently checking for the jax installtion here https://github.com/theislab/cellrank/blob/master/cellrank/tl/kernels/_utils.py#L13 and the warning you're seeing comes from https://github.com/theislab/cellrank/blob/master/cellrank/tl/kernels/_velocity_kernel.py#L204.
Could you try importing it as:
```python
import jax.numpy as jnp
from jax import jit, hessian
```
I've tested this myself (``jax==0.1.77 jaxlib==0.1.55``
Also please note that there's 1 issue with this mode: it get's very slow to this end - we're working on a workaround that will be faster that doesn't require jax.

**Comment by Marius1311** [comment]
Jax speed is fine, no need to worry about this. It scales at worst linearly in cell number, so easily scales to very large datasets.

**Comment by jmchan88** [comment]
Oh perfect! Those lines seemed to work! Thank you so much guys! I'll close this issue now :D

**Comment by Marius1311** [comment]
Thanks for handling this @michalk8 !
