### ISSUE TITLE
Enable caching transition matrix computation using scachepy

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#381]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Can we add `cr.tl.transition_matrix` to scachepy? For the stochastic computation modes, this would be very convenient.

**Comment by michalk8** [comment]
Implemented via https://github.com/theislab/scachepy/commit/66244487b2284f11b94437de4a3a5a8efbfd577f
However, it might not work (like 99% sure) by default for backward case (scachepy is very flawed and I still haven't gotten around that refactoring, maybe over the weekend), so please in the backward case, specify the key explicitly.

**Comment by Marius1311** [comment]
Thanks Mike. Calling 
```kernel_fwd = c.tl.transition_matrix(adata, weight_connectivities=0.2, mode="stochastic", n_jobs=8, 
                                    softmax_scale=None)```

where `c` is my chache object does work and upon calling it the second time, I get
```
Loading data from: `transition_matrix.pickle`.
`adata.obsp` already contains key: `'T_fwd'`.
`adata.uns` already contains key: `'T_fwd_params'`.
```

however, this does not return the actual kernel object, so I cant' initialise an `estimator` based on `kernel_fwd`. Is this an inherent limitation of the current scachepy implementation, or easily fixable?

**Comment by Marius1311** [comment]
Current workaround is this:
```python
from cellrank.tl.kernels import PrecomputedKernel

c.tl.transition_matrix(adata, weight_connectivities=0.2, mode="stochastic", n_jobs=8, 
                                    softmax_scale=None)

kernel_fwd = PrecomputedKernel(adata.obsp['T_fwd'], adata)
```

**Comment by Marius1311** [comment]
This works, except for the pearson correlations which are not written to AnnData, but that's really a minor problem.

**Comment by michalk8** [comment]
Yes, that's the limitation (I don't save any custom objects created) and there's no other workaround for it other than the one you did (we could in principle save the whole kernel in uns, but then subsetting the cells won't work, etc.).
As I've said, it needs a lot of refactoring - I will keep this in mind.

**Comment by michalk8** [comment]
@Marius1311 
Estimators can also be initialize as `g = cr.tl.estimators.GPCCA(adata, obsp_key="T_fwd")`.

**Comment by Marius1311** [comment]
Oh awesome, thanks!
