### ISSUE TITLE
Does `cr.pl.cluster_lineage` take into account a `data_key`?

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#386]
Is that key passed on?

**Comment by michalk8** [comment]
Yes, based on these lines (and some more):
- https://github.com/theislab/cellrank/blob/master/cellrank/pl/_cluster_lineages.py#L165
- https://github.com/theislab/cellrank/blob/master/cellrank/pl/_cluster_lineages.py#L216
- https://github.com/theislab/cellrank/blob/master/cellrank/pl/_cluster_lineages.py#L40
- https://github.com/theislab/cellrank/blob/master/cellrank/pl/_cluster_lineages.py#L79

**Comment by Marius1311** [comment]
thanks.
