### ISSUE TITLE
Unable to write GPCCA estimator to file

### ISSUE THREAD

**Issue by jmchan88** [theislab/cellrank#389]
Hey guys!

I'm interested in saving my GPCCA kernel to a file with the code below:
```
from cellrank.tl.estimators import GPCCA
g = GPCCA(combined_kernel)
g.compute_schur(n_components=20)
g.compute_metastable_states(n_states=7, cluster_key='cell_type')
g.set_final_states_from_metastable_states()
g.compute_absorption_probabilities()
g.write(out_dir + 'cellrank.dynamical.dc_corr.%s.GPCCA' % (thr))
```
but I get the following error:

```
WARNING: Unable to compute metastable states with `n_states=7` because it will split the conjugate eigenvalues. Increasing `n_states` to `8`
Traceback (most recent call last):
  File "/home/chanj3/scripts/HTA.RU263.RNA_velocity/run_cellrank.select_genes.dc_corr.py", line 98, in <module>
    g.write(out_dir + 'cellrank.dynamical.dc_corr.%s.GPCCA' % (thr))
  File "/home/chanj3/anaconda3/envs/py3.7/lib/python3.7/site-packages/cellrank/tl/estimators/_base_estimator.py", line 928, in write
    pickle.dump(self, fout)
  File "/home/chanj3/anaconda3/envs/py3.7/lib/python3.7/enum.py", line 44, in _break_on_call_reduce
    raise TypeError('%r cannot be pickled' % self)
TypeError: stochastic cannot be pickled
```
Any help is as always super appreciated!

Joe

**Comment by michalk8** [comment]
Hi @jmchan88 ,
this is an issue with Python3.6 - it can't pickle enums. I am in the process of fixing this.

**Comment by michalk8** [comment]
Please let me knot if #390 fixed this for you.

**Comment by aterceros** [comment]
Hello,

If I save the GPCCA kernel using g.write('g.GPCCA' ), how can I open it afterwards?
Thanks

**Comment by Marius1311** [comment]
Hi @aterceros, the documentation for the `write` method tell you: `Serialize self to a file using [pickle](https://docs.python.org/3/library/pickle.html#module-pickle)` (see https://cellrank.readthedocs.io/en/latest/api/_autosummary/estimators/cellrank.estimators.GPCCA.html#cellrank.estimators.GPCCA.write). Asking chatGPT how to read in pickled objects tell me: 

```
import pickle

with open('your_file.pkl', 'rb') as file:
    loaded_object = pickle.load(file)
```

In this case, the `loaded_object` should be your GPCCA estimator object again.

**Comment by aterceros** [comment]
Thank you so much!
