### ISSUE TITLE
Cluster fates cleaner subsetting

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#39]
For future reference: once new version of `anndata` releases, we can use proper subsetting [here](https://github.com/theislab/cellrank/blob/master/cellrank/plotting/_cluster_fates.py#L329) of the `Lineage` class thanks to  https://github.com/theislab/anndata/pull/335.

**Comment by Marius1311** [comment]
has there already been another anndata release?

**Comment by michalk8** [comment]
I've bumped the version of `anndata` to `>=0.7.2`, where te numpy-view is already in place (not to mention that `.obsp` and other things are available from `0.7.0`, which also `scvelo` requires).

**Comment by Marius1311** [comment]
that's really nice, thanks. Did you test whether this causes any problems already?
