### ISSUE TITLE
Can we cache the output of `cr.pl.cluster_lineage`?

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#396]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Takes quite long when you compute this for all genes.

**Comment by michalk8** [comment]
It should being "cached" - if you run it twice for the same lineage, no recomputation is being done (see the ``recompute`` paramter).
Or did you mean scachepy?

**Comment by michalk8** [comment]
I hope the above answers your question (I wouldn't want to add this to scachepy if that's what you've meant).

**Comment by Marius1311** [comment]
I actually meant scachepy! Otherwise, I always have to re-run this when I restart my kernel, right?
