### ISSUE TITLE
Error installing pip install cellrank

### ISSUE THREAD

**Issue by roofya** [theislab/cellrank#398]
Hi
I have installed successfully all dependencies to install cellrank however when I'm installing
pip install cellrank
I got this error:
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
I really appreciate it if you could help me to fix this error. Thank you so much in advance for your help.

Best Regards,

**Comment by michalk8** [comment]
Hi @roofya ,
this seems to be the same problem as here: https://github.com/theislab/cellrank/issues/361
The solution there was to upgrade the numba version.

**Comment by roofya** [comment]
@michalk8 Thank you so much I have installed it by 
conda install -c conda-forge -c bioconda cellrank-krylov
Its successfully installed.

**Comment by Marius1311** [comment]
Thanks @michalk8! I'm closing this as I think it's solved.
