### ISSUE TITLE
Markov Chain Interface

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#4]
A lot of functions in `MarkovChain` are beginning with `compute_` or `plot_`. Also, we have a lot of attributes - maybe they should be read-only properties, since user shouldn't set them (and perhaps we can hide a few). Also, I'd give the functions more descriptive names (e.g. `eigen` instead of just `eig`)
For the former, I propose splitting the functions into modules, e.g.
```python
mc_fwd = cr.tl.MarkovChain(...)
mc_fwd.compute.eigen()
...
mc_fwd.plot.eigen_embedding()
```
We could also have `properties` module, e.g.
```python
mc_fwd.props.G2M_score
```
@Marius1311 what do you think?

**Comment by michalk8** [comment]
@Marius1311 I'd like your feedback on this. My attitute towards this has changes, I think the cost of maintenance will be too high and the benefits rather miniscule.
If you agree, I'd then close this.

**Comment by Marius1311** [comment]
Could you please explain why the cost of maintenance would be higher if we introduced these changes?

**Comment by michalk8** [comment]
Issue is that the only way I know of is to create 3 classes (e.g. `Tools`, `Plotting` and `Props`,
that have a backreference to MC, not to mention `Plotting` and `Tools` need reference to `Props`, etc.
The debugging will become harder, as well as writing new functions (keeping things in the correct place).

**Comment by Marius1311** [comment]
In that, case, let's leave it as it is at the moment.
