### ISSUE TITLE
'connectivities' stored in adata.obsp instead of adata.uns

### ISSUE THREAD

**Issue by VolkerBergen** [theislab/cellrank#40]
In the latest version of anndata (and with the upcoming release), the neighbor graph will be stored in `adata.obsp['distances']` and `adata.obsp['connectivities']`, which we should already be accounting for now. Could, for instance, be done with a helper function that allows for both conventions
```
def get_neighs(adata, mode='distances'):
    return adata.obsp[mode] if hasattr(adata, 'obsp') and mode in adata.obsp.keys() else adata.uns['neighbors'][mode]
```

**Comment by michalk8** [comment]
Will the `'params'` still be stored in `uns`?

**Comment by VolkerBergen** [comment]
Yes, in `uns['neighbors']`.
