### ISSUE TITLE
Automatic cluster names for tl.cluster_lineage

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#407]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Based on gene set enrichment.

**Comment by Marius1311** [comment]
This is a bit tricky but you can try to get meaningful GO terms by restricting to biological pathway and KEGG and restricting the term size to be smaller 200 or so

**Comment by Marius1311** [comment]
I don't think we really need this. Correct me if you feel differently and feel free to reopen.
