### ISSUE TITLE
Easy interface for `cr.pl.graph`

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#41]
I often want to quickly visualise a small directed graph and I think your function would be nice for this. It would be great if we could add a way to just pass it a numpy array or sparse matrix, instead of having to save the matrix in an anndata object first. Do you agree, or do you think I should just use networkx straight away?

**Comment by michalk8** [comment]
Done via #43

**Comment by Marius1311** [comment]
Thanks, will check this out as well.

**Comment by Marius1311** [comment]
```python
P_1 = np.array([[0.8, 0.1, 0.1], [0.5, 0.0, 0.5], [0.0, 0.1, 0.9]])
cr.pl.graph(data=P_1)
```
gives
```python
--------------------
TypeErrorTraceback (most recent call last)
<ipython-input-129-f4145b11bf6c> in <module>
----> 1 cr.pl.graph(data=P_1)

TypeError: graph() missing 1 required positional argument: 'graph_key'
```

**Comment by michalk8** [comment]
Should be fixed on master now.
