### ISSUE TITLE
Allow renaming terminal states

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#417]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

It can useful when we want to either combine long names or many macrostates into 1 state, or even if selecting a state with the suffix `_<some number>`.
Proposed change:
```python3
g.set_terminal_states_from_macrostates(names=['Alpha', 'Beta', 'Epsilon', 'Delta'])  # just as before
g.set_terminal_states_from_macrostates(names={'foo': 'foo_1, foo_2', 'bar': 'bar', 'baz': 'quux']})
# keys are the new names to be assigned
```
@Marius1311 any thoughts on this?

**Comment by Marius1311** [comment]
as long as we keep both modes (passing a list vs. passing a dict), I think this is a good idea.

**Comment by Marius1311** [comment]
thanks, good initiative.
