### ISSUE TITLE
`_create_categorical_colors` returns duplicate colors

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#419]
Calling `cellrank.tl._colors._create_categorical_colors` returns duplicate colors when more than 10 colors are requested. That's becasue we use both `cm.tab10` as well as `cm.tab20` which partly overlap.

**Comment by Marius1311** [comment]
can we use scanpy's default color palette?

**Comment by michalk8** [comment]
Yes, we can start with vega_20 (modified version of tab20). Do you want by default colorblind-friendly version?

**Comment by Marius1311** [comment]
yes, sure, sounds good. We just need to make sure that the colormaps we combine don't have repeated colors, e.g. if we do 
```[cm.tab10, cm.tab20, cm.Paired, cm.Accent, cm.Set1, cm.Set2, cm.Set3]```

than this is useless if tab 10 and tab20 have repeated colors. It makes more sense to desing say three different colormaps, one with 10 colors, one with 20 and one with 30. And for all of these, we make sure that colors are not repeated. I think Volker has designed some colormaps we can use here. This would be the nicest solution.

**Comment by Marius1311** [comment]
thanks.
