### ISSUE TITLE
preset terminal and initiate states

### ISSUE THREAD

**Issue by wangmhan** [theislab/cellrank#425]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] in cr.tl.terminal_states

...
Hi,

I tried the cellRank. But the terminal states suggested by the algorithm is not what we expected, while the initiate states looks fine.
The trajectory we expected is Progenitor-Intermediate1-Intermediate2-Differentiated.
Cellrank identified initiate states: Progenitor, but terminal states: Intermediate2.

 Is it possible to preset terminal state, based on cell type?
Thanks a lot!

**Comment by michalk8** [comment]
Hi @wangmhan ,
yes, you can manually set the terminal states when using the estimators as `your_estimator.set_terminal_states(...)`.
You can either supply it with categorical `pandas.Series`, where `NaN` mark non-terminal cells or a dictionary as `{'your_terminal_cluster_1': [<list of observation names in adata.obs_names or cell indices>], 'your_terminal_cluster_2': [...], ...}`.

As for the initial, there's a private function available called `_set_initial_states` with the same functionality. Note that this function only writes the initial states+probabilities in `adata.obs` (`set_terminal_states` also updates the estimator).

Let me know if this has solved the problem for you.

**Comment by wangmhan** [comment]
Hi,

Thanks for the quick reply.

I tried to set terminal states with command:
cr.tl.estimators.GPCCA.set_terminal_states_from_macrostates(names='differentiated')

But then comes to error: TypeError: set_terminal_states_from_macrostates()
I tried self=adata, or self=cr.tl.estimators. None of them works.

**Comment by michalk8** [comment]
That's because `set_terminal_states_from_macrostates` is not a class method - you need to create an instance of the estimator.
Here's an example workflow:
```python
k = cr.tl.transition_matrix(adata, ...)  # or the way you're computing the transition matrix
g = cr.tl.estimators.GPCCA(k)
g.compute_schur(<number_of_states + 1>)
g.compute_macrostates(<number_of_states>, cluster_key=<key in `adata.obs` to try
                      and associate the macrostate names with the cluster labels - this is optional>)
g.set_terminal_states_from_macrostates('differentiated')
```
I recommend checking out second tutorial, especially the estimators part: https://cellrank.readthedocs.io/en/latest/pancreas_advanced.html#Estimators

**Comment by wangmhan** [comment]
Thanks, it works fine.

Will check out the second tutorial for sure.

**Comment by Marius1311** [comment]
Thanks for handling this @michalk8! Can we close this?

**Comment by Marius1311** [comment]
I'm closing this as I assume the issue has been resolved. Feel free to reopen and any time.

**Comment by Fougere87** [comment]
Hi, 

Thank you for this interesting package  ! 
I'm looking for the _set_initial_states function you are talking about above but I can't find it... was it removed. How can we compute/set initial states then  ? I can create a backward kernel and redo everything, but then it replaces terminal states and does not creates initial states... so no lineages can be computed...
