### ISSUE TITLE
update CellRank's page on pypi

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#434]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

It's outdated and should be updated to reflect what we have currently in our docs.

**Comment by Marius1311** [comment]
Thinks like root & final, metastable states, etc.

**Comment by michalk8** [comment]
This will happen when we make a new release.

**Comment by michalk8** [comment]
Closed via https://github.com/theislab/cellrank/commit/f2f41987f1e761c77d3e560e8fafb8a6110c623e

**Comment by Marius1311** [comment]
Thanks.
