### ISSUE TITLE
Make lung data public in `cr.datasets`

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#441]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

It's fine to do this now.

**Comment by michalk8** [comment]
Closed via #442

**Comment by Marius1311** [comment]
thanks @michalk8 !
