### ISSUE TITLE
y axis in cluster_fates plot not showing absorption probabilities

### ISSUE THREAD

**Issue by giovp** [theislab/cellrank#443]
Running the pancreas advanced tutorial, last plot `cr.pl.cluster_fates()` does not return correct y axis

```python
cr.pl.cluster_fates(adata, cluster_key='clusters', mode='violin') # pancreas advanced
```

![image](https://user-images.githubusercontent.com/25887487/96976113-b599fc00-151b-11eb-8c67-848f7e83e07c.png)

#### Versions:

> cellrank==1.0.0-rc.12 scanpy==1.5.1 anndata==0.7.4 numpy==1.19.1 numba==0.51.2 scipy==1.5.2 pandas==1.1.3 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.8.3 scvelo==0.2.2 pygam==0.8.0 matplotlib==3.3.2 seaborn==0.11.0

**Comment by michalk8** [comment]
Hi @giovp ,
I can reproduce it with you scanpy version using. Upgrading to 1.6 however fixes this issue. I will update the requirements to use `scanpy>=1.6`.

```python3
import cellrank as cr
adata = cr.datasets.pancreas_preprocessed()
cr.tl.terminal_states(adata, cluster_key='clusters')
cr.tl.lineages(adata)
cr.pl.cluster_fates(adata, cluster_key='clusters', mode='violin')
```

**Comment by giovp** [comment]
Thanks!
