### ISSUE TITLE
'Latest additions' section in the docs

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#445]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

I think it would make sense to have a scanpy-like "latest addition" section prominently placed in the `index.rst` so that people are informed about new features, like to upcoming p-values. Not many people will check the release notes, so all of the nice new features risk being overlooked otherwise.

**Comment by michalk8** [comment]
Closed via #448

**Comment by Marius1311** [comment]
Looks very nice, thanks.
