### ISSUE TITLE
Morris reprogramming data

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#448]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

New dataset: `cellrank.datasets.reprogramming` from https://github.com/morris-lab/BiddyetalWorkflow
TODOs:
- [x] clean the object
- [ ] post it on the figshare
- [ ] create the function with arguments to subset the 45k/85k
- [ ] nicely explain what are the obs (@Marius1311 )

I wouldn't test for download of this since it will be quite large (compare to the other we have).
Once this is and #445 is done, it's time for 1.1.0 release (hopefully Monday the latest).

**Comment by Marius1311** [comment]
Fantastic, thanks.
