### ISSUE TITLE
Info on cluster_fates barplot

### ISSUE THREAD

**Issue by mbuttner** [theislab/cellrank#458]
Hi there,

I just happen to write up a description for my `cluster_fates` barplot and was wondering what the bar height and whiskers denote. Clearly, would be very happy to find this information in the documentation rather than digging through the code. 
Second, I assume that the whiskers in the barplot of `cluster_fates` show the standard deviation, however, when you compute the standard deviation, you divide by the square root of the number of rows (entries?) in each dataset. That looks strange to me, because I assume that `nanstd` already accounts for the number of cells per group. Can you please comment on this and add a description of your stats somewhere in the documentation? 

https://github.com/theislab/cellrank/blob/6dcb6a7cb0e732211391618926513731cc189ba7/cellrank/pl/_cluster_fates.py#L492

**Comment by Marius1311** [comment]
Hi @mbuttner, thanks for bringing this up. We did this because we wanted the standard error on the mean, https://en.wikipedia.org/wiki/Standard_error

Let me know if that makes sense from your point of view, happy to hear your input.

**Comment by michalk8** [comment]
> Clearly, would be very happy to find this information in the documentation rather than digging through the code.

You're right, I will add this once this is resolved.

**Comment by mbuttner** [comment]
Hmm, I am not a big fan to use the standard error on the mean (SEM) because it tends to zero when the population size increases. If you interpret the fate probability mean in the light of the central limit theorem, then it's sound to use the SEM, but when you interpret the fate probability mean as unknown and to be determined by the samples that contribute to the mean, then it would make sense to have the standard error (without scaling by the number of samples). I guess that your interpretation of the fate probability mean and its deviation is rather in the light of the central limit theorem, therefore, SEM actually makes sense.

**Comment by Marius1311** [comment]
Thanks Maren! We will add some description about this to the docstring of the function.

**Comment by michalk8** [comment]
Closed via https://github.com/theislab/cellrank/commit/fb415068f158581b2d82b3dee8ad0d74b742b64e.
