### ISSUE TITLE
Using pyGPCCA under the hood

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#465]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

What will the process look like of switching to pyGPCCA under the hood? When can we initiate the move?

**Comment by michalk8** [comment]
> What will the process look like of switching to pyGPCCA under the hood? When can we initiate the move?

I can start now, but merge only after pyGPCCA is on PyPI - we also need to discuss write release notes:
- mention circular embedding
- mention pyGPCCA

**Comment by Marius1311** [comment]
Oh, now that you mention it, I just checked our release notes [here](https://cellrank.readthedocs.io/en/latest/release_notes.html) and we don't seem to have any for 1.1 - what happened there?

**Comment by michalk8** [comment]
closed via #472

**Comment by Marius1311** [comment]
Very nice!
