### ISSUE TITLE
Optimisation of CI

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#467]
Hi there @Marius1311 and @michalk8.

I had a brief look at your CI implementation using GitHub Actions and believe it could be slightly optimised: For the job `linting`, you are currently running `pip install -e ".[docs,dev]"` [here](https://github.com/theislab/cellrank/blob/62391589f1f97a62c8ae2c20dd3073836a7d2471/.github/workflows/ci.yml#L45). This will install quite a few libraries not needed for linting (e.g. `cellrank`, `scvelo`, `seaborn`, ...). AFAICT from briefly skimming your `.pre-commit-config.yaml` file installing `black`, `isort`, etc. would suffice.

**Comment by michalk8** [comment]
Hi @WeilerP ,
thanks for pointing this out - indeed a simple `pre-commit install && pre-commit run --all-files` would suffice (maybe witch caching of pre-commits), instead of full package installation. Will update this later today.

**Comment by Marius1311** [comment]
Thanks @WeilerP for going through our CI, let us know if you have any other suggestions!
