### ISSUE TITLE
Missing jax installation and stochastic mode

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#469]
@Marius1311 I remember that an error popped up when trying `mode='stochastic'`, but jax has not been installed and that
this error was rather ominous.
This must've changed  in 1.1.0, when I've changed the detection (i.e. `'stochastic'` mode does not "need" jax, it just needs an attribute called `hessian` ([here](https://github.com/theislab/cellrank/blob/master/cellrank/tl/kernels/_velocity_kernel.py#L217)'s the check).
I did add dummy functions [here](https://github.com/theislab/cellrank/blob/master/cellrank/tl/kernels/_velocity_schemes.py#L73) which should produce a nice error message, but they don't.

#### Versions:
cellrank==1.1.0

**Comment by Marius1311** [comment]
mhm, do you have an idea how to resolve this?

**Comment by Marius1311** [comment]
great! thanks @michalk8
