### ISSUE TITLE
models.GAM renamed?

### ISSUE THREAD

**Issue by tinjac** [theislab/cellrank#471]
Hej!

Using cr v.1.0.0-rc.0 I ran into problems fitting a Generalized Additive Model.

Running `model = cr.ul.models.GAM(adata, grid=None)` gives me "model = cr.ul.models.GAM(adatasub, grid=None)". I checked the documentation, but this should be the correct command. 
Thus, I was wondering if maybe you updated something and the function changed name?

Thanks in advance!

**Comment by michalk8** [comment]
Hi @tinjac ,

`v.1.0.0-rc.0` is and old release candidate, the documentation you see at https://cellrank.readthedocs.io/en/latest/ is the latest one (i.e. the one you could get from GitHub).
I'd recommend to updating to `1.1.0`, which is the current version on `PyPI`, the documentation for this version is https://cellrank.readthedocs.io/en/v1.1.0/

**Comment by tinjac** [comment]
Thank you so much. Updating indeed solved the issue. Sorry for the hassle.
