### ISSUE TITLE
Add links to pyGPCCA

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#477]
@michalk8, Bernhard was asking us whether we could include a link to pyGPCCA in our docs. I was thinking of simply exchanging the following sentence:

"The Markov chain is coarse-grained into a set of macrostates which represent initial & terminal states as well as transient intermediate states."

into

"The Markov chain is coarse-grained into a set of macrostates which represent initial & terminal states as well as transient intermediate states using _Generalized Perron Cluster Cluster Analysis_ (G-PCCA)[**add citation**] as implemented in the novel [pyGPCCA](https://pygpcca.readthedocs.io/en/latest/index.html) package."

**Comment by msmdev** [comment]
Thank you very much @Marius1311, I like your suggestion. :)

Further I would be happy about a mention in the `cellrank.tl.estimators.GPCCA` docstring [here](https://github.com/theislab/cellrank/blob/f501b5345c1dc25c40ca1cb14d4d6af1ff42a664/cellrank/tl/estimators/_gppca.py#L36) as well, e.g.
`Generalized Perron Cluster Cluster Analysis [GPCCA18]_ as implemented in [pyGPCCA]_`
and the related notebook [here](https://cellrank.readthedocs.io/en/latest/auto_examples/estimators/compute_terminal_states_gpcca.html#sphx-glr-auto-examples-estimators-compute-terminal-states-gpcca-py), e.g.
"This estimator makes use of Generalized Perron Cluster Cluster Analysis [GPCCA18] [Reuter19] as implemented in [pyGPCCA]."

**Comment by msmdev** [comment]
@Marius1311 @michalk8 just a hint: your file were you integrate GPCCA in `cellrank/cellrank/tl/estimators/_gppca.py` is called _gppca with two p - is this intentional?

**Comment by michalk8** [comment]
closed via #480
