### ISSUE TITLE
Make STEMNET reference more explicit

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#478]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Current docstring for `cellrank.pl.circular_projection` is "Plot absorption probabilities on a circular embedding.". 

Plese change this to "Plot absorption probabilities on a circular embedding as it is done in STEMNET [cite]". We should be a bit more explicit here, I believe.

**Comment by michalk8** [comment]
closed via #480
