### ISSUE TITLE
Lineage class reduction permutes the colors

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#479]
Calling `adata_air.obsm['to_terminal_states']` displays
![image](https://user-images.githubusercontent.com/24494650/106585463-a75e7180-6547-11eb-9ee3-4addd26208d2.png)
which is the correct set of colors. 

However, I am now interested in seeing the mean abs.probs per lineage so I call `adata_air.obsm['to_terminal_states'].mean(axis=0)`, which displays
![image](https://user-images.githubusercontent.com/24494650/106585587-c78e3080-6547-11eb-98b1-60d05ad74c4d.png)

The order of the lineages remained the same but their colors have been permuted. 

#### Versions:
cellrank==1.1.0+gb36eac8 scanpy==1.6.0 anndata==0.7.4 numpy==1.19.5 numba==0.52.0 scipy==1.5.3 pandas==1.1.3 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.8.3 scvelo==0.2.2 pygam==0.8.0 matplotlib==3.2.2 seaborn==0.11.0
> ...

**Comment by michalk8** [comment]
The 2nd row is using the default colormap - somehow the color info is not propagated.

**Comment by Marius1311** [comment]
Excellent, thanks for looking into it.
