### ISSUE TITLE
`gene_trends`only shows cells for the first lineage

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#485]
I'm trying to plot gene expression trends along several lineages at the same time using 

```
model = cr.ul.models.GAMR(adata_raw, n_knots=5)

fig_kwargs = {'model': model,
              'data_key': 'magic_imputed_data', 
              'genes': ['Pdx1'], 
              'time_key': 'palantir_pseudotime', 
              'weight_threshold': (0.05, 0.05)
             }
cr.pl.gene_trends(adata_raw, **fig_kwargs)
```

This gives
![image](https://user-images.githubusercontent.com/24494650/107045624-02050100-67c6-11eb-9ebd-27288eeb1792.png)

For some reason, cells are only shown for the first lineage. I think that's a bug. 

#### Versions:
cellrank==1.2.0 scanpy==1.6.0 anndata==0.7.4 numpy==1.19.5 numba==0.52.0 scipy==1.5.3 pandas==1.1.3 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.8.3 scvelo==0.2.2 pygam==0.8.0 matplotlib==3.2.2 seaborn==0.11.0
> ...

**Comment by michalk8** [comment]
will be closed in #487
