### ISSUE TITLE
pyGPCCA seems to return the wrong number of macrostates

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#491]
I came across a very degenerate example which already caused trouble in https://github.com/msmdev/pyGPCCA/issues/18. Basically, it's reducible and has several recurrent classes. BTW, this is dyngen's linear example @michalk8. So for whatever reason, requesting 5 macrostates via `g_fwd.compute_macrostates(n_states=5)` prints
```python
Computing `5` macrostates
WARNING: No stationary distribution found in GPCCA object
Adding `.macrostates_memberships`
       `.macrostates`
       `.schur`
       `.coarse_T`
    Finish (0:00:52)
```

but then only gives me 3 macrostates:
![image](https://user-images.githubusercontent.com/24494650/107538874-b20eab80-6bc4-11eb-8a43-8bc17c3600e0.png)

But that's not yet it - when I increase to `6` macrostates, I expect it to fail/warn and to give me 7 macrostates because 6 and 7 are complex conjugates, see the spectrum in the [pygpcca issue](https://github.com/msmdev/pyGPCCA/issues/18). However, that's not what happens and I get precisely 6 macrostates: 
![image](https://user-images.githubusercontent.com/24494650/107539174-fef28200-6bc4-11eb-8773-37c4c1e36a7c.png)

maybe this is also relevant for @msmdev 

#### Versions:
cellrank==1.2.0 scanpy==1.6.0 anndata==0.7.4 numpy==1.19.5 numba==0.52.0 scipy==1.5.3 pandas==1.1.3 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.8.3 scvelo==0.2.2 pygam==0.8.0 matplotlib==3.2.2 seaborn==0.11.0
> ...

**Comment by Marius1311** [comment]
Happy to share this example btw

**Comment by michalk8** [comment]
> @michalk8. So for whatever reason, requesting 5 macrostates via g_fwd.compute_macrostates(n_states=5) prints

Can you check if the lineage object has 5 components?If yes, what are the values for `3` and `5`? I suspect scVelo's plotting isn't handling the value well (they might be all 0s).

**Comment by Marius1311** [comment]
Will do, thanks. I have an update: for 6 macrostates, it does realize it's splitting complex conjugates: 
```
WARNING: Unable to compute macrostates with `n_states=6` because it will split the conjugate eigenvalues. Increasing `n_states` to `7`
Computing `7` macrostates
WARNING: No stationary distribution found in GPCCA object
Adding `.macrostates_memberships`
       `.macrostates`
       `.schur`
       `.coarse_T`
```
However, it sill only shows 6 macrostates.

**Comment by Marius1311** [comment]
You were right, `g_fwd.macrostates_memberships.shape` is `(3000, 5)` for the first case. For the second case, it's (3000, 7), so also correct.

**Comment by michalk8** [comment]
Ok, so this can be close right? Maybe you could open an issue on scVelo, if needed.

**Comment by Marius1311** [comment]
Yes, this can be closed, it did realise when conjugate splitting occured and it did also return the right number of macrostates.
