### ISSUE TITLE
why `__set_initial_states_from_macrostates` not visible? 

### ISSUE THREAD

**Issue by giovp** [theislab/cellrank#494]
https://github.com/theislab/cellrank/blob/f53a6a77359bc3b2b90f7b43971b2240f2370563/cellrank/tl/estimators/_gpcca.py#L1141

is there a reason for being hidden that is relevant re the analysis? I asked this question @Marius1311 already and you pointed me to `g._compute_initial_states()` but I (think? I) want to specify the names of the metastable states explicitly. 

Precisely, I have this velocity vector field:
![image](https://user-images.githubusercontent.com/25887487/107991242-7ade3700-6fd6-11eb-9fc1-106f3726e828.png)

and these are the metastable states found
![image](https://user-images.githubusercontent.com/25887487/107991259-86316280-6fd6-11eb-998d-558f5ee5ca22.png)

so naively I'd say I want to set 3 and 5 to terminal, and 1 to initial. 
Does it makes sense? am I over interpreting?
thank you!!!

**Comment by giovp** [comment]
Ok maybe I got it, in order to get a lineage "towards 1" I should have a different set kernel with `backward=True`. Then the metastable state 0 will become the "terminal" state of a backward process.
Indeed, I have this in adata.obsm
```python
adata.obsm
>>> AxisArrays with keys: PCA, TSNE, UMAP, X_pca, X_umap, velocity_umap, macrostates_bwd, from_initial_states
```

now I should do kernels+estimators again, with `backward=False` and indeed this is what I get
```python
adata.obsm
>>> AxisArrays with keys: PCA, TSNE, UMAP, X_pca, X_umap, velocity_umap, macrostates_bwd, from_initial_states, macrostates_fwd, to_terminal_states
```
I guess this was not clear to me because I didn't realize that an `initial_state` is different than a `terminal_states` with backward process.
Let me know if this understanding is correct. Thank you!

**Comment by michalk8** [comment]
You're right; the reason it's hidden is because originally, it was intended that 1 estimator = 1 direction.
I have no strong opinion whether to make this public, though some tests would be in order.

**Comment by Marius1311** [comment]
Hi @giovp, and thanks to @michalk8 for explaining this already. I would currently leave it as is - I think having two public ways to compute the initial states is confusing. In the future, we can maybe think of exposing this and re-writing parts of the documentation to accommodate for this

**Comment by giovp** [comment]
makes a lot of sense. I think it would be maybe worth an example that described this difference? like why `initial_states` are different than `terminal_bwd` states. I'll close this anywa, and thanks for the very romptprompt reply!
