### ISSUE TITLE
Package for shared code between CellRank and scVelo

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#497]
Hi there @Marius1311, @michalk8, @VolkerBergen!

Given that there is some overlap between code used in CellRank and scVelo, it might be worthwhile moving it to a common repo. For example, as of `scvelo==0.2.3` the parallelisation of recovering gene dynamics is basically equivalent to the implementation by @michalk8 in CellRank. Thus, bugs found in one project would need to be fixed in the other as well.

Further, with [this](https://github.com/theislab/scvelo/pull/354) PR, we start refactoring the scVelo codebase. This introduces, for example, first unit tests based on [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) as well as the accompanying machinery which may be interesting for CellRank as well.

**Comment by Marius1311** [comment]
Thanks for the initiative @WeilerP! What's your opinion here @michalk8? Can you think of other parts of CellRank that could make sense to be shared between the packages?

**Comment by michalk8** [comment]
Definitely plotting (scatterplots) would be great having.

**Comment by Marius1311** [comment]
@michalk8 @WeilerP let's add this to the agenda for our next meeting after easter to see what synergies can be achieved here.

**Comment by michalk8** [comment]
I'd close this, since it's really low-prio.

**Comment by WeilerP** [comment]
Fine by me. I'll potentially reopen it after scvelo has been refactored and made stable.
