### ISSUE TITLE
Switch differentiation potential

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#500]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

I would switch our differentiation potential (simple entropy over fate-probs) for STEMNETs `priming_degree` that we have already implemented in the circular projection (https://cellrank.readthedocs.io/en/latest/api/cellrank.pl.circular_projection.html#cellrank.pl.circular_projection). It has the conceptual advantage of monotonically increasing from progenitors to terminally differentiated cells.

**Comment by Marius1311** [comment]
By that, I mean that we should show this as a default when we plot e.g. absorption probabilities, rather than the entropy.

**Comment by michalk8** [comment]
I think both `priming {degree,direction}` can then be moved to `Lineage` class.

**Comment by Marius1311** [comment]
Yes, I think it makes sense to move it there.
