### ISSUE TITLE
Kall for Kernel tutorial

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#505]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

This should be a walk-trough of how a user can implement their own kernel, and how it can be applied in practice3.

**Comment by michalk8** [comment]
On this side, we just need to modify this: https://github.com/theislab/cellrank/blob/master/docs/source/conf.py#L35
and https://github.com/theislab/cellrank/blob/master/docs/source/index.rst

**Comment by Marius1311** [comment]
nice!

**Comment by Marius1311** [comment]
Comments: 
- very well done! I changed the wording in a few places (and pushed), please go over it once to check whether its accurate
- please finish the Conclusion section.
