### ISSUE TITLE
New adaptive weighting scheme for kernels

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#506]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

This is something we have to discuss in more detail, but I think it's already clear we will need a more general weighting scheme in 1.3 to handle different sorts of kernels.

**Comment by michalk8** [comment]
closed in favor of #654
