### ISSUE TITLE
Macrostates are missing from the plot

### ISSUE THREAD

**Issue by Hrovatin** [theislab/cellrank#507]
When I plot macrostate probabilities on single plot not all states are plotted (e.g. 7 instead of 9). This may be related to low probabilities of these states (see the split-up plot).
![image](https://user-images.githubusercontent.com/47607471/109315819-3d39a380-784b-11eb-9154-76d8a441430f.png)
![image](https://user-images.githubusercontent.com/47607471/109316205-a9b4a280-784b-11eb-96b9-f03e14402b4b.png)

Version: '1.2.0'

**Comment by Marius1311** [comment]
Hi @Hrovatin, thanks for posting this! This is a known bug in scVelo's gradient plotting. @michalk8 , maybe the easiest solution on our side would be to issue a warning for now - alternatively, we could open an issue in the scvelo repo.

**Comment by michalk8** [comment]
As Marius said, it's really an scVelo issue, the culprit line being here: https://github.com/theislab/scvelo/blob/master/scvelo/plotting/scatter.py#L278
The gradient colors are constructed pairwise and if for a pair of lineages `l1` and `l2` we don't find at least `2` cells where both of these have the top probabilities, then the gradient is simply not plotted.

**Comment by Marius1311** [comment]
We can issue a warning for this on our side though, no?

**Comment by michalk8** [comment]
Yes, if we reimplement the part of the logic which causes this. But I would prefer fixing this rather then warning.

**Comment by Marius1311** [comment]
I don't understand you comment @michalk8 - do you mean opening a PR in scVelo to fix this?

**Comment by Marius1311** [comment]
hi @WeilerP, we have an issue here with gradient plotting in scvelo - very subdominant lineages (see Mike's comment above) are currently just not being plotted. Do you have an idea for how we could solve this?

**Comment by WeilerP** [comment]
I'll have a look at it ASAP and will get back to you.
Without having looked at the problem (i.e., the following may be complete rubbish so don't hesitate to point it out): Based on @michalk8 [comment](https://github.com/theislab/cellrank/issues/507#issuecomment-789236068), how would you plot a gradient based on solely a single cell? Wouldn't a single cell intrinsically lack any sense of directionality?

**Comment by Marius1311** [comment]
Hi @WeilerP, any news on this yet?

**Comment by Marius1311** [comment]
@michalk8, I recall you had a solution for this in mind?

**Comment by michalk8** [comment]
Yes, it was about not using the #combinations of colormaps, just define a HSV cylinder and create 1 colormap out of it.
Will implement it later this week.

**Comment by Marius1311** [comment]
Nice, looking forward - esp. to the color wheel, if you can include that as well.

**Comment by michalk8** [comment]
Here's how it looks so far:
- left column: this is the idea I had in mind, slightly adjusted (each cells is assigned into the triangle in the circular plot's polygon and I use barycentric interpolation to interpolate between 3 colors - between lineages + white). Alpha value show lineage priming (entropy-based).
- middle: similarly as done in scVelo and the above: assign every cell to 1 triangle from the circ. embedding, but interpolate the color between lineages, with white color always in the middle (e.g. blue -> white -> red) - this shows the gradient between 2 lineages, ignoring all others (i.e. how close it is to the center of the circ. embedding)
- right current implementation (colors are buggy...)

re color wheel: it only makes sense to do this for the 1st col., but I don't really want to do it (too much effort for too little value).

![index](https://user-images.githubusercontent.com/46717574/113515941-c98c6400-9577-11eb-888e-593e6da2d8a8.png)

**Comment by Marius1311** [comment]
Okay, mhm, I think we need to discuss this in person.

**Comment by michalk8** [comment]
No new impl. is happening, only warning will be issued if a lineage/macrostate may be missing from a legend.
closed via #556
