### ISSUE TITLE
Error computing macrostates with cluster_key set to "louvain"

### ISSUE THREAD

**Issue by Anarion07** [theislab/cellrank#511]
Running estimator.compute_macrostates without a cluster_key set works fine. However, the colours do not match the clusters previously calculated, so setting cluster_key to "louvain" should do the trick, but throws an error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-91-dba755b4adc9> in <module>
----> 1 estimator.compute_macrostates(n_states=3, cluster_key="louvain")

~\AppData\Roaming\Python\Python37\site-packages\cellrank\tl\estimators\_gpcca.py in compute_macrostates(self, n_states, n_cells, use_min_chi, cluster_key, en_cutoff, p_thresh)
    188             cluster_key=cluster_key,
    189             p_thresh=p_thresh,
--> 190             en_cutoff=en_cutoff,
    191         )
    192 

~\AppData\Roaming\Python\Python37\site-packages\cellrank\tl\estimators\_gpcca.py in _set_macrostates(self, memberships, n_cells, cluster_key, en_cutoff, p_thresh, check_row_sums)
    928             en_cutoff=en_cutoff,
    929             p_thresh=p_thresh,
--> 930             add_to_existing=False,
    931         )
    932 

~\AppData\Roaming\Python\Python37\site-packages\cellrank\tl\estimators\_base_estimator.py in _set_categorical_labels(self, attr_key, color_key, pretty_attr_key, categories, add_to_existing_error_msg, cluster_key, en_cutoff, p_thresh, add_to_existing)
    900                 series_query=series_query,
    901                 colors_reference=colors_reference,
--> 902                 en_cutoff=en_cutoff,
    903             )
    904             setattr(self, color_key, colors)

~\AppData\Roaming\Python\Python37\site-packages\cellrank\tl\_colors.py in _map_names_and_colors(series_reference, series_query, colors_reference, en_cutoff)
    231     cats_query = series_query.cat.categories
    232     cats_reference = series_reference.cat.categories
--> 233     association_df = DataFrame(None, index=cats_query, columns=cats_reference)
    234 
    235     # populate the dataframe - compute the overlap

~\anaconda3\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    433             )
    434         elif isinstance(data, dict):
--> 435             mgr = init_dict(data, index, columns, dtype=dtype)
    436         elif isinstance(data, ma.MaskedArray):
    437             import numpy.ma.mrecords as mrecords

~\anaconda3\lib\site-packages\pandas\core\internals\construction.py in init_dict(data, index, columns, dtype)
    237             else:
    238                 nan_dtype = dtype
--> 239             val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
    240             arrays.loc[missing] = [val] * missing.sum()
    241 

~\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py in construct_1d_arraylike_from_scalar(value, length, dtype)
   1447     else:
   1448         if not isinstance(dtype, (np.dtype, type(np.dtype))):
-> 1449             dtype = dtype.dtype
   1450 
   1451         if length and is_integer_dtype(dtype) and isna(value):

AttributeError: type object 'object' has no attribute 'dtype'

**Comment by michalk8** [comment]
Hi @Anarion07 ,
could you please post the output of the line below?
```python3
import cellrank as cr
cr.logging.print_versions()
```

**Comment by Anarion07** [comment]
`cellrank==1.2.0 scanpy==1.7.1 anndata==0.7.5 numpy==1.20.1 numba==0.52.0 scipy==1.4.1 pandas==1.0.1 scikit-learn==0.22.1 statsmodels==0.11.0 python-igraph==0.8.2 scvelo==0.2.3.dev35+g95d90de pygam==0.8.0 matplotlib==3.3.4 seaborn==0.10.0`

**Comment by michalk8** [comment]
@Anarion07 
I am able to reproduce this with the above versions, thanks! This seems to be problem with too low version of pandas for `numpy==1.20.1` Running `pip install pandas>=1.2.0` solved the issue for me.
