### ISSUE TITLE
Add a check for matrix reversibility

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#517]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

Reversibility is the Markov-chain equivalent of a symmetric matrix - in practice, it means that the process looks the same if we invert time, i.e. if we run the process backwards. Such a process will only have real eigenvectors. I will need to think about what the most efficient way to check this for potentially very large, sparse matrices is. Any idea @msmdev?

**Comment by Marius1311** [comment]
That would be a check for symmetry of the underlying adjacency matrix which we don't have access to. We need to have a check directly on T for reversibility.

**Comment by msmdev** [comment]
> That would be a check for symmetry of the underlying adjacency matrix which we don't have access to. We need to have a check directly on T for reversibility.

I didn't want to indicate the adjacency matrix with `a` - just an arbitrary matrix `a`.
T should be symmetric too, if the process is reversible - that's (aka all eigenvalues/-vectors are real) what one assumes in standard MSM and PCCA+.

**Comment by msmdev** [comment]
Just calculate `T = PI.T*P` - with `PI` being a matrix with `PI_ij = pi_j`  and `P` the transition matrix - and check, if `T` is symmetric.

**Comment by msmdev** [comment]
Or, if you don't have the stationary vector (to hard to calculate), you could use Kolomogorov's Criterion [here](https://en.wikipedia.org/wiki/Kolmogorov%27s_criterion).
Should be doable.

**Comment by msmdev** [comment]
> Or, if you don't have the stationary vector (to hard to calculate), you could use Kolomogorov's Criterion [here](https://en.wikipedia.org/wiki/Kolmogorov%27s_criterion).
> Should be doable.

For a NxN transition matrix the number of distinct Kolmogorov equations will be `\sum_{i=3}^N \binom{N}{i} \frac{(i - 1)!}{2}`... so it might be alot...

**Comment by msmdev** [comment]
> Just calculate `T = PI.T*P` - with `PI` being a NxN matrix with `PI_ij = pi_j` and `P` the NxN transition matrix - and check, if `T` is symmetric (* is elementwise multiplication - Hadamard product).

In practice, one can use this by computing `P^n` to a large enough power `n` (say n=100), which will result in a matrix with common rows and each row is the the stationary vector `pi` (if the Markov chain is irreducible). Then we compute `(P^n).T*P` and check for symmetry.

**Comment by Marius1311** [comment]
Okay, it's probably most efficient to compute the stationary vector and then check for symmetry.

**Comment by msmdev** [comment]
@Marius1311 So you will give `T = PI.T*P` a try?
And in case you can't calculate the stationary vector you already know that `P` isn't reversible...

**Comment by Marius1311** [comment]
Well, If P was made up of two separate recurrent classes which were both reversible, than the overall P would also be reversible, no? In that case, no unique stationary distribution would exist.

**Comment by Marius1311** [comment]
But that's an edge case and we could get around it by restricting P to it's recurrent classes

**Comment by msmdev** [comment]
> Well, If P was made up of two separate recurrent classes which were both reversible, than the overall P would also be reversible, no? In that case, no unique stationary distribution would exist.

I wouldn't say so, since the overall system wouldn't be ergodic, because the stationary distribution isn't unique.

**Comment by msmdev** [comment]
So summing it up: if we don't have a unique stationary vector `P` isn't ergodic and thus not reversible. Only, if we can calculate a unique `pi` we need to check for reversibility via checking for symmetry of `T=PI.T*P`.

**Comment by Marius1311** [comment]
This will be delayed to a later release.

**Comment by michalk8** [comment]
@Marius1311 what's the status here? Should we move this to https://github.com/msmdev/pyGPCCA/issues/24?

**Comment by Marius1311** [comment]
Sure, feel free to move this one.

**Comment by michalk8** [comment]
closed in favor of https://github.com/msmdev/pyGPCCA/issues/24
