### ISSUE TITLE
Decision tree for kernels

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#524]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Some help for users in the right choice of kernel

**Comment by michalk8** [comment]
TODO:
- [ ] create a blank about CellRank

**Comment by michalk8** [comment]
I think this can be closed, was related to #534 .
