### ISSUE TITLE
Experimental time kernel

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#525]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [x] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

I.e. from experiments.

**Comment by Marius1311** [comment]
Great to see this - have you started validation for this yet?

**Comment by Marius1311** [comment]
I would start looking into this for a very simple dataset that we understand (or a subset of timepoints) and then moving on to something bigger.

**Comment by michalk8** [comment]
Closing this.
