### ISSUE TITLE
CytoTRACE kernel

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#528]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [x] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

...

**Comment by michalk8** [comment]
closed via #527

**Comment by Marius1311** [comment]
This has been closed in #527.
