### ISSUE TITLE
Add simulations for kernels

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#529]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

...

**Comment by Marius1311** [comment]
Okay, so the idea here is to have an estimator which allows you to get a "feeling" for your transition matrix, without the aim to be quantitative. It should draw realisations from the Markov chain defined though the transition matrix, i.e. simulate trajectories, and have convenient plotting functions to show them in the embedding, making it obvious where they **start** and **end**.  The simulation method should have parameters
- `n_draws`: number of simulations to run
- `n_steps`: how long to run each simulation
- `n_jobs`: parallelisation, these draws can be computed entirely in parallel
- `initialize_in`: where to start the simulations. Should accept a dict of the form `{cluster_key: cluster_value}`, or alternatively a `cell_index` or `cell_obs_name`, in which case we sample starting points from that cell's neighbors. If `None` is passed, we just sample starting cells randomly. 
- `stopping_criterion`:  Should determine when to stop the simulation. Should be `Optional[str, dict[str, list]]`, which defaults to stopping after `n_steps`, but also allows you to give a dict specifying a cluster key and a list of clusters, which means that the random walk is terminated as soon as any of these clusters are reached. 

The plotting function should show these random walks in a choosen embedding with any cell-level coloring and a nice visualisation of start and end points.

**Comment by Marius1311** [comment]
We agreed to make this a kernel method instead.

**Comment by michalk8** [comment]
closed via #537
