### ISSUE TITLE
Lineage drivers vs cluster markers

### ISSUE THREAD

**Issue by YitengDang** [theislab/cellrank#531]
I have a conceptual question about one of CellRank's key features, namely computing lineage driver genes. As I understand, the drivers are identified by computing Pearson correlation values between fate probabilities and gene expression.
Conceptually, I would expect these to have significant overlap with marker genes of the identified clusters. These would be the ones computed in scanpy by differential expression using one of many statistical tests such as the t-test. 

Hence I compared them in my data set and found a significant overlap between the top lineage drivers (with highest absolute correlation values) and the top cluster markers (with highest p-values):

*Top 5 lineage drivers*
cluster 1 | cluster 2 | cluster 3 | cluster 4 |
-- | -- | -- | --
Dlk1 | Tcf4 | Gja1 | Mef2c
Mfap5 | Twist2 | Apoe | Sp7
Dcn | Ptma | Fxyd5 | Gsn
Cd34 | Cxcl14 | Rbp1 | Tmem119
Nov | Col6a1 | Cldn11 | Alpl

*Top 5 cluster markers (differentially expressed genes)*
cluster 1 | cluster 2 | cluster 3 | cluster 4 |
-- | -- | -- | -- 
Dlk1 | Tcf4 | Gja1 | Ibsp
Mfap5 | Twist2 | Apoe | Sgms2
Dcn | Osr2 | Rbp1 | Gsn
Meg3 | Ptma | Fxyd5 | Fkbp11
Ebf1 | Malat1 | Akap12 | Tmem119

Therefore, my question is: what are the main (dis)advantages of using lineage drivers rather than the cluster marker genes for the identified terminal states? Are there situations in which these would differ significantly?

**Comment by Marius1311** [comment]
Hi @YitengDang, that's a great question! This will massively depend on your dataset - if you have a large proportion of cells in and around terminal states, then I would expect to see a large overlap with cluster markers, as you report above. If however most cells are in intermediate states, there will be a larger difference between lineage drivers and marker genes. 

In general, cluster markers are a great way to do a discrete comparison across groups, and if you're interested in genes which are differentially upregulated in your terminal cell types, then you should probably use them. If however, you're looking for genes which show different dynamical expression patterns along lineages that lead to different terminal states, then lineage drivers are really what you're looking for. 

If you're interested in more fine-grained questions that relate to dynamic expression changes along different lineages, then maybe tradeSeq is something for you: https://github.com/statOmics/tradeSeq. It may be possible to use CellRank's fate probabilities to define lineages in tradeSeq, however, we haven't explored this further at this point.
