### ISSUE TITLE
Link from docs to GitHub is not working

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#532]
## Description

Clicking on _Edit on GitHub_ to go from the docs (e.g. [here](https://cellrank.readthedocs.io/en/latest/api/cellrank.tl.transition_matrix.html#)) to the corresponding code on GitHub, Read the Docs redirects to a non existing page (and consequently complaining that the page does not yet exist). Seems like the new link is identical to the old one except for a missing `.html` at the end instead of the correct link to GitHub.

**Comment by michalk8** [comment]
Thanks, this was also problematic in squidpy (where a fix fixing most of these worked) https://github.com/theislab/squidpy/pull/294
Will include it here later as well.

**Comment by Marius1311** [comment]
nice, thanks.

**Comment by michalk8** [comment]
closed via #538
