### ISSUE TITLE
Scaling CellRank to large datasets

### ISSUE THREAD

**Issue by emdann** [theislab/cellrank#540]
Hi,
I'm an enthusiastic user of CellRank and I'd like to try to apply it for fate inference on a large dataset (~ 500k cells, complex hematopoietic-like lineages). I've run a few tests on a subset of ~ 70k cells, using only the connectivity kernel and setting the terminal states manually and the computation of absorption probabilities took quite a long time (> 12 hours) and ~ 50GB of memory. Is this to be expected or are there any specific options and tweaks I can use to speed up the computation? I've run `g.compute_absorption_probabilities(n_jobs=10, use_petsc=True)`.
Any tips on how to scale up efficiently would be greatly appreciated!

**Comment by Marius1311** [comment]
Hi @emdann! Great to hear that you enjoy using CellRank! The time & memory consumption on 70k cells surprises me - this should be **much** faster. In our own comparisons, using an Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz and 32 cores with 90GiB memory allocated, we computed fate probabilities towards 3 terminal states (30 cells each) for **100k cells** in about **2 min** with a maximum memory consumption of **35 GiB**. 

Let's try the following things: 
- could you please make sure you're using the latest versions of both CellRank and pyGPCCA (Should be CellRank 1.2 and pyGPCCA 1.0.1)
- could you please make sure you're actually allocating enough cores on your server, i.e. at least 10 for `n_jobs=10`
- how many terminal states are you computing? Are you using the low-level interface, i.e. using kernels and esimators?

**Comment by emdann** [comment]
Thanks @Marius1311 for the quick response
> could you please make sure you're using the latest versions of both CellRank and pyGPCCA (Should be CellRank 1.2 and pyGPCCA 1.0.1)

I installed the development version from github following the instructions in the docs, this is the version number. Should I try installing from bioconda? pyGPCCA is the latest version 
```
# Name                    Version                   Build  Channel
cellrank                  1.1.1.dev36+g825af03           dev_0    <develop>
cellrank-krylov           1.1.0              pyhd784808_0    bioconda
```
> could you please make sure you're actually allocating enough cores on your server, i.e. at least 10 for n_jobs=10

I'm allocating 10 cores and 150GB of memory.

> how many terminal states are you computing? 

I'm computing 3 terminal states, but with the manual assignment for each state I assign > 1000 cells. Would restricting to fewer terminal cells help? 

> Are you using the low-level interface, i.e. using kernels and esimators?

Yep

Thanks a lot for your help!

**Comment by Marius1311** [comment]
I wonder why the development version is at 1.1, should really be 1.2. Could you try uninstalling and re-installing please? And yes, 1000 cells per terminal state is an issue, that will **massively** slow you down, try with something like 50 cells per terminal state please.

**Comment by emdann** [comment]
Removing the repo, cloning again and reinstalling updated to the right version
```
# Name                    Version                   Build  Channel
cellrank                  1.2.1.dev12+g8e8ace5           dev_0    <develop>
cellrank-krylov           1.1.0              pyhd784808_0    bioconda
```
Computing absorption probabilities with 30 cells per terminal state now takes a smashing 36 seconds. 

Great to see there was a simple explanation. Thanks for your help!

**Comment by Marius1311** [comment]
Amazing, really happy that this worked so well! I will close this issue.

**Comment by Marius1311** [comment]
BTW @emdann, please let me know how CellRank performs on 500k cells - I'm really interested in this. If you can request more cores, than please do (e.g. like 32) - computation of absorption probabilities is fully parallelised, so you get a direct speed up.

**Comment by Marius1311** [comment]
Uh, one thing to keep in mind though is that RNA velocity often has difficulties in hematopeisis, keep that in mind.

**Comment by emdann** [comment]
Thanks @Marius1311, I'll send updates. 

As far as kernels go, I am actually testing whether I could bypass the use of velocity by just combining the connectivity kernel and a transition matrix based on real time (we have samples from 11 time points). I got excited when I saw the ExperimentalTimeKernel PR https://github.com/theislab/cellrank/pull/526, then my hopes were shattered again. I'd be curious to know what you think are the hardest challenges here.

**Comment by Marius1311** [comment]
Hi @emdann, sorry to shatter your hopes with closing #526 - we just realized we need a bit more time to validate this before putting this on dev. One option for you would be to use WadingtonOT to link together your time points - in essence, that would give you one transition matrix per pair of time points, but we could stitch them together to get one combined large transition matrix. Or, maybe even better, you use the recent extension by the Schiebinger lab called gWOT, see here: https://github.com/zsteve/gWOT

I've never tried but from what I understand, it gives you one combined transition matrix for all your time points. You could then import this into CellRank via a `PrecomputedKernel` and proceed as always - I would be super curious about the results!

**Comment by Marius1311** [comment]
@michalk8 was involved in #526 and may be interested in this discussion.

**Comment by michalk8** [comment]
#526 didn't really worked, will start looking into Waddington OT/generalized Waddington OT for this.

**Comment by Marius1311** [comment]
great, thanks. @emdann, happy to involve you in this if you're interested.

**Comment by Marius1311** [comment]
The scalability part of this is closed, the real-time discussion will continue in #551.
