### ISSUE TITLE
Embedding projection fails when the embedding coordinates contain any Nan values

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#545]
I have an embedding which contains few Nan's. When I run `kernel.compute_projection()` to project the transition matrix into that embedding, the resulting projection in `adata.obsm` is all Nans. 

#### Versions:
cellrank==1.2.0+g62915ec.d20210222 scanpy==1.6.0 anndata==0.7.5 numpy==1.19.2 numba==0.51.2 scipy==1.5.3 pandas==1.1.4 pygpcca==1.0.1 scikit-learn==0.23.2 statsmodels==0.12.1 python-igraph==0.8.3 scvelo==0.2.3 pygam==0.8.0 matplotlib==3.3.2 seaborn==0.11.0
> ...

**Comment by Marius1311** [comment]
Replacing the Nan values in the embedding coordinates with zeros solved the problem.

**Comment by michalk8** [comment]
@Marius1311 I've merged it asap s othat you can finish the tutorial (tests should pass)
closed via #546

**Comment by Marius1311** [comment]
Fantastic, thanks a lot Mike.
