### ISSUE TITLE
Image in the `kernels_and_estimators` tutorial does not load

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#550]
That's how the page appears to me when I open it: 
![image](https://user-images.githubusercontent.com/24494650/112815597-c4637c80-9080-11eb-972e-ebb8160a8092.png)

**Comment by Marius1311** [comment]
Maybe it's a problem with the html code I use to embed the image? Or maybe the image is too large?

**Comment by michalk8** [comment]
> Maybe it's a problem with the html code I use to embed the image? Or maybe the image is too large?

I don't think so - I've wrapped `<src>` tag with `<center>`, because when trying it locally, it wasn't centered. I've removed the tag, let's see if it's fixed.

**Comment by michalk8** [comment]
Fixed now, though the image is not centered.
closed via https://github.com/theislab/cellrank_notebooks/commit/f4f093b2bf4157627fd03b68428d35ee72663006
