### ISSUE TITLE
Real-time integration

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#551]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

This is about including a kernel that computes a directed transition matrix base on real-time information. Some options that come to my mind:
- WaddingtonOT [WOT] (pairwise unbalanced optimal transport among time-points), see https://www.cell.com/cell/pdf/S0092-8674(19)30039-X.pdf
- global Waddington OT [gWOT] (same as WOT, but OT problem solved simultaneously for all time points rather than pairwise), see https://github.com/zsteve/gWOT
- Dana's harmony (heuristic that uses mutual nearested neighbors in conjunction with regression to estimate the existence and strength of inter-timepoint links), see https://www.nature.com/articles/s41586-019-1127-1 or https://github.com/dpeerlab/Harmony

These are just three, there are probably more out there. Architecture-wise, it would probably make most sense to include this via the `external` interface.

**Comment by Marius1311** [comment]
We have decided to integrate WOT. @michalk8, are there any news here?

**Comment by michalk8** [comment]
closed via #595
