### ISSUE TITLE
GPCCA compute_lineage_priming missing

### ISSUE THREAD

**Issue by mzhibo** [theislab/cellrank#557]
...
Hi, 
Great job building this super helpful package!
I found in the Classes-estimators-GPCCA, there is a function ompute_lineage_priming. However, it returns an error of no attribute when I tried to call it. Is this missing or it has to be combined with velocity?
Thanks,
Zhibo
 

```
from cellrank.tl.kernels import PalantirKernel
pk=PalantirKernel(adata, time_key='monocle3_pseudotime').compute_transition_matrix()
print(pk)
from cellrank.tl.estimators import GPCCA
g = GPCCA(pk)
print(g)
...
g.compute_lineage_priming()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-100-80871743a0bc> in <module>
----> 1 g.compute_lineage_# not working

AttributeError: 'GPCCA' object has no attribute 'compute_lineage_priming'priming
```

**Comment by Marius1311** [comment]
Hi @mzhibo, can you please post the CellRank version you're using here, and make sure it's the most recent one, i.e. 1.3?

**Comment by mzhibo** [comment]
I am using the 1.2. Is it something new in 1.3?
_________________
Running CellRank 1.2.0, on 2021-04-06 15:12.

**Comment by Marius1311** [comment]
Yes, the method you're trying to call only exists in 1.3 so please update.

**Comment by mzhibo** [comment]
Great! Thank you!
