### ISSUE TITLE
Doubt about arrows and dashed lines in directed PAGA

### ISSUE THREAD

**Issue by alexmascension** [theislab/cellrank#560]
Hi

I've got a question about the directed PAGA. I see that different clusters are joined by arrows or dashed lines, but I didn't find any info on their meaning in cellrank docs. Could you explain what's their difference? What does two clusters connected with a thick dashed line imply?

![image](https://user-images.githubusercontent.com/35657291/114151999-0496ea80-991e-11eb-8b5e-092497b001e1.png)

![image](https://user-images.githubusercontent.com/35657291/114151412-5f7c1200-991d-11eb-896a-c9d9c2028631.png)

Thanks for your help!

**Comment by Marius1311** [comment]
Hi @alexmascension, thanks for your questions. We use scVelos implementation to compute the directed PAGA graph , see https://scvelo.readthedocs.io/scvelo.tl.paga.html#scvelo.tl.paga and our plotting function is based on scVelo's PAGA plotting function, see https://scvelo.readthedocs.io/scvelo.pl.paga.html#scvelo.pl.paga

In short, dashed lines reflect transcriptomic similarity, as in the original PAGA implementation, and arrows are computed on the basis of the velocity flow from one cluster to the other. More details on this are also given in our [preprint](https://www.biorxiv.org/content/10.1101/2020.10.19.345983v2), see the Online Methods part, Section 2 ("Computing a directed PAGA graph").

**Comment by alexmascension** [comment]
Oh, that's nice. Thanks for your help!
