### ISSUE TITLE
Not a valid transition matrix, not all rows sum to 1

### ISSUE THREAD

**Issue by notimenocall** [theislab/cellrank#567]
Hi, thanks for the great tool! I run into an error with `cr.tl.terminal_states(adata, cluster_key='leiden', weight_connectivities=0.2)`. Could you please advise?

```python
ValueError                                Traceback (most recent call last)
<ipython-input-45-905a2b11ccb4> in <module>
----> 1 cr.tl.terminal_states(adata, cluster_key='leiden', weight_connectivities=0.2)

/cellrank/tl/_init_term_states.py in terminal_states(adata, estimator, mode, n_states, cluster_key, key, show_plots, copy, return_estimator, fit_kwargs, **kwargs)
    210 ) -> Optional[AnnData]:
    211 
--> 212     return _initial_terminal(
    213         adata,
    214         estimator=estimator,

/cellrank/tl/_init_term_states.py in _initial_terminal(adata, estimator, backward, mode, backward_mode, n_states, cluster_key, key, show_plots, copy, return_estimator, fit_kwargs, **kwargs)
     91 
     92     try:
---> 93         kernel = PrecomputedKernel(key, adata=adata, backward=backward)
     94         write_to_adata = False  # no need to write
     95         logg.info("Using precomputed transition matrix")

/cellrank/tl/kernels/_precomputed_kernel.py in __init__(self, transition_matrix, adata, backward, compute_cond_num)
     90 
     91         if not np.allclose(np.sum(transition_matrix, axis=1), 1.0, rtol=_RTOL):
---> 92             raise ValueError("Not a valid transition matrix, not all rows sum to 1")
     93 
     94         if adata is None:

ValueError: Not a valid transition matrix, not all rows sum to 1`

**Comment by Marius1311** [comment]
Hi @notimenocall, it looks like `initi_term_states` is trying to use a precomputed matrix you have saved in your AnnData object - what version of CellRank are you using? Could you please make sure it's the latest, i.e. `1.3.1`?

**Comment by michalk8** [comment]
> Hi @notimenocall, it looks like initi_term_states is trying to use a precomputed matrix you have saved in your AnnData object - what version of CellRank are you using? Could you please make sure it's the latest, i.e. 1.3.1?

It should be saved under `adata.obsm['T_fwd']`. We're using `rtol=1e-12`, because of `pygpcca` , see [here](https://github.com/msmdev/pyGPCCA/blob/91bd8871cf3a4b48e5319a8b3bc6bf2db15f5385/pygpcca/utils/_utils.py#L121).

**Comment by notimenocall** [comment]
Hi both, thanks for your reply! I upgraded to 1.3.1 from 1.3.0. But the issue seems to be related to adata.obsp['T_fwd'] and goes away with an object without adata.obsp['T_fwd'].
