### ISSUE TITLE
Prune requirements

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#569]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

I think 2 can be removed:
- ipywidgets (not necessary)
- tzlocal (not sure why this is present, think @Marius1311 you've had some problem when it was missing)
- wrapt? (use simple decorators)
- h5py (was due to some error in 3.0.0 [strings as bytearrays], should be fine now)
- future_fstrings (needed only for <3.6, which we no longer support)
- anndata (done through scanpy)

Also `numba>=0.53.0` should be checked to see what the problem (if any) is.

**Comment by Marius1311** [comment]
Sound good to me!

**Comment by michalk8** [comment]
closed via #571
