### ISSUE TITLE
Recommendations about diverse samples analysis

### ISSUE THREAD

**Issue by mxposed** [theislab/cellrank#570]
Hi, thank you for the wonderful package.

I was wondering what are the best practices / advice when analysing a set of samples with different cell types.

1. Do you expect serious complications if we just merge spliced / unspliced counts between samples and proceed with scvelo and cellrank analysis? Or would you recommend to run cellrank on individual samples and not to merge them? We use scVI to integrate counts only.
2. Our samples have several different cell lineages: epithelial, T cells, macrophages, etc. Do you recommend subsetting on each of them individually or typically they will be separated naturally with the analyses?

**Comment by Marius1311** [comment]
Hi @mxposed, thanks for your interest in CellRank! 
- Re 1: Integration of spliced/unspliced counts is an open question in the field, see #461 and https://www.hansenlab.org/velocity_batch for some early approaches. I would just give it a go: if there's no large batch effects in `.X`, spliced and unspliced counts should be fine. If there is a batch effect, there is a chance velocity estimation still works because it looks at the ration of spliced/unspliced counts - however, all of this is experimental, we have no best practices here yet!
- Re 2: different lineages won't be a problem, these should be separated naturally.

**Comment by Marius1311** [comment]
Hi @mxposed, is there any other way in which I can help you?

**Comment by mxposed** [comment]
Thank you very much, Marius!

Re 1: we will try just putting them together and see if there's batch effect. I will also read the linked resources, thanks.

Re 2: with a test analysis that I ran on one of our datasets it turned out to be true, T cell and myeloid lineages did not mix. However, low-quality cells did seem to influence analysis a little. Another thing is that transcriptionally similar cells like DC and Macrophages start having some overlap in terms of RNA velocity, and it's hard to know if it's an artefact or biology.

Another question that came up: what is the difference between automated terminal/initial state discovery vs. telling the algorithm how many states I want? Is there any metric to examine that my choice of, say, 5 terminal states actually makes sense in the dataset?

**Comment by Marius1311** [comment]
Hi @mxposed, re your new question, I suppose you use the low [level API](https://cellrank.readthedocs.io/en/stable/api.html) and you compute terminal states by first computing macrostates using `estimator.compute_macrostates()` and then terminal states using `estimator.compute_terminal_states()`, see the [GPCCA estimator](https://cellrank.readthedocs.io/en/stable/classes.html#cellrank.tl.estimators.GPCCA). If you're not using the low level API, then you would recommend you get familiar with it by going through our [kernels and estimators tutorial](https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html) - you just won't get the level of control you need for complex biological systems with the high level API. Let's go though the method calls I mentioned above one by one:
1. **macrostates**: when you [compute macrostates](https://cellrank.readthedocs.io/en/stable/auto_examples/estimators/compute_macrostates.html#), these include initial, intermediate and terminal states. You can either provide the number of macrostates you want (via `n_states` parameter), or you can use the `min_chi` (See e.g. [Reuter et al., 2018](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.8b00079)) heuristic to determine them automatically, in that case, you pass an interval to search over, i.e. `n_states=[min, max]`. Another heuristic you can use to determine this number is the `eigengap`  - again, going through our tutorials will make you familiar with this. 
2. **terminal states**, some, but not all of your macrostates will represent [terminal states](https://cellrank.readthedocs.io/en/stable/auto_examples/estimators/compute_terminal_states_gpcca.html#). There are various ways to find the subset of macrostates that's terminal, the default is via the [stability of the macrostates](https://cellrank.readthedocs.io/en/stable/classes.html#cellrank.tl.estimators.GPCCA.compute_terminal_states), i.e. their self-transition probability in the coarse-grained transition matrix. That's the default when you call `estimator.compute_terminal_states()`

If you would like to find out more about this, and about the theoretical foundations behind this, please make sure to go through the Online methods of [our preprint](https://www.biorxiv.org/content/10.1101/2020.10.19.345983v2).

**Comment by mxposed** [comment]
I was using higher-level API. Will read more and switch to lower level. Thank you
