### ISSUE TITLE
CellRank unable to identify a biologically sound initial state

### ISSUE THREAD

**Issue by dilworthlab** [theislab/cellrank#573]
... 
Hello, thank you for this amazing package and the great tutorials/paper. 

I am currently trying to delineate trajectories in my mouse single-cell RNAseq data. The data includes regenerating muscle stem cells after injury. When I analyze the data with CellRank, what should be the initial state (known stem cell population), is identified as the terminal population. I have gotten these results with both Velocyto and scVelo. A few things to note:

1-  As expected, the time-point at which the cells were collected, resulted in a large cluster of stem cells and a relatively small cluster of differentiated cells. I suspect that this may be causing some problems in the identification of the correct initial state. 

2- I also noticed that one of the very important differentiation markers was filtered out while preprocessing the data because of the thresholds used. 

Temporary Solution: 
While preprocessing, I retained the differentiation marker irrespective of the thresholds and also changed the _n_states_  parameter when identifying terminal states. This allowed the differentiated cell cluster to be identified as one of the 4 terminal states. 

Remaining problem:
Stem cell cluster is still being identified as "terminal". 
 _It is worth noting that when I just look at the trajectory leading towards the correct differentiating population, the lineage drivers and gene dynamics generally make a lot of sense._ 

I was hoping to get some advice on how to tackle this problem. Should I perhaps abandon RNA velocity to deduce directionality in this case? With the differentiating cell population being much smaller than the stem cell population, RNA velocity may not work with my system. 

Thanks in advance!

**Comment by Marius1311** [comment]
Hi @dilworthlab, thanks a lot for your interest in CellRank! Let's go though this step by step:
1. How do you interact with CellRank? Do you use the [high-level API ](https://cellrank.readthedocs.io/en/stable/api.html)(i.e. `cr.tl.terminal_states`) or the low-level API (i.e. via kernels and estimators). I **highly** recommend using the low-level API, please see our [kernels and estimators](https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html) tutorial on this. It just gives you the control you need for complex biological systems. 
2. Do velocities generally make sense for your data? i.e. do velocities projected into an embedding *generally* recover what you expect? Doesn't have to be perfect, we shouldn't overinterpret 2D embeddings, but just roughly? Also, how about per-gene velocities, did you look at the top likelihood genes? See [scVelo's tutorial](https://scvelo.readthedocs.io/DynamicalModeling.html) on that. Before we go into any detail here, we have to establish whether RNA velocity *generally* works for your system.

**Comment by Marius1311** [comment]
Hi @dilworthlab, I'm closing as I assume the linked tutorials and infos solve your questions - feel free to re-open if anything is still unclear!
