### ISSUE TITLE
Transition matrix in custom kernel

### ISSUE THREAD

**Issue by dawe** [theislab/cellrank#579]
Hi all, I'm trying to implement a custom kernel for cellrank, following the example in documentation. In the `compute_transition_matrix()` function I have all instructions to build a square matrix of weights I want to use in cellrank. However, I noticed that after the method calls `self._compute_transition_matrix()` which, as far as I can tell, does some checks and sets `self.transition_matrix`, the values are not the ones I calculated, e.g. these are some example values for the matrix I calculate
```
T[:3, :3]
array([[8.20000000e-01, 6.12340866e-14, 1.24509309e-12],
       [6.77667862e-40, 5.78757876e-01, 3.77047752e-02],
       [5.99879653e-26, 3.02035733e-02, 6.09560710e-01]])
```

and these are the values I find in the kernel

```
K.transition_matrix.A[:3, :3]
array([[1.88332568e-02, 1.40638692e-15, 2.85965341e-14],
       [1.57640402e-41, 1.34631771e-02, 8.77095740e-04],
       [1.48124952e-27, 7.45800065e-04, 1.50515441e-02]])
```

Manually setting the values does not change the results (`K.transition_matrix = T` does not change the stored values). Note that I'm setting `density_normalize=False`, having it true return different values but still not the computed ones. Any hint?

**Comment by dawe** [comment]
Nevermind, I’ve just found out that all rows must sum to 1 and this is enforced

**Comment by Marius1311** [comment]
Sorry, I was on holidays and just saw this - I hope all is good now!

**Comment by dawe** [comment]
Hope you had terrific holidays! It's all good now, thanks
