### ISSUE TITLE
plot with different gene labels

### ISSUE THREAD

**Issue by dawe** [theislab/cellrank#581]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

I have AnnData var names as EnsID, there's a adata.var['Symbol'] column for readability. It would be useful if alternate gene labels could then be passed to cr.pl functions, in particular `cr.pl.heatmap()` but also `cr.pl.gene_trends()`

**Comment by dawe** [comment]
AFAIK if a list of names other than `adata.var_names` is given to `sc.pl.heatmap` , you need to specify the column in `adata.var` that stores the values of the given list through the argument `gene_symbols`. So, to have symbols one has to call `sc.pl.heatmap(adata, ['gs1', 'gs2',…], gene_symbols='Symbol')` assuming `adata.var` has a column `Symbol`.
I find scanpy solution a bit counterintuitive, IMHO a easier solution would be to call heamtap with actual var_names and let the plot function to get the appropriate names from the specified column: `sc.pl.heatmap(adata, ['ens1', 'ens2',…], gene_symbols='Symbol')`. If I have multiple columns I want to use for names in different plots I only have to change the key, whereas the current implementations forces me to pass a different list for each plot.

**Comment by Marius1311** [comment]
@michalk8, could you draft an implementation for this?

**Comment by Marius1311** [comment]
Hi @michalk8, what's the status here?

**Comment by Marius1311** [comment]
@michalk8, any progress on this yet?

**Comment by michalk8** [comment]
Currently, this is not on my priority list.

**Comment by Marius1311** [comment]
@michalk8, let's either close this (can add to release schedule if important) or add to 1.5, I leave this to you.

**Comment by michalk8** [comment]
> @michalk8, let's either close this (can add to release schedule for a later release if important) or add to 1.5, I leave this to you.

I have context manager implemented in `squidpy` which switches between gene symbols stored elsewhere in `adata.var`, so I think I can just rehash that (as long as it's fine I make the gene symbols unique if they are not unique, otherwise, the implementatin is a bit problematic [we store the fitted models in a dict of dics, `<lineage>: <gene>: ...`]).

**Comment by Marius1311** [comment]
That sounds like a good solution, let's go for that.

**Comment by michalk8** [comment]
closed via #726 (parameter name is `gene_symbols`)
