### ISSUE TITLE
Add vein plot

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#591]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [x] New plotting function in `cr.pl`?
- [ ] Other?

This plot can nicely describe transition matrice., see fig. 7c from [Mittnenzweig. *et. al.*](https://www.cell.com/cell/fulltext/S0092-8674(21)00439-6).

**Comment by Marius1311** [comment]
Hi @michalk8 , what's the state of this?

**Comment by michalk8** [comment]
No progress so far, also not high on my priority list right now.

**Comment by Marius1311** [comment]
Hi @WeilerP, would you like to take care of this? Basically, the idea here is to add a kernel-level plotting function for time-series datasets to visualize the transition matrix, i.e. how probability mass moves between clusters across time points. Given a cell-cell transition matrix, obs-level experimental time and cluster levels, we would like to re-implement the `vein plot` function from  [Mittnenzweig. *et. al.*](https://www.cell.com/cell/fulltext/S0092-8674(21)00439-6). They use this e.g. in their Fig. 4a or 7c. The vein plot can be considered an abstraction of their "network flow model" of their Fig. 2D. This is based on their "metacell" model, see [Baran et al., Genome Bio 2019](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1812-2). Ideally, I would like to not use the metacell model but have an independent implementation. 

Their (R) implementation can be found here: https://github.com/tanaylab/embflow. @michalk8 will be able to tell you more. 

Fig. 1
<img width="524" alt="Screenshot 2021-05-31 at 11 55 18" src="https://user-images.githubusercontent.com/24494650/120176027-1b173f00-c207-11eb-96b5-853f65efea26.png">

**Comment by WeilerP** [comment]
Yes, will do! This is not super urgent, right? I'll be able to get to it by the beginning of next week.

**Comment by Marius1311** [comment]
That's fine! I envisage this to be a part of our 1.4 release. We don't have a release plan for that yet, but we can draft something tomorrow in our meeting. 

This vein plot function should probably be a method of the RealTimeKernel class - any kernel that makes use of real (experimental) time should inherit such a plotting function.

**Comment by Marius1311** [comment]
@WeilerP, Mike started to look into this, so you can focus on #603

**Comment by michalk8** [comment]
closed via #615
