### ISSUE TITLE
Update bibtex template for sphinx

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#596]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Please add

**Comment by michalk8** [comment]
closed via #601
