### ISSUE TITLE
Real-time kernel tutorial

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#597]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Show WOT in action though CellRank external kernel.

**Comment by michalk8** [comment]
closed via https://github.com/theislab/cellrank_notebooks/pull/35
