### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#598]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Remove some of the very technical examples (from the estimators section), introduce kernel section with examples like project transition matrix, sample random walks, etc. Could also include things like showing off particular kernels, i.e. StationaryOT kernel, that we don't have tutorials for.

**Comment by michalk8** [comment]
closed via #602
