### ISSUE TITLE
WOTKernel requires KNN graph

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#599]
When I initialize the WOTKernel via `wk = WOTKernel(adata, time_key='day')`, it complains that no KNN graph was found: 
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/Projects/cellrank/cellrank/ul/_utils.py in _get_neighs(adata, mode, key)
    198         try:
--> 199             res = _read_graph_data(adata, key)
    200             assert isinstance(res, (np.ndarray, spmatrix))

~/Projects/cellrank/cellrank/ul/_utils.py in _read_graph_data(adata, key)
    236 
--> 237     raise KeyError(f"Unable to find key `{key!r}` in `adata.obsp`.")
    238 

KeyError: "Unable to find key `'connectivities'` in `adata.obsp`."
```
which is expected, because there is no KNN graph in this AnnData object. However, I don't think WOT needs one to compute the transition maps, so we should probably remove this requirement. 

#### Versions:

> cellrank==1.3.1+ga966e79 scanpy==1.7.2 anndata==0.7.5 numpy==1.19.2 numba==0.51.2 scipy==1.5.3 pandas==1.2.1 pygpcca==1.0.2 scikit-learn==0.24.0 statsmodels==0.12.1 python-igraph==0.8.3 scvelo==0.2.3 pygam==0.8.0 matplotlib==3.3.3 seaborn==0.11.0

**Comment by michalk8** [comment]
closed via #600
