### ISSUE TITLE
Update example workflows for CytoTRACE and WOT

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#604]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

The CytoTRACE workflow didn't include the actual part where we use the kernel, so I added that. I also re-phrased some stuff in the WOT example workflow.

**Comment by michalk8** [comment]
closed via #605
