### ISSUE TITLE
Update `estimator.set_terminal_states` docstring

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#606]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Outdated, based on approximate recurrent classes, should be macrostates, terminal states, etc. Also, unclear how to use pre-defined cluster-labels to define terminal states. For real-time data, would be nice to combine cluster labels with time annotations, to pick cells from a set of clusters, restricted to the last time points.

**Comment by michalk8** [comment]
closed via #607

**Comment by Marius1311** [comment]
Did you also implement the extra option to use time-point information, or did you skip that one? (just wondering)
