### ISSUE TITLE
Change default thresholding scheme for PseudoTime Kernel to be `soft`

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#613]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Makes more sense I think, works better usually and get nicer embedding projection.

**Comment by michalk8** [comment]
> works better usually

I will take a look at the benchmarks we did, but I remember hard threshold working better (at least in 1 of the benches) + there was this issue https://github.com/theislab/cellrank/issues/559

> get nicer embedding projection

I'd rather have a robust fix for #603 - I suspect that changes in the KNN graph violates some assumption with UMAP.

**Comment by Marius1311** [comment]
Ok, fine by me, let's close this then, and let's see what comes out of #603.
