### ISSUE TITLE
Installation of cellrank[krylov] dependencies fail in Mac OS M1 silicon 

### ISSUE THREAD

**Issue by EmilyMiddendorp** [theislab/cellrank#618]
Hi! I am trying to install cell rank on a MacBook M1 silicon. I am constantly getting an error because the dependencies (petsc, petsc4py, slepsc and slepsc4py) are not compatible with this processor. Does anyone know a wat around this or a version of the dependencies that will install in python 3.9?

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by michalk8** [comment]
Hi @EmilyMiddendorp ,

as far as I know there shouldn't be any specific problems with M1 (at least with PETSc). Could you please send me the full error log? Also, have you tried with a fresh environment?
If fresh env doesn't work, you could also try with pip as `pip install cellrank[krylov]`, or go through the [Dependencies](https://cellrank.readthedocs.io/en/stable/installation.html#dependencies) section in the docs; on Mac, it would be something like (though I have my doubts):
```bash
brew install open-mpi

pip install --user mpi4py

# intall petsc and petsc4py
pip install --user petsc 
pip install --user petsc4py

# install slepsc and slepsc4py
pip install --user slepc
pip install --user slepc4py
```
If that also doesn't work, the last thing to try would be to build PETSc/SLEPc from source - [pyGPCCA's installation docs for Mac](https://pygpcca.readthedocs.io/en/latest/installation.html#macos) may be useful in this case - e.g. in the CI, we build PETSc/SLEPc from source [here](https://github.com/msmdev/pyGPCCA/blob/main/.scripts/ci/install_dependencies.sh#L36).

**Comment by michalk8** [comment]
Simples way would be to run `pip instal cellrank[krylov] --ignored-installed`. And if this doesn't work, manually removing the package should do. To find the directory, simply run:
```bash
python -c "import llvmlite; from pathlib import Path; print(Path(llvmlite.__file__).parent)"
```
and then just remove it and try the installation again.

**Comment by michalk8** [comment]
Have you had any success with the installation @EmilyMiddendorp ?

**Comment by EmilyMiddendorp** [comment]
> Have you had any success with the installation @EmilyMiddendorp ?

Hi Michal, 

Unfortunately no. I tried uninstalling llvmite manually, but that did not allow to install CellRank and it gave me problems when running ScVelo. I am not really sure what the problem is anymore. I thought at first the Numba version problem that I had encountered before and I saw on the GitHub that other users as well but that was not it either. Any other tips you might have for me?

**Comment by michalk8** [comment]
> Any other tips you might have for me?

The only thing that comes to mind is to create a new conda environment and try to install the newest release as:
```bash
conda create python=3.8 --name cellrank3.8
conda activate cellrank3.8
which cellrank3.8  # to ensure current env is correctly loaded, e.g.: <some-path>/envs/cellrank3.8/bin/python
conda install -c conda-forge -c bioconda cellrank-krylov
```

**Comment by Marius1311** [comment]
Hi @EmilyMiddendorp, does this persist in CellRank 1.4, given @michalk8's hints from above?

**Comment by EmilyMiddendorp** [comment]
> Hi @EmilyMiddendorp, does this persist in CellRank 1.4, given @michalk8's hints from above?

Hi Marius, 

The problem still persists with CellRank 1.4. I tried all the hints from Michal again, all the dependencies are installed, but I still get the same llvmlite error.

**Comment by Marius1311** [comment]
@michalk8 I think your expertise is needed here.

**Comment by EmilyMiddendorp** [comment]
Hi! 

I have tried a couple of more things to install cell rank, but it seems that the issue is with llvmlite not being available for M1 silicone. I have tried installing it again and it seemed to work after installing brew install llvm@9. After that conda install llvmlite run without problem. However, installing CellRank with Conda gives me a compatibility error and with pip gives the same error as before. Any ideas?

**Comment by Marius1311** [comment]
Any idea @michalk8 ?

**Comment by EmilyMiddendorp** [comment]
Hi Marius, 

I also tried installing CellRank in a Linux server that we have (with python 3.9 as well). I got the same llvmlite error and all the same problems. But it was easily solved by uninstalling llvmlite and installing CellRank with Conda so I think that the problem is that there is no compatible version for the Conda installation with M1 silicon. Could that be the reason?

**Comment by michalk8** [comment]
Hi @EmilyMiddendorp ,
based on [this](https://github.com/numba/numba/issues/7071), `numba` should be available through `pip` M1 in 6-12 months, however, it should be available through conda. I'd try this:
1. create a fresh conda env
2. install numba first as `conda install -c numba numba` (might also try `conda install -c conda-forge numba` if the former doesn't work)
3. clone cellrank as `git clone https://github.com/theislab/cellrank` and `cd cellrank`
4. modify `requirements.txt` by removing the line with `numba>=0.51.0,<0.53.0`
5. run `pip install -e.` (to see if it can be installed without PETSc/SLEPc)
6. if 5. succeeds, try `pip install -e.'[krylov]'`, see also my above [comment](https://github.com/theislab/cellrank/issues/618#issuecomment-865329396) if problems arise

If this doesn't work, someone found a way to `pip` install `llvmlite`, but it's not really recommended/might not work, see https://github.com/numba/llvmlite/issues/693#issuecomment-844195477. The idea is as follows:
1. correctly export `LLVM_CONFIG` as described in the comment
2. install cellrank, either through pip (as `pip install cellrank` or `pip install 'cellrank[krylov]'`) or if that fails, through conda as seen in our [docs](https://cellrank.readthedocs.io/en/stable/installation.html#bioconda)

**Comment by EmilyMiddendorp** [comment]
> Hi @EmilyMiddendorp ,
> based on [this](https://github.com/numba/numba/issues/7071), `numba` should be available through `pip` M1 in 6-12 months, however, it should be available through conda. I'd try this:
> 
> 1. create a fresh conda env
> 2. install numba first as `conda install -c numba numba` (might also try `conda install -c conda-forge numba` if the former doesn't work)
> 3. clone cellrank as `git clone https://github.com/theislab/cellrank` and `cd cellrank`
> 4. modify `requirements.txt` by removing the line with `numba>=0.51.0,<0.53.0`
> 5. run `pip install -e.` (to see if it can be installed without PETSc/SLEPc)
> 6. if 5. succeeds, try `pip install -e.'[krylov]'`, see also my above [comment](https://github.com/theislab/cellrank/issues/618#issuecomment-865329396) if problems arise
> 
> If this doesn't work, someone found a way to `pip` install `llvmlite`, but it's not really recommended/might not work, see [numba/llvmlite#693 (comment)](https://github.com/numba/llvmlite/issues/693#issuecomment-844195477). The idea is as follows:
> 
> 1. correctly export `LLVM_CONFIG` as described in the comment
> 2. install cellrank, either through pip (as `pip install cellrank` or `pip install 'cellrank[krylov]'`) or if that fails, through conda as seen in our [docs](https://cellrank.readthedocs.io/en/stable/installation.html#bioconda)

YES!! The first solution worked out!! Thank you so much!

**Comment by michalk8** [comment]
> YES!! The first solution worked out!! Thank you so much!

Glad that if finally works. I think this can be closed now - if any other problems arise, simply open an issue.

**Comment by Marius1311** [comment]
Thanks a lot @michalk8 for digging into this! Really great work.

**Comment by EmilyMiddendorp** [comment]
Thank you both for all the help!
