### ISSUE TITLE
Speed up the computation of absorption probabilities

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#619]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Currently, when we want to compute absorption probabilities towards terminal macrostates, we select the N most confidently assigned cells per macrostate (by default, N=30) and we compute absorption probabilities towards them individually. Afterwards, we sum up absorption probabilities across all cells assigned to the same macrostates, to get one number per macrosate. However, this can be massively speed up by creating one pseudo-cell per macrostate which summarizes these N cells and computing absorption probabilities towards just these. Ignoring parallelisation, that's a speed up by factor N, i.e. 30 by default. 

to do's include
- make sure there are regression tests for absorption probabilities before changing anything. If we don't have any, add at least one. 
- implement the new routine based on the pseudo-cells
- make sure tests (esp. regression tests) pass

**Comment by michalk8** [comment]
closed via #638

**Comment by Marius1311** [comment]
Thanks @WeilerP, great work! I'm really glad this worked out so quickly, very well done!

**Comment by WeilerP** [comment]
@Marius1311, should the section *Computing fate probabailities* in the [kernel and estimators](https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html#Estimate-fate-probabilities) tutorial be updated? Or at least a note added that the comment *"did not select too many cells per terminal state when calling g.set_terminal_states_from_macrostates() or g.compute_terminal_states(). The default value is 30 cells per terminal state and this should be enough in most situations."* does no longer apply for `cellrank>=1.4`?

**Comment by Marius1311** [comment]
Nice catch! I'll update tutorials today anyways and will make the corresponding changes to this section.
