### ISSUE TITLE
Multi-flow plotting function

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#620]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Similar to our single-flow plotting function, only that this should be able to handle outgoing flow from several clusters by enforcing a tree-like structure.

**Comment by michalk8** [comment]
> Similar to our single-flow plotting function, only that this should be able to handle outgoing flow from several clusters by enforcing a tree-like structure.

Should this simply be a modification of the `plot_single_flow`, i.e. by adding some argument by which you pass the tree?
Or should it be like Fig. 7c in https://www.cell.com/cell/fulltext/S0092-8674(21)00439-6 - the 3D vein plot (would also need to pass the tree to limit the flow)?

**Comment by Marius1311** [comment]
Good question. Should we even compute the tree externally, or should it be computed internally when we call the plotting function? Also, how do the authors restrict the flow in their Fig. 7c, if at all?

**Comment by michalk8** [comment]
> Should we even compute the tree externally, or should it be computed internally when we call the plotting function? 

The tree requires prior knowledge, how do you want to compute it? I tought we'd just supplie, e.g. a dictionary defining the tree and nothing more (or a flat list of tuples, where we specify allowed outgoing flow).

> Also, how do the authors restrict the flow in their Fig. 7c, if at all?

By thresholding.

**Comment by Marius1311** [comment]
We can fit a Minimum Spanning Tree, that doesn't require any prior knowledge apart from maybe the root cluster, please check e.g. https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.minimum_spanning_tree.html

There's an option for this implemented in scanpy to get a filtered version of a PAGA graph which is a tree.

**Comment by michalk8** [comment]
@Marius1311 what's the priority for this? Also, I remember discussing the tree how to solve the missing directionality; maybe use directed PAGA?

**Comment by Marius1311** [comment]
- priority: let's do this soon as it's very similar to the single-flow plotting function and we can benefit from our previous work
- methodology: can we just do this by a set of rules? i.e. 
  - flows can only go from earlier to later time-points
  - if A -> B and B -> C and D, then there can be no flow from A -> C or D

Directed PAGA won't work for us here - it already needs a pseudotime an initial/terminal states, whereas we really want a kernel-level visualization function.

**Comment by michalk8** [comment]
@Marius1311 current progress:
![index](https://user-images.githubusercontent.com/46717574/125196759-89114600-e24a-11eb-8d2c-31d0752c1e8f.png)

Re horizntal lines, 2 problems:
- the smoothing with loess doesn't work (way to oversmooths, am fiddling with params/other functions), though I think non-smoothed values (in the plot above) are also fine
- it seems like the depth for each cluster is specified externally (I've set the depth to 1 for all) - in the original publication, they are located in `embflow/data/external_data/fig7_vein_parameters.txt`

Not sure how relevant are these for us, but I'd consider dropping the horizntal lines.

2nd sets of problems:
- how to limit the flow between clusters
- should we visualize direction in? in the above plot, some flows heavily overlap + large incoming/outgoing flows (close to 1) between 2 clusters in 1 time point will become almost indistinguishable (current, low alpha is start, high alpha is endpoint, as in the original `plot_single_flow`).

TODOs:
- optimal ordering
- deal with above issues
- clean code/abstract away

**Comment by Marius1311** [comment]
Let's talk about the details in a call today, see MM. In general, to check whether the function works, please use the Schiebinger data - it's a simpler process with fewer clusters and expected transitions.

**Comment by Marius1311** [comment]
Hi @michalk8, let's talk again about this later this week. Please switch to the Schiebinger data for this.

**Comment by michalk8** [comment]
closed in favor of #832
