### ISSUE TITLE
Enable computing driver genes towards combined lineages

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#622]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

I have three lineages, let's call them A, B, C and D. Lineage hierarchy: first A or (B, C, D), then B, C or D. I'm interested in finding driver genes for the first fate decision, i.e. A or (B, C, D). Ideally, I would like to be able to call
`g.compute_lineage_drivers(return_drivers=False, lineages=['A', 'B, C, D'])`, as we have it in some other parts of the code. However, that doesn't work here and I get `Key Error: ['B, C, D'] not in index`. Could we enable this behaviour?

**Comment by michalk8** [comment]
Thanks, this was a bug. Closed via #624 .
