### ISSUE TITLE
Add reprogramming data to `cr.datasets`

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#625]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

We'll need this for our real-time tutorial. @michalk8, could you prepare the method, I'll upload the data to figshare and fill in the details of the docstring? Thanks!

**Comment by michalk8** [comment]
closed via #631
