### ISSUE TITLE
Add proliferation and apoptosis gene sets to estimate growth rates

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#626]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

We need this for the external WOT kernel and for our real-time tutorial. @michalk8, could you prepare the abstraction/infrastructure for this please, I'll take care of finding the lists for the main model organisms.

**Comment by Marius1311** [comment]
@michalk8, from Schiebinger et al, Cell 2019, you should get 98 proliferation markers and 193 apoptosis markers.

**Comment by Marius1311** [comment]
For humans, use
- this [link](https://www.gsea-msigdb.org/gsea/msigdb/cards/HALLMARK_APOPTOSIS) for apoptosis genes (161 of them). 
- Following the [scanpy tutorial on the cell cycle](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/180209_cell_cycle/cell_cycle.ipynb), I would recommend to use [this list](https://www.dropbox.com/s/3dby3bjsaf5arrw/cell_cycle_vignette_files.zip?dl=1) for proliferation. The list comes from this paper (which we should cite): https://science.sciencemag.org/content/352/6282/189

For all of these, please make sure to cite the origin. In case of the first one, a link to the website should suffice.

**Comment by Marius1311** [comment]
With mouse and human covered, we should have enough for now. We can always add more later when we come across informative resources.

**Comment by michalk8** [comment]
closed via #630
