### ISSUE TITLE
Exchange links in tutorials using bibtex

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#639]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Do this for the old tutorials.

**Comment by michalk8** [comment]
closed via https://github.com/theislab/cellrank_notebooks/pull/35
