### ISSUE TITLE
Proportion of cells in terminal states biases absorbtion probability?

### ISSUE THREAD

**Issue by mtvector** [theislab/cellrank#643]
Hi there,
I have noticed that it seems like the probabilities are biased towards more common end states, which have been manually annotated, and I would like to know which transition cells are likely to give rise to rare end states. Is this true in your experience? If so, is there a way to renormalize the probabilities so that probabilities don’t “default to” the most common terminal states?
Thanks!

**Comment by Marius1311** [comment]
Hi @mtvector, if you know the terminal states in your system, I would recommend using GPCCA to compute macrostates and to manually assign some of them terminal status - that ensures the states actually have some level of metastability. By default, that uses the 30 most confidently assigned cells per state to compute absorption probabilities. We show how to do this e.g. in the [CytoTRACE tutorial](https://cellrank.readthedocs.io/en/stable/beyond_rna_velocity.html), but this works for every kernel (i.e. doesn't matter which kernel you used to compute your transition matrix.)

**Comment by mtvector** [comment]
So you're saying that calculating absorption probabilities after computing macrostates will have a different result from `set_final_states`?

Here's plots of what I'm talking about:
![image](https://user-images.githubusercontent.com/28308459/123862523-49a73900-d8dd-11eb-9c0f-c1c48cb9901e.png)
![image](https://user-images.githubusercontent.com/28308459/123862588-62afea00-d8dd-11eb-9f61-75d320d41d15.png)

Thanks for the fast response!

**Comment by Marius1311** [comment]
Hi @mtvector, yes, I think you should make sure that you have at least roughly the same number of cells per terminal state. The best way to do this is to use the GPCCA estimator to compute macrostates and then to manually or automatically annotate some of them as terminal. This will make sure you have the same number of cells per terminal state, and it will also make sure that you assign cells with high metastability to each state.

**Comment by mtvector** [comment]
Thanks for the explanation, I understand now! This makes sense to me.
