### ISSUE TITLE
Update bioconda to v1.4

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#650]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

...

**Comment by michalk8** [comment]
Related PR: https://github.com/bioconda/bioconda-recipes/pull/29348

**Comment by michalk8** [comment]
Done.
