### ISSUE TITLE
Add contributions section to the readthedocs page

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#651]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Similar to [pyGPCCA](https://pygpcca.readthedocs.io/en/latest/) and [scanpy](https://scanpy.readthedocs.io/en/latest/). We are three people now that contribute @michalk8 @WeilerP and we should make this visible in our docs.

**Comment by michalk8** [comment]
closed via #655
