### ISSUE TITLE
Bound `frac_to_keep` in hard thresholding pseudo-time scheme

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#659]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

## Description

The fraction of neighbors to keep when using the hard thresholding scheme in the `PseudotimeKernel` should be in the interval `[0, 1]`.

**Comment by WeilerP** [comment]
If we want more sophisticated type checks, we could, for example, use [pydantic](https://pydantic-docs.helpmanual.io/).

**Comment by michalk8** [comment]
> If we want more sophisticated type checks, we could, for example, use pydantic.

Looks nice, but it's only for types, right? Contracts might be nicer (i.e. to inspect whether `key` is present in `AnnData`, see [here](https://github.com/Parquery/icontract).

closed via #660
