### ISSUE TITLE
Option to run without MPI

### ISSUE THREAD

**Issue by demuellae** [theislab/cellrank#661]
Hi,
I am trying to run cr.tl.terminal_states and receive the error message below. The error seems linked to OpenMPI and not directly to cellrank.  I still though I'd ask: Is it possible to deactivate OpenMPI for running this function?

 OPAL ERROR: Unreachable in file pmix3x_client.c at line 112
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
  PMI-2 support. SLURM builds PMI-1 by default, or you can manually
  install PMI-2. You must then build Open MPI using --with-pmi pointing
  to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

**Comment by michalk8** [comment]
Hi @demuellae ,
you should be able to use the following:
```python
cr.tl.terminal_states(..., fit_kwargs={"method": "brandts"})
```
Note that this will dramatically slow down computation of the Schur decomposition and works only on dense matrices.
For computing absorption probabilities, you can run:
```python
cr.tl.lineages(..., use_petsc=False)
```
This will use `scipy` sparse/dense solvers under the hood, but will also most likely be slower than PETSc.

**Comment by michalk8** [comment]
I believe this can be closed - the above should not use MPI in any way; feel free to re-open.
