### ISSUE TITLE
How can I get quatitative measurements of wk.plot_single_flow

### ISSUE THREAD

**Issue by haikuol** [theislab/cellrank#662]
...
Hello!

I am following the tutorial of time series datasets.
At one step it runs 'wk.plot_single_flow' and generates a figure.
Although the cell flow visualization is very informative, I am not sure about the meaning of the flow. Does the width of a flow indicate the proportion of cell A that will become cell B later?
Insteading of just visualizing it, how can I get the exact width of a flow?

Thanks in advance!

**Comment by Marius1311** [comment]
Hi @haikuol, thanks for your question. You're right, the width of a flow corresponds to the amount of mass that flows from cluster A to B at time point t. This plotting function is meant to give you a qualitative overview of your dataset - it's not meant to be quantitative. In general, cellrank uses `kernels` to compute transition matrices and to visualize them and `estimators` to do (quantitative) inference based on them. So in short:
- kernels: qualitative visualization
- estimators: quantitative inference

Please go through the [kernels and estimators](https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html) tutorial to learn more.

**Comment by michalk8** [comment]
I believe this question has been answered by Marius, feel free to reopen if anything else arises.
