### ISSUE TITLE
Prettify our tutorials

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#663]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Try jupytex to prettify our tutorials.

**Comment by WeilerP** [comment]
[MyST Markdown](https://myst-parser.readthedocs.io/en/latest/) can be used to add e.g. colored boxes with content. The [Jupyter Book](https://jupyterbook.org/intro.html) docs show quite a few example on how to use MyST Markdown and other features.

**Comment by Marius1311** [comment]
This will go into a later release. @WeilerP, can you add this to the release schedule for a later release?

**Comment by Marius1311** [comment]
This is important; you can generate nice colorful boxed both in markdown as well as in jupyter notebooks, see two scVi-tools examples below:
![Screenshot 2022-06-21 at 14 16 15](https://user-images.githubusercontent.com/24494650/174796844-efcf015d-f74c-4787-a9cb-6187377dfe10.png)
Pretty boxes in jupyter

![Screenshot 2022-06-21 at 14 16 47](https://user-images.githubusercontent.com/24494650/174796934-bd4ea97a-88d6-4dd0-a1d0-e620c272207c.png)
Pretty boxes in markdown.

**Comment by Marius1311** [comment]
done, we have beautiful tutorials now.
