### ISSUE TITLE
plot_random_walks AttributeError

### ISSUE THREAD

**Issue by TSun-tech** [theislab/cellrank#666]
...
Dear CellRank team,
I am trying to run the plot random walks example with the jupyter notebook script example, but has received an AttibuteError as following:
![image](https://user-images.githubusercontent.com/54978093/125604933-e302eadd-0bdc-4a7c-9cab-de1e138e23da.png)
May I ask how can I fix it? 
Thanks a lot in advance!

**Comment by michalk8** [comment]
Hi @TSun-tech,

unfortunately, I wasn't able to reproduce this using the below code:
```python
import cellrank as cr
adata = cr.datasets.pancreas_preprocessed()
k = cr.tl.transition_matrix(adata)
print(type(k))  # make sure it's the correct type
k.plot_random_walks(10)
```

Could you please post the output of:
```python
import cellrank as cr
cr.logging.print_version_and_date()
```
and your Python version?

**Comment by Marius1311** [comment]
Hi @TSun-tech, this is a bug - please select `bug` rather than `question` next time when opening an issue, then you will get another template and we will automatically check for the info we need. Only this way, we can ensure efficient debugging. Thanks!

**Comment by TSun-tech** [comment]
> Hi @TSun-tech,
> 
> unfortunately, I wasn't able to reproduce this using the below code:
> 
> ```python
> import cellrank as cr
> adata = cr.datasets.pancreas_preprocessed()
> k = cr.tl.transition_matrix(adata)
> print(type(k))  # make sure it's the correct type
> k.plot_random_walks(10)
> ```
> 
> Could you please post the output of:
> 
> ```python
> import cellrank as cr
> cr.logging.print_version_and_date()
> ```
> 
> and your Python version?

Hi @michalk8 ,

My python is at version 3.8.8 and with CellRank 1.2.0.

**Comment by TSun-tech** [comment]
> Hi @TSun-tech, this is a bug - please select `bug` rather than `question` next time when opening an issue, then you will get another template and we will automatically check for the info we need. Only this way, we can ensure efficient debugging. Thanks!

Roger that, Sorry for the confusion...I was not sure if this is really a bug or my insufficient coding skill.

**Comment by michalk8** [comment]
@TSun-tech seems like you have an older version of CellRank. `plot_random_walks` was introduces in version `1.3.0` (current one is `1.4.0`), so you need to upgrade it as e.g. using `pip` as:
```bash
pip install --upgrade cellrank
```
For more info, please see the [installation instructions](https://cellrank.readthedocs.io/en/stable/installation.html).

**Comment by TSun-tech** [comment]
> @TSun-tech seems like you have an older version of CellRank. `plot_random_walks` was introduces in version `1.3.0` (current one is `1.4.0`), so you need to upgrade it as e.g. using `pip` as:
> 
> ```shell
> pip install --upgrade cellrank
> ```
> 
> For more info, please see the [installation instructions](https://cellrank.readthedocs.io/en/stable/installation.html).

@michalk8 
Problem solved! 
Thank you so much!
