### ISSUE TITLE
Embedding projection for non-knn based kernels

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#668]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

## Description

#665 fixes the embedding projection for knn based kernels. However, the fix restricts the method to only these kernels. As already discussed in #603, the (original) embedding projection did not work correctly for `WOTKernel`. As outlined [here](https://github.com/theislab/cellrank/issues/603#issuecomment-877067538) in #603, using the originally implemented projection on the on reprogramming data from Schiebinger et al., Cell 2019 leads to 

<img width="393" alt="original" src="https://user-images.githubusercontent.com/28675704/126062791-489d07ea-99e5-40b6-bb7f-44027c13a8d9.png">

Omitting the random uniform correction term leads to improved results:

<img width="390" alt="wo_random_uniform" src="https://user-images.githubusercontent.com/28675704/126062813-644ef95c-128e-46a7-8d85-3fdc82a7f108.png">

This is also true when weighing by inverse connectivities:

<img width="385" alt="w_weighted_conns" src="https://user-images.githubusercontent.com/28675704/126062825-46e6b83d-7373-41e8-a7f0-a6a4ff1e66aa.png">

As discussed [here](https://github.com/theislab/cellrank/issues/603#issuecomment-877067538), results look not as promising for the `PseudoTimeKernel`.

**Comment by Marius1311** [comment]
Thanks for opening this issue! We may make some progress here using the optimization approach Ruslan suggested.

**Comment by WeilerP** [comment]
> Thanks for opening this issue! We may make some progress here using the optimization approach Ruslan suggested.

Yes! I opened the issue before I read the email. Will look into it.

**Comment by michalk8** [comment]
> Thanks for opening this issue! We may make some progress here using the optimization approach Ruslan suggested.

Doesn't the suggested optimization approach solve only the problem of: `P_{i, j} uniform => proj_vec = (0, 0)` and not the non-KNN based projection (i.e. WOT case), or am I missing something?
Also, 1 idea I had to achieve `(0, 0)` projection if uniform is to scale the vector by `scale = 1 - (entropy(probs, base=2) / np.log2(len(probs)))`.

**Comment by Marius1311** [comment]
In your last comment, @michalk8, you mean achieving this for non-KNN based graphs? Because we know how to do it for KNN- based graphs, our current implementation takes care of that already. You can check that for 0-velocity vector, the current implementation will give a zero vector in the embedding.

**Comment by Marius1311** [comment]
@WeilerP, if I remember correctly, we wanted to look at this for at least 1 other non-KNN based projection before making a decision on this.

**Comment by WeilerP** [comment]
@Marius1311, @michalk8, I think we can close is. We tried the `WOTKernel` on the the erythroid branch of the mouse gastrulation data by [Pijuan-Sala et al.](https://www.nature.com/articles/s41586-019-0933-9) where it did not work.
ATM, we check in `compute_projection` whether or not a connectivity matrix exists [here](https://github.com/theislab/cellrank/blob/889a6612ce30ca17011b9081d686ce6838faa252/cellrank/tl/kernels/_base_kernel.py#L301-L306). Do you think this suffices or should we be more specific and explicitly exclude the case of non-knn based methods (e.g. through a class attribute acting as a flag)?

**Comment by WeilerP** [comment]
> > I think that's okay for now. If there's no connectivity matrix, the kernel isn't KNN based, hence the current projection won't work.
> 
> But what about combined kernels, e.g. `0.9 * WOTKernel + 0.1 ConnectivityKernel`? In this case, there will be a connectivity matrix but the projection will (most likely) be off.

@michalk8, any thoughts on this? Or do you agree with @Marius1311 s.t. we can close the issue?

**Comment by michalk8** [comment]
closed via #733
