### ISSUE TITLE
Unable to plot fate map

### ISSUE THREAD

**Issue by CromitDolores0808** [theislab/cellrank#670]
The terminal states and initial states work perfectly. But here is another error below. Thanks.

```python
cr.pl.cluster_fates(adata, mode="bar",save='NEU_bar.png')
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/miniconda3/lib/python3.7/site-packages/cellrank/pl/_cluster_fates.py", line 468, in cluster_fates
    raise KeyError(f"Lineage key `{lk!r}` not found in `adata.obsm`.")
KeyError: "Lineage key `'to_terminal_states'` not found in `adata.obsm`."
pkurun: error: c07b04n02: task 0: Exited with exit code 1

<!-- Put your error output in the block below (if applicable, else delete the block): -->
```pytb
...
```

#### Versions:

> ...cellrank==1.4.0+g0d8747d scanpy==1.8.1 anndata==0.7.5 numpy==1.17.4 numba==0.52.0 scipy==1.5.4 pandas==1.3.0 pygpcca==1.0.2 scikit-learn==0.24.2 statsmodels==0.11.0rc2 python-igraph==0.8.3 scvelo==0.2.3 pygam==0.8.0 matplotlib==3.4.2 seaborn==0.11.1

**Comment by michalk8** [comment]
Hi @CromitDolores0808 ,
it seems like that there's no key in `adata.obsm['to_terminal_states']`, i.e. they haven't been computed using `cr.tl.lineages(adata, backward=False, ...)`.
Maybe you're trying to plot the initial states? if that's the case, `cr.pl.cluster_fates(adata, backward=True, mode="bar",save='NEU_bar.png')`, should do the trick. If not, could you please post the output of `print(adata)` and maybe also the CellRank functions you ran before?

**Comment by michalk8** [comment]
I'm assuming this has been resolved, feel free to open if not.
