### ISSUE TITLE
Make `start_ixs` more flexible in `plot_random_walks`

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#680]
## Description

The kernel method `plot_random_walks` accepts the argument `start_ixs` to set starting cells for the random walks. This only works on categorical columns, however. When working with pseudo-times, you do not have categories. Instead, the cells with a pseudo-time below a certain threshold are considered to be starting cells. It'd be good if `plot_random_walks` could handle such cases as well.

**Comment by Marius1311** [comment]
We could use either a range or a percentile, what do you guys think?

**Comment by WeilerP** [comment]
Why not both? We could do `range` (temporally speaking), `precentile` and number of cells assigned the lowest pseudo-time (`n_early_cells`?). By default, the arguments would be `None` and only one can be set.

**Comment by Marius1311** [comment]
I wouldn't over-complicate and go for max. 2 options.

**Comment by michalk8** [comment]
closed via #691 (I've settled for range instead of percentile)
