### ISSUE TITLE
Refactor code to fix `FutureWarning` from `anndata`

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#681]
## Description

During testing, `anndata` throws the following `FutureWarning` in `tests/test_kernel.py`

```pytb
FutureWarning: During AnnData slicing, found matrix at .uns['velocity_graph'] that happens to be dimensioned at n_obs×n_obs (200×200). These matrices should now be stored in the .obsp attribute. This slicing behavior will be removed in anndata 0.8.
```

See, for example, the testing stack trace in [this](https://github.com/theislab/cellrank/runs/3118375279?check_suite_focus=true) CI run.

**Comment by michalk8** [comment]
closed via #692
