### ISSUE TITLE
Speed up testing in CI

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#684]
## Description

This is a rather generic issue with the goal to speed up the testing step in the CI.

**Comment by WeilerP** [comment]
@michalk8, I checked again and the runtime of the CI: (ubuntu-latest, 3.7) and (mac-os, 3.8) take roughly 15 minutes, (ubuntu-latest, 3.8) takes over half an hour. Is the reason for this that we download and check the datasets in the latter case? If so, wouldn't it suffice to only check this when we change one of the functions downloading the datasets, on the cron job and before a new release (in this case just to ensure everything is working)?

**Comment by WeilerP** [comment]
Also possibly related is this `RuntimeWarning` by `matplotlib` in `tests/test_plotting.py::TestGeneTrend::test_transpose_all_models_for_1_lineage_failed_same_plot`:

```pytb
RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory.
```

**Comment by WeilerP** [comment]
We should also check if using a `lil_matrix` in `tests/test_utils.py` speeds things up:

```pytb
SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
```

**Comment by michalk8** [comment]
> @michalk8, I checked again and the runtime of the CI: (ubuntu-latest, 3.7) and (mac-os, 3.8) take roughly 15 minutes, (ubuntu-latest, 3.8) takes over half an hour. Is the reason for this that we download and check the datasets in the latter case?

Nope, it's the PETSc/SLEPc installation in that case (takes 14 minutes, testing takes 12 minutes).
In `pygppca`, I cache the `.tox` dir [here](https://github.com/msmdev/pyGPCCA/blob/main/.github/workflows/ci.yml#L123), so we should do this here once `tox` is used for CI as well.
Afaik I've tried to make PETSc/SLEPc work on Mac as well with the cache, but because of 1 extra step (manually building it from source and dynamically linking some stuff), the cache breaks things - however, we should revisit this (maybe I made some mistake).

**Comment by michalk8** [comment]
Running the tests locally as ``pytest --durations=0``, I got:
```bash
286.85s call     tests/test_kernels.py::TestKernel::test_transition_forward_stoch_high_lvl
192.32s call     tests/test_kernels.py::TestKernel::test_precomputed_from_kernel
187.26s call     tests/test_kernels.py::TestKernel::test_precomputed_adata_origin
184.72s call     tests/test_kernels.py::TestKernel::test_precomputed_different_adata
162.80s call     tests/test_kernels.py::TestKernel::test_row_normalized_dense_norm_stoch
136.27s call     tests/test_kernels.py::TestKernel::test_manual_combination_stoch
63.83s call     tests/test_kernels.py::TestMonteCarlo::test_mc_and_second_order_fwd
58.77s call     tests/test_datasets.py::TestDataSet::test_lung
51.35s call     tests/test_datasets.py::TestDataSet::test_pancreas_preprocessed
39.54s call     tests/test_kernels.py::TestKernel::test_kernel_reads_correct_connectivities[None-ConnectivityKernel]
33.93s call     tests/test_kernels.py::TestMonteCarlo::test_mc_and_mc_fwd_10k
28.87s call     tests/test_kernels.py::TestKernel::test_kernel_reads_correct_connectivities[None-VelocityKernel]
25.52s call     tests/test_datasets.py::TestDataSet::test_pancreas
22.35s call     tests/test_plotting.py::TestHeatmap::test_heatmap_genes
20.25s call     tests/test_plotting.py::TestHeatmap::test_heatmap_genes_1_gene_failed
19.46s call     tests/test_external.py::TestWOTKernel::test_last_time_point[connectivities]
18.08s call     tests/test_kernels.py::TestKernel::test_kernel_reads_correct_connectivities[None-PseudotimeKernel]
13.34s call     tests/test_plotting.py::TestHeatmap::test_heatmap_cmap
11.99s call     tests/test_plotting.py::TestHeatmap::test_heatmap_abs_probs_genes
11.92s call     tests/test_plotting.py::TestGeneTrend::test_transpose_all_models_for_1_gene_failed
11.71s call     tests/test_plotting.py::TestGeneTrend::test_trends_perc
11.65s call     tests/test_plotting.py::TestGeneTrend::test_trends_time_key_del_latent_time
11.57s call     tests/test_plotting.py::TestGeneTrend::test_trends_suptitle
11.55s call     tests/test_plotting.py::TestGeneTrend::test_trends_time_range
11.42s call     tests/test_kernels.py::TestMonteCarlo::test_mc_and_mc_fwd_1k
11.27s call     tests/test_plotting.py::TestHeatmap::test_heatmap_no_cbar_genes
10.99s call     tests/test_plotting.py::TestGeneTrend::test_trends_time_key
10.00s call     tests/test_plotting.py::TestGeneTrend::test_trends_gene_no_legend
```
