### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#685]
## Description

With Python 3.6 being rather old, we can stop supporting it.

**Comment by michalk8** [comment]
Mostly related to 2 things:
- pickling an `estimator`
- usage of `Literal` from `typing_extensions`

**Comment by michalk8** [comment]
closed via #693

**Comment by Marius1311** [comment]
Update installation instructions (still says 3.6 is okay)

**Comment by Marius1311** [comment]
At least on master, not sure whether you updated here. Just as a reminder.
