### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#687]
## Description

The unit tests currently cover about 88% of the code base. While this is already quite a bit, we should increase it even further. From skimming the coverage report, I'd say we need to add unit tests for functions/code parts in `cellrank/tl/_cflare.py`, `cellrank/tl/_utils.py`, `cellrank/ul/models/_utils.py`, `cellrank/pl/_circular_projection.py`.

**Comment by Marius1311** [comment]
This is pretty generic, should we close for now @michalk8  @WeilerP ?
