### ISSUE TITLE
Latest release notes in docs

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#688]
## Description

ATM, the latest release notes are not listed in the section *Release Notes* on the ReadTheDocs page but only on the landing page. This is a bit counter intuitive. The detailed change log which is currently only on the landing page should be visible in the *Release Notes* section as well.

**Comment by WeilerP** [comment]
@Marius1311, I think it'd suffice to show a less detailed change log on the landing page to showcase the highlights of the release in some bullet points. Seems a bit cleaner and clearer to me. We can always link to the release notes section for more details. What do you think?

**Comment by michalk8** [comment]
Re release notes: currently, I have no preference, though the idea was to have the latest one always on the landing page since they are the most relevant.
Also, I hate writing them, we should look into e.g. https://github.com/twisted/towncrier

**Comment by Zethson** [comment]
Or you use https://github.com/release-drafter/release-drafter

If interested ping me for a config.

**Comment by WeilerP** [comment]
> Re release notes: currently, I have no preference, though the idea was to have the latest one always on the landing page since they are the most relevant.

Agreed, just think that they do not need to go into such detail on the landing page. To make things easier and speed up writing the release notes we can always add some kind of label to PRs we want to mention in the release notes. This should also be compatible with @Zethson's suggestion.

**Comment by michalk8** [comment]
> Or you use https://github.com/release-drafter/release-drafter
> 
> If interested ping me for a config.

Thanks for the suggestion, will take a look. Quick question: can it also output `.rst` files - was thinking of embedding them in the docs.

**Comment by Zethson** [comment]
> > Or you use https://github.com/release-drafter/release-drafter
> > If interested ping me for a config.
> 
> Thanks for the suggestion, will take a look. Quick question: can it also output `.rst` files - was thinking of embedding them in the docs.

Not that I am aware of, but would be interesting.

**Comment by michalk8** [comment]
closed via #690
