### ISSUE TITLE
Passing `weight_connectivities=0` to `tl.transition_matrix` reverts to default?

### ISSUE THREAD

**Issue by adamgayoso** [theislab/cellrank#702]
Shouldn't the printed kernel be 100% `VelocityKernel` in this case?

```
kernel = cr.tl.transition_matrix(adata, mode="deterministic", gene_subset=velo_genes, weight_connectivites=0)
print(kernel)
((0.8 * <VelocityKernel>) + (0.2 * <ConnectivityKernel>))
```

Version: '1.3.1'

**Comment by michalk8** [comment]
> Shouldn't the printed kernel be 100% VelocityKernel in this case?

Yes, and it does, you have a small typo there `weight_connectivites -> weight_connectivities`.
Also, I'd recommend using the "lower" level API (this will be removed in `2.0`) + upgrading to `1.4`.

**Comment by adamgayoso** [comment]
Shouldn't passing an argument with a typo in the param name raise some kind of error?

**Comment by Marius1311** [comment]
That's a good point. @michalk8, is that related to using the high level API?

**Comment by Marius1311** [comment]
In any case, we should raise an exception in such a case, it leads to unexpected behaviour.

**Comment by Marius1311** [comment]
Any update here @michalk8 ?
