### ISSUE TITLE
No release notes for 1.4

### ISSUE THREAD

**Issue by adamgayoso** [theislab/cellrank#703]
I can't seem to find the release notes for v1.4 on the docs page.

https://cellrank.readthedocs.io/en/stable/release_notes.html

**Comment by adamgayoso** [comment]
Actually it's on the latest version (not default):

https://cellrank.readthedocs.io/en/latest/release/notes-1.4.0.html

**Comment by michalk8** [comment]
> Actually it's on the latest version (not default):

Yes, previously (by design), they were only shown on the index page [here](https://cellrank.readthedocs.io/en/stable/#latest-additions).
Will hijack this issue to figure out how to use `towncrier` to have even the smallest news fragments rendered in the docs.

**Comment by Marius1311** [comment]
@adamgayoso, we're in the process of switching to `towncrier` to automaticaly render our release notes from the set of PRs associated with a particular release. @michalk8 is taking care of that.

**Comment by michalk8** [comment]
closed via #708 - #712 (seems to finally work).
