### ISSUE TITLE
Docs overhaul

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#706]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

With the deprecations of #677 and #688, we should make sure to update the docs accordingly (possibly also the tutorials).

**Comment by Marius1311** [comment]
Good initiative!
