### ISSUE TITLE
Edit on GitHub button not working for kernels and estimators

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#715]
The _Edit on GitHub_ button doesn't seem to work on the docs for kernels and estimators (e.g. [here](https://cellrank.readthedocs.io/en/stable/api/cellrank.tl.kernels.VelocityKernel.html) or [here](https://cellrank.readthedocs.io/en/stable/api/cellrank.tl.estimators.GPCCA.html)).

#### Versions:

> cellrank==1.4.0

**Comment by michalk8** [comment]
Can we also close this? From my side, there are not plans of reintroducing this and/or fixing it on current master (pointless with a new release behind the corner).

**Comment by WeilerP** [comment]
But shouldn't we fix it in the new release? Or do you think it is pointless since it's being deprecated and removed in the near future (removed in the sense of `tl/kerenels` replaced by `kernels/`)?

**Comment by michalk8** [comment]
> But shouldn't we fix it in the new release? Or do you think it is pointless since it's being deprecated and removed in the near future (removed in the sense of tl/kerenels replaced by kernels/)?

This doesn't affect only `kernels` and `estimators`, but all auto-generated `.rst` files (try [here](https://cellrank.readthedocs.io/en/stable/api/cellrank.pl.cluster_fates.html#cellrank.pl.cluster_fates)) - that's why there's the `[source]` button instead (should've removed this earlier).

**Comment by WeilerP** [comment]
Ah, so what you are saying is that with the new release, the *Edit on GitHub* button will disappear all together and we will only have the *source* button? Then yes, let's close this!
