### ISSUE TITLE
Edit on GitHub button on latest docs

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#716]
## Description

The latest docs do not show the _Edit on GitHub_ button. @michalk8, is this intentional or can the button be shown as well to easily move to the corresponding code on `cellrank@dev`?

**Comment by michalk8** [comment]
I've intentionally removed removed it since fixing it isn't worth the effort (the `[source]` button achieves the same and is reliable).
Unless you want to reintroduce it, I'd close this.

**Comment by WeilerP** [comment]
Yes, happy to close this one but think everything should work in the case of #715. We can continue discussing it there.
