### ISSUE TITLE
WOTKernel changes time key to categorical

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#722]
## Description

When instantiating the `WOTKernel`, the data type of the time key column in `adata.obs` is transformed into categorical. Is this necessary? Or is this done automatically by `wot`? If the data type was originally `float`, for example, all scatter plots before the instantiation can be colored nicely using e.g. the viridis colormap. After instantiation, each category is assigned a random color when first plotting the data.

**Comment by michalk8** [comment]
Afaik no, WOT doesn't require it, it's our requirement in `ExpTimeKernel`, since it really should be categorical (if it already isn't) + makes some operations easier.
As far as the colors go, we can update it [here](https://github.com/theislab/cellrank/blob/master/cellrank/tl/kernels/_exp_time_kernel.py#L64), though personally, I'd use `gnuplot` as the colormap there).

**Comment by WeilerP** [comment]
The problem is the following: I ran WOT on the Erythroid branch of the mouse gastrulation data from [Pijuan-Sala *et al.*](https://www.nature.com/articles/s41586-019-0933-9), for example. Prior to instantiating the `WOTKernel`, the UMAP embedding looks as follows, i.e. you can nicely see the temporal evolution:

<img width="405" alt="pre_wot" src="https://user-images.githubusercontent.com/28675704/130089560-0635cfca-a268-4716-b9fc-2fd2cd0f6fa4.png">

After instantiation, this is lost since the colors assigned appear to be random:

<img width="352" alt="post_wot" src="https://user-images.githubusercontent.com/28675704/130089870-b305374f-d368-41e5-a213-8f607eca24dd.png">

I think defining `TIME_KEY_colors` in `adata.uns` using a continuous color map when converting to categorical would be good.

**Comment by michalk8** [comment]
closed via 14c8db0 (sorry I didn't make a PR, forgot and was lazy to fix it).
