### ISSUE TITLE
Update package requirements

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#728]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

With `scvelo==0.2.4` released, we can unpin the upper bound on `numba`. This applies both for the CellRank repo on GitHub and on bioconda.

**Comment by WeilerP** [comment]
@michalk8, I opened #729. Do you want to take care of bioconda once `cellrank==1.5.0` is released?

**Comment by michalk8** [comment]
> @michalk8, I opened #729. Do you want to take care of bioconda once cellrank==1.5.0 is released?

Sure, I will take care of it.
closed via #729
