### ISSUE TITLE
Is adata.obsm["to_terminal_states"] a probability? Or a p-value?

### ISSUE THREAD

**Issue by jeremymsimon** [theislab/cellrank#758]
My dataset contains multiple samples, and we'd like to compare the mean probabilities of each sample to differentiate into one of the terminal states. The values look as we'd expect using `adata.obsm["to_terminal_states"]` with the only difference in our logic being that these could represent p-values as opposed to probabilities themselves. 

Can you please clarify what these values actually are? I want to make sure we interpret our results correctly.

Thanks!

**Comment by michalk8** [comment]
> Can you please clarify what these values actually are? I want to make sure we interpret our results correctly.

The values in ``adata.obsm["to_terminal_states"]`` are absorption probabilities (as defined in the Markov chain theory), not p-values.

**Comment by Marius1311** [comment]
@jeremymsimon, feel free to consult our [preprint](https://www.biorxiv.org/content/10.1101/2020.10.19.345983v2), especially the Online Methods for further details.
