### ISSUE TITLE
Lineage class and consolidation of cluster representations with scanpy

### ISSUE THREAD

**Issue by ivirshup** [theislab/cellrank#759]
From an earlier discussion with @Marius1311, I was wondering about the implementation of the lineage class and if we could do some consolidation with scanpy.

### Scanpy consolidation

It would be great to have a consistent way of representing a clustering (and fuzzy clustering) which keeps names and colors associated with the categories in scanpy,  and generally across the ecosystem (see also https://github.com/theislab/scanpy/issues/1832). The way we currently associate these (using keys in `uns`) has more indirection than I'd like. It would also be great to have support for plotting more kinds of categorical representations available in the base package (like fuzzy or multilabel clusterings).

### Implementation

Why subclass an ndarray if it's implemented as a wrapper? There are a number of assumptions about numpy arrays (e.g. their memory representation and the operations available) may cause issues. For example, this implementation precludes a sparse encoding for the groupings.

If the goal is simply to put labels and some metadata on an array, could using a `xarray.DataArray` be more straight forward? This could also make storage in the anndata object easier.

**Comment by Marius1311** [comment]
@michalk8, do you want to proceed with this in some way, or can we close this?
