### ISSUE TITLE
Combining kernels, only addition is supported?

### ISSUE THREAD

**Issue by dawe** [theislab/cellrank#765]
Hi all, I am testing multiple kernels on the same data and I'd like to combine them. As far as I understand, kernels can only be combined as weighted sums (i.e. aK<sub>1</sub> + bK<sub>2</sub>, a > 0, b>0) I'd like to know if more complex operations can be done. How combination works? Is it just a weighted sum of the transition matrices?

**Comment by Marius1311** [comment]
Thanks for @michalk8 for the explanations! Just adding one point from my side: weighted sums and reverting the directionality of the data has been tested many times on real data by us and others and works well. Re the other operations @michalk8 mentioned, in particular, the `^` operator, this is experimental, so be careful.
