### ISSUE TITLE
`.set_approx_rcs` improvements

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#77]
It would be nice if `.set_approx_rcs` would have an option `add_to_existing: bool = True`, where
- True: the new recurrent classes are added to the existing. If a dict is passed, this should be easy, as we can expect to only get indices of recurrent states. If a series is passed, I would ignore Nan's, i.e. not override previously recurrent classes as transient, but only add more recurrent classes
- False: current behaviour.

**Comment by michalk8** [comment]
So you want a union if I understand it correctly.

**Comment by Marius1311** [comment]
Yes, I would like an option for a union, exactly.

**Comment by michalk8** [comment]
Done via #78.
