### ISSUE TITLE
Using CellRank for inferring trajectories of non-disease to disease cell states

### ISSUE THREAD

**Issue by aanchalsharma833** [theislab/cellrank#771]
...
I am trying to run CellRank for one of the publicly available datasets in Alzheimer's disease space. I have the single cell profiles of two cell states, disease and "non-disease" (based on certain markers), from same patient across 8 samples. I did basic processing of the data including: QC, normalization, integration and clustering and was able to get different clusters of cells. Going ahead, for one of the clusters of excitatory neurons, cluster1, which has mix of both diseased and non-disease cells (highlighted in red square in image below), I was wondering if there exists some trajectory between two states and if it could be inferred it using cellRank . 
![clusters](https://user-images.githubusercontent.com/64595682/140567594-5d954b34-248d-4c9e-a573-d2a3cf0d9966.jpg)

I followed the 'cellRank beyond RNA velocity' tutorial and could get it working for my data. But I have few doubts/questions:

1) As per experts in this field it seems reasonable to assume that the cells, although marked as two distinct states, will have some transition states in between going from non-disease to disease and hence I am attempting to infer the trajectory here. Would CellRank work in such a scenario?

2) The labelling of disease and non-disease cells seem to be swapped as seen in the image below. Disease cells appear to be more than non-disease in this image compared to the image above.

3) Based on the eigenvalues plot (image below), I am unsure if any macro states exist at all. Since there appears to be an eigengap before and after 1 and 2 eigenvalues, could I attempt to calculate two macro states?

![CellRank](https://user-images.githubusercontent.com/64595682/140567578-4f70bb69-f33c-479d-9c40-6e3e48de62da.jpg)

Any insight would be very helpful! Thanks in advance.

**Comment by Marius1311** [comment]
@michalk8, could you help with the second quetion please?

**Comment by michalk8** [comment]
> @michalk8, could you help with the second question please?

I'd need to know the following:
```python
key = ...  # key in adata.obs where the disease/non-disease is stored
print(adata.obs[key].value_counts())  # does it match original (i.e not swapped?)
print(adata.obs[key].cat.categories)
print(adata.uns[f"{key}_colors"])
```
Also, which unction you're using to plot the left figure in `3.`?

**Comment by aanchalsharma833** [comment]
> @aanchalsharma833, re question 1, yes, if there's a continuous trajectory between the two states, then CellRank can be applied. However, if there is only one terminal population (disease within cluster 1), you know your initial and terminal state and the direction is clear (non-disease -> disease), I'm not sure what CellRank can give you as it's really about modeling fate decisions. If you're only interested in computing a pseudotime, there are simpler methods that do this for you like [DPT](https://scanpy.readthedocs.io/en/latest/generated/scanpy.tl.dpt.html#scanpy.tl.dpt).
> 
> If you give me a bit more info on what you're actually trying to learn from this data, I can tell you more about how you can apply CellRank.

Thanks @Marius1311 for your reply. Although I know the two states here, disease and non-disease, but I am interested in: 

- calculating transition probabilities for non-disease cells. I am hoping this might give some idea whether they are headed towards disease path OR its just a population of cells which is not susceptible and will/was not meant to develop disease. In other words, to get an idea whether development of this phenotype is is a gradual process or matter of susceptibility. 

- In case its a gradual process, then identifying any transition states and genes driving this shift. 

Hypothesis is that, some of the non-disease cells might have begun the process to be diseased or some of the disease cells might still be in the early stages, so clubbing all the non-disease cells as starting point (defining as root - a requirement for most of the tools around) might not be a good way to approach the problem. I tried using Monocle3 for my data, but I got a very complicated trajectory  multiple branches culminating into a loop). Hence thought of giving CellRank (CytoTrace) a try where prior information is not needed. 

Please correct me if the thought process is not making sense.

**Comment by aanchalsharma833** [comment]
> > @michalk8, could you help with the second question please?
> 
> I'd need to know the following:
> 
> ```python
> key = ...  # key in adata.obs where the disease/non-disease is stored
> print(adata.obs[key].value_counts())  # does it match original (i.e not swapped?)
> print(adata.obs[key].cat.categories)
> print(adata.uns[f"{key}_colors"])
> ```
> 
> Also, which unction you're using to plot the left figure in `3.`?

@michalk8 , My apologies for the confusion regarding 2. point. There was mix up of the numbers between different clusters. The labelling is not swapped.

Regarding left plot in 3. I used following:

```

# Compute & visualize a transition matrix
ctk.compute_transition_matrix(threshold_scheme="soft", nu=0.5)
ctk.compute_projection(basis="umap")
scv.pl.velocity_embedding_stream(adata_sub, color="groups", vkey="T_fwd", basis="umap", legend_loc="right")
```

**Comment by Marius1311** [comment]
Hi @aanchalsharma833, CellRank can only give you fate probabilities in *comparison settings*, i.e. you have early state A and late states B and C and you want to know how likely early cells are to go to either B or C. In your example, I take it you only have one early state A and one late state B. In such a setting, computing fate probabilities with CellRank wouldn't make sense. Correct me if I'm wrong here, and please clearly state what B and C would correspond to in your example, if they exist.

**Comment by Marius1311** [comment]
Any update on this @aanchalsharma833 ?

**Comment by aanchalsharma833** [comment]
I agree that from the nature of experiment we know of only two labels (states) here, A (non-disease) and B (disease), but is it possible that CellRank could identify the hidden states in case anything exists? As we can see from the UMAP plot (all the cells are neurons), the disease cells are enriched in different clusters, could these represent different states?

**Comment by Marius1311** [comment]
Yes, just go ahead and try applying the GPCCA esimator to the full dataset and see what you can find! If you find different meaningful terminal states, you can compte fate probabilities towards these. We explain this in detail in our tutorials.
