### ISSUE TITLE
Refactor kernels

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#772]
TODOs:
- [x] differentiate between directional and non-directional
- [x] make inversion not an inplace operation
- [x] don't compute `CytoTRACE` score on initialization
- [x] remove adaptive scaling (if reintroduced, will be added in a better form)
- [x] use elementwise multiplication when multiplying 2 kernels, not matmul
- [x] move `_tmap_as_tmat` from #664 
- [x] refactor `RandomWalk` class to include plotting
- [x] refactor `compute_projection`
- [x] add a better way of handling optional connectivities (`ConnectivityMixin`?)
- [x] add common decorator to check whether `.transition_matrix` is present
- [x] remove condition number check?
- [x] add docs/comments for some internal code
- [x] improve public docstrings

**Comment by Marius1311** [comment]
Re condition number checks, let's leave them in, they're probably not super essential to most users, but they're helpful to me when I'm debugging.

**Comment by Marius1311** [comment]
good initiative!

**Comment by michalk8** [comment]
closed via #791
