### ISSUE TITLE
Installation bug on Windows 10

### ISSUE THREAD

**Issue by hyjforesight** [theislab/cellrank#776]
**Hello CellRank,
I created a totally new python 3.8 environment and conda install -c conda-forge -c bioconda cellrank-krylov
The errors came as below:**
```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

Note: you may need to restart the kernel to use updated packages.

Building graph of deps:   0%|          | 0/4 [00:00<?, ?it/s]
Examining @/win-64::__win==0=0:   0%|          | 0/4 [00:00<?, ?it/s]
Examining @/win-64::__archspec==1=x86_64:  25%|██▌       | 1/4 [00:00<?, ?it/s]
Examining python=3.8:  50%|█████     | 2/4 [00:00<?, ?it/s]                    
Examining cellrank-krylov:  75%|███████▌  | 3/4 [00:00<00:00,  3.87it/s]
Examining cellrank-krylov: 100%|██████████| 4/4 [00:00<00:00,  5.16it/s]
                                                                        

Determining conflicts:   0%|          | 0/4 [00:00<?, ?it/s]
Examining conflict for python cellrank-krylov:   0%|          | 0/4 [00:00<?, ?it/s]
                                                                                    

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
**Then I tried to install the dependencies first, conda install -c conda-forge openmpi, still errors:**
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

Note: you may need to restart the kernel to use updated packages.

PackagesNotFoundError: The following packages are not available from current channels:

  - openmpi

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Windows 10 21H1 x64, Anaconda 2.1.0, Python 3.8
Thanks!
Best,
YJ**

**Comment by hyjforesight** [comment]
One interesting thing is that, everytime I run the conda install -c conda-forge -c bioconda cellrank-krylov, conda-script.py will be open automatically by my VS Code.

**Comment by hyjforesight** [comment]
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Yuanjian\.conda\envs\Py38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\petsc_beeb58ac6adc4b68b671c9a13bde12b4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\petsc_beeb58ac6adc4b68b671c9a13bde12b4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Yuanjian\AppData\Local\Temp\pip-wheel-nhetse4p'
       cwd: C:\Users\Yuanjian\AppData\Local\Temp\pip-install-_mo9hrdf\petsc_beeb58ac6adc4b68b671c9a13bde12b4\
  Complete output (1 lines):
  petsc: this package cannot be built as a wheel
  ----------------------------------------
  ERROR: Failed building wheel for petsc
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Yuanjian\.conda\envs\Py38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\petsc4py_6af1e6d7a93442ffa9c5cef9376abe34\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\petsc4py_6af1e6d7a93442ffa9c5cef9376abe34\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Yuanjian\AppData\Local\Temp\pip-wheel-h2j64_sg'
       cwd: C:\Users\Yuanjian\AppData\Local\Temp\pip-install-_mo9hrdf\petsc4py_6af1e6d7a93442ffa9c5cef9376abe34\
  Complete output (27 lines):
  running bdist_wheel
  PETSC_DIR not specified
  running build
  running build_src
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\petsc4py
  copying src\PETSc.py -> build\lib.win-amd64-3.8\petsc4py
  copying src\__init__.py -> build\lib.win-amd64-3.8\petsc4py
  copying src\__main__.py -> build\lib.win-amd64-3.8\petsc4py
  creating build\lib.win-amd64-3.8\petsc4py\lib
  copying src\lib\__init__.py -> build\lib.win-amd64-3.8\petsc4py\lib
  creating build\lib.win-amd64-3.8\petsc4py\include
  creating build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\include\petsc4py\numpy.h -> build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\include\petsc4py\petsc4py.h -> build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\include\petsc4py\petsc4py.PETSc.h -> build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\include\petsc4py\petsc4py.PETSc_api.h -> build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\include\petsc4py\petsc4py.i -> build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\include\petsc4py\PETSc.pxd -> build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\include\petsc4py\__init__.pxd -> build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\include\petsc4py\__init__.pyx -> build\lib.win-amd64-3.8\petsc4py\include\petsc4py
  copying src\PETSc.pxd -> build\lib.win-amd64-3.8\petsc4py
  copying src\lib\petsc.cfg -> build\lib.win-amd64-3.8\petsc4py\lib
  running build_ext
  error: PETSc not found
  ----------------------------------------
  ERROR: Failed building wheel for petsc4py
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Yuanjian\.conda\envs\Py38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\slepc_3ad72095b3ce492dbdfc24a19ff71468\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\slepc_3ad72095b3ce492dbdfc24a19ff71468\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Yuanjian\AppData\Local\Temp\pip-wheel-4hlof6jm'
       cwd: C:\Users\Yuanjian\AppData\Local\Temp\pip-install-_mo9hrdf\slepc_3ad72095b3ce492dbdfc24a19ff71468\
  Complete output (1 lines):
  slepc: this package cannot be built as a wheel
  ----------------------------------------
  ERROR: Failed building wheel for slepc
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Yuanjian\.conda\envs\Py38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\slepc4py_9aea1bc4e0454cd8aba98d48e8be6b5f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\slepc4py_9aea1bc4e0454cd8aba98d48e8be6b5f\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Yuanjian\AppData\Local\Temp\pip-wheel-zqt4iih1'
       cwd: C:\Users\Yuanjian\AppData\Local\Temp\pip-install-_mo9hrdf\slepc4py_9aea1bc4e0454cd8aba98d48e8be6b5f\
  Complete output (27 lines):
  running bdist_wheel
  PETSC_DIR not specified
  SLEPC_DIR not specified
  running build
  running build_src
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\slepc4py
  copying src\SLEPc.py -> build\lib.win-amd64-3.8\slepc4py
  copying src\__init__.py -> build\lib.win-amd64-3.8\slepc4py
  copying src\__main__.py -> build\lib.win-amd64-3.8\slepc4py
  creating build\lib.win-amd64-3.8\slepc4py\lib
  copying src\lib\__init__.py -> build\lib.win-amd64-3.8\slepc4py\lib
  creating build\lib.win-amd64-3.8\slepc4py\include
  creating build\lib.win-amd64-3.8\slepc4py\include\slepc4py
  copying src\include\slepc4py\slepc4py.h -> build\lib.win-amd64-3.8\slepc4py\include\slepc4py
  copying src\include\slepc4py\slepc4py.SLEPc.h -> build\lib.win-amd64-3.8\slepc4py\include\slepc4py
  copying src\include\slepc4py\slepc4py.SLEPc_api.h -> build\lib.win-amd64-3.8\slepc4py\include\slepc4py
  copying src\include\slepc4py\slepc4py.i -> build\lib.win-amd64-3.8\slepc4py\include\slepc4py
  copying src\include\slepc4py\SLEPc.pxd -> build\lib.win-amd64-3.8\slepc4py\include\slepc4py
  copying src\include\slepc4py\__init__.pxd -> build\lib.win-amd64-3.8\slepc4py\include\slepc4py
  copying src\include\slepc4py\__init__.pyx -> build\lib.win-amd64-3.8\slepc4py\include\slepc4py
  copying src\SLEPc.pxd -> build\lib.win-amd64-3.8\slepc4py
  copying src\lib\slepc.cfg -> build\lib.win-amd64-3.8\slepc4py\lib
  running build_ext
  error: PETSc not found
  ----------------------------------------
  ERROR: Failed building wheel for slepc4py
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Yuanjian\.conda\envs\Py38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\petsc_beeb58ac6adc4b68b671c9a13bde12b4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\petsc_beeb58ac6adc4b68b671c9a13bde12b4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Yuanjian\AppData\Local\Temp\pip-record-o74r87d6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Yuanjian\.conda\envs\Py38\Include\petsc'
         cwd: C:\Users\Yuanjian\AppData\Local\Temp\pip-install-_mo9hrdf\petsc_beeb58ac6adc4b68b671c9a13bde12b4\
    Complete output (32 lines):
    running install
    PETSc: configure
    configure options:
        --prefix=C:\Users\Yuanjian\.conda\envs\Py38\Lib\site-packages\petsc
        PETSC_ARCH=arch-python-win-amd64
        --with-shared-libraries=1
        --with-debugging=0
        --with-c2html=0

 --with-mpi=0
    ===============================================================================
                 Configuring PETSc to compile on your system
    ===============================================================================
    ===============================================================================
     *** Windows python detected. Please rerun ./configure with cygwin-python. ***
    ===============================================================================
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Yuanjian\AppData\Local\Temp\pip-install-_mo9hrdf\petsc_beeb58ac6adc4b68b671c9a13bde12b4\setup.py", line 294, in <module>
        setup(name='petsc',
      File "C:\Users\Yuanjian\.conda\envs\Py38\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Yuanjian\.conda\envs\Py38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Yuanjian\.conda\envs\Py38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Yuanjian\.conda\envs\Py38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Yuanjian\AppData\Local\Temp\pip-install-_mo9hrdf\petsc_beeb58ac6adc4b68b671c9a13bde12b4\setup.py", line 230, in run
        config(prefix, self.dry_run)
      File "C:\Users\Yuanjian\AppData\Local\Temp\pip-install-_mo9hrdf\petsc_beeb58ac6adc4b68b671c9a13bde12b4\setup.py", line 166, in config
        if status != 0: raise RuntimeError(status)
    RuntimeError: 3
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Yuanjian\.conda\envs\Py38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\petsc_beeb58ac6adc4b68b671c9a13bde12b4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yuanjian\\AppData\\Local\\Temp\\pip-install-_mo9hrdf\\petsc_beeb58ac6adc4b68b671c9a13bde12b4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Yuanjian\AppData\Local\Temp\pip-record-o74r87d6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Yuanjian\.conda\envs\Py38\Include\petsc' Check the logs for full command output.

**Comment by hyjforesight** [comment]
pip install cellrank, succeed.
But when

import scvelo as scv
import scanpy as sc
import cellrank as cr
import numpy as np

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_10804/1598530259.py in <module>
----> 1 import scvelo as scv
      2 import scanpy as sc
      3 import cellrank as cr
      4 import numpy as np
      5 

~\.conda\envs\Py38\lib\site-packages\scvelo\__init__.py in <module>
      1 """scvelo - RNA velocity generalized through dynamical modeling"""
----> 2 from anndata import AnnData
      3 from scanpy import read, read_loom
      4 
      5 from scvelo import datasets, logging, pl, pp, settings, tl, utils

~\.conda\envs\Py38\lib\site-packages\anndata\__init__.py in <module>
      5 if not within_flit():
      6     del within_flit
----> 7     from ._core.anndata import AnnData, ImplicitModificationWarning
      8     from ._core.merge import concat
      9     from ._core.raw import Raw

~\.conda\envs\Py38\lib\site-packages\anndata\_core\anndata.py in <module>
     15 from typing import Tuple, List  # Generic
     16 
---> 17 import h5py
     18 from natsort import natsorted
     19 import numpy as np

~\.conda\envs\Py38\lib\site-packages\h5py\__init__.py in <module>
     31         raise
     32 
---> 33 from . import version
     34 
     35 if version.hdf5_version_tuple != version.hdf5_built_version_tuple:

~\.conda\envs\Py38\lib\site-packages\h5py\version.py in <module>
     13 
     14 from collections import namedtuple
---> 15 from . import h5 as _h5
     16 import sys
     17 import numpy

h5py\h5.pyx in init h5py.h5()

ImportError: DLL load failed while importing defs

**Comment by hyjforesight** [comment]
**here are the packages i installed**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Yuanjian/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Yuanjian/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Package | Version
-- | --
----------------------------- | --------------------
alabaster | 0.7.12
anndata | 0.7.8
anndata2ri | 1.0.6
annoy | 1.17.0
anyio | 2.2.0
argon2-cffi | 20.1.0
async-generator | 1.1
attrs | 21.2.0
Babel | 2.9.1
backcall | 0.2.0
backports.zoneinfo | 0.2.1
bbknn | 1.5.1
bleach | 4.0.0
brotlipy | 0.7.0
cached-property | 1.5.2
cellrank | 1.5.1.dev10+g10479a9
certifi | 2021.10.8
cffi | 1.15.0
charset-normalizer | 2.0.4
click | 8.0.3
colorama | 0.4.4
cryptography | 35.0.0
cycler | 0.11.0
Cython | 0.29.24
debugpy | 1.4.1
decorator | 5.1.0
defusedxml | 0.7.1
docrep | 0.3.2
docutils | 0.17.1
dunamai | 1.7.0
entrypoints | 0.3
future | 0.18.2
future-fstrings | 1.2.0
get-version | 3.5.3
h5py | 3.5.0
idna | 3.2
igraph | 0.9.8
imagesize | 1.3.0
importlib-metadata | 4.8.1
ipykernel | 6.4.1
ipython | 7.29.0
ipython-genutils | 0.2.0
ipywidgets | 7.6.5
jedi | 0.18.0
Jinja2 | 3.0.2
joblib | 1.1.0
json5 | 0.9.6
jsonschema | 3.2.0
jupyter-client | 7.0.1
jupyter-core | 4.9.1
jupyter-server | 1.4.1
jupyterlab | 3.2.1
jupyterlab-pygments | 0.1.2
jupyterlab-server | 2.8.2
jupyterlab-widgets | 1.0.2
kiwisolver | 1.3.2
legacy-api-wrap | 0.0.0
leidenalg | 0.8.8
llvmlite | 0.37.0
loompy | 3.0.6
MarkupSafe | 2.0.1
matplotlib | 3.4.3
matplotlib-inline | 0.1.2
mistune | 0.8.4
mock | 4.0.3
mpi4py | 3.1.2
natsort | 8.0.0
nbclassic | 0.2.6
nbclient | 0.5.3
nbconvert | 6.1.0
nbformat | 5.1.3
nest-asyncio | 1.5.1
networkx | 2.6.3
notebook | 6.4.5
numba | 0.54.1
numexpr | 2.7.3
numpy | 1.20.3
numpy-groupies | 0.9.14
olefile | 0.46
packaging | 21
pandas | 1.3.4
pandocfilters | 1.4.3
parso | 0.8.2
patsy | 0.5.2
pickleshare | 0.7.5
Pillow | 8.4.0
pip | 21.0.1
progressbar2 | 3.53.1
prometheus-client | 0.11.0
prompt-toolkit | 3.0.20
pycparser | 2.21
pygam | 0.8.0
Pygments | 2.10.0
pygpcca | 1.0.2
pynndescent | 0.5.5
pyOpenSSL | 21.0.0
pyparsing | 3.0.4
pyrsistent | 0.18.0
PySocks | 1.7.1
python-dateutil | 2.8.2
python-igraph | 0.9.8
python-utils | 2.5.6
pytz | 2021.3
pytz-deprecation-shim | 0.1.0.post0
pywin32 | 228
pywinpty | 0.5.7
pyzmq | 22.2.1
requests | 2.26.0
rpy2 | 3.4.5
scanpy | 1.8.2
scikit-learn | 1.0.1
scipy | 1.7.2
scvelo | 0.2.4
seaborn | 0.11.2
Send2Trash | 1.8.0
setuptools | 58.0.4
sinfo | 0.3.4
six | 1.16.0
sniffio | 1.2.0
snowballstemmer | 2.1.0
Sphinx | 4.3.0
sphinxcontrib-applehelp | 1.0.2
sphinxcontrib-devhelp | 1.0.2
sphinxcontrib-htmlhelp | 2.0.0
sphinxcontrib-jsmath | 1.0.1
sphinxcontrib-qthelp | 1.0.3
sphinxcontrib-serializinghtml | 1.1.5
statsmodels | 0.13.1
stdlib-list | 0.8.0
tables | 3.6.1
terminado | 0.9.4
testpath | 0.5.0
texttable | 1.6.4
threadpoolctl | 3.0.0
tokenize-rt | 4.2.1
tornado | 6.1
tqdm | 4.62.3
traitlets | 5.1.0
typing-extensions | 3.10.0.2
tzdata | 2021.5
tzlocal | 4.1
umap-learn | 0.5.2
urllib3 | 1.26.7
wcwidth | 0.2.5
webencodings | 0.5.1
wheel | 0.37.0
widgetsnbextension | 3.5.2
win-inet-pton | 1.1.0
wincertstore | 0.2
wrapt | 1.13.3
xlrd | 1.2.0
zipp | 3.6.0



</body>

</html>

**Comment by michalk8** [comment]
Hi @hyjforesight ,

re the 1st error: afaik our ``meta.yml`` conda doesn't specify a build for Windows (afaik ``openmpi`` is not built for Windows based on [this](https://anaconda.org/conda-forge/openmpi)).
re the 2nd error: seems like ``PETSc`` installation problems; unfortunately I don't a Windows machine at my disposal, but
it looks like you might need to installing ``PETSc`` manually (hinted by the message:
```
     *** Windows python detected. Please rerun ./configure with cygwin-python. ***
```
Here are the official installation [instructions](https://petsc.org/release/install/windows/), hopefully they are of help.
re the 3rd error: ``h5py`` issue, please take a look at the following [comment](https://github.com/h5py/h5py/issues/1914#issuecomment-871271469) whether it can fix it or now.

**Comment by hyjforesight** [comment]
Hello @michalk8,
I realize that i cannot install the cellrank[krylov], which requires openmpi but doesnt support Windows. So I just use pip install cellrank. It works well.
Is there any plan to make cellrank[krylov] support Windows?
Thanks!
Best,
YJ

**Comment by michalk8** [comment]
>  Is there any plan to make cellrank[krylov] support Windows?

I've had a quick look, seems for Windows, we can use `MS-MPI` impl. (it's both on conda and `mpi4pi` supports it, so it shouldn't be problem, will take a stab at it.

**Comment by michalk8** [comment]
> I've had a quick look, seems for Windows, we can use MS-MPI impl. (it's both on conda and mpi4pi supports it, so it shouldn't be problem, will take a stab at it.

I've tried updating ``pygpcca`` to Windows, however, there are many problems (PETSc can be installed on Windows, but it's not as easy [e.g. can't use MS-MPI and other difficulties] and it doesn't provide a conda package).
If you have large data and want to use ``cellrank-krylov`` on Windows, the best way would be running the analysis inside a Docker container.

**Comment by hyjforesight** [comment]
Hello @michalk8 ,
Thanks for the solution! Until now, it works fine by using cellrank without krylov. We'll try Docker once needed.
Thanks!
Best,
YJ

**Comment by michalk8** [comment]
Ok, if you encounter any problems, feel free to (re-)open; closing this.
