### ISSUE TITLE
Refactor Lineage class

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#777]
TODOs:
- ~[ ] consider not subclassing `numpy.ndarray` (related to #759 )~
- [x] remove some redundancies (esp. w.r.t. to indexing)
- [x] document/simplify indexing behavior
- [x] fix KeyError when wrong lineage is passed - e.g.
  ``KeyError: "Invalid lineage name: `Notoch`. Valid names are: `['Early Blastomeres_1', 'Early Blastomeres_2', 'Notochord']`."`` when passing ``Notochord2`` and ``Notochord`` is present

**Comment by Marius1311** [comment]
How do you want to proceed with this @michalk8 ?

**Comment by ivirshup** [comment]
@michalk8, as we had discussed before (last year?), I recommend against creating a custom on-disk schema for the Lineage class if you can avoid it.

* It seems like casting things that have been read as arrays to `Lineage` objects works fine at the moment
* If cellrank hasn't been imported, other libraries will not be able to read in AnnData's containing Lineages
* Libraries from other languages will also not be read these in.

From my perspective, it seems like you'd be giving up a lot of interoperability for something that works as is. In terms of maintenance, on disk formats kinda require you support them forever. APIs can change with a version bump.
