### ISSUE TITLE
Some elements of chi are significantly negative: < -2.220446049250313e-15 when computing macrostates

### ISSUE THREAD

**Issue by hyjforesight** [theislab/cellrank#781]
**Hello CellRank,
I got the errors like this when running cytoTRACE kernal. Could you please help me with this issue? Thanks!**
![image](https://user-images.githubusercontent.com/75048821/144364924-0698e2c4-0256-488f-82e4-5e5f5619668e.png)
![image](https://user-images.githubusercontent.com/75048821/144365288-7be12df6-dc91-4e25-aecb-b41011b21bf8.png)

```python 3.8
...


#### Versions:
<!-- Output of cellrank.logging.print_versions() -->
> ...scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.20.3 scipy==1.7.2 pandas==1.3.4 scikit-learn==1.0.1 statsmodels==0.13.1 python-igraph==0.9.8 pynndescent==0.5.5
scvelo==0.2.4  scanpy==1.8.2  anndata==0.7.8  loompy==3.0.6  numpy==1.20.3  scipy==1.7.2  matplotlib==3.5.0  sklearn==1.0.1  pandas==1.3.4  
cellrank==1.5.0 scanpy==1.8.2 anndata==0.7.8 numpy==1.20.3 numba==0.54.1 scipy==1.7.2 pandas==1.3.4 pygpcca==1.0.2 scikit-learn==1.0.1 statsmodels==0.13.1 python-igraph==0.9.8 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.0 seaborn==0.11.2

**Comment by Marius1311** [comment]
@michalk8, I think that's an example of a threshold in pyGPCCA being to tight, the deviation is very small, `10^-15`. Would you mind opening a PR to pyGCCA where you adjust this to say

```python
    # Check for negative elements in chi and handle them.
    if np.any(chi < 0.0):
        if np.any(chi < -1e3 * EPS):
```

**Comment by hyjforesight** [comment]
Hello @Marius1311 and @michalk8,
Thanks for the solution! You guys are amazing! Unlike developers of other packages, you solve every issue so effciently! I really appreciate it!
Thanks!
Best,
YJ
