### ISSUE TITLE
Wrong colors for macrostate composition per time step

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#782]
## Description

When running the tutorial for time-series datasets [here](https://cellrank.readthedocs.io/en/stable/real_time.html) the colors stored for each `day` are all the same. This leads to the plot produced by `g.plot_macrostate_composition(key="day")` be incorrect/uninformative.

### Expected plot

![image](https://user-images.githubusercontent.com/28675704/144439637-6541ed76-4fa8-4f5f-bf4e-f77abf57e4c1.png)

### Actual plot

![image](https://user-images.githubusercontent.com/28675704/144439588-c0015a8c-da45-4d1d-9a08-f727f463f209.png)

#### Versions:

> cellrank==1.5.0+g10479a98.d20211116 scanpy==1.8.1 anndata==0.7.6 numpy==1.21.1 numba==0.52.0 scipy==1.7.0 pandas==1.3.1 pygpcca==1.0.2 scikit-learn==0.24.2 statsmodels==0.12.2 python-igraph==0.9.8 scvelo==0.2.3 pygam==0.8.0 matplotlib==3.4.2 seaborn==0.11.1

**Comment by michalk8** [comment]
closed via #784

**Comment by mortunco** [comment]
Hi,

I am trying to implement Timeseries tutorial to our dataset.

at `g.plot_macrostate_composition(key="time_points")` step, the generated plot colors are similar to #782. I think the error persists. Thats why i wanted to re-open the issue.

![image](https://user-images.githubusercontent.com/12833865/170546354-303c9050-79c1-4cc1-b51f-ec8b91c508de.png)

Here is the key that I am coloring. 
```
AAACCCAAGTGGACTG-2      0.0
AAACCCACAAGTGACG-2      0.0
AAACCCACATATACCG-2      0.0
AAACCCAGTTTCGACA-2      0.0
AAACGAAAGGCAGTCA-2      0.0
                       ... 
TTTGGTTAGAATCTAG-17    22.0
TTTGGTTAGCATGCGA-17    22.0
TTTGGTTCACTTGTCC-17    22.0
TTTGTTGCAACAGATA-17    22.0
TTTGTTGGTGTAGGAC-17    22.0
Name: time_points, Length: 40304, dtype: category
Categories (8, float64): [0.0 < 2.0 < 4.0 < 8.0 < 12.0 < 16.0 < 20.0 < 22.0]
```
#### Versions:
```
cellrank==1.5.1 scanpy==1.9.1 anndata==0.8.0 numpy==1.21.0 numba==0.55.1 scipy==1.8.0 pandas==1.4.2 pygpcca==1.0.3 scikit-learn==1.0.2 statsmodels==0.13.2 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.2 seaborn==0.11.2
```

Thank you very much for developing cellrank and providing support to community.

I really appreciate it ,
Best,
T.

**Comment by WeilerP** [comment]
Works for me when running on the latest version (didn't try with `cellrank==1.5.1` yet, though). @michalk8 do you remember changing/fixing anything related to this after the latest release?

**Comment by mortunco** [comment]
I see. Sorry didnt realise 1.5.1 wasnt the latest version. Is there a matplotlib trick that i can override? Because colors work fine in my previous plots. Just this one is acting weird.

**Comment by TLukas1** [comment]
@mortunco , I had a similar problem.

**Comment by TLukas1** [comment]
@mortunco - had a similar problem. 
Manually changing `adata.uns["key_colors"]` is an easy fix. 
`adata.uns["Timepoint_colors"] = ['#9b5fe0', '#16a4d8', '#60dbe8', '#8bd346', '#efdf48', '#f9a52c', '#d64e12']`
