### ISSUE TITLE
Inconsistency in CytoTRACE tutorial

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#783]
## Description

The Schur decomposition in the CytoTRACE tutorial [here](https://cellrank.readthedocs.io/en/stable/beyond_rna_velocity.html) highlights an eigengap after `5` eigenvalues.

![image](https://user-images.githubusercontent.com/28675704/144440031-35df7d35-0079-493f-99c6-374a1427e89d.png)

The following text, however, talks about an eigengap after `3` eigenvalues which is supposedly shown in the figure. Am I missing something or do we need to update this @Marius1311, @michalk8?

**Comment by michalk8** [comment]
This might've happened when the notebook was automatically regenerated (the better case) or we changed the defaults and this caused the issue.

**Comment by Marius1311** [comment]
I used to get the plot below:

<img width="779" alt="Screenshot 2021-12-07 at 18 37 50" src="https://user-images.githubusercontent.com/24494650/145078792-f2dcc535-9cf4-47be-b585-4e039b64e5f9.png">

**Comment by Marius1311** [comment]
The random walks also used to look slighly different - which change could have caused this @michalk8?

**Comment by Marius1311** [comment]
In line 10, we fix most of the relevant parameters: `ctk.compute_transition_matrix(threshold_scheme="soft", nu=0.5)`

**Comment by Marius1311** [comment]
This cannot yet be caused by https://github.com/theislab/cellrank/pull/778, right?

**Comment by michalk8** [comment]
> This cannot yet be caused by #778, right?

No, it cannot.

**Comment by Marius1311** [comment]
@WeilerP volunteered to check what caused this change. Thanks @WeilerP!

**Comment by WeilerP** [comment]
@michalk8, the proposed eigengap switches from 3 to 5 when applying [this](https://github.com/theislab/cellrank/commit/2bfbd3ceae3b0e9f2470675dedd95d9fe4f79eac) commit, i.e. after merging #583. I presume it is due to the changes to `Pseudotimekernel.compute_transition_matrix`. Specifying `b=20` indentifies the gap after 4 eigenvalues. What was the reason for removing `percentile` and `density_normalize` as function arguments?

**Comment by michalk8** [comment]
> @michalk8, the proposed eigengap switches from 3 to 5 when applying this commit, i.e. after merging #583. I presume it is due to the changes to Pseudotimekernel.compute_transition_matrix. Specifying b=20 indentifies the gap after 4 eigenvalues. What was the reason for removing percentile and density_normalize as function arguments?

We've had the internal finetuning of these on Zebrafish + other dataset (also linked in the PR, should be visible for you) and it did perform slightly worse.

**Comment by WeilerP** [comment]
Yes, but why not simply use default values (`density_normalize=False`, `percentile=None`) to allow for more flexibility?

**Comment by Marius1311** [comment]
@WeilerP, would you mind checking whether this is due to `density_normalize`, `percentile`, or both of them? I recall `percentile` just didn't make much sense to me intuitively, that's why we removed it (also, it didn't give better performance, as @michalk8 stated above).

**Comment by hyjforesight** [comment]
Hello CellRank,
This is also what I'm curious about. If the dash line is at Index '4', how many `n_states` shall we set for `g_fwd.compute_macrostates(n_states=?)`, 4 or 5?
Thanks!
Best
YJ

**Comment by Marius1311** [comment]
In the example below, the eigengap would be inferred aver 5 eigenvalues, so you should compute 5 macrostates, as a starting point. Keep in mind the eigengap statistic is a heuristic though, so take this more as a starting point to your analysis. 

![image](https://user-images.githubusercontent.com/24494650/154519713-48007b1d-775e-4728-b2a9-e7c4aff85583.png)

**Comment by WeilerP** [comment]
@Marius1311, @michalk8, is there a reason why we start counting the eigenvalues at 0? I always found this rather confusing, TBH.

**Comment by Marius1311** [comment]
Not that I recall - happy to change this so that we start counting with 1.
