### ISSUE TITLE
Is it possible to draw the CytoTRACE pseudotime-directed PAGA graph?

### ISSUE THREAD

**Issue by hyjforesight** [theislab/cellrank#788]
...
**Hello CellRank,
We know by recovering the latent time, it's available to combine the 'velocity_pseudotime' or 'latent_time' with the initial state and terminal state calculated by CellRank to draw the directed PAGA graph by the below coding:**

```
scv.tl.recover_latent_time(adata, root_key="initial_states_probs", end_key="terminal_states_probs")    # recover latent time by using the CellRank determined initial states and terminal states
scv.tl.paga(adata, groups="clusters", root_key="initial_states_probs", end_key="terminal_states_probs", use_time_prior="latent_time")    # combine the latent-time with the CellRank determined initial states and terminal states to calculate PAGA
cr.pl.cluster_fates(adata, mode="paga_pie", cluster_key="clusters", basis="umap")    # latent time directed fate-probability-PAGA
```

**Because CytoTRACE can also calculate 'ct_pseudotime' by ctk = CytoTRACEKernel(adata), we tried to use ct_pseudotime to draw the CytoTRACE pseudotime-directed PAGA, but it failed. It looks like directed PAGA can be only done based on scVelo?**
![image](https://user-images.githubusercontent.com/75048821/144786851-4ac385f5-7746-407e-92cf-487199803846.png)

**We're wondering whether it is possible to draw the CytoTRACE pseudotime-directed PAGA graph with or without combining with the CellRank determined initial states and terminal states?
Thanks!
Best,
YJ**

**Comment by Marius1311** [comment]
That's a good point, I don't think that's currently possible, but I'm not entirely sure how `scv.tl.paga` uses the velocities under the hood, @VolkerBergen implemented this function. In any case, this is not currently supported, I'm afraid.

**Comment by Marius1311** [comment]
Feel free to open a PR to scVelo to suggest a solution that doesn't make use of the velocities, but just uses a pseudotime.

**Comment by hyjforesight** [comment]
@Marius1311 Thanks for the response. I open a request issue at scVelo.
