### ISSUE TITLE
Incorrect displaying of citations in docs

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#790]
## Description

The citations in the docs are not displayed correctly. In the _CellRank beyond RAN velocity_ tutorial_ [here](https://cellrank.readthedocs.io/en/stable/beyond_rna_velocity.html), for example, the citations are not supposed to be shown directly but only made accessible through a hyperlink. To give concrete example: The first sentence is displayed as _This tutorial shows how to work with CellRank when no [La Manno et al., 2018] information is available [...]_ but should be _This tutorial shows how to work with CellRank when no RNA velocity information is available [...]_ with a link to _La Manno et al., 2018_ via RNA velocity.

**Comment by michalk8** [comment]
Must've happened when we switched to bibtex for citations, will fix.

**Comment by Marius1311** [comment]
Thanks for raising this @WeilerP! And thanks for fixing @michalk8.
