### ISSUE TITLE
Why are the driver genes by default are ranked using correlation values rather than p values?

### ISSUE THREAD

**Issue by subercui** [theislab/cellrank#792]
...
Hi, as shown in the [tutorial for computing driver genes](https://cellrank.readthedocs.io/en/stable/cellrank_basics.html?highlight=driver#Compute-lineage-drivers):

> plot the top 5 driver genes (based on the correlation), e.g. for the Alpha lineage.

Why are the driver genes by default are ranked using correlation values rather than p values? For example, I saw negative correlations of large absolute values in my case. Why these are excluded from the top drivers?

**Comment by Marius1311** [comment]
Thanks for your question @subercui. You can easily sort them in whichever way you like using standard pandas sorting, i.e. df.sort_values(by=`YOUR_QUANTITY_OF_INTEREST`), see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html.
