### ISSUE TITLE
Change cellrank default PAGA calculation recommendation

### ISSUE THREAD

**Issue by Zethson** [theislab/cellrank#795]
Hey,

nothing short of amazing work @Marius1311 and @michalk8.
Not an import feature request, but thought I'd bring it up nevertheless.
When attempting to

`cr.pl.cluster_fates(adata, mode="paga_pie", basis="umap", cluster_key="leiden_0_5")`

cellrank tells me to use `scvelo.tl.paga` which only works when velocity data is actually available. However, in my case it is not (using EHR data + connectivity kernel).

It works flawlessly with scanpy's paga

`ep.tl.paga(adata, groups="leiden_0_5")`

Request: 
Formulate the error message in such a way that people without velocity information will run scanpys paga computation.

Cheers

**Comment by michalk8** [comment]
Hi @Zethson, thanks for the suggestion!

>  Formulate the error message in such a way that people without velocity information will run scanpys paga computation.

Sounds good (would maybe add arg `flavor: Literal['scanpy', 'scvelo'] = 'scvelo` with the error message you suggest.

**Comment by michalk8** [comment]
closed via #799
