### ISSUE TITLE
Using CellRank to infer healthy to disease trajectories and how to handle multiple samples/conditions/celltypes

### ISSUE THREAD

**Issue by natallah** [theislab/cellrank#801]
...
Hello, similar to the question asked in issue #771, I am curious about whether I can use CellRank to infer disease trajectories when we have one initial point: healthy and two disease states: mild and severe.  We do not know whether the usual trajectory is from healthy to mild to severe disease (unbranching trajectory) or if it is from healthy to mild disease in some patients and healthy to severe in others (branching trajectory).  Will CellRank enable us to determine which trajectory the disease takes?  

Another question I have is how do you recommend that we handle multiple samples, conditions, and types of cells in this analysis?  We have 3 disease states,  23 samples (3 normal, 10 mild disease, 10 severe disease), and multiple types of immune cells.  We are most interested in the trajectory of two types of cells (macrophages and T lymphocytes).

**Comment by stela2502** [comment]
One totally off-topic reply: Could it be possible that you already know what could be the case and all you need is the computer to read your mind of how to put a timeline into your data?
In case you want to check if your brain is able to find an 'interesting' trajectory/timeline in your data you can try out CellexalVR.
https://www.cellexalvr.med.lu.se/

**Comment by Marius1311** [comment]
Hi @natallah, as long as batch effects aren't very pronounced, I would work with unintegrated data, compute RNA velocity jointly on all samples and proceed with CellRank analysis. Using the low level pipeline (check out our kernels and estimators tutorial) will allow you to look into macrostates and their stability, i.e. figuring out whether you have one or two terminal states. Also, you can compute fate probabilities towards any macrostate to delineate your two trajectories. I hope this helps as a starting point.

**Comment by Marius1311** [comment]
I will close this issue for now, feel free to reopen if questions persist once you have gone through the tutorial.
