### ISSUE TITLE
Missing python packages missing?

### ISSUE THREAD

**Issue by stela2502** [theislab/cellrank#802]
Running your example analysis using the human liver cell atlas data (158k cells) I hit a dead end:
```
WARNING: Unable to import `petsc4py` or `slepc4py`. Using `method='brandts'`
WARNING: For `method='brandts'`, dense matrix is required. Densifying
```

Could I ask to add these packages petsc4py and/or slepc4py  to the requirements?

Thank you!

**Comment by stela2502** [comment]
Oh - now I get why you do not have it in the requirements. 111Mb of additional packages for the Ubuntu 20.04 package python3-slepc4py...

**Comment by michalk8** [comment]
> Oh - now I get why you do not have it in the requirements. 111Mb of additional packages for the Ubuntu 20.04 package python3-slepc4py...

We have them listed as an optional requirement [here](https://github.com/theislab/cellrank/blob/master/setup.py#L42), but PETSc/SLEPc is sometimes a bit of a pain to install through `pip`.
I'd recommend using `conda install -c conda-forge -c bioconda cellrank-krylov` (other options are listed here, but I think you've found it: https://cellrank.readthedocs.io/en/stable/installation.html)

**Comment by michalk8** [comment]
Think this can be closed, will continue the installation problem discussion in #800

**Comment by Marius1311** [comment]
Just as a comment, once you have PETSc/SLEPc set up correctly @stela2502, analyzing 158k cells in CellRank won't cause you any problems. In fact, in the most recent version of CellRank, we have internally run CellRank on 100k cells on a moderate server in less than one minute (this includes macrostate computation and fate probabilities).

**Comment by stela2502** [comment]
@Marcus1311 correct, installing PETSc/SLEPc is not too simple, but I got it to work in a singularity image. Install from the packaged tar files for both libraries was necessary as well as some import magic in every jupyter script one runs.
Back to CellRank: Yes CellRank does work and the whole process is also memory efficient.
Nevertheless I could not finish the whole tutorial (https://cellrank.readthedocs.io/en/stable/cellrank_basics.html) as the paga step did not make use of the c libraries and was unable to finish after blowing up one matrix to dense. How important is this  paga step? Could something similar be achieved using the louvain pseudo-time? I also hear that scarf is rather memory efficient and also has a pseudo-time functionality.

**Comment by Marius1311** [comment]
Hi @stela2502, would you mind opening a new issue for this? Thanks!
