### ISSUE TITLE
identifying cluster marker genes when using CellRank without RNA velocity

### ISSUE THREAD

**Issue by tarak77** [theislab/cellrank#806]
Hi, I was able to implement CellRank on my data which does not have any RNA velocity information available. With the limited cells I have, I obtained a few clusters in the final output. Is it possible to know the marker genes in each cluster? 
<img width="680" alt="Screen Shot 2022-02-06 at 4 44 45 PM" src="https://user-images.githubusercontent.com/32019333/152678163-8f48db6e-a696-49c6-a0cb-ff5ba2128836.png">

Any help will be great!

**Comment by Marius1311** [comment]
Hi @tarak77, thanks for your question. There doesn't seem to be much trajectory structure in your data to begin with, is there any underlying biology that pushed you towards a trajectory approach like CellRank? If not, I would rather advise you to follow a standard scanpy/scVI workflow which looks for discrete, cluster level variation in the data, possibly applying PAGA to find cluster-level connectivity.

**Comment by tarak77** [comment]
Makes sense. I will work on that!
