### ISSUE TITLE
Low-level API heatmap

### ISSUE THREAD

**Issue by shaln** [theislab/cellrank#813]
Hello. I have a question about plotting gene expression trends and heatmaps when running the low-level API. Would the following steps be the appropriate way to get the plots when using the low-level API?

I first ran the low-level API per the tutorial to get the terminal states, and then computed the initial states by repeating the analysis using `backward=True` when initialising the kernel objects (`VelocityKernel` and `ConnectivityKernel`). Next, I computed the latent time and heatmap using the following codes from the high-level API:

```
scv.tl.recover_latent_time(
    disease, root_key="initial_states_probs", end_key="terminal_states_probs"
)

root_idx = np.where(disease.obs["initial_states"] == "Cell State_2")[0][0]
disease.uns["iroot"] = root_idx
sc.tl.dpt(disease)

scv.pl.scatter(
    disease,
    color=["seurat_clusters", root_idx, "latent_time", "dpt_pseudotime"],
    fontsize=16,
    cmap="viridis",
    perc=[2, 98],
    colorbar=True,
    rescale_color=[0, 1],
    title=["seurat_clusters", "root cell", "latent time", "dpt pseudotime"],
)

model = cr.ul.models.GAM(disease)
cr.pl.heatmap(
    disease,
    model,
    genes=disease.varm['terminal_lineage_drivers']["Cell State_2_corr"].sort_values(ascending=False).index[:100],
    show_absorption_probabilities=True,
    lineages="Cell State_2",
    n_jobs=1,
    backend="loky",
)
```

**Comment by hyjforesight** [comment]
Hi @shaln
Right, you should recover `latent_time` by this function if your data was not proceeded by scVelo dynamical model. If your input data has `dpt_pseudtime` or 'velocity_pseudotime', no need to do `scv.tl.recover_latent_time()`
```python
scv.tl.recover_latent_time(
    disease, root_key="initial_states_probs", end_key="terminal_states_probs"
)
```
No need to do this step. It just comparing the similarity between "latent_time" and "dpt_pseudotime".
```python
root_idx = np.where(disease.obs["initial_states"] == "Cell State_2")[0][0]
disease.uns["iroot"] = root_idx
sc.tl.dpt(disease)

scv.pl.scatter(
    disease,
    color=["seurat_clusters", root_idx, "latent_time", "dpt_pseudotime"],
    fontsize=16,
    cmap="viridis",
    perc=[2, 98],
    colorbar=True,
    rescale_color=[0, 1],
    title=["seurat_clusters", "root cell", "latent time", "dpt pseudotime"],
)
```
you should run `cr.pl.lineage_drivers()` or `g.compute_lineage_drivers()` before drawing the lineage gene heatmap because it returns `adata.varm['terminal_lineage_drivers']`, which is required.
model = cr.ul.models.GAM(disease)
cr.pl.heatmap(
    disease,
    model,
    genes=disease.varm['terminal_lineage_drivers']["Cell State_2_corr"].sort_values(ascending=False).index[:100],
    show_absorption_probabilities=True,
    lineages="Cell State_2",
    n_jobs=1,
    backend="loky",
)

**Comment by shaln** [comment]
Thanks, @hyjforesight! I couldn't find `velocity_pseudotime` initially even though I had pre-processed my data using scVelo's dynamical model. This was because I had only ran the following before running CellRank. 

```
scv.pp.filter_and_normalize(disease, min_shared_counts=20, n_top_genes=2000)
scv.pp.moments(disease, n_pcs=50, n_neighbors=30)
scv.tl.recover_dynamics(disease)
scv.tl.velocity(disease, mode='dynamical')
scv.tl.velocity_graph(disease)
scv.pl.velocity_embedding_stream(disease, basis='umap', color='seurat_clusters')
```

I am now able to get the heatmap and gene expression trends after running `scv.tl.latent_time(disease)` at the end of the above chunk.
