### ISSUE TITLE
CellRank in google co-lab fails

### ISSUE THREAD

**Issue by bsmith030465** [theislab/cellrank#814]
Hi,

I was just trying to get started with the tutorial in google co-lab [link](https://colab.research.google.com/github/theislab/cellrank_notebooks/blob/master/tutorials/kernels_and_estimators.ipynb#scrollTo=DSnv6U52fKvd), but I get an error in the first block of code:

```python
import sys

if "google.colab" in sys.modules:
    !pip install -q git+https://github.com/theislab/cellrank@dev

```

```pytb
  Building wheel for loompy (setup.py) ... done
  Building wheel for umap-learn (setup.py) ... done
  Building wheel for pynndescent (setup.py) ... done
  Building wheel for numpy-groupies (setup.py) ... done
  Building wheel for sinfo (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
```

How should I go about resolving this?

thanks!

**Comment by michalk8** [comment]
Hi @bsmith030465 , did you try restarting the runtime in `Runtime > Restart runtime`?
I can confirm I got the above error as well, but after restarting it, I was able to install the package.

**Comment by michalk8** [comment]
Think this can be closed, the above mentioned steps should work. As far as I'm aware, there isn't anything to do on our side to fix this.
