### ISSUE TITLE
Loading of kernels and handling of attached AnnData

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#818]
## Description

I ran an analysis on a time series dataset with the WOTKernel and saved it for later use. 

```python
# Some preprocessing
wk = WOTKernel(adata)
wk.compute_initial_growth_rates(organism="mouse", key_added="growth_rate_init")
wk.compute_transition_matrix(
    growth_iters=3, growth_rate_key="growth_rate_init", last_time_point="connectivities"
)
wk.write(fname='wot_kernel')
```

When restarting the analysis and reading the kernel from file, the `AnnData` object in the analysis does not change. Inferring macro states, lineage drivers, etc. only modifies the AnnData attribute of the kernel (seems obvious once you realized it but is a bit confusing when you are not aware of it).
@michalk8, did you have a best practice in mind of how to do these steps? You could, of course, simply do

```python
adata = wk.adata
```

**Comment by michalk8** [comment]
You can save the kernel without the `AnnData` object as `wk.write(fname="wot_kernel", write_adata=False)`.
Afterwards, you can read it as `WOTKernel.read(fname="wot_kernel.pickle", adata=adata)`.
As a 3rd alternative, you can also set the `AnnData` object as `wk.adata = adata`, but I wouldn't recommend doing this.

**Comment by WeilerP** [comment]
Yes, but I **do** want to save the AnnData object. Otherwise, how will I have all the attributes added prior to saving the kernel? Or would these be added automatically when running `WOTKernel.read(fname="wot_kernel.pickle", adata=adata)`?

**Comment by michalk8** [comment]
> Otherwise, how will I have all the attributes added prior to saving the kernel

If you mean the `Kernel` attributes, they are saved in the `pickle` file, the read doesn't read anything from `AnnData` to store in the `Kernel`, it's equivalent to:
```python
k = WOTKernel("wot_kernel.pickle")
k.adata = adata
```
Think the `adata = wk.adata` is a better approach though (less places to have inconsistent objects), saving without `AnnData` was developed so that you can separate saving these 2.

**Comment by michalk8** [comment]
Would converge that the best practice is `adata = wk.adata`. I could try fancy stuff like modifier callee's frame after load and creating the `adata` reference automatically, but this is too intrusive. Closing this, feel free to re-open.
