### ISSUE TITLE
`GPCCA.compute_lineage_drivers(return_drivers=False)` returns lineage drivers DataFrame

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#820]
## Description

When computing the lineage drivers with `g.compute_lineage_drivers(return_drivers=False)` (`g = GPPCA(adata)`) the drviers is returned, nonetheless. This can, for example, be reproduced by running the tutorial for time series data.

#### Versions:

> cellrank==1.5.1+g10479a98.d20211116 scanpy==1.8.1 anndata==0.7.6 numpy==1.21.1 numba==0.52.0 scipy==1.7.0 pandas==1.3.1 pygpcca==1.0.2 scikit-learn==0.24.2 statsmodels==0.12.2 python-igraph==0.9.8 scvelo==0.2.5.dev81+g64c76b2.d20220202 pygam==0.8.0 matplotlib==3.4.2 seaborn==0.11.1

**Comment by michalk8** [comment]
`return_drivers` was removed during estimators refactoring, now it's always being returned.

**Comment by Marius1311** [comment]
Closing this.
