### ISSUE TITLE
Plot cluster lineage optimising advice

### ISSUE THREAD

**Issue by e1992** [theislab/cellrank#821]
...
Hi, 
I've been using cr.pl.cluster_lineage to cluster driver genes in a specific lineage, but some of my clusters look very similar (see attached). What is the best way to optimise this, can I change the clustering resolution in some way? Change n_points does not generate clear clusters. Any pointers would be great! Thanks. 

Ive been following the default setting using GAM model:

model = cr.ul.models.GAM(adata)
cr.pl.cluster_lineage(adata, model, genes = CD14MonocyteGenes[1:586], time_key = "ct_pseudotime", backward = True, save = "CD14_clus_lin_testing.pdf", lineage = "CD14+ Monocytes", recompute = True)

[CD14_clus_lin_testing.pdf](https://github.com/theislab/cellrank/files/8116272/CD14_clus_lin_testing.pdf)

**Comment by Marius1311** [comment]
Note to @michalk8: we should rename this function, I really hard to think hard for a moment about what it does, `cluster_lineage` just sounds like we're clustering lineages, which does not make sense. I suggest something like `cluster_gene_trends`.

**Comment by Marius1311** [comment]
@e1992, these clusters look quite bad, essentially all the same. I would try to vary the PCA, clustering and KNN graph parameters, please check the API here: https://cellrank.readthedocs.io/en/stable/api/cellrank.pl.cluster_lineage.html#cellrank.pl.cluster_lineage

See also below. 

pca_kwargs ([Dict](https://docs.python.org/3/library/typing.html#typing.Dict)) – Keyword arguments for [scanpy.pp.pca()](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.pca.html#scanpy.pp.pca).

neighbors_kwargs ([Dict](https://docs.python.org/3/library/typing.html#typing.Dict)) – Keyword arguments for [scanpy.pp.neighbors()](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.neighbors.html#scanpy.pp.neighbors).

clustering_kwargs ([Dict](https://docs.python.org/3/library/typing.html#typing.Dict)) – Keyword arguments for [scanpy.tl.leiden()](https://scanpy.readthedocs.io/en/stable/generated/scanpy.tl.leiden.html#scanpy.tl.leiden).

**Comment by michalk8** [comment]
@e1992 They also look the same since the `y` values are not shared and are of slightly different scales, you can try using `sharey=True`. But in general agree with @Marius1311 's comments.

**Comment by e1992** [comment]
@Marius1311 @michalk8 Thanks both for your suggestions, I've be able to to optimise the clustering with parameter you suggested
