### ISSUE TITLE
WARNING: There is only 1 recurrent class, all cells will have probability 1 of going there 

### ISSUE THREAD

**Issue by kragrawa** [theislab/cellrank#822]
...

Hi, I am trying to run CellRank's kernels and estimators tutorial on my data set, but I do not understand this warning. Three macrostates were identified, but when I run g.compute_absorption_probabilities() I get this warning. Thank you for your help!

**Comment by michalk8** [comment]
> Hi, I am trying to run CellRank's kernels and estimators tutorial on my data set, but I do not understand this warning. Three macrostates were identified, but when I run g.compute_absorption_probabilities() I get this warning. Thank you for your help!

After computing the macrostates, a subset of them is selected (either manually or in your case automatically) as terminal states. Towards these we then calculate absorption probabilities - if there's only 1 terminal state, all other cells will have probability `1` of being absorbed there, which is uninformative.
The automatic setting of terminal states from macrostates relies on the `eigengap` heuristic, I'd recommend looking at the spectrum using [this method](https://cellrank.readthedocs.io/en/stable/api/cellrank.tl.estimators.GPCCA.plot_spectrum.html#cellrank.tl.estimators.GPCCA.plot_spectrum) with `real_only=True` and then manually setting the terminal states using this [function](https://cellrank.readthedocs.io/en/stable/api/cellrank.tl.estimators.GPCCA.set_terminal_states_from_macrostates.html#cellrank.tl.estimators.GPCCA.set_terminal_states_from_macrostates).

**Comment by Marius1311** [comment]
I suppose this answered your question @kragrawa
