### ISSUE TITLE
cr.pl.cluster_fates not working with kernels/estimators

### ISSUE THREAD

**Issue by SabrinaRichter** [theislab/cellrank#823]
I would like to use the directed paga plot functionality (cr.pl.cluster_fates) with my GPCCA estimator and PseudotimeKernel.

I used the following Code

```
pk = cr.tl.kernels.PseudotimeKernel(adata)
pk.compute_transition_matrix()
g = cr.tl.estimators.GPCCA(pk)
g.compute_eigendecomposition()
g.compute_macrostates(cluster_key='cluster')
g.compute_terminal_states()
g.compute_absorption_probabilities()
```
and then calling cluster_fates
```
cr.pl.cluster_fates(
    adata,
    mode="paga_pie",
    cluster_key="ct_prediction",
    basis="umap",
    legend_kwargs={"loc": "top right out"},
    legend_loc="top left out",
    node_size_scale=5,
    edge_width_scale=1,
    max_edge_width=4,
    title="directed PAGA",
)
```
I get this error
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/var/folders/v4/qpdfw37s6rjf6vgqr7hbw3tdckysnv/T/ipykernel_28145/3873610078.py in <module>
----> 1 cr.pl.cluster_fates(
      2     adata,
      3     mode="paga_pie",
      4     cluster_key="ct_prediction",
      5     basis="umap",

~/anaconda3/envs/grn_inference/lib/python3.8/site-packages/cellrank/pl/_cluster_fates.py in cluster_fates(adata, mode, backward, lineages, cluster_key, clusters, basis, cbar, ncols, sharey, fmt, xrot, legend_kwargs, figsize, dpi, save, **kwargs)
    460 
    461     if lineage_key not in adata.obsm:
--> 462         raise KeyError(f"Lineage key `{lineage_key!r}` not found in `adata.obsm`.")
    463 
    464     if lineages is not None:

KeyError: "Lineage key `'to_terminal_states'` not found in `adata.obsm`."
```

**Comment by michalk8** [comment]
Similar thing was reported in https://github.com/theislab/cellrank/issues/808
Seems like `g.compute_absorption_probabilities()` doesn't update `adata` for some reason (or maybe `g.adata` is not `adata`).

**Comment by SabrinaRichter** [comment]
Also the set_terminal_states method of the estimator does not set terminal_states_probabilities as promised, neither in adata not g.adata and later on I get this error, but the estimator does not seem to have a '.compute_terminal_states_memberships()' method.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/var/folders/v4/qpdfw37s6rjf6vgqr7hbw3tdckysnv/T/ipykernel_25503/2229520573.py in <module>
----> 1 g.plot_terminal_states()

~/anaconda3/envs/grn_inference/lib/python3.8/site-packages/cellrank/tl/estimators/mixins/_utils.py in wrapper(wrapped, instance, args, kwargs)
    405             # prefer `continuous` for a prettier format
    406             attr = continuous if continuous is not None else discrete
--> 407             raise RuntimeError(f"Compute `.{attr}` first as `.compute_{attr}()`.")
    408 
    409         if colors is None:

RuntimeError: Compute `.terminal_states_memberships` first as `.compute_terminal_states_memberships()`.

**Comment by michalk8** [comment]
I've discussed this with Sabrina, the issue was that estimators are after stateful and will try to maintain consistency in self and the linked AnnData by e.g. unsetting absorption probabilities in terminal states have changed. This will be documented in the new tutorials + I will mention this explicitly in the docs as well when moving for the 2.0 release.
Closing this

**Comment by Marius1311** [comment]
Thanks for working this out with @SabrinaRichter @michalk8
