### ISSUE TITLE
Ordering of macrostates

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#836]
Hi @michalk8, I'm looking into the new ordering methods you introduced for the `plot_coarse_T` method and I have a few remarks:
- could you please invert the sorting? Most users read figures from left to right, top to bottom. That means the early states, i.e. low stability, should be in the top left corner. Currently, it's the other way around, see Fig. 1 below. 
- this should be consistent across all ordering options - i.e. whatever sorting I use, I should always find my putative early states in the top left corner, and my putative late states in the lower right corner. It's also inverted for `stat_dist` at the moment, see Fig. 2.
- could you add add mode `outgoing` please? 

## Fig. 1
<img width="821" alt="Screenshot 2022-03-06 at 15 16 04" src="https://user-images.githubusercontent.com/24494650/156940567-dc122e48-69d2-41a9-b6de-3046342ef958.png">

## Fig. 2
<img width="821" alt="Screenshot 2022-03-06 at 15 19 50" src="https://user-images.githubusercontent.com/24494650/156940660-f96b045a-5003-44a3-8085-cfefa7d19e97.png">

**Comment by michalk8** [comment]
Re 1 and 2: ok, that's not a problem.
Re 3: it always sums to 1, so I think it's meaningless.

**Comment by michalk8** [comment]
Outgoing included, diagonal ignored. Closed via #839
