### ISSUE TITLE
Generalization of `_merge_approx_rcs`

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#85]
I would generalize this a bit so that you can pass two series, and optionally, two color arrays associated with the categories. Potentially, you could use this: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.combine.html

I'm opening this up because I need such a utility function at the moment and rather than writing a second one, it would be nice to just have one general one. I would also rename the function and the variables inside it to not have any refernece to recurrent classes, to just keep it general.

**Comment by michalk8** [comment]
@Marius1311 I was thinking of the `combine` as you've suggested, but there's no inplace option (it might be useful in the future).
You you're satisfied with this, you can merge #89.

**Comment by Marius1311** [comment]
Thanks Mike! Will check this out.

**Comment by michalk8** [comment]
Implemented via #89
