### ISSUE TITLE
Is `magicked` data recommanded for `cellrank` pipeline?

### ISSUE THREAD

**Issue by jiangpuxuan** [theislab/cellrank#852]
I use `velocyte` to get `.loom` from 10x results, and  `seurat`, then transform the `seurat` object into  `adata` and run `scvelo + cellrank` pipeline. 
However, I found huge differences between the raw `RNA` and `MAGIC_RNA` results. 

<img width="342" alt="3dc3e8cc1d210f9b65d444d08688eff" src="https://user-images.githubusercontent.com/81287604/162745414-66d9b1db-36e8-449d-a5ce-b359fd08b706.png">

**Comment by Marius1311** [comment]
Hi @jiangpuxuan, this seems to be an scVelo question I suppose? I'm closing this issue here, please re-open in the scVelo repo and try to be a bit more specific - e.g. how exactly does MAGIC enter the pipeline, do you use it to replace moment-imputed counts? etc.

**Comment by jiangpuxuan** [comment]
> Hi @jiangpuxuan, this seems to be an scVelo question I suppose? I'm closing this issue here, please re-open in the scVelo repo and try to be a bit more specific - e.g. how exactly does MAGIC enter the pipeline, do you use it to replace moment-imputed counts? etc.

I am sorry for this ambiguty. Then I would open this issue on  scvelo.
