### ISSUE TITLE
Lineage drivers using CytoTRACEKernel

### ISSUE THREAD

**Issue by MoritzTh** [theislab/cellrank#854]
Hi, 
I was following the [Cellrank beyond RNA velocity tutorial ](https://cellrank.readthedocs.io/en/stable/beyond_rna_velocity.html#) using the CytoTRACEKernel. Everything works fine until the end of the tutorial, however, when I try to compute lineage drivers via ```g_fwd.lineage_drivers(adata)``` it results in the error: ```TypeError: 'NoneType' object is not callable```. Do you know how to properly call that?

**Comment by michalk8** [comment]
Hi @MoritzTh ,

it should be called as :
```python
drivers = g_fwd.compute_lineage_drivers()
# alt. you can access them later as:  drivers = g_fwd.lineage_drivers
```

**Comment by MoritzTh** [comment]
Got it, thanks!
