### ISSUE TITLE
TypeError: Expected object to be `categorical`, found `string` when doing g_bwd.set_terminal_states()

### ISSUE THREAD

**Issue by hyjforesight** [theislab/cellrank#857]
Hello CellRank,
I compute the initial state automatically by `g_bwd.compute_terminal_states()`, but the result is not consistent with the existing knowledge. So we tried to set the initial state manually by `g_bwd.set_terminal_states()`, but we met TypeError.
Appreciate it if you could help us with this issue.
Thanks!
Best,
YJ

```python
g_bwd.compute_terminal_states()
adata.obs['initial_states']
Name: initial_states, Length: 1906, dtype: category
Categories (1, object): ['Squamous epithelial']

g_bwd.set_terminal_states(labels=['Proliferating']) 
~\anaconda3\envs\HYJ_py38\lib\site-packages\cellrank\tl\estimators\terminal_states\_term_states_estimator.py in set_terminal_states(self, labels, cluster_key, add_to_existing, **kwargs)
    112             existing = None
    113 
--> 114         states, colors = self._set_categorical_labels(
    115             categories=labels,
    116             cluster_key=cluster_key,

~\anaconda3\envs\HYJ_py38\lib\site-packages\cellrank\tl\estimators\terminal_states\_term_states_estimator.py in _set_categorical_labels(self, categories, cluster_key, existing)
    200             categories = _convert_to_categorical_series(categories, list(self.adata.obs_names))
    201         if not is_categorical_dtype(categories):
--> 202             raise TypeError(f"Expected object to be `categorical`, found `{infer_dtype(categories)}`.")
    203 
    204         if existing is not None:

TypeError: Expected object to be `categorical`, found `string`.
```

```pytb
TypeError: Expected object to be `categorical`, found `string`.
```

#### Versions:
scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.21.5 scipy==1.7.3 pandas==1.3.5 scikit-learn==1.0.2 statsmodels==0.13.1 python-igraph==0.9.9 pynndescent==0.5.5
scvelo==0.2.4  scanpy==1.8.2  anndata==0.7.8  loompy==3.0.6  numpy==1.21.5  scipy==1.7.3  matplotlib==3.5.1  sklearn==1.0.2  pandas==1.3.5  
cellrank==1.5.1 scanpy==1.8.2 anndata==0.7.8 numpy==1.21.5 numba==0.55.0 scipy==1.7.3 pandas==1.3.5 pygpcca==1.0.3 scikit-learn==1.0.2 statsmodels==0.13.1 python-igraph==0.9.9 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.1 seaborn==0.11.2
> ...

**Comment by michalk8** [comment]
Hi @hyjforesight ,

`.set_terminal_states` accepts these types of inputs:
- either you supply a categorical `pandas.Series` where non-NaN values mark the terminal states
- or you pass as a `dict` of e.g. `{'prolif1': ['obs_name1', ...], 'prolif2': ['obs_name2', ...]}`
- or you pass as a `dict` with 1 key only corresponding to a categorical `adata.obs`, e.g.,
  `labels={'clusters': ['Proliferating']}` would set 1 set of terminal states (named `'Proliferating'`) defined by `adata.obs['clusters'] == 'Proliferating'`

**Comment by hyjforesight** [comment]
Hello @michalk8 
Thanks for the response. I called the `labels={'clusters': ['Proliferating']` and error was solved. It was my fault that I was not familiar with the `dist` operation. Thanks for your help!
Best,
YJ
