### ISSUE TITLE
Saving Paga Pie

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#86]
When I save a paga with pie charts with a `.pdf` extension, then the legend keywords are ignored, i.e. they are just always plotted on data: 

[15.5_backwards_paga_pie.pdf](https://github.com/theislab/cellrank/files/4529336/15.5_backwards_paga_pie.pdf)

This is not the case when I save as e.g. `.png`

**Comment by michalk8** [comment]
I'm not sure why is this happening, I can't reproduce it on my machine (always get the appropriate #legends, whether it's png or pdf).
There were some issues with `paga_pie` not properly displaying legends, maybe #88 fixes it.

**Comment by Marius1311** [comment]
Let's talk about thing tonight, maybe we can solve it together.

**Comment by michalk8** [comment]
@Marius1311 did the `scvelo` PAGA help? If not, I will take a look when we meet, since I really can't reproduce it.

**Comment by Marius1311** [comment]
I haven't tried yet but will do so later!

**Comment by Marius1311** [comment]
Still the same issue, saving as a pdf ignores legend position, but this is not too major at the moment, I can live with the png.

**Comment by michalk8** [comment]
This also seems like an issue I cannot really fix, since it's mpl-backend dependent, over which I have no control.

**Comment by Marius1311** [comment]
Okay, let's close this for now then.
