### ISSUE TITLE
Setting a higher number for 'n_cells=' argument in cellrank.tl.estimators.GPCCA.set_terminal_states_from_macrostates

### ISSUE THREAD

**Issue by JesseRop** [theislab/cellrank#862]
Dear developers, thank you very much for the great tool that is very easy to use and informative. I would like to know whether setting a higher 'n_cells=' number in cellrank.tl.estimators.GPCCA.set_terminal_states_from_macrostates increases power to identify drivers genes? The default number is 30 and this seems very small. I have >500 cells in my terminal clusters. 

Thanks,
Jesse

**Comment by JesseRop** [comment]
Thank you very much @Marius1311 !
Could you kindly advise on whether I can use all good quality genes (not just highly variable or those with >20 spliced counts) in my dataset when looking for driver genes when using either the PseudotimeKernel or VelocityKernel. I see no reason to limit my genes to only highly variable or those with high spliced counts.

**Comment by Marius1311** [comment]
Hi @JesseRop, for sure, these are gene filtering routines for velocity computation and representation learning, you may use other filters for driver gene identification - for example, you may want to include some genes that are expressed at lower levels (many TFs are expressed at low levels) or you may want to filter out mitochondrial, ribosomal or cell-cycle genes.

**Comment by JesseRop** [comment]
Many thanks @Marius1311 . 
I presume the only preprocessing I will need to do on the raw counts is normalization to cell size and log transformation before running pseudotimeKernel if I already have the pseudotime computed?

**Comment by JesseRop** [comment]
Thank you very much @Marius1311 . I have raised an issue requesting for a feature to easily incorporate all genes in driver analysis here https://github.com/theislab/cellrank/issues/870#issue-1234432016 . If you have advice on this, I will be grateful. Thanks
