### ISSUE TITLE
Results of `cr.tl.lineage_drivers(adata)`   have no index column.

### ISSUE THREAD

**Issue by jiangpuxuan** [theislab/cellrank#863]
Hi,
I worked with the `.h5ad` file converted from `seurat` object,  and `DefaultAssay(seurat_object)` is `MAGIC_RNA`.
Here is my `adata.var`, every gene has its name:
<img width="206" alt="e0e4eb7c257f710924271b4a0219169" src="https://user-images.githubusercontent.com/81287604/164965208-ebdb59e6-3eb2-492d-80a3-70319bd6301e.png">

But the results of `cr.tl.lineage_drivers(adata)`   have no index column:

![image](https://user-images.githubusercontent.com/81287604/164965342-365e37f5-f0cd-4324-a2f2-90a2ede3982f.png)

Thank you for your advice about this issue.

**Comment by michalk8** [comment]
Hi @jiangpuxuan ,

`cr.tl.lineage_drivers` take the index from `adata.var_names` (or `adata.raw.var_names`, if `use_raw=True`), which in your case seems to be numeric values. Try setting the index before as `adata.var_names = adata.var['_index']`.

**Comment by Marius1311** [comment]
Hi @jiangpuxuan, can this issue be closed?

**Comment by jiangpuxuan** [comment]
> Hi @jiangpuxuan, can this issue be closed?

I am sorry that I have not mentioned github for days. This issue had been solved, so, I would like to let it be closed.
Thank you for your help.
