### ISSUE TITLE
New openmpi conda-forge version does not install libmpi.so.40

### ISSUE THREAD

**Issue by leahrosen** [theislab/cellrank#864]
Hi, I've solved the issue, but thought it was worth flagging the bug:

I just installed cellrank using:
```
conda create -n cellrank python=3.9
conda activate cellrank
conda install -c conda-forge -c bioconda cellrank-krylov
conda install jupyter
```

When I run `g.compute_schur(n_components=20)` I get the following error: `ImportError: libmpi.so.40: cannot open shared object file: No such file or directory`. When I checked `/software/conda_envs/cellrank/lib` I could not find `libmpi.so.40`

I noticed that openmpi=4.1.3 was only uploaded in the last week, so downgraded to openmpi=4.1.2. Now I do have the libmpi.so.40 file, and g.compute_schur works :)

So in case anyone else has this issue: `conda install -c conda-forge openmpi=4.1.2` does the trick!

**Comment by michalk8** [comment]
Thanks for pointing this out! Will adjust the conda yaml file for the next release.

**Comment by Marius1311** [comment]
Thanks also from my side @leahrosen!

**Comment by HowHuang** [comment]
lt seems that the `openmpi=4.14` still does not install libmpi.so.40
```
(xxx) dell@dell:~$ python -c "from mpi4py import MPI"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libmpi.so.40: cannot open shared object file: No such file or directory
(xxx) dell@dell:~$ conda list openmpi
# packages in environment at /home/dell/anaconda3/envs/etLUmpi:
#
# Name                    Version                   Build  Channel
openmpi                   4.1.4                external_0    conda-forge
```

**Comment by Marius1311** [comment]
What's your opinion on this @michalk8 ?

**Comment by niklassiemer** [comment]
Since I found your issue while trying to solve a very similar issue (https://github.com/pyiron/pyiron_atomistics/issues/681) - I just wanted to let you know that `install -c conda-forge openmpi=4.1.4=ha1ae619_100` (on linux64) solved the issue on our end.

**Comment by Marius1311** [comment]
Great, thanks @niklassiemer

**Comment by HowHuang** [comment]
> Since I found your issue while trying to solve a very similar issue ([pyiron/pyiron_atomistics#681](https://github.com/pyiron/pyiron_atomistics/issues/681)) - I just wanted to let you know that `install -c conda-forge openmpi=4.1.4=ha1ae619_100` (on linux64) solved the issue on our end.

@niklassiemer it works well, thanks for your response!
