### ISSUE TITLE
changing colors of both cells and pie charts in pl.cluster_fates

### ISSUE THREAD

**Issue by FerrenaAlexander** [theislab/cellrank#866]
...
Hello, thanks for all your great work! I'm wondering if you can help me to change the color palette of the pie charts in cr.pl.cluster_fates.

I can change just the cell color using the option palette = dictionary key with cluster names, please see the screeshot. However, this does not change the pie chart color palette. 

![image](https://user-images.githubusercontent.com/35900744/165361224-1809aa25-022b-4bc1-b26f-4f2656b08b04.png)

I also tried to manually change the adata.uns like so:
col_key = {
    '2':"#C99800",
    '3':"#A3A500",
    '4':"#6BB100",
    '10':"#619CFF"
}

adata.uns['RNA_snn_res.0.4_colors'] = col_key
adata.uns['terminal_states_colors'] = col_key
adata.uns['clusters_gradients_colors'] = col_key

If I do this, it does make the cluster_fates with cells colored how I want without using the palette option, but the pie charts colors do not change.

Please excuse me if there is something obvious I'm missing, still getting used to python :) Thank you!

**Comment by michalk8** [comment]
Hi @FerrenaAlexander ,

`cr.pl.clusters_fates` takes the colors from the lineage object stored in `adata.obsm['to_terminal_states']`; you can set the colors as:
```python
# the color order will depend on the terminal names,
# see `adata.obsm['to_terminal_states'].names`
adata.obsm['to_terminal_states'].colors = ["#C99800", "#A3A500", "#A3A500", "#619CFF"]
```
Let me know if this works.

**Comment by FerrenaAlexander** [comment]
Hi, thanks a lot, this worked! I just had to make sure the list of cluster specific color strings matched the columns in adata.obsm['to_terminal_states'].

I was able to color both pies and cells by combining your suggestion with setting palette with the col_keys dict above.
Thank you!
