### ISSUE TITLE
Return figure in cellrank.pl.heatmap

### ISSUE THREAD

**Issue by rschauner** [theislab/cellrank#869]
I'm making a bunch of plots and want to be able to modify them before saving in my script. It looks like many of the plotting functions don't clearly return a figure object, just options to directly save. Can an option be added to return the figure or is this type of functionality already present? I'm giving an example of what I would like to do below:

```
      with PdfPages("cellrank_heatmap.pdf") as f:
          for l in lineages:
              fig = cr.pl.heatmap(
                  adata,
                  model,
                  genes=adata.varm["terminal_lineage_drivers"][f"{l}_corr"].sort_values(ascending=False).index[:100],
                  lineages=l) 
              plt.title(f"Patient ID: {patient_id}, Lineage: {l}")
              fig.savefig(f, format="pdf")

```

**Comment by michalk8** [comment]
This functionality is unfortunately not present at the moment, but easy to add.
