### ISSUE TITLE
Handeling both legends in PAGA pie

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#87]
Getting both legends to somehow not overlap with the data is a real challenge. What's missing is the option to position the cellrank legend (`final_states`) outside of the data, like the scvelo/scanpy legend (`clusters`). 

![image](https://user-images.githubusercontent.com/24494650/80237064-605c5b00-865c-11ea-8592-6201371433b4.png)
scvelo legend is set to `right`, cellrank legend is `left`. The problem is, it's not really outside the plotting area. `best` does not give me anything better:
![image](https://user-images.githubusercontent.com/24494650/80237144-841fa100-865c-11ea-947a-4acaeb36b48c.png)

If at least I could turn the `clusters` legend off, and if I were able to put the cellrank legend to the place there the scvelo legend currently is, that would already help me a lot.

**Comment by michalk8** [comment]
This will be soon addressed in #88, I am writing tests as we speak.

**Comment by Marius1311** [comment]
Great, thanks a lot!

**Comment by Marius1311** [comment]
Thanks, I will check this out later.
