### ISSUE TITLE
Determining number of macrostates

### ISSUE THREAD

**Issue by mortunco** [theislab/cellrank#873]
Hi folks,

Thank you very much for coming up Cellrank but most importantly making the tutorials very clear.

I have a question regarding running cellrank without rna velocity tutorial --> https://cellrank.readthedocs.io/en/stable/beyond_rna_velocity.html#Compute-macrostates

At the part where we compute macrostates, we do schur decomposition and then we visualize it to define our number of macrostates. I shared a screenshot that dashed line plot is on the 5th point. However in the further steps, we pick 3 macro states with the following explanation.
`CellRank automatically identified an ‘eigengap’ after three eigenvalues (dashed line above), so we’ll compute three macrostates:`

I got a little bit confused because `(dashed line above),`, wanted to ask if this a typo or could you please guide me to pick the best number for my case?

Thanks in advance,

Best regards,

Tunc.

### This is a screenshot from cellrank tutorial.
![image](https://user-images.githubusercontent.com/12833865/169921828-9a11ec32-d694-41ca-ba15-cd31ebc0d7ad.png)

### This is my case 
![image](https://user-images.githubusercontent.com/12833865/169922362-79ea1229-9ce4-493b-8dec-3cc5492d4105.png)

**Comment by michalk8** [comment]
> I got a little bit confused because (dashed line above),, wanted to ask if this a typo or could you please guide me to pick the best number for my case?

Originally, only 3 macrostates were showing up, but we've changed the underlying kernel (afaik just some defaults) and didn't update the tutorials yet (we track this in https://github.com/theislab/cellrank_notebooks/issues/43).

Regarding picking the number: the eigengap is just a helper heuristic, so I'd try different values. In your case, I'd try 2, 3, 4 and 7. Key think to remember that macrostates can ultimately contain metastable states, which can be not only terminal states, but also initial/intermediate metastable states.

**Comment by Marius1311** [comment]
Closing this, will be fixed when we update our tutorials.
