### ISSUE TITLE
Merge biological similar lineages/macrostates

### ISSUE THREAD

**Issue by kobeho24** [theislab/cellrank#874]
![image](https://user-images.githubusercontent.com/19304007/170535877-02eaa443-4c0a-47f6-ad02-ffb9b8a2c57a.png)
I am trying to do some gene trend plots, using the celltrace kernel in cellrank. The algorithm found 2 lineages that are essentially very similar. I tried to tune the number of macrostates, but a desired lineage will only come out after the 2 similar ones mentioned above. How can I merge the 2 lineages/macrostates? For example, merging the Alpha and Beta lineages. So that the downstream plotting will be cleaner.

Best regards,
Gary

**Comment by michalk8** [comment]
Hi @kobeho24 ,

you can try running, e.g.:
```python
lin: cr.tl.Lineage = adata.obsm['to_terminal_states']
lin[["Alpha, Beta", "Epsilon"]]  # will merge Alpha/Beta into a new state called "Alpha, Beta"
```

If you're using using the GPCCA and `set_terminal_states_from_macrostates`, this feature can be used directly there as e.g.
```python
g = cr.tl.estimators.GPCCA(k)
g.compute_schur()
g.compute_macrostates(3, cluster_key="clusters")
g.set_terminal_states_from_macrostates(["Alpha, Beta", "Epsilon"])
...
```

**Comment by Marius1311** [comment]
Maybe it's easier to merge when computing absorption probabilities towards macro states, we have a syntax for this implemented, please see the API for this.

**Comment by Marius1311** [comment]
Sorry, what I said is essentially equivalent to @michalk8's last point.
