### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#881]
Move from ``bioconda`` to ``conda-forge`` https://github.com/conda-forge/staged-recipes/pull/19264.

**Comment by michalk8** [comment]
@WeilerP requires ``scvelo`` to move from ``bioconda`` first.

**Comment by michalk8** [comment]
@WeilerP any update regarding moving `scvelo`?

**Comment by WeilerP** [comment]
Still waiting to be added as a maintainer on PyPI. Once that's done, we can release `scvelo==0.2.5` and move to `bioconda`.

**Comment by Marius1311** [comment]
I think @michalk8 added you recently, at least I got a notification from pypi. I thought we wanted to switch from bioconda to conda forge?

**Comment by WeilerP** [comment]
Yes, sorry, I meant `conda-forge`. I need to be added to scVelo (working on it) but am only part of CellRank on PyPI, ATM. I'll keep you posted.

**Comment by michalk8** [comment]
Tracked here, needs 2.0 release on PyPI: https://github.com/conda-forge/staged-recipes/pull/23198

**Comment by Marius1311** [comment]
@michalk8, I suppose we can close this now...?

**Comment by michalk8** [comment]
Yes, 2.0 is here: https://anaconda.org/conda-forge/cellrank
