### ISSUE TITLE
Minor quality of life improvements

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#895]
Got 3 changes to the API I'd like make:
- make `__repr__` and `__str__` be the same (or swap them); this means that we don't have to run `print(ck)` to show the parameters, just `ck`
  I'd do this for both kernels and estimators; alternatively we can just swap them
- return `self` in most of the estimators' methods so that we can chain function calls, e.g. `g.fit().predict()` or `g.compute_schur().compute_macrostates().set_terminal_states().compute_absorption_probabilites()`
- improve TermStatesEstimator repr by including `#term states` there + include `#macrotates` for GPCCA

**Comment by Marius1311** [comment]
Sounds good!
