### ISSUE TITLE
Introduce some hierarchy in the API

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#898]
...
At the moment, our API menu looks like this: 
![Screenshot 2022-06-21 at 14 20 06](https://user-images.githubusercontent.com/24494650/174797541-36c799dd-2975-4500-ad48-7f914f388ca7.png)

That's not very nice, the list is way too long. In contrast, scVi-tools displays this much nicer with some hierarchical structure: 
![Screenshot 2022-06-21 at 14 20 59](https://user-images.githubusercontent.com/24494650/174797685-0bee0ece-d877-4139-afb2-a089fe1c5c78.png)

I suggest to do the same for CellRank, let's use the sub-headings we already have, e.g. Kernels, External Kernels, Estimators, Plotting, Models, Datasets. This will look much cleaner.

**Comment by Marius1311** [comment]
BTW, @michalk8, what did you plan to put under the developer API? Can we also move this as an extra sub-heading, like the other ones above? Or would you like to keep a top-level heading for this?

**Comment by michalk8** [comment]
> BTW, @michalk8, what did you plan to put under the developer API? 

What was there named before as `Classes`. 

> Or would you like to keep a top-level heading for this?

No preference.

**Comment by michalk8** [comment]
> That's not very nice, the list is way too long. In contrast, scVi-tools displays this much nicer with some hierarchical structure:

They also have flat list (it's because the theme), just expand API. Not sure how to change this atm.
