### ISSUE TITLE
Precomputed kernel does not recognize kernel direction correctly

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#906]
I'm writing a `VelocityKernel` in forward mode with computed transition matrix to `AnnData` using `vk.write_to_adata()`. When I then use this `AnnData` object to initialize a new `PrecomputedKernel` using `pk = cr.kernels.PrecomputedKernel(adata)`, I get

```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-20-9cf032fa66f5> in <module>
----> 1 pk = cr.kernels.PrecomputedKernel(adata)

~/Projects/cellrank/cellrank/kernels/_precomputed_kernel.py in __init__(self, object, adata, obsp_key, **kwargs)
     53     ):
     54         if isinstance(object, AnnData):
---> 55             self._from_adata(object, obsp_key=obsp_key, **kwargs)
     56         elif isinstance(object, KernelExpression):
     57             self._from_kernel(object, copy=kwargs.get("copy", False))

~/Projects/cellrank/cellrank/kernels/_precomputed_kernel.py in _from_adata(self, adata, obsp_key, backward, copy)
     82         if obsp_key is None:
     83             obsp_key = Key.uns.kernel(backward)
---> 84         tmat = _read_graph_data(adata, obsp_key)
     85         if backward is PrecomputedKernel._SENTINEL:
     86             # not ideal, since None/False share the same key, we prefer False

~/Projects/cellrank/cellrank/_utils/_utils.py in _read_graph_data(adata, key)
   1707         return adata.obsp[key]
   1708 
-> 1709     raise KeyError(f"Unable to find data in `adata.obsp[{key!r}]`.")
   1710 
   1711 

KeyError: "Unable to find data in `adata.obsp['T_bwd']`."
```
So for whatever reason, the `PrecomputedKernel` tries to find the backwards transition matrix. I can prevent this from happening by explicitly passing `backward=False`, in that case, I get to error. 

#### Versions:
cellrank==1.5.1+g4bab618c.d20220621 scanpy==1.7.2 anndata==0.8.0 numpy==1.21.4 numba==0.51.2 scipy==1.5.3 pandas==1.3.3 pygpcca==1.0.2 scikit-learn==0.24.0 statsmodels==0.12.1 python-igraph==0.8.3 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.3.3 seaborn==0.11.0
> ...

**Comment by Marius1311** [comment]
Another thing, related to both this issue and #905: using this workaround for reading in a kernel from a saved AnnData object means I don't get any info on how the transition matrix was computed originally, calling `print(pk)` just gives `PrecomputedKernel[origin="adata.obsp['T_fwd']"]`. It would be much nicer if the `VelocityKernel` would just read in both again, the transition matrix as well as the parameters, so I can easily check how this matrix has been computed.

**Comment by Marius1311** [comment]
Another downside: you can't do as many things with a `PrecomputedKernel`, e.g. `pk.plot_projection()` yields: 
`TypeError: PrecomputedKernel is not a kNN based kernel. The embedding projection only works for kNN based kernels.`

**Comment by michalk8** [comment]
closed via #915

**Comment by emdann** [comment]
I bumped into this issue while trying to use a PrecomputedKernel and I wanted to use `plot_projection` to sanity check my transition matrix. I installed from the development version but I still get the `TypeError` above when I try to run `plot_projection`. Any plan to remove this check?

**Comment by michalk8** [comment]
> I installed from the development version but I still get the TypeError above when I try to run plot_projection. Any plan to remove this check?

We could relax this for just a warning in all kernels, or just use a warning for precomputed kernel + keep the error for others (think the 1st option is better/more consistent)
Could you please open an issue for this?
