### ISSUE TITLE
Cannot use TransportMapKernel to load precomputed transition matrices

### ISSUE THREAD

**Issue by Bastiaanspanjaard** [theislab/cellrank#912]
I would like to use a precomputed transition matrix of transitions between all cells at t1 to all cells at t2 to create a kernel for downstream computation of driver genes. However, the function compute_transition_matrix does not work.

#### Minimal reproducible example:
```python
class HeartKernel(TransportMapKernel):
    def _compute_tmap(self, t1: Any, t2: Any, **kwargs: Any) -> Union[np.ndarray, spmatrix, AnnData]:
        print("Computing for:", t1, t2)
        return AnnData(tmat)
tmat = pd.read_csv("./path_to_file", index_col=0)
adata_subset = adata_dpis[list(tmat.index) + list(tmat.columns)].copy()
adata_subset.obs['time_num'] = adata_subset.obs['time'].cat.rename_categories({"3dpi": 2, "Ctrl": 1, "7dpi": 3})
k = HeartKernel(adata_subset, time_key='time_num')
k.compute_transition_matrix(threshold=None, last_time_point='diagonal')
```

#### Error output:
```pytb
Computing for: 2 3
Computing transition matrix based on `adata.obsp['connectivities']`
    Finish (0:00:00)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [18], in <module>
      1 #set_trace()
----> 2 k.compute_transition_matrix(threshold=None, last_time_point='diagonal')

File ~/anaconda3/envs/cellrank_dev/lib/python3.8/site-packages/cellrank/kernels/_transport_map_kernel.py:199, in TransportMapKernel.compute_transition_matrix(self, threshold, self_transitions, conn_weight, conn_kwargs, **kwargs)
    196 if threshold is not None:
    197     self._threshold_transport_maps(self._tmaps, threshold=threshold, copy=False)
--> 199 self.transition_matrix = self._restich_tmaps(
    200     self._tmaps,
    201     self_transitions=self_transitions,
    202     conn_weight=conn_weight,
    203     conn_kwargs=conn_kwargs,
    204 ).X
    206 return self

File ~/anaconda3/envs/cellrank_dev/lib/python3.8/site-packages/cellrank/kernels/_base_kernel.py:552, in Kernel.transition_matrix(self, matrix)
    550 @transition_matrix.setter
    551 def transition_matrix(self, matrix: Any) -> None:
--> 552     KernelExpression.transition_matrix.fset(self, matrix)

File ~/anaconda3/envs/cellrank_dev/lib/python3.8/site-packages/cellrank/kernels/_base_kernel.py:447, in KernelExpression.transition_matrix(self, matrix)
    445     if should_norm(matrix):  # some rows are all 0s/contain invalid values
    446         n_inv = np.sum(~np.isclose(np.asarray(matrix.sum(1)).squeeze(), 1.0, rtol=1e-12))
--> 447         raise ValueError(f"Transition matrix is not row stochastic, {n_inv} rows do not sum to 1.")
    448 # fmt: on
    450 self._transition_matrix = matrix

ValueError: Transition matrix is not row stochastic, 3 rows do not sum to 1.
```
The error occurs in line 199 of compute_transition_matrix, while restitching the transport maps. Output suggests it is calculating a transport map, which I would really like to supply myself. Maybe I need to also supply the additional diagonal transport maps? Or explicitly set the t_2 -> t_1 part to 0?

#### Versions:

> cellrank==1.5.1+geb182f5 scanpy==1.8.2 anndata==0.8.0 numpy==1.21.5 numba==0.55.1 scipy==1.8.0 pandas==1.4.1 pygpcca==1.0.3 scikit-learn==1.0.2 statsmodels==0.13.2 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.1 seaborn==0.11.2

**Comment by Bastiaanspanjaard** [comment]
@Marius1311

**Comment by Marius1311** [comment]
Thanks for posting! To get started, please make sure you're on the latest commit on master, see my comments in #911

**Comment by michalk8** [comment]
> Updated packages to latest commit on master. Updated error message and versions in initial post.

Seems like there must be 3 all zero rows (possible due to unbalancedness?) in the transport map - would remove these.
Alternatively if you wanna keep these cells, uniform distribution could be used.

**Comment by Marius1311** [comment]
I agree, check the raw transport maps before you input them to the kernel and locate the three rows that only contain zeros.

**Comment by Bastiaanspanjaard** [comment]
Thanks! But I don't think there are all zero rows:
```python
(tmat.sum(axis = 1) == 0).value_counts()
```
has output
```pytb
False    645
dtype: int64
```
Also, I'm not an expert but neither the initialization nor the compute_transition_matrix command for k references tmat. So to me it looks like either it grabs tmat from the global environment, or it tries to compute a transition matrix based on something else (it claims it is computing based on 'connectivities'). Is there a way to explicitly feed in tmat?

**Comment by michalk8** [comment]
> TypeError: Can't instantiate abstract class HeartKernel with abstract methods _compute_tmap

This is by design, because it's supposed to be implemented by whoever subclasses it.

**Comment by Bastiaanspanjaard** [comment]
> This is by design, because it's supposed to be implemented by whoever subclasses it.

Gotcha. Will continue on this when I'm back from holiday.
