### ISSUE TITLE
Add a "how to cite us" page

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#922]
This should make users aware of the packages CellRank uses under the hood to enable certain functionality, in particular, pyGPCCA for the GPCCA estimator, and encourage them to cite both, CellRank and the original work.

**Comment by msmdev** [comment]
Some first prototype suggestion regarding pyGPCCA/GPCCA:
"If you use CellRank to compute initial/intermediate/terminal macrostates or fate/absorption probabilities of your biological system (via coarse-graining of the Markov Chain using Generalized Perron Cluster Cluster Analysis (GPCCA)) please cite GPCCA [Reuter et al., 2018] as well as [Lange et al., 2022]."
Suggestions/Adaptions are very welcome. :)

**Comment by msmdev** [comment]
Some further modifications I would request:
- On the [main cellrank docu page](https://cellrank.readthedocs.io/en/stable/index.html) and in the GitHub Readme you don't link the pyGPCCA package. I would would like to ask you to link it and add it to the References as done in the paper (Reuter, B. pyGPCCA: pyGPCCA - python GPCCA: Generalized Perron Cluster Cluster Analysis package to coarse-grain reversible and non-reversible Markov State Models. (Github) https://github.com/msmdev/pyGPCCA)
- On the [main cellrank docu page](https://cellrank.readthedocs.io/en/stable/index.html) you abbreviate Generalized Perron Cluster Cluster Analysis by G-PCCA, but mostly everywhere else (and in the paper as well) you write it as GPCCA. I would vote to always abbreviate it as GPCCA.

**Comment by Marius1311** [comment]
Hi @msmdev, this is taken care of in the linked PR, feel free to leave your review.

**Comment by Marius1311** [comment]
Just one minor point @msmdev, would you mind adding @michalk8 and my ORCID to the Zenodo entry?
- @michalk8: 0000-0002-2433-6380
- me: 0000-0002-4846-1266

Thanks!

**Comment by Marius1311** [comment]
Closed with #936
