### ISSUE TITLE
Can't compute transition_matrix

### ISSUE THREAD

**Issue by jindalk** [theislab/cellrank#926]
Hi, I recently installed the master branch and am unable to find the transition_matrix function. This was previously accessible via cr.tl.transition_matrix

I remember seeing the following warning in a past version:
 `cellrank.tl.transition_matrix` will be removed in version `2.0`. Please use the `cellrank.kernels` or `cellrank.estimators` interface instead.
  cr.tl.transition_matrix(adata,

Has it been already moved to a new location? If so, how could I access the function?

I am trying to replicate some of the analysis described here: https://github.com/theislab/cellrank_reproducibility/blob/master/notebooks/fig_4_mef_reprogramming/ML_2021-09-23_mef_reprogramming.ipynb

**Comment by michalk8** [comment]
The `cr.tl.transition_matrix` was already removed, since we're getting close to `2.0` release.
The new API can be seen here: https://cellrank.readthedocs.io/en/latest/api.html
Re trying to replicate the analysis, follow should be equivalent (sorry for any typos):
```python
...
ck = cr.kernels.ConnectivityKernel(adata).compute_transition_matrix()
vk = cr.kernels.VelocityKernel(adata).compute_transition_matrix(
    mode=mode,
    softmax_scale=softmax_scale,
    n_jobs=n_jobs,
)
kernel = weight_connectivities * ck + (1 - weight_connectivities) * vk
```
