### ISSUE TITLE
Control point sizes in random walk plot

### ISSUE THREAD

**Issue by emdann** [theislab/cellrank#927]
Hi, I'm using the `plot_random_walks` function on a dataset with a few thousand cells and I want to increase the point size in the plot to visualize start and end cells better. If I use the `size` argument passed to the scanpy plotting functions, it increases the size of the background cells but it doesn't increase the size of the highlighted cells.

Example call
```python
k.plot_random_walks(basis='umap', n_sims=30, max_iter = 1000, size=100, figsize=(10,10), start_ixs={"anno_lvl_2_final_clean": "DP(P)_T"})
```
Output:
![test_random_walks](https://user-images.githubusercontent.com/32264060/179223605-153cdd0c-dc13-48e6-be04-d4222ed9c785.png)

#### Versions:

> cellrank==1.5.1+g54ada10 scanpy==1.9.1 anndata==0.8.0 numpy==1.20.2 numba==0.53.0 scipy==1.5.2 pandas==1.3.5 pygpcca==1.0.3 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.9.9 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.2 seaborn==0.11.0

**Comment by michalk8** [comment]
Nice, catch, thanks! It was previously controlled by `s=100` argument.
