### ISSUE TITLE
Loading of adata object

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#93]
Since we rely on the Lineage class, which cannot be reconstructed when loading the `adata`
object using `sc.read`, I think we should have our own wrapper that will also optionally create dummy names, such as `Lineage 1` if not present, as well as colors

**Comment by Marius1311** [comment]
Can we still use `sc.write`, or would we also have to replace that?

**Comment by michalk8** [comment]
We can still use that, there's no issue, since `Lineage` is just a subclass of `numpy.ndarray`.

**Comment by VolkerBergen** [comment]
@michalk8 alternatively you could also store it as rec.array.

**Comment by michalk8** [comment]
Doesn't recarray support only fixed sized strings for record names? I think this was the main reason why I haven't looked more into them.

**Comment by VolkerBergen** [comment]
It's almost like a dataframe with a string name stored for each column.

**Comment by michalk8** [comment]
Implemented via #97
