### ISSUE TITLE
cr.tl.terminal_states not identified

### ISSUE THREAD

**Issue by rrotkopf** [theislab/cellrank#932]
Hello,

I am trying to run your example script (https://cellrank.readthedocs.io/en/stable/cellrank_basics.html)
and when I run the following line:
cr.tl.terminal_states(adata, cluster_key="clusters", weight_connectivities=0.2)

I get the error:
AttributeError: module 'cellrank' has no attribute 'tl'

cellrank (v. 1.5.1) seems to be installed properly. What could be the issue?

Thanks,
Ron

**Comment by Marius1311** [comment]
Hi @rrotkopf, high level functions, like `cr.tl.terminal_states` will be deprecated in our next release and are already deprecated on master, sorry for the inconvenience. We have a note for this in our API: 

<img width="898" alt="Screenshot 2022-07-27 at 17 21 47" src="https://user-images.githubusercontent.com/24494650/181285727-613345cb-2ad5-48ad-84d2-d78890566587.png">
