### ISSUE TITLE
Construct GAM without RNA velocity

### ISSUE THREAD

**Issue by siefejo1** [theislab/cellrank#939]
...
Thanks for the great program! I am using the CytoTRACEKernel to run Cellrank functions in the absence of RNA velocity. Is it possible to construct a GAM from this transition matrix?

**Comment by siefejo1** [comment]
Got it. With regards to determining the terminal states and lineages first, if I run the GPCCA estimator on a combined kernel of CytoTRACEKernel and ConnectivityKernel, will that update the adata object with the necessary parameters for the GAM?

**Comment by michalk8** [comment]
> Got it. With regards to determining the terminal states and lineages first, if I run the GPCCA estimator on a combined kernel of CytoTRACEKernel and ConnectivityKernel, will that update the adata object with the necessary parameters for the GAM?

Yes, it should be updated so that all data needed for GAM fitting is there.

**Comment by Marius1311** [comment]
I'm closing this, it looks solved.
