### ISSUE TITLE
PyPI and Anaconda

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#94]
Start slowly preparing to do this.

**Comment by michalk8** [comment]
Now that #178 is merged, I will focus on this.

**Comment by michalk8** [comment]
Hi, @flying-sheep,
I'm struggling to put CellRank on `testpypi`, the main culprit being here: https://github.com/theislab/cellrank/blob/master/setup.py#L42
The problem is this: `HTTPError: 400 Client Error: Invalid value for requires_dist. Error: Can't have direct dependency: 'msmtools @ git+git://github.com/msmdev/msmtools@krylov_schur#egg=msmtools' for url: https://test.pypi.org/legacy/`
This problem occures when I build `bdist_wheel`. If I only build `sdist`, it gets uploaded.
However, after running `pip install -i https://test.pypi.org/simple/ cellrank==1.2.3.dev2`,
I get the following error and I don't know how to fix it:
```python
Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/michal/.miniconda3/envs/cellrank/bin/python /home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ant09w4q/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://test.pypi.org/simple/ -- setuptools setuptools_scm wheel
       cwd: None
  Complete output (3 lines):
  Looking in indexes: https://test.pypi.org/simple/
  ERROR: Could not find a version that satisfies the requirement setuptools (from versions: none)
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/michal/.miniconda3/envs/cellrank/bin/python /home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ant09w4q/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://test.pypi.org/simple/ -- setuptools setuptools_scm wheel Check the logs for full command output.
```
Here's the full [log](https://github.com/theislab/cellrank/files/4745534/log.txt).

Based on [this](https://stackoverflow.com/questions/54887301/how-can-i-use-git-repos-as-dependencies-for-my-pypi-package#answer-54894359), I'm not sure if it's even possible to specify dependency that way.
As far as I know, `dependency_links` could've worked (haven't tried them, they were deprecated).
Other thing I tried is using `cmdclass` in `setup.py`, calling `pip install <the package>`, similar to [this](https://stackoverflow.com/questions/19569557/pip-not-picking-up-a-custom-install-cmdclass#45021666), but it always fails with not being able to find pip:
```python
Traceback (most recent call last):
      File "/home/michal/.miniconda3/envs/cellrank/bin/pip", line 7, in <module>
        from pip._internal.cli.main import main
    ModuleNotFoundError: No module named 'pip'
```
Any help on this would be greatly appreciated!

**Comment by Marius1311** [comment]
In the meantime, I would vote for putting it on pypi without the msmtools dependency, include msmtools it in the installation instructions and initiate a merge of the krylov-schur branch into upstream msmtools.

**Comment by Marius1311** [comment]
We could even let functions/methods default to CFLARE if no msmtools is found and print a message, urging the user to install msmtools...

**Comment by Marius1311** [comment]
@flying-sheep, can you help us with this?

**Comment by flying-sheep** [comment]
The reason one can’t have URLs as dependencies is explained in pypa/pip#6301.

One option to solve this is to vendorize it, i.e. bundle the dependency with your package. [This tool](https://pypi.org/project/vendorize/) could help, I think it’s able to resolve and install from an URL since it uses pip.

The way it works is that you use the CLI command `python-vendorize` to install the package to a local (git-ignored) directory, and include that directory when building a package for PyPI.

I suggest you use an URL with a commit hash instead of the branch name in the URL. This way when building a package, you always get the same version and not whatever is the newest one at build time.

**Comment by michalk8** [comment]
@flying-sheep  Thanks a lot!
That's what I was afraid of - bundling stuff together, but if it's the only solution, then so be it. There were some issues with docs + tests, but  https://github.com/theislab/cellrank/pull/225 should make it work.

**Comment by michalk8** [comment]
Done via #225 and later commit. Will create separate issue for Anaconda.

**Comment by Marius1311** [comment]
Amazing, thanks so much.
