### ISSUE TITLE
Is the result still reliable after doing scvelo's differential kinetics

### ISSUE THREAD

**Issue by BW15061999** [theislab/cellrank#941]
Hi,
If I have a dataset with cells with distinct cell states and lineages and run **differential kinetics** as scvelo suggested, will the result of cellrank still be reliable?
Thank you! 

Bset

**Comment by Marius1311** [comment]
Hi @BW15061999, sorry for the very slow response to this, I hope it's still relevant. As long as you trust the velocity results (which you should check by looking at e.g. individual gene fits), this should be no issue for CellRank
