### ISSUE TITLE
R script using dygen

### ISSUE THREAD

**Issue by HuangDDU** [theislab/cellrank#944]
CellRank is a user-friendly tool!
  I want to ask you if you can provide R script using dygen in paper fig1. I want to kown the details of parameters such as regulator relationship, which help me have a better knowledge of cellrank process and result.
  Thank you very much!

**Comment by michalk8** [comment]
Hi @HuangDDU , I this this is the notebook you're looking for: 
[dyngen.ipynb.txt](https://github.com/theislab/cellrank/files/9543592/dyngen.ipynb.txt)

**Comment by HuangDDU** [comment]
Thank you very much!
