### ISSUE TITLE
Prettify the Teams page

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#956]
Currently, it looks like this (I just provided all the data via links):

<img width="832" alt="Screenshot 2022-10-10 at 10 13 44" src="https://user-images.githubusercontent.com/24494650/194823562-e6c0e2ce-b7bb-4548-875f-67b5becf875a.png">

It would be great if we could make it a bit prettier, similar to the way scVI does it: 

<img width="907" alt="Screenshot 2022-10-10 at 10 14 49" src="https://user-images.githubusercontent.com/24494650/194823649-6fb0e73b-22a5-4a7d-8a9a-64831f70e961.png">
 
Could you take care of this please @michalk8 ?

**Comment by michalk8** [comment]
Can't do it easily, on `scvi-tools` side, it's done in a separate repo (using Javascript).
In principle I could force it to use `sphinx` only, but not a priority right now

**Comment by michalk8** [comment]
Think this can be used: https://sphinx-design.readthedocs.io/en/latest/cards.html

**Comment by Marius1311** [comment]
Oh, amazing! That would be great!

**Comment by Marius1311** [comment]
Feel free to make a suggestion when you find the time and I can fill in the details.
