### ISSUE TITLE
ValueError on PseudotimeKernel.plot_single_flow()

### ISSUE THREAD

**Issue by anderswe** [theislab/cellrank#964]
Hi CellRank team, super grateful for your work!

I'm trying to run ```PseudotimeKernel.plot_single_flow()``` on a 26684 x 36601 AnnData object as here:
```
ptk = PseudotimeKernel(adata).compute_transition_matrix() #runs without issue
ptk.plot_single_flow(cluster = 'stem', cluster_key = 'celltype', time_key = 'dpt_pseudotime')
```

and encounter the following error:
```
ValueError: Unable to convert `adata.obs['dpt_pseudotime']` to `categorical` since it would create `26611` categories.
```

I suspect this is related to the relatively large number of observations in this object. I have thought about binning pseudotime values if that's the case.

I would appreciate any suggestions about how to fix this! Thank you!
Anders

**Comment by michalk8** [comment]
Hi @anderswe , `plot_single_flow` requires an experimental time (like 3h/6h/12h/, etc.), which will be stored as a categorical variable, not a continuous time like DPT.
If you don't have such info in your data, binning the pseudotime is a possibility (or having another notion of discrete time, e.g., based on developmental stages).

**Comment by anderswe** [comment]
Perfect, thank you so much!
