### ISSUE TITLE
Applying Cell Rank on the CellRanger filtered outputs

### ISSUE THREAD

**Issue by Sidy2015** [theislab/cellrank#965]
Hello,

I'm new to velocity analysis. I would like to apply CellRank to cellranger filtered outputs (the counts matrix, the feature and the barcodes files). Is it possible to apply CellRank without generating the spliced-unpliced matrices with Velocyto? 

Thank you in advance

**Comment by Zethson** [comment]
Not one of the developers, but you can use a different kernel such as the PseudotimeKernel

**Comment by Marius1311** [comment]
Exactly, thanks @Zethson. Please check out the corresponding tutorials @Sidy2015, e.g. the CellRank beyond RNA velocity tutorial, to see how CellRank can be applied in the absence of velocity information.

**Comment by Sidy2015** [comment]
Thank you @Zethson and @Marius1311 for your answers
