### ISSUE TITLE
'CytoTRACEKernel' object has no attribute 'compute_projection'

### ISSUE THREAD

**Issue by joseph-siefert** [theislab/cellrank#966]
Has the compute_projection function been removed in the newest version. Previously:
```
from cellrank.tl.kernels import CytoTRACEKernel
...
ctk.compute_projection(basis="draw_graph_fa")
```
Worked fine. Now:
```
from cellrank.kernels import CytoTRACEKernel
...
ctk.compute_projection(basis="draw_graph_fa")
```
Gives the error:
`'CytoTRACEKernel' object has no attribute 'compute_projection'`

**Comment by Marius1311** [comment]
I think we just renamed it to "plot_projection" since that's a bit more intuitive, see https://cellrank.readthedocs.io/en/latest/api/_autosummary/kernels/cellrank.kernels.CytoTRACEKernel.html#cellrank.kernels.CytoTRACEKernel.plot_projection

**Comment by joseph-siefert** [comment]
Got it, thanks!
