### ISSUE TITLE
Returning cell components for a specific trajectory lineage

### ISSUE THREAD

**Issue by hl-xue** [theislab/cellrank#970]
Hello,

I am using CellRank for trajectory analysis, and I got a question please.
I am plotting driver-gene heatmap of a specific lineage with `cr.pl.heatmap` function (command shown as below), and I would like to see the names of `cluster_key` of this `lineage1`.

```
cr.pl.heatmap(adata_h, model=model_h, genes=driver_genes, lineages="lineage1",
              data_key="X", time_key="dpt_pseudotime", show_all_genes=True,
              cluster_key="leiden", figsize=(25, 10), cbar=True, return_models=True)
```

For now, the clusters are shown as column colours with `cluster_key="leiden"`, but there are too many and impossible to distinguish among them, besides, I also need to know how many cells are there for each cluster within this lineage.

So, I would like to know if it is possible to get the cells (for example, the corresponding values in `.obs["leiden"]`, or the corresponding `.obs.index`) of this specific lineage?

Thanks!
...

**Comment by Marius1311** [comment]
Hi @hl-xue, trajectory membership in CellRank is defined via fate probabilities, i.e., we don't do a hard cell <-> trajectory assignment, but we use soft weights. Upon computing fate probabilities, they are written to `adata.obsm['lineages_fwd']`and you can use these to check for trajectory <-> leiden cluster relationships. In fact, we have a few dedicated plotting functions that help you interrogate fate bias at the cluster level, check out https://cellrank.readthedocs.io/en/stable/api/cellrank.pl.cluster_fates.html#cellrank.pl.cluster_fates

**Comment by hl-xue** [comment]
Hi Marius,

Thank you very much for your quick reply.
Actually I am using CellRank beyond beyond RNA velocity, so if I understood correctly, I cannot use `scvelo.tl.paga()` which is required by `cr.pl.cluster_fates()`?
Also, I did not find the adata.obsm['lineages_fwd'], is this normal?

Thanks again!

**Comment by Marius1311** [comment]
Hi @hl-xue, `cr.pl.cluster_fates` does not necessarily require a PAGA graph; that depends on the `mode` parameter. For fate probabilities, I think they are by default written to `adata.obsm['to_terminal_states']`, but you can check the kernels and estimators tutorial to make sure: https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html#

Note that the documentation is currently a bit outdated; we're currently working on a major update which should be done soon.

**Comment by hl-xue** [comment]
Hi @Marius1311,

Thank you very much for the reply.  I can now run the `cr.pl.cluster_fate`.  I have two following questions please:

1. So to be sure, the "aggregate lineage probabilities at a cluster level" is the sum of fate probability (i.e., values in `adata.obsm['to_terminal_states']`) for all cells within each cluster? If so, how should I interpret this value?
2. Also, if I really need to assign each cell to a specific trajectory, do you think it's reasonable to assign cells to the terminal state with the highest fate probability?  What will I lose comparing to the soft assignment?

Thanks again!

**Comment by hl-xue** [comment]
And another question please: I found another field `.terminal_states_memberships` in GPCCA result (named as g_fwd in tutorial).  If I understand correctly, this is computed after the absorption probability stage, and indicates probability of soft assignment to different terminal states?  If so, does it make sense if I "manually" assign each cell to the terminal state according to the maximum value of this `.terminal_states_memberships`?

**Comment by Marius1311** [comment]
Close due to inactivity.
