### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#972]
Hi all, I have two naming suggestions. 
1. I would rename "lineages" to "trajectories" everywhere - we don't really estimate lineages, but abstracted cell trajectories
2. I would rename "absorption probabilities" as "fate probabilities" everywhere - since we want users to directly interact with estimators in version 2, I feel like the old term is too technical, and some users might not find what they are looking for (which will most likely be fate probabilities). 

What do both of you think? @michalk8 @WeilerP

**Comment by michalk8** [comment]
I agree with the 2., 1. I'd keep for now (need to think about it more).
