### ISSUE TITLE
correlation method for compute_lineage_drivers()

### ISSUE THREAD

**Issue by flde** [theislab/cellrank#981]
Hello CellRank team, 

I tried to follow the source code to understand the correlation method for compute_lineage_drivers() which should be the return value from here https://github.com/theislab/cellrank/blob/f9faeefdc1d14826e5262b67313acca64150db58/cellrank/_utils/_utils.py#L342-L355  Can you tell me which method is used here? I just don't get it (sorry). 

Best wishes, 
Florian

**Comment by Marius1311** [comment]
I think that should be Pearson correlation in vectorized form for the special case where you want to correlate a matrix X (containing expression values for several genes) with a vector y (containing your fate probabilities).

**Comment by flde** [comment]
Many thanks @Marius1311 for taking the time to explain! Its just a minor suggestion but it would be nice to include that information with the API description and add a method with fewer assuption about the data like Spearman? 

Again, many thanks! Best, Flo

**Comment by Marius1311** [comment]
Hi Flo, I think both are great suggestions, thank you! @michalk8, I think @MUCDK has included spearman correlation in moscot, so we could just copy that over here. For the p-values and confidence intervals, we could either just return None, or use the exact these we already have for Peason and run that for Spearman as well.

**Comment by MUCDK** [comment]
I checked in the literature and it's actually valid to use the Fisher transformation for the Spearman correlation, too. See e.g. [here](https://www.sciencedirect.com/topics/mathematics/spearman-correlation)

**Comment by Marius1311** [comment]
amazing, thanks!

**Comment by flde** [comment]
Thats cool, many thanks for the literature link and all your great work!
