### ISSUE TITLE
Change default time key for `time_key`

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#988]
At the moment, the default time key for plotting gene trends (and other high-level functions) is `time_key="latent_time"`. I think it'd be a good idea to remove the default value since it appears to be an artifact from when CellRank was designed as a downstream analysis tool for RNA velocity.

**Comment by WeilerP** [comment]
Any objections or something I missed, @Marius1311, @michalk8?

**Comment by Marius1311** [comment]
No, this is fine. We can either change to `dpt_pseudotime`, or remove the default altogether. Either one is fine for me.

**Comment by michalk8** [comment]
> Any objections or something I missed, @Marius1311, @michalk8?

No objections, only 1 question: shall we then also remove the defaults from the high lvl functions (or at the very least unify the `time_key`, in case they are not)?

**Comment by WeilerP** [comment]
> No, this is fine. We can either change to `dpt_pseudotime`, or remove the default altogether. Either one is fine for me.

Well, `dpt_pseudotime` makes equally no sense, IMO. That's also why we removed the default key for the `PseudotimeKernel`.

> No objections, only 1 question: shall we then also remove the defaults from the high lvl functions (or at the very least unify the time_key, in case they are not)?

Yes, good point! Should have checked if there are other functions with the same "issue".
