### ISSUE TITLE
Add Python=3.9 (or similar) as mandatory for the installation

### ISSUE THREAD

**Issue by Al3n70rn** [theislab/cellrank#992]
Hi,

Thanks for this amazing library.

I have had some issues related with the installation process of cellrank. According to the setup.py, the Python version should be =<3.9; however, it is not clearly indicated in the installation process (i.e. conda install -c conda-forge -c bioconda cellrank). Given that the current Python version is 3.11, it is impossible (at least to me) to install it with this Python version, and I believe it could be more straightforward, to clearly indicate the Python version in the conda installation to adapt the cellrank environment (i.e. conda install -c conda-forge -c bioconda cellrank python=3.9).

I think this could make easier the installation process.

Best regards,
Agusti

**Comment by michalk8** [comment]
Hi @Al3n70rn , sorry for such a late reply. There shouldn't be any limitation w.r.t. the Python version. I will look into this and upgrade our CI to also test for 3.11 in a couple of days.
We will also be putting the new version on `conda-forge` and not on `bioconda` to make the installation easier.

**Comment by michalk8** [comment]
closed via #1046
