### ISSUE TITLE
Problems combining loom file with my adata object

### ISSUE THREAD

**Issue by Pawan291** [theislab/cellrank#998]
...
Hello everyone,
I am quite new to cell rank package and just trying to combine my processed adata object from a single sample to a loom file using the code given on scvelo repository. Here is the code and the output.
Code:
adata = scv.read(folder + "UMAP regressed.h5ad", cache=True)
ldata = scv.read(folder + "loomDWSoloRNA.loom", cache=True)
adata = scv.utils.merge(adata, ldata)

Output for adata before merging with loom file:
AnnData object with n_obs × n_vars = 4404 × 21445
obs: 'identifier', 'name', 'cells', 'grouping', 'n_counts', 'n_genes', 'percent.mito', 'S_score', 'G2M_score', 'phase', 'louvain'
var: 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'mean', 'std'
uns: 'grouping_colors', 'louvain', 'louvain_colors', 'name_colors', 'neighbors', 'pca', 'umap'
obsm: 'X_pca', 'X_umap'
varm: 'PCs'
layers: 'counts'
obsp: 'connectivities', 'distances'

Output after merging with loom file:
AnnData object with n_obs × n_vars = 4404 × 156
obs: 'identifier', 'name', 'cells', 'grouping', 'n_counts', 'n_genes', 'percent.mito', 'S_score', 'G2M_score', 'phase', 'louvain', 'nCount_RNA', 'nFeature_RNA', 'orig.ident'
var: 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'mean', 'std'
uns: 'grouping_colors', 'louvain', 'louvain_colors', 'name_colors', 'neighbors', 'pca', 'umap'
obsm: 'X_pca', 'X_umap'
varm: 'PCs'
layers: 'counts'
obsp: 'connectivities', 'distances'

As you can see the number of cells remains the same but the number of genes reduced from 21445 to 156. I don't really understand the problem here and how to solve this.

Thank you very much for the help.

Pawandeep

**Comment by Marius1311** [comment]
Hi @Pawan291, this seems to be an scVelo issue. Please post this issue in the scVelo repo.
